/**
 * LandingPage.tsx — Single screen, no scroll.
 * 5 cards in a 2P+3BAT grid (3 top row, 2 bottom row centered).
 * Start face-down with TAP prompt. Tap to flip and reveal real in-game card fronts.
 */
import { useState, useMemo, useCallback, useEffect } from "react";
import type { GamePhase, PlayerCard, Achievement } from "../adapters/types";
import { BaseballCard } from "./BaseballCard";
import { CardBackGeneric } from "./CardBackGeneric";
import { ensureLoaded, getLogsByKey } from "../engines/dataEngine";
import { sportAdapter } from "../adapters/SportAdapter";
// Baseball ships local headshots at /baseball/headshots/{id}.png. Vite serves
// the public/ folder at the SPA's base path (`/baseball/`), so an absolute
// URL is what the browser needs. The shared headshotUrl helper is NBA-default
// and would return `/headshots/{id}.png`, which wouldn't resolve here.
function baseballHeadshotUrl(id: string): string {
  return id ? `/baseball/headshots/${id}.png` : "";
}
import { useAuth } from "@shared/auth/useAuth";
import { RegisterModal } from "@shared/components/RegisterModal";

// ─── Card definitions ────────────────────────────────────────────────────────

type LandingCardDef = {
  id: string;
  name: string;
  pos: string;
  salary: number;
  fp: number;
  team: string;
  season: string;
  basePlayerId: string;
  /** Explicit tier — must match production tiers in baseball/public/data/players.json. */
  tier: PlayerCard["tier"];
  achievements: Achievement[];
};

// Tiers, salaries, and avgFP below are sourced from baseball/public/data/players.json
// (regenerated by scripts/recalc-tiers.mjs). Keep in sync if the dataset is regraded.
const CARDS: LandingCardDef[] = [
  // Row 1 — three batters
  {
    id: "c1", name: "Shohei Ohtani", pos: "BAT", salary: 54, fp: 53.6,
    team: "Los Angeles Dodgers", season: "2425", basePlayerId: "660271",
    tier: "RED",
    achievements: [
      { id: "GOING_YARD", icon: "⚾", label: "Going Yard", fp: 8 },
      { id: "PERFECT_DAY", icon: "🌞", label: "Perfect Day", fp: 15 },
    ],
  },
  {
    id: "c2", name: "Fernando Tatis Jr.", pos: "BAT", salary: 44, fp: 43.5,
    team: "San Diego Padres", season: "2425", basePlayerId: "665487",
    tier: "PURPLE",
    achievements: [
      { id: "GOING_YARD", icon: "⚾", label: "Going Yard", fp: 8 },
      { id: "SPEEDSTER", icon: "💨", label: "Speedster", fp: 4 },
    ],
  },
  {
    id: "c3", name: "Freddie Freeman", pos: "BAT", salary: 43, fp: 42.7,
    team: "Los Angeles Dodgers", season: "2425", basePlayerId: "518692",
    tier: "PURPLE",
    achievements: [
      { id: "HIT_MACHINE", icon: "🎯", label: "Hit Machine", fp: 3 },
      { id: "CLEANUP", icon: "🧹", label: "Cleanup Hitter", fp: 8 },
    ],
  },
  // Row 2 — two pitchers
  {
    id: "c4", name: "Tarik Skubal", pos: "P", salary: 73, fp: 73.3,
    team: "Detroit Tigers", season: "2425", basePlayerId: "669373",
    tier: "RED",
    achievements: [
      { id: "ACE", icon: "👑", label: "Ace", fp: 10 },
      { id: "QUALITY_START", icon: "✅", label: "Quality Start", fp: 6 },
    ],
  },
  {
    id: "c5", name: "Garrett Crochet", pos: "P", salary: 66, fp: 66.3,
    team: "Boston Red Sox", season: "2425", basePlayerId: "676979",
    tier: "RED",
    achievements: [
      { id: "ACE", icon: "👑", label: "Ace", fp: 10 },
      { id: "QUALITY_START", icon: "✅", label: "Quality Start", fp: 6 },
    ],
  },
];

// gridColumn for each card index in the 6-column 3+2 layout
const GRID_COLUMNS = ["1 / span 2", "3 / span 2", "5 / span 2", "2 / span 2", "4 / span 2"];

// ─── Component ───────────────────────────────────────────────────────────────

interface Props { onPlay: () => void; }

// Pick one game log per landing card from /baseball/data/game-logs.json,
// then compute its FP + earned badges via sportAdapter. Run once on mount;
// before logs load, the cards still render with avg FP from CARDS so the
// page never flashes "0.0".
type ResolvedLanding = { actualFp: number; statLine: Record<string, number>;
  achievements: Achievement[]; gameInfo: { date: string; opponent: string; homeAway?: "H" | "A" } };

function pickRandomPositiveLog(logs: any[] | undefined): any | null {
  if (!logs || logs.length === 0) return null;
  // Prefer logs with non-trivial FP-relevant stats so the landing card looks
  // alive (not a 0-0-0 night). Fall back to any log if filter is empty.
  const positive = logs.filter(l => {
    const s = l?.stats ?? {};
    return Number(s.h ?? 0) > 0 || Number(s.hr ?? 0) > 0 || Number(s.rbi ?? 0) > 0
      || Number(s.bb ?? 0) > 0 || Number(s.sb ?? 0) > 0
      || Number(s.ip ?? 0) > 0 || Number(s.k ?? 0) > 0;
  });
  const pool = positive.length ? positive : logs;
  return pool[Math.floor(Math.random() * pool.length)];
}

function resolveLandingCard(d: LandingCardDef): ResolvedLanding | null {
  let logsByKey: Map<string, any[]>;
  try { logsByKey = getLogsByKey(); } catch { return null; }
  const candidates =
    logsByKey.get(`${d.basePlayerId}|2425`) ??
    logsByKey.get(d.basePlayerId) ?? [];
  const log = pickRandomPositiveLog(candidates);
  if (!log) return null;
  const stats = { ...(log.stats ?? {}), _position: d.pos };
  const baseFp = sportAdapter.computeFantasyPoints(stats);
  const earned = sportAdapter.computeBadges(stats) as Achievement[];
  const badgeBonus = earned.reduce((s, b: any) => s + (b?.fp ?? 0), 0);
  return {
    actualFp: Math.round((baseFp + badgeBonus) * 10) / 10,
    statLine: stats,
    achievements: earned,
    gameInfo: {
      date: String(log.date ?? ""),
      opponent: String(log.opponent ?? ""),
    },
  };
}

export function LandingPage({ onPlay }: Props) {
  const { isAnonymous, signUp, linkGoogle, signIn, signInGoogle } = useAuth();
  const [showSignIn, setShowSignIn] = useState(false);
  const [flipped, setFlipped] = useState<Set<string>>(new Set());
  const phase: GamePhase = "RESULTS";

  // Per-card resolved game-log state. Empty until dataEngine finishes loading.
  const [resolved, setResolved] = useState<Record<string, ResolvedLanding>>({});

  useEffect(() => {
    let cancelled = false;
    ensureLoaded().then(() => {
      if (cancelled) return;
      const next: Record<string, ResolvedLanding> = {};
      for (const d of CARDS) {
        const r = resolveLandingCard(d);
        if (r) next[d.id] = r;
      }
      setResolved(next);
    }).catch(() => { /* fall through to avg-FP fallback */ });
    return () => { cancelled = true; };
  }, []);

  const handlePlay = useCallback(() => { onPlay(); }, [onPlay]);

  function toggleCard(id: string) {
    setFlipped(prev => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id); else next.add(id);
      return next;
    });
  }

  const playerCards = useMemo(() => {
    return CARDS.map((d, slotIndex) => {
      const cardId = `landing-${d.id}`;
      const r = resolved[d.id];
      return {
        cardId,
        basePlayerId: d.basePlayerId,
        photoCode: d.basePlayerId,
        headshotUrl: baseballHeadshotUrl(d.basePlayerId),
        name: d.name,
        team: d.team,
        season: d.season,
        position: d.pos,
        tier: d.tier,
        salary: d.salary,
        projectedFp: d.fp,
        // Pre-load: show the avg as a placeholder so the FP slot never reads 0.
        // Post-load: real game-log FP including badge bonuses.
        actualFp: r ? r.actualFp : d.fp,
        fpDelta: 0,
        gameInfo: r?.gameInfo ?? { date: "", opponent: "", homeAway: "" as any },
        statLine: r?.statLine ?? {},
        achievements: r?.achievements ?? d.achievements,
        slotIndex,
        wasHeld: false,
      } satisfies PlayerCard;
    });
  }, [resolved]);

  return (
    <div style={{
      background: "linear-gradient(180deg, #070A12 0%, #0A1020 38%, #070A12 100%)",
      color: "#F0F2F5",
      fontFamily: "'Inter', system-ui, sans-serif",
      height: "100dvh", maxHeight: "100dvh", overflow: "hidden",
      display: "flex", flexDirection: "column",
    }}>
      <style>{`
        @keyframes lp-pulse {
          0%,100% { box-shadow: 0 0 0 0 rgba(127,255,0,0); }
          50%     { box-shadow: 0 0 22px 7px rgba(127,255,0,.5); }
        }
        .lp-cta {
          cursor:pointer;
          background: linear-gradient(135deg,#7FFF00 0%,#5BBE00 100%);
          color: #070A12; border: none; border-radius: 2px;
          font-weight: 800; letter-spacing: .12em; text-transform: uppercase;
          font-family: 'Impact','Arial Narrow',Arial,sans-serif;
          animation: lp-pulse 2s ease-in-out infinite;
        }
        .lp-card-inner {
          position: relative; width: 100%; height: 100%;
          transform-style: preserve-3d;
          transition: transform 0.55s cubic-bezier(0.4,0,0.2,1);
        }
        .lp-card-inner.flipped { transform: rotateY(180deg); }
        .lp-card-face {
          position: absolute; inset: 0; border-radius: 14px;
          backface-visibility: hidden; -webkit-backface-visibility: hidden;
          overflow: hidden;
        }
        .lp-card-back { transform: rotateY(0deg); }
        .lp-card-front { transform: rotateY(180deg); }
        @keyframes lp-tap-pulse { 0%,100% { opacity:.4; } 50% { opacity:.9; } }
        @keyframes lp-float {
          0%, 100% { transform: translateY(0); }
          50% { transform: translateY(-5px); }
        }
      `}</style>

      {/* NAV */}
      <nav style={{
        flexShrink: 0, display: "flex", justifyContent: "space-between", alignItems: "center",
        padding: "10px 20px",
      }}>
        <div style={{ fontWeight: 950, fontSize: 22, letterSpacing: -0.5 }}>
          REPLAY <span style={{ color: "#FFB14A" }}>IFS</span>
        </div>
        {isAnonymous && (
          <button
            onClick={() => setShowSignIn(true)}
            aria-label="Sign in"
            style={{
              background: "none", border: "1px solid rgba(255,255,255,0.15)",
              borderRadius: "50%", width: 32, height: 32,
              display: "flex", alignItems: "center", justifyContent: "center",
              cursor: "pointer", color: "rgba(255,255,255,0.5)", fontSize: 15, padding: 0,
            }}
          >
            👤
          </button>
        )}
      </nav>

      {/* MAIN */}
      <main style={{
        flex: 1, minHeight: 0,
        display: "flex", flexDirection: "column", alignItems: "center",
        justifyContent: "center",
        padding: "0 16px env(safe-area-inset-bottom, 12px)", gap: 16, textAlign: "center",
      }}>

        {/* 3+2 CARD GRID — 6-column, row 1: slots 0-2, row 2: slots 3-4 centered */}
        <div style={{
          display: "grid",
          gridTemplateColumns: "repeat(6, 1fr)",
          gap: 6, width: "100%", maxWidth: 340,
        }}>
          {CARDS.map((c, i) => {
            const isFlipped = flipped.has(c.id);
            const card = playerCards[i];
            return (
              <div
                key={c.id}
                onClick={() => toggleCard(c.id)}
                style={{
                  gridColumn: GRID_COLUMNS[i],
                  aspectRatio: "329 / 478",
                  perspective: "800px",
                  cursor: "pointer",
                  animation: `lp-float ${1.8 + i * 0.2}s ease-in-out infinite`,
                }}
              >
                <div className={`lp-card-inner${isFlipped ? " flipped" : ""}`}>
                  {/* Back (face-down) — generic card back with logo */}
                  <div className="lp-card-face lp-card-back">
                    <CardBackGeneric />
                    {!isFlipped && (
                      <span style={{
                        position: "absolute", top: "16%", left: 0, right: 0, textAlign: "center",
                        fontSize: 8, fontWeight: 800, letterSpacing: 2, textTransform: "uppercase",
                        color: "rgba(255,255,255,0.35)",
                        animation: "lp-tap-pulse 1.8s ease-in-out infinite",
                        zIndex: 2,
                      }}>TAP</span>
                    )}
                  </div>
                  {/* Front (face-up) — real in-game card with headshot */}
                  <div className="lp-card-face lp-card-front">
                    <BaseballCard
                      card={card}
                      phase={phase}
                      canFlip={false}
                      noTransition
                      visibleFp={card.actualFp}
                      badges={(card.achievements ?? []).map(a => ({
                        id: a.id,
                        icon: a.icon || "⭐",
                        label: a.label,
                        fp: a.fp ?? 0,
                      }))}
                    />
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {/* HEADLINE + CTA */}
        <div style={{ maxWidth: 360, display: "flex", flexDirection: "column", alignItems: "center", gap: 14 }}>
          <p style={{
            fontSize: 10, fontWeight: 700, letterSpacing: ".3em", textTransform: "uppercase",
            color: "#C9A84C", margin: 0,
          }}>
            Beta · Free to Play · No Sign-Up
          </p>
          {showSignIn && (
            <RegisterModal
              signInMode
              onClose={() => setShowSignIn(false)}
              onSuccess={() => setShowSignIn(false)}
              signUp={signUp}
              linkGoogle={linkGoogle}
              signIn={signIn}
              signInGoogle={signInGoogle}
            />
          )}
          <h1 style={{
            fontFamily: "'Impact','Arial Narrow',Arial,sans-serif", fontWeight: 900,
            fontSize: "clamp(24px, 5vw, 40px)", textTransform: "uppercase", lineHeight: 0.95, margin: 0,
          }}>
            You already know who balled out.<br />
            <em style={{ color: "#C9A84C", fontStyle: "normal" }}>Prove it.</em>
          </h1>
          <p style={{ fontSize: 12, color: "rgba(240,242,245,0.38)", lineHeight: 1.6, margin: 0 }}>
            Real stats. Real history. Your fantasy result instantly.
          </p>
          <button className="lp-cta" onClick={handlePlay} style={{ padding: "14px 52px", fontSize: 16 }}>
            Play IFS
          </button>
          <span style={{ fontSize: 10, color: "rgba(240,242,245,0.38)" }}>
            <span style={{ color: "#7FFF00" }}>✓</span> Skill based &nbsp;·&nbsp;
            <span style={{ color: "#7FFF00" }}>✓</span> Fantasy &nbsp;·&nbsp;
            <span style={{ color: "#7FFF00" }}>✓</span> Instant results
          </span>
        </div>
      </main>
    </div>
  );
}
