/**
 * baseball/src/components/LandingPage.tsx — sport-specific shim.
 *
 * Renders @shared/components/LandingPage with a baseball-flavored adapter:
 * the demo roster (3 batters + 2 pitchers), the BaseballCard renderer, a
 * local headshot URL builder, a 3+2 centered grid, and a real-game-log
 * resolver that swaps avg FP for a randomly-picked positive game once
 * dataEngine finishes loading. No audio bed (baseball ships none).
 */
import { useMemo } from "react";
import { LandingPage as SharedLandingPage } from "@shared/components/LandingPage";
import type { LandingAdapter, LandingCardDef, LandingResolved } from "@shared/components/LandingPage";
import type { Achievement } from "../adapters/types";
import { BaseballCard } from "./BaseballCard";
import { ensureLoaded, getLogsByKey } from "../engines/dataEngine";
import { sportAdapter } from "../adapters/SportAdapter";

// Baseball ships local headshots at /baseball/headshots/{id}.png. Vite serves
// the public/ folder at the SPA's base path (`/baseball/`), so an absolute
// URL is what the browser needs. The shared headshotUrl helper is NBA-default
// and would return `/headshots/{id}.png`, which wouldn't resolve here.
function baseballHeadshotUrl(id: string): string {
  return id ? `/baseball/headshots/${id}.png` : "";
}

// Tiers, salaries, and avgFP below are sourced from baseball/public/data/players.json
// (regenerated by scripts/recalc-tiers.mjs). Keep in sync if the dataset is regraded.
const CARDS: LandingCardDef[] = [
  // Row 1 — three batters
  {
    id: "c1", name: "Shohei Ohtani", pos: "BAT", salary: 54, fp: 53.6,
    team: "Los Angeles Dodgers", season: "2425", basePlayerId: "660271",
    tier: "RED",
    achievements: [
      { id: "GOING_YARD", icon: "⚾", label: "Going Yard", fp: 8 },
      { id: "PERFECT_DAY", icon: "🌞", label: "Perfect Day", fp: 15 },
    ],
  },
  {
    id: "c2", name: "Fernando Tatis Jr.", pos: "BAT", salary: 44, fp: 43.5,
    team: "San Diego Padres", season: "2425", basePlayerId: "665487",
    tier: "PURPLE",
    achievements: [
      { id: "GOING_YARD", icon: "⚾", label: "Going Yard", fp: 8 },
      { id: "SPEEDSTER", icon: "💨", label: "Speedster", fp: 4 },
    ],
  },
  {
    id: "c3", name: "Freddie Freeman", pos: "BAT", salary: 43, fp: 42.7,
    team: "Los Angeles Dodgers", season: "2425", basePlayerId: "518692",
    tier: "PURPLE",
    achievements: [
      { id: "HIT_MACHINE", icon: "🎯", label: "Hit Machine", fp: 3 },
      { id: "CLEANUP", icon: "🧹", label: "Cleanup Hitter", fp: 8 },
    ],
  },
  // Row 2 — two pitchers
  {
    id: "c4", name: "Tarik Skubal", pos: "P", salary: 73, fp: 73.3,
    team: "Detroit Tigers", season: "2425", basePlayerId: "669373",
    tier: "RED",
    achievements: [
      { id: "ACE", icon: "👑", label: "Ace", fp: 10 },
      { id: "QUALITY_START", icon: "✅", label: "Quality Start", fp: 6 },
    ],
  },
  {
    id: "c5", name: "Garrett Crochet", pos: "P", salary: 66, fp: 66.3,
    team: "Boston Red Sox", season: "2425", basePlayerId: "676979",
    tier: "RED",
    achievements: [
      { id: "ACE", icon: "👑", label: "Ace", fp: 10 },
      { id: "QUALITY_START", icon: "✅", label: "Quality Start", fp: 6 },
    ],
  },
];

// gridColumn for each card index in the 6-column 3+2 layout
const GRID_COLUMNS = ["1 / span 2", "3 / span 2", "5 / span 2", "2 / span 2", "4 / span 2"];

function pickRandomPositiveLog(logs: any[] | undefined, pos: string): any | null {
  if (!logs || logs.length === 0) return null;
  const isPitcher = sportAdapter.isPitcherPosition(pos);
  // Role-aware filter: BAT cards must pull a log with batter events; P cards
  // must pull a log where the player actually pitched. Two-way players (Ohtani
  // et al.) have separate batter + pitcher entries on the same date — without
  // this filter a BAT card can grab the pitcher line and render a 0/0/0
  // batter stat-back ("no game log"). Landing tightens further to require
  // marquee stats (h/hr/rbi/sb/2B/3B for BAT, ip+k for P) so the showcase
  // always looks alive — no walk-and-scored-only nights.
  const role = logs.filter(l => {
    const s = l?.stats ?? {};
    if (isPitcher) {
      return Number(s.ip ?? 0) > 0 && Number(s.k ?? 0) > 0;
    }
    return Number(s.h ?? 0) > 0 || Number(s.hr ?? 0) > 0 || Number(s.rbi ?? 0) > 0
      || Number(s.sb ?? 0) > 0 || Number(s.doubles ?? 0) > 0 || Number(s.triples ?? 0) > 0;
  });
  const pool = role.length ? role : logs;
  return pool[Math.floor(Math.random() * pool.length)];
}

function resolveLandingActuals(d: LandingCardDef): LandingResolved | null {
  let logsByKey: Map<string, any[]>;
  try { logsByKey = getLogsByKey(); } catch { return null; }
  const candidates =
    logsByKey.get(`${d.basePlayerId}|2425`) ??
    logsByKey.get(d.basePlayerId) ?? [];
  const log = pickRandomPositiveLog(candidates, d.pos);
  if (!log) return null;
  const stats = { ...(log.stats ?? {}), _position: d.pos };
  const baseFp = sportAdapter.computeFantasyPoints(stats);
  const earned = sportAdapter.computeBadges(stats) as Achievement[];
  const badgeBonus = earned.reduce((s, b: any) => s + (b?.fp ?? 0), 0);
  return {
    actualFp: Math.round((baseFp + badgeBonus) * 10) / 10,
    statLine: stats,
    achievements: earned,
    gameInfo: {
      date: String(log.date ?? ""),
      opponent: String(log.opponent ?? ""),
    },
  };
}

interface Props {
  onPlay: () => void;
  onShowProfile?: () => void;
  onShowSignIn?: () => void;
}

export function LandingPage({ onPlay, onShowProfile, onShowSignIn }: Props) {
  const adapter = useMemo<LandingAdapter>(() => ({
    landingCards: CARDS,
    landingHeadshotUrl: baseballHeadshotUrl,
    landingCardComponent: BaseballCard,
    landingGridLayout: {
      templateColumns: "repeat(6, 1fr)",
      gridColumnFor: (i) => GRID_COLUMNS[i],
    },
    landingAudioBedSrc: null,
    // Each card already ships an explicit tier — return it; landingTierFor is
    // only consulted when d.tier is undefined.
    landingTierFor: (d) => d.tier ?? "WHITE",
    ensureLandingDataLoaded: () => ensureLoaded(),
    resolveLandingActuals,
  }), []);
  return <SharedLandingPage adapter={adapter} onPlay={onPlay} onShowProfile={onShowProfile} onShowSignIn={onShowSignIn} />;
}
