/**
 * culture_pilot_review.ts — Generated culture entries (pilot mode)
 * Generated: 2026-05-16T17:42:08.142Z
 * Canary: CULTURE_PILOT_V1_20260517
 *
 * REVIEW each entry. Do NOT auto-merge into playerCulture.ts.
 */

// Paul Pierce — basePlayerId 1718 — teams: BOS
  pierce_1718: {
    basePlayerId: "1718",
    nicknames: ["The Truth", "PP"],
    knownFor: "The clutch Celtic who carried Boston to the '08 title and never let you forget it.",
    salaryTier: "star",
    tier1: ["34 straight Finals appearances. Wheelchair game in '08. The Truth verified.", "Hit clutch shots for eighteen seasons. Retired his own jersey in his mind daily."],
    tier2: ["Outdueled LeBron in the '08 playoffs when it mattered most. Never stopped talking about it.", "The stepback jumper was automatic. Kobe's toughest Eastern Conference matchup for a decade."],
    tier3: ["Predicted his own HOF speech in real time. The confidence was earned, the delivery was Pierce."],
    overperform: ["When Pierce got hot, the trash talk volume went to eleven. Age never dulled the daggers.", "The old man still had range. Father Time got the stepover treatment too."],
    underperform: ["Even The Truth had off nights. The shot selection stayed aggressive regardless.", "Pierce never met a contested jumper he didn't like. Live by it, die by it."],
    onPace: ["Vintage Pierce. The midrange was money, the confidence was maximum.", "Another night of Pierce being Pierce. Clutch gene stays active forever."],
    turnovers: ["Pierce forced passes like he forced shots. The confidence cut both ways."],
    defensive: ["Could guard multiple positions when motivated. Playoff Pierce was a different defender."],
    bigGame: ["48 points against New Jersey in December 2001. The Garden went nuclear.", "74.9 fantasy points on pure shooting violence. This is why they called him The Truth.", "When Pierce locked in, the Celtics became must-watch television."],
    quietGame: ["Even legends have human nights. Pierce's floor was still competitive.", "The shots weren't falling, but the confidence never wavered."],
    famousGameHint: ["50 points in Cleveland, February 2006. Overtime thriller that broke the building.", "LeBron was watching from the other bench. Pierce was making statements.", "Some performances age like wine. This one aged like championship vindication."],
    controversy: ["The wheelchair game became meme material, but he came back and won the title.", "Never backed down from calling himself better than Kobe. The audacity was legendary.", "Said he had a better career than Dwyane Wade. The debates still rage.", "Retired as a Celtic, played elsewhere. Some exits aren't as clean as the legacy."],
    formerTeam: ["Never played his former team because he never left Boston until the sunset years."],
    rivalry: ["Lakers-Celtics was personal for Pierce. Kobe brought out his absolute best.", "The LeBron rivalry defined the late 2000s East. Pierce usually got the last laugh."],
    milestones: ["26,000 career points as mostly a Celtic. The franchise's modern scoring king.", "Hall of Fame lock who never needed voters to validate his confidence."],
    streakLines: ["Hot Pierce was appointment television. The confidence became infectious for teammates.", "Cold streaks never changed his shot selection. The next one was always going in.", "Pierce in the zone was unstoppable. The Truth became self-evident."],
    salaryNarrative: ["At $49, Pierce delivers clutch value. The veteran presence pays dividends.", "Star money for a player who defined what star meant in Boston for two decades."],
    teamContext: ["Drafted by Boston, became Boston. The perfect marriage of player and city.", "Carried the franchise through the rebuilding years until KG and Allen arrived."],
    draftAndPath: ["10th overall in '98. The Celtics hit on their franchise cornerstone.", "Kansas product who became the ultimate Celtic. Some fits are destiny."],
    opponentFlavor: { LAL: "Kobe's equal in his own mind. The rivalry was real, the results were split.", MIA: "LeBron's biggest Eastern Conference headache until The Decision moved him.", CLE: "Dropped 50 on their home court. Made them remember Boston's excellence.", NYK: "Madison Square Garden became his personal highlight reel venue.", PHI: "Iverson battles were must-see TV. Two alphas, zero backing down." },
    signatureGames: [
      { date: "2001-12-01", opponent: "NJN", fp: 74.9, line: "48p/12r/1a - The Garden erupted" },
      { date: "2003-12-13", opponent: "CLE", fp: 74.8, line: "41p/9r/6a - Peak Truth mode" },
      { date: "2002-12-20", opponent: "MIN", fp: 73.8, line: "42p/14r/4a - Complete domination" },
      { date: "2006-02-15", opponent: "CLE", fp: 66.4, line: "50p/7r/8a - Career high explosion" },
      { date: "2005-02-02", opponent: "NJN", fp: 69, line: "28p/10r/10a - Triple-double excellence" },
    ],
    teamEras: {
      BOS: {
        framing: ["The Boston Pierce is the only Pierce that matters. Eighteen seasons, one banner, forever Celtic.", "From lottery years to championship glory. The Truth carried the franchise on his back.", "Garden favorite who never met a clutch shot he couldn't hit. Banner 17 happened because of him."],
        bigGameVariant: "Garden eruption incoming. Pierce owned that building like he paid the mortgage.",
        quietGameVariant: "Even in Boston, The Truth had human nights. The crowd stayed patient.",
      },
    },
  },

// LaMarcus Aldridge — basePlayerId 200746 — teams: POR/SAS
  aldridge_200746: {
    basePlayerId: "200746",
    nicknames: ["LMA", "L-Train"],
    knownFor: "The midrange master who carried Portland and anchored San Antonio's twilight years.",
    salaryTier: "role",
    tier1: ["Seven All-Star selections powered by the most reliable midrange shot of the 2010s.", "Portland's franchise centerpiece who almost single-handedly kept them competitive."],
    tier2: ["The Spurs signing was supposed to be dynasty extension. Father Time had other plans.", "Texas two-step master. The footwork was poetry, the results were automatic."],
    tier3: ["Retired mid-season in 2021 due to heart concerns. Health always comes first."],
    overperform: ["When LMA got going, the midrange became a layup line. Vintage shot-making clinic.", "The old-school game still worked. Analytics never solved fundamental excellence."],
    underperform: ["The shots weren't falling, but the attempts kept coming. LMA lived in his spots.", "Even master craftsmen have off nights. The next game was always a reset."],
    onPace: ["Classic Aldridge efficiency. The midrange money was always reliable.", "Steady production from a player who defined consistency for a decade-plus."],
    turnovers: ["LMA protected the ball like fine china. Fundamentals were his religion."],
    defensive: ["Solid rim protection when engaged. The Spurs system made him look even better."],
    bigGame: ["56 points against OKC in January 2019. The vintage performance nobody saw coming.", "At 33, LMA reminded everyone why he was a seven-time All-Star.", "The Thunder had no answer for the midrange clinic. Pure basketball artistry."],
    quietGame: ["Even fundamental masters have quiet nights. LMA never forced bad shots.", "The efficiency stayed high even when the volume dropped."],
    famousGameHint: ["31 points, 25 rebounds against Houston, December 2013. The glass was his property.", "Dwight Howard was in the building. LMA put on a rebounding masterclass.", "Some nights the ball just finds you. This was one of those nights."],
    controversy: ["Left Portland after promising loyalty. The small-market curse claimed another star.", "The Spurs years never reached championship level. High expectations, modest results.", "Abrupt retirement raised questions about NBA health protocols. Valid concerns all around."],
    formerTeam: ["Facing Portland was always emotional. The Moda Center crowd gave him respect.", "The relationship ended badly, but the basketball memories were pure."],
    rivalry: ["The Blake Griffin duels were underrated. Two power forwards, different styles.", "Houston matchups were always physical. The Southwest Division battles were real."],
    milestones: ["20,000 career points on pure skill. No athleticism shortcuts needed.", "Seven All-Star selections earned through consistent excellence, not highlights."],
    streakLines: ["Hot LMA was automatic money. The midrange became unstoppable when he locked in.", "Cold streaks never lasted long. The fundamentals always brought him back.", "Peak Aldridge was must-watch basketball. Old-school excellence in a modern game."],
    salaryNarrative: ["At $33, LMA offers reliable veteran production. The midrange mastery never expires.", "Role-player pricing for a former All-Star. The value proposition writes itself."],
    teamContext: ["The Brooklyn tenure was brief but meaningful. Heart issues ended the story early.", "Always found ways to contribute regardless of the situation or system."],
    draftAndPath: ["Second overall in 2006. The Blazers built their future around his skill set.", "Texas product who found his NBA home in unlikely places. Fundamentals travel well."],
    opponentFlavor: { OKC: "Career-high 56 points proved he could still dominate elite competition.", HOU: "25 rebounds against the Rockets showed his complete skill set.", GSW: "The Warriors couldn't solve his midrange game in the playoffs.", LAL: "Always played well in Los Angeles. The big stage brought out his best.", DEN: "Altitude never bothered his shot. Mile High became a favorite venue." },
    signatureGames: [
      { date: "2019-01-10", opponent: "OKC", fp: 79.8, line: "56p/9r/4a - Career-high explosion" },
      { date: "2013-12-12", opponent: "HOU", fp: 75, line: "31p/25r/2a - Rebounding masterpiece" },
      { date: "2019-03-24", opponent: "BOS", fp: 72.6, line: "48p/13r/6a - Vintage performance" },
      { date: "2014-01-23", opponent: "DEN", fp: 71.1, line: "44p/13r/5a - Mile High domination" },
      { date: "2013-11-23", opponent: "GSW", fp: 69.7, line: "30p/21r/3a - Complete excellence" },
    ],
    teamEras: {
      POR: {
        framing: ["The Portland LMA was franchise basketball. Seven seasons of carrying the city's hopes.", "Rip City's foundation for nearly a decade. The midrange kept them competitive nightly.", "Before the departure drama, he was their everything. The loyalty meant something then."],
        bigGameVariant: "Moda Center magic was real. LMA owned that building for years.",
        quietGameVariant: "Even quiet nights in Portland felt significant. The expectations were massive.",
      },
      SAS: {
        framing: ["The Spurs LMA was supposed to extend the dynasty. Good player, wrong timing.", "San Antonio's bridge between eras. The fundamentals fit, the results were mixed.", "Pop's system made him more efficient. The championships never followed though."],
        bigGameVariant: "AT&T Center appreciation night. 56 against OKC was vintage excellence.",
        quietGameVariant: "The Spurs system covered quiet nights. Team-first basketball worked.",
      },
    },
  },

// Pau Gasol — basePlayerId 2200 — teams: CHI/LAL/MEM
  gasol_2200: {
    basePlayerId: "2200",
    nicknames: ["The Spanish Tower", "Pau Pau"],
    knownFor: "The European big who helped Kobe win two titles and proved skilled centers could still dominate.",
    salaryTier: "value",
    tier1: ["Two rings with Kobe's Lakers. The skilled big man who made triangle offense sing again.", "Six All-Star games, Rookie of the Year, Hall of Fame resume. European royalty."],
    tier2: ["The Grizzlies trade that changed everything. Memphis got a franchise, LA got championships.", "22-year career across four countries. The globalization of basketball in human form."],
    tier3: ["14 assists against Portland in 2016 at age 35. Point-center before it was cool."],
    overperform: ["46 points against Milwaukee in 2015. The vintage performance nobody saw coming.", "When the shot-blocking and passing click, he's 2009 Pau with gray in his beard."],
    underperform: ["The post-Lakers years were a slow fade. Chicago couldn't recreate the magic.", "Father Time catching the European game. The footwork's there, the explosion isn't."],
    onPace: ["Double-double reliability for two decades. The consistency that made him championship caliber.", "18 and 9 with blocks and assists. The complete big man package, delivered nightly."],
    turnovers: ["The ambitious passer who'd thread needles and hit brick walls. High-risk, high-reward."],
    defensive: ["Rim protection with positioning over athleticism. The thinking man's shot-blocker."],
    bigGame: ["72 fantasy points twice in his career peak. The skilled big dominating every category.", "27 points, 18 rebounds, 7 assists against Utah in '06. The complete performance.", "Triple-doubles from the five spot. The point-center blueprint before Jokic."],
    quietGame: ["The efficient nights that don't make highlights. 12 points, 8 rebounds, two blocks."],
    famousGameHint: ["46 points against Milwaukee in January 2015. The vintage explosion at age 34.", "22 rebounds against New Orleans in 2010. The glass-cleaning masterclass."],
    controversy: ["The soft label that never stuck. European finesse mistaken for lack of toughness.", "Left Memphis for championships. The small-market departure that built two dynasties.", "The triangle offense's last great practitioner. Phil Jackson's final championship ingredient."],
    formerTeam: ["Facing Memphis meant facing the past. The franchise he helped build watching him leave."],
    rivalry: ["Celtics-Lakers Finals. The Big Three versus the Spanish Tower and Kobe."],
    milestones: ["First European to win Finals MVP voting consideration. The international breakthrough."],
    streakLines: ["Hot Pau means triple-double alerts and vintage footwork. The skilled big awakening.", "Cold stretches expose the aging legs. When the shots won't fall, Father Time whispers.", "Five triple-doubles in 22 seasons. The passing big man before it was trendy."],
    salaryNarrative: ["$19 salary reflects the sunset years. Value play for teams needing veteran presence.", "The championship pedigree at discount prices. Hall of Fame resume, role-player cost."],
    teamContext: ["The international big man who proved European skills translated to championship basketball."],
    draftAndPath: ["Third overall by Atlanta, traded to Memphis draft night. The franchise-altering deal."],
    opponentFlavor: { SAS: "Tim Duncan battles. Fundamentals versus fundamentals, decided by inches.", MIL: "Career-high games waiting to happen. Milwaukee brings out vintage Pau.", UTA: "The Jazz frontcourt matchups. Big men who could pass and shoot.", DET: "Pistons defensive tests. The Eastern Conference gauntlet years.", POR: "14 assists against Portland in 2016. Point-center mastery on display." },
    signatureGames: [
      { date: "2006-01-06", opponent: "UTA", fp: 72.1, line: "27p/18r/7a/4b" },
      { date: "2015-01-10", opponent: "MIL", fp: 72.1, line: "46p/18r/3a" },
      { date: "2010-02-08", opponent: "SAS", fp: 71.8, line: "21p/19r/8a/5b" },
      { date: "2006-03-08", opponent: "SEA", fp: 71.4, line: "21p/12r/12a/3b" },
      { date: "2016-02-27", opponent: "POR", fp: 71.2, line: "22p/16r/14a/3b" },
    ],
    teamEras: {
      MEM: {
        framing: ["The cornerstone years. Seven seasons building Memphis into relevance.", "Rookie of the Year, first All-Star game, the foundation of Grizzlies basketball."],
        bigGameVariant: "Triple-double against Seattle in '06. The point-center prototype in Memphis.",
        quietGameVariant: "The steady production that built a franchise. 18 and 9 nightly.",
      },
      LAL: {
        framing: ["The championship years. Two titles with Kobe, triangle offense mastery.", "The trade that changed everything. Gasol-Odom-Bynum frontcourt dominance."],
        bigGameVariant: "19 rebounds against San Antonio in 2010. Finals-level intensity.",
        quietGameVariant: "Championship consistency. The reliable second option behind Kobe.",
      },
      CHI: {
        framing: ["The veteran leader years. Trying to recapture magic in the post-Rose era.", "Three seasons of steady production. The elder statesman mentoring young Bulls."],
        bigGameVariant: "46 points against Milwaukee in 2015. Vintage performance at 34.",
        quietGameVariant: "The professional approach. 18 and 11 while teaching youngsters.",
      },
    },
  },

// Vince Carter — basePlayerId 1713 — teams: NJN/TOR
  carter_1713: {
    basePlayerId: "1713",
    nicknames: ["Vinsanity", "Air Canada", "Half-Man Half-Amazing"],
    knownFor: "The dunk contest king who put Toronto on the map then became the ultimate professional.",
    salaryTier: "max",
    tier1: ["The 2000 dunk contest. Eight dunks that changed basketball forever.", "Rookie of the Year, eight All-Star games, 22 seasons. Longevity and athleticism personified."],
    tier2: ["Dunked over 7-foot Frederic Weis in the Olympics. The dunk that broke the internet.", "From Vinsanity to veteran leadership. The career arc nobody saw coming.", "North Carolina legend who brought showtime to Toronto. The highlight reel come to life."],
    tier3: ["Last player from the 1990s to retire. The bridge between Jordan and LeBron eras."],
    overperform: ["87 fantasy points against Washington in '07. The vintage explosion at age 30.", "When the legs still had bounce, every game was appointment television.", "51-point games in different decades. The athletic prime that lasted forever."],
    underperform: ["The playoff shortcomings that defined early career. Spectacular regular season, invisible April.", "Accused of not trying in Toronto's final season. The effort questions that stuck."],
    onPace: ["25 and 5 with highlight dunks. The reliable scoring punch for two decades.", "Professional veteran doing professional veteran things. No drama, just production."],
    turnovers: ["The ambitious drives that ended in turnovers. High-flying risk with high-flying reward."],
    defensive: [],
    bigGame: ["46 points, 16 rebounds, 10 assists against Washington. The triple-double masterpiece.", "51 points against Phoenix and Miami. The half-century club in different uniforms.", "42 points with 12 assists against New Orleans. The complete offensive showcase."],
    quietGame: ["The veteran nights of 12 and 4. Professional production without the fireworks."],
    famousGameHint: ["51 points against Phoenix in February 2000. The coming-out party in year two.", "46-16-10 against Washington in 2007. The complete performance few remember.", "42 points with 15 rebounds against Denver in 2001. Peak Vinsanity on full display."],
    controversy: ["The Toronto exit that scarred a fanbase. Admitted to not trying his final season.", "From savior to villain in one trade demand. The relationship that never healed.", "Graduation ceremony over playoff game seven. Priorities that raised eyebrows.", "The dunking decline that marked Father Time's arrival. When bounce becomes memory.", "22 seasons without a ring. The individual brilliance that never found team success."],
    formerTeam: ["Facing Toronto meant facing the complicated legacy. Boos that lasted decades.", "The relationship that defined two franchises. Hero to villain to respected elder."],
    rivalry: ["Nets-Pistons playoff battles. Eastern Conference wars in the post-Jordan era."],
    milestones: ["25,000 career points across four decades. The longevity few saw coming."],
    streakLines: ["Hot Vince meant highlight reels and 40-point eruptions. The athletic prime unleashed.", "Cold stretches exposed the jump-shot dependence. When dunks disappeared, consistency wavered.", "Five triple-doubles in 22 seasons. The complete games few remember from the dunker."],
    salaryNarrative: ["$60 max salary reflects the peak Toronto years. Vinsanity commanded premium prices.", "The franchise player investment that didn't deliver rings. Maximum dollars, maximum expectations."],
    teamContext: ["The cornerstone who put Toronto basketball on the global map. Canada's first superstar."],
    draftAndPath: ["Fifth overall to Golden State, traded to Toronto draft night. The deal that changed everything."],
    opponentFlavor: { WAS: "Career-best 87 fantasy points in 2007. Washington brought out vintage Vince.", MIL: "48 points in Milwaukee, 2000. The breakout performance that announced arrival.", PHX: "51 points against Phoenix. The half-century club inauguration game.", DEN: "42 points, 15 rebounds in 2001. Peak athleticism on Rocky Mountain display.", MIA: "51 points against the Heat. The second member of his exclusive club." },
    signatureGames: [
      { date: "2007-04-07", opponent: "WAS", fp: 87.2, line: "46p/16r/10a/3b" },
      { date: "2001-12-07", opponent: "DEN", fp: 86, line: "42p/15r/6a/5s" },
      { date: "2000-11-18", opponent: "MIL", fp: 79, line: "48p/10r/4a/3s" },
      { date: "2000-02-27", opponent: "PHX", fp: 67.3, line: "51p/9r/1a/3s" },
      { date: "2005-12-23", opponent: "MIA", fp: 64.6, line: "51p/8r/4a" },
    ],
    teamEras: {
      TOR: {
        framing: ["The Vinsanity era. Dunk contest legend who made Toronto appointment television.", "Eight seasons of highlights and heartbreak. The relationship that ended badly.", "Air Canada soaring over SkyDome. The athletic prime that defined a generation."],
        bigGameVariant: "51 points against Phoenix in 2000. The breakout performance that announced stardom.",
        quietGameVariant: "The nights between highlights. 22 and 5 while building a fanbase.",
      },
      NJN: {
        framing: ["The mature wing years. Post-dunk contest Vince learning to be a complete player.", "Five seasons of playoff basketball. The veteran leadership Brooklyn needed.", "Half-Man Half-Professional. The evolution from dunker to dependable scorer."],
        bigGameVariant: "46-16-10 against Washington in 2007. The complete performance at age 30.",
        quietGameVariant: "The steady veteran production. 23 and 6 without the circus dunks.",
      },
    },
  },

// Stephon Marbury — basePlayerId 950 — teams: undefined
  marbury_950: {
    basePlayerId: 950,
    nicknames: ["Starbury", "Steph"],
    knownFor: "Brooklyn point guard who had the talent but never the rings.",
    salaryTier: "max",
    tier1: ["The fourth pick who could score 40 any night. Chemistry was optional.", "Five teams in 13 years tells the whole story about his NBA arc."],
    tier2: ["Averaged 20 and 8 for a decade, never won a playoff series as the main guy.", "The China years rehabilitated his reputation better than his NBA tenure did."],
    tier3: ["The And1 Mixtape Tour aesthetic in an NBA body."],
    overperform: ["When Starbury hit his ceiling, 50-point nights happened. The Knicks years had flashes.", "He could still run point at an elite level when the mood struck him."],
    underperform: ["The talent screamed All-NBA. The results whispered role player.", "Too much me, not enough we. Brooklyn attitude meets team sport reality."],
    onPace: ["Starbury doing Starbury things. Twenty and eight, some turnovers, no defense.", "The floor was always high. The ceiling stayed theoretical."],
    turnovers: ["Five turnovers against the Lakers trying to prove he belonged with Kobe.", "Point guards who hunt their own shot tend to lose track of everyone else's."],
    defensive: [],
    bigGame: ["50 against the Lakers in 2001, 12 assists included. Peak Starbury theater.", "The February 13th line that reminded you what Brooklyn point guards could do.", "Kobe got 30 that night. Marbury got 50. The W still went to LA."],
    quietGame: ["Even his quiet nights featured eight assists. The floor was never that low.", "Fifteen and six feels underwhelming when you're built for 40-point explosions."],
    famousGameHint: ["That 50-point night against the Lakers included 12 assists and 5 turnovers.", "February 2001 in Phoenix when he reminded everyone why he was drafted fourth.", "Kobe was watching from the other sideline. The student outscored the master."],
    controversy: ["Five teams in 13 years because talent and chemistry don't always shake hands.", "The Knicks tenure was reality TV with basketball interruptions.", "Called out teammates, coaches, front offices. Brooklyn honesty meets corporate diplomacy.", "The China years proved he could lead when the spotlight wasn't quite so bright.", "Vaseline on his face, sneakers for $15. The people's champion who couldn't win for the people."],
    formerTeam: ["Playing your old team meant 30 shots and zero conscience.", "Former teammates got the full Starbury experience. No mercy for old friends."],
    rivalry: ["The Kidd comparisons haunted him. Different Brooklyn, same point guard debate.", "Every Knicks-Nets game was personal. The borough's basketball honor at stake."],
    milestones: ["Hit 16,000 career points. The numbers were never the problem.", "Five All-Star games in seven years. Peak Starbury was undeniable."],
    streakLines: ["When Starbury got hot, 25-game stretches of elite point guard play emerged.", "Cold streaks meant team meetings and trade rumors. The volatility was real.", "The 2003 Phoenix run where he averaged 25 and 9 for two months straight."],
    salaryNarrative: ["Max money for max talent. The results were negotiable, the salary wasn't.", "Fifty-six dollars for a point guard who could go for 50. Fair market value.", "Brooklyn's finest export commanding top dollar. The entertainment value was guaranteed."],
    teamContext: ["Every team thought they could fix the chemistry. Every team was wrong.", "The talent was obvious. The fit was theoretical."],
    draftAndPath: ["Fourth overall in 1996. Georgia Tech one-and-done before it was trendy.", "Brooklyn to Minnesota to New Jersey to Phoenix to New York. The basketball nomad."],
    opponentFlavor: { LAL: "50 against Kobe's Lakers. The night Starbury reminded LA what Brooklyn looked like.", CHI: "His only triple-double came against the Bulls. 33, 11, and 12 in 39 minutes.", SAS: "43 against the Spurs in 2002. Even Pop's system couldn't contain peak Starbury.", ATL: "38 and 9 in 51 minutes against the Hawks. The March 2007 marathon special.", IND: "Twenty assists against the Pacers in 1999. The floor general at his finest." },
    signatureGames: [
      { date: "2007-03-03", opponent: "ATL", fp: 74.5, line: "38p/5r/9a/5s in 51 minutes" },
      { date: "2003-12-29", opponent: "LAC", fp: 71.3, line: "40p/4r/9a/5s in 41 minutes" },
      { date: "2001-02-13", opponent: "LAL", fp: 66.6, line: "50p/3r/12a in 47 minutes" },
      { date: "2003-01-17", opponent: "DAL", fp: 68.3, line: "41p/4r/11a in 46 minutes" },
      { date: "1999-02-17", opponent: "HOU", fp: 68.8, line: "40p/4r/12a in 40 minutes" },
    ],
    teamEras: {
      MIN: {
        framing: ["The rookie season with KG. Two Brooklyn kids trying to build something in Minneapolis.", "Averaged 15 and 8 as a teenager. The talent was obvious from day one.", "The trade to New Jersey after two years. Minnesota couldn't wait for the chemistry."],
        bigGameVariant: "Forty against Houston in his second year. The teenager could score with anyone.",
        quietGameVariant: "Quiet nights in Minnesota still featured eight assists. The floor was high early.",
      },
      NJN: {
        framing: ["The Jason Kidd replacement experiment. Different point guard, different results.", "Two years in Jersey trying to be the floor general Kidd was naturally.", "The Phoenix trade that saved his career. New Jersey wasn't built for Starbury ball."],
        bigGameVariant: "Forty-three against the Knicks in 2003. MSG knew exactly what Brooklyn looked like.",
        quietGameVariant: "Even his quiet Jersey nights featured the Starbury flair. Style over substance.",
      },
      PHX: {
        framing: ["The Mike D'Antoni marriage made in basketball heaven. Finally, a system for Starbury.", "Two All-Star years running Steve Nash's old offense. The talent fit the pace.", "The brief window where everything clicked. Phoenix unlocked peak Marbury basketball."],
        bigGameVariant: "Fifty against the Lakers in Phoenix. The night Starbury outscored Kobe on his home court.",
        quietGameVariant: "Quiet Phoenix nights still featured 20 and 8. The system maximized his gifts.",
      },
      NYK: {
        framing: ["The homecoming that became a soap opera. Madison Square Garden, meet Starbury.", "Isaiah Thomas thought star power could overcome chemistry. The experiment failed publicly.", "Five years of drama, some highlights, zero playoff series wins. New York, naturally."],
        bigGameVariant: "Thirty-eight in 51 minutes against the Hawks. MSG marathons were Starbury specialty.",
        quietGameVariant: "Quiet Knicks nights still made back-page headlines. The New York pressure was real.",
      },
    },
  },

// Reggie Miller — basePlayerId 397 — teams: undefined
  miller_397: {
    basePlayerId: 397,
    nicknames: ["The Knick Killer", "Reg"],
    knownFor: "Indiana's shooter who turned Madison Square Garden into his personal playground.",
    salaryTier: "role",
    tier1: ["Eight points in nine seconds against the Knicks. The shot that built a legacy.", "Eighteen years, one team, five Finals appearances. They don't make careers like this anymore."],
    tier2: ["The trash talk matched the three-point stroke. Spike Lee's personal nightmare.", "Clutch gene activated every May. The playoffs were Reggie's annual showcase."],
    tier3: ["Retired as the all-time three-point king. Curry eventually passed him, obviously."],
    overperform: ["When Miller got hot, opposing crowds went quiet. The road warrior at his finest.", "Playoff Reggie was a different species. The stakes brought out his best basketball."],
    underperform: ["Regular season games in November didn't move the needle. Miller saved it for May.", "When the shot wasn't falling, the Pacers offense ground to a halt around him."],
    onPace: ["Miller doing Miller things. Seven threes, some trash talk, a clutch bucket late.", "The consistency was boring until it mattered. Then it was championship-level."],
    turnovers: ["One turnover per game for a career. Ball security was part of the craft.", "Never forced the issue with his handle. Let the screens do the work."],
    defensive: ["The defensive effort matched the offensive output. Indiana's two-way wing.", "Stripped guards reaching for steals. The fundamentals extended beyond shooting."],
    bigGame: ["Forty-one against Milwaukee in 2000. Peak Miller at age 35 was still elite.", "The November explosion that reminded everyone why he was built for big moments.", "Age was theoretical when the stroke was pure. Father Time kept missing Reggie."],
    quietGame: ["Fifteen points on seven shots. Efficiency over volume was the Miller way.", "Quiet Miller games still featured clutch threes. The impact transcended the stat sheet."],
    famousGameHint: ["That 41-point night against Milwaukee came at age 35. The old legs, pure stroke.", "November 2000 when he reminded everyone that retirement was still theoretical.", "Five assists and one turnover in 42 minutes. The complete performance at veteran age."],
    controversy: ["The Spike Lee feud defined 90s basketball drama. Garden theater at its finest.", "Never backed down from trash talk with stars, fans, or future Hall of Famers.", "The choke sign in 1994. New York never forgave him for that gesture.", "Played through injuries when teammates couldn't. The competitive streak ran deep.", "Zero rings despite five Finals appearances. The resume's only missing piece."],
    formerTeam: [],
    rivalry: ["The Knicks rivalry defined his career. Madison Square Garden was his personal stage.", "Jordan's Bulls were the measuring stick. Six games from a ring in 1998."],
    milestones: ["Retired with 2,560 career threes. The three-point king until Curry arrived.", "Five Finals appearances without a ring. The closest near-miss in NBA history."],
    streakLines: ["When Miller caught fire, six-game playoff series became formalities for Indiana.", "Cold stretches were rare but devastating. The Pacers lived and died with his stroke.", "The 2000 season where he averaged 18 points at age 35. Vintage wine."],
    salaryNarrative: ["Thirty-eight dollars for a playoff assassin. The value play of the century.", "Role player money for a franchise legend. The modern market would've paid him properly.", "Indiana got 18 years of clutch for the price of three good seasons elsewhere."],
    teamContext: ["Drafted 11th by Indiana in 1987. The Pacers found their franchise player by accident.", "Eighteen seasons in blue and gold. One-team careers don't exist anymore."],
    draftAndPath: ["UCLA shooter taken 11th overall. The Pacers got their Jordan stopper.", "Eighteen years later, still wearing the same uniform. Loyalty in professional sports."],
    opponentFlavor: { NYK: "The Knick Killer earned his nickname. Eight points in nine seconds, among other crimes.", CHI: "Jordan's Bulls were the only team that consistently handled playoff Reggie.", ORL: "Thirty-four and 12 rebounds against the Magic in 1996. The complete performance.", MIL: "Forty-one against Milwaukee at age 35. The veteran showcase special.", LAL: "Shaq's Lakers ended his championship dreams twice. The West was stronger." },
    signatureGames: [
      { date: "1996-12-18", opponent: "ORL", fp: 57.9, line: "34p/12r/7a in 47 minutes" },
      { date: "2000-11-08", opponent: "MIL", fp: 52.9, line: "41p/2r/5a in 42 minutes" },
      { date: "2004-01-16", opponent: "SAS", fp: 51.5, line: "28p/5r/5a/3s in 32 minutes" },
      { date: "1997-03-28", opponent: "CHH", fp: 51.1, line: "39p/3r/3a/2s in 42 minutes" },
      { date: "2000-11-15", opponent: "DET", fp: 50.4, line: "30p/2r/8a/2s in 42 minutes" },
    ],
    teamEras: {
      IND: {
        framing: ["The Indiana Pacer for life. Eighteen seasons, five Finals trips, zero rings.", "From young shooter to veteran leader, all in blue and gold.", "The franchise's greatest player and biggest what-if wrapped into one career."],
        bigGameVariant: "Forty-one at age 35 against Milwaukee. The vintage wine was still pouring.",
        quietGameVariant: "Quiet regular season, vintage playoffs. Miller saved his best for when it mattered.",
      },
    },
  },

// John Stockton — basePlayerId 304 — teams: undefined
  stockton_304: {
    basePlayerId: 304,
    nicknames: ["Stock", "The Mailman's Wingman"],
    knownFor: "The all-time assists leader who made Karl Malone a Hall of Famer twice a night.",
    salaryTier: "star",
    tier1: ["15,806 assists. That record might outlive the league itself.", "Played 19 seasons, missed 22 games total. The accountant who never called in sick."],
    tier2: ["Those Finals runs weren't accidents. Stock quarterbacked two trips past Jordan's Bulls.", "The pick-and-roll with Malone was basketball geometry. Fifteen years of the same equation."],
    tier3: ["Shot 51% from three in '88. The quiet efficiency that made Sloan's system work."],
    overperform: ["31 points against the Nets while dishing 11 assists. The complete floor general takeover.", "When Stock went hunting for his own shot, defenses had no answer ready."],
    underperform: ["The turnover games were rare but painful. Six against Minnesota hurt more than the score.", "Father Time caught him on the wrong nights, legs heavy from two decades of floor burns."],
    onPace: ["Fifteen assists, three steals, perfect tempo. Classic Stock doing Stock things.", "The metronome game that made Utah's offense hum for nearly two decades."],
    turnovers: ["Eighteen assists against Cleveland with just three turnovers. The precision was surgical."],
    defensive: ["Eight steals against Portland in '99. The pickpocket who made passing lanes dangerous.", "Quick hands, quicker mind. Stock read offenses like sheet music."],
    bigGame: ["31 points, 11 assists against New Jersey. The complete floor general eruption.", "When Stock decided to score, defenses scrambled. They'd prepared for the pass, not the shot.", "62.7 fantasy points on perfect efficiency. The night Utah's point guard went nuclear."],
    quietGame: ["Single-digit scoring but still controlling tempo. Stock's floor was every team's ceiling.", "Bad shooting nights didn't stop the assists. The offense ran through him regardless."],
    famousGameHint: ["18 assists against Chicago in '98. MJ's Bulls got carved up by Utah's conductor.", "That February night when Stock made Jordan's defense look helpless in the halfcourt.", "The game film Sloan probably still watches. Pure pick-and-roll poetry against greatness."],
    controversy: ["Zero Finals rings despite two chances. The what-if that haunts Utah forever.", "Malone got the MVP votes, Stock got the harder job. History remembers both.", "The quiet assassin who never needed the spotlight. Results spoke louder than words.", "Played physical in an era when point guards got bullied. Never backed down.", "Retirement at 40 when he could've kept going. Left on his own terms, rare in sports."],
    formerTeam: [],
    rivalry: ["Magic and Isiah got the headlines. Stock got the record book.", "The Bulls rivalry that defined two Finals. Stock vs Jordan's defensive schemes."],
    milestones: ["15,806 assists. The record that made Malone rich and defenses dizzy.", "3,265 steals. The pickpocket total that might never get touched."],
    streakLines: ["Hot shooting meant 15 assists and 25 points. The complete offensive takeover.", "Cold nights still featured perfect passing. Stock's floor was championship level.", "Three straight games with 14+ assists. The rhythm that made Utah's system sing."],
    salaryNarrative: ["At $43, you're paying for 19 years of floor general mastery. The safe bet.", "Star-tier pricing for the most reliable point guard in history. Book it."],
    teamContext: ["Draft day 1984, pick 16. Sloan knew he'd found his conductor.", "Nineteen seasons in the same jersey. Loyalty that doesn't exist anymore."],
    draftAndPath: ["Gonzaga to Utah, straight line to greatness. Small school, big-time results.", "The 16th pick who made 15 players above him look like mistakes."],
    opponentFlavor: { LAL: "Magic's successor who never got the same love. Different era, same excellence.", CHI: "Jordan's kryptonite in the pick-and-roll. Made MJ work on defense.", POR: "Eight steals against Drexler's Blazers. Turned defense into fast breaks.", NYK: "Carved up Ewing's defense with surgical precision. MSG never warmed to him.", DEN: "48 points for Hakeem, 14 assists for Stock. Two legends trading haymakers." },
    signatureGames: [
      { date: "1997-03-12", opponent: "NJN", fp: 62.7, line: "31p/6r/11a/3s" },
      { date: "1996-12-20", opponent: "ORL", fp: 62.5, line: "22p/5r/15a/4s/1b" },
      { date: "1998-02-04", opponent: "CHI", fp: 59.6, line: "17p/3r/18a/5s" },
      { date: "2000-03-07", opponent: "CLE", fp: 43.4, line: "8p/2r/18a/3s" },
      { date: "1999-03-02", opponent: "POR", fp: 60.7, line: "15p/6r/7a/8s/2b" },
    ],
    teamEras: {
      UTA: {
        framing: ["The Jazz Point Guard. Nineteen seasons, two Finals, infinite assists.", "Made Malone an MVP candidate and Utah a contender. The perfect system player.", "Sloan's on-court son who ran the pick-and-roll better than anyone before or since."],
        bigGameVariant: "31 points in Salt Lake City. When the system player became the system.",
        quietGameVariant: "Bad shooting, perfect passing. Classic Jazz-era Stock doing Stock things.",
      },
    },
  },

// Hakeem Olajuwon — basePlayerId 165 — teams: undefined
  olajuwon_165: {
    basePlayerId: 165,
    nicknames: ["The Dream", "Akeem the Dream"],
    knownFor: "The greatest post moves in basketball history wrapped around two championship rings.",
    salaryTier: "role",
    tier1: ["The Dream Shake. No center in history had footwork like that.", "Back-to-back titles in '94 and '95. Jordan was playing baseball, Hakeem was dominating."],
    tier2: ["3,830 career blocks. The shot-swatting record that stood for decades.", "Finals MVP both championship years. Carried Houston when it mattered most.", "The quadruple-double. Only player ever to record one in the playoffs."],
    tier3: ["Played soccer growing up in Nigeria. The footwork translated perfectly to hardwood."],
    overperform: ["48 points against Denver at age 34. Father Time kept getting juked by footwork.", "82.2 fantasy points against Jordan's Bulls. Prime Dream against the GOAT's squad.", "Six blocks with 32 points. The two-way dominance that defined championship seasons."],
    underperform: ["The late-career legs betrayed the mind. Still had the moves, lost the elevation.", "Turnover-heavy nights when the double teams finally arrived on time."],
    onPace: ["Twenty-five points, twelve boards, four blocks. Classic Dream doing Dream things.", "The baseline expectation that would've been any other center's career night."],
    turnovers: ["Seven turnovers against Utah with 41 points. Even greatness had sloppy nights."],
    defensive: ["Seven blocks against Dallas. The paint was his personal no-fly zone.", "Defensive Player of the Year twice. The anchor that made Houston's defense elite."],
    bigGame: ["32 points, 16 rebounds, five blocks against Chicago. Prime Dream dismantling Jordan's Bulls.", "82.2 fantasy points in 39 minutes. The complete two-way destruction that few could match.", "When Hakeem was locked in, opposing centers needed mental health counselors."],
    quietGame: ["Bad shooting nights still featured elite defense. The Dream's floor was intimidation.", "Single-digit scoring but six blocks. Offense slumped, defense never did."],
    famousGameHint: ["48 points against Denver in January '97. The vintage performance at 34 years old.", "That triple-double against the Clippers with 22-16-10. The complete statistical takeover.", "Six blocks against Milwaukee while scoring 37. The two-way dominance in December."],
    controversy: ["Only one ring if Jordan doesn't retire. The what-if that defines his legacy.", "Should've won more MVPs. Robinson and Malone got votes Hakeem deserved.", "The spelling change from Akeem to Hakeem mid-career. Cultural identity in sports.", "Never played with another superstar in his prime. Carried Houston alone for years.", "The Toronto experiment at 39 was painful to watch. Legends should know when to quit."],
    formerTeam: [],
    rivalry: ["Robinson and the Spurs. The Texas rivalry that defined Western Conference basketball.", "Shaq's Lakers. Two dominant centers trading punches in the paint for years."],
    milestones: ["3,830 blocks. The shot-swatting record that defined rim protection for a generation.", "Back-to-back Finals MVPs. The peak that every center measures themselves against."],
    streakLines: ["Three straight 40-point games in '97. The vintage Dream refusing to age gracefully.", "Five consecutive games with 5+ blocks. The defensive dominance that anchored championships.", "Hot shooting meant unstoppable post moves. Cold shooting still meant elite defense."],
    salaryNarrative: ["At $34, you're getting championship pedigree at a discount. The Dream at role-player pricing.", "Best footwork in NBA history for the price of a rotation big. Highway robbery."],
    teamContext: ["First overall pick in '84. Houston won the lottery and the next decade.", "Carried the Rockets through two championships when the city needed heroes most."],
    draftAndPath: ["University of Houston to Houston Rockets. Phi Slama Jama to NBA champion.", "Beat Jordan, Barkley, and Stockton to be pick #1. The draft class that changed everything."],
    opponentFlavor: { CHI: "82 fantasy points against Jordan's Bulls. Made the dynasty work for it.", UTA: "41 points against Stockton and Malone. The Dream vs the Jazz machine.", DEN: "48 points at 34. Reminded everyone why he was still The Dream.", LAC: "The triple-double special. 22 points, 16 boards, 10 assists with blocks.", MIL: "37 points, six blocks. The complete two-way masterclass in Milwaukee." },
    signatureGames: [
      { date: "1997-01-19", opponent: "CHI", fp: 82.2, line: "32p/16r/4a/4s/5b" },
      { date: "1997-01-30", opponent: "DEN", fp: 67.5, line: "48p/10r/3a/2b" },
      { date: "1997-03-04", opponent: "LAC", fp: 67.2, line: "22p/16r/10a/3s/2b" },
      { date: "1996-12-23", opponent: "MIL", fp: 76.5, line: "37p/15r/3a/1s/6b" },
      { date: "1997-03-25", opponent: "MIN", fp: 76.2, line: "39p/11r/4a/1s/6b" },
    ],
    teamEras: {
      HOU: {
        framing: ["The Rockets Dream. Two championships, endless highlights, the greatest center in franchise history.", "Made Houston basketball relevant for a generation. The post moves that launched a thousand imitators.", "From Phi Slama Jama to back-to-back titles. The hometown hero who delivered everything."],
        bigGameVariant: "48 points in Houston against Denver. The Dream refusing to wake up at 34.",
        quietGameVariant: "Bad offense, elite defense. Classic Dream anchoring the paint regardless.",
      },
    },
  },

// Tim Hardaway — basePlayerId 896 — teams: MIA
  hardaway_896: {
    basePlayerId: "896",
    nicknames: ["UTEP Two-Step", "The UTEP Kid"],
    knownFor: "The killer crossover that broke ankles and the Run TMC years that broke hearts.",
    salaryTier: "star",
    tier1: ["The crossover that made defenders question their career choices. Trademark move trademarked.", "Run TMC with Golden State was basketball poetry. Three guys who could score from anywhere."],
    tier2: ["Five All-Star games, zero rings. The definition of great player, wrong era.", "The knee injury robbed him of two prime years. What could've been in '93 and '94."],
    tier3: ["Miami's veteran leadership during their first playoff runs. The point guard Pat Riley trusted."],
    overperform: ["When the crossover was cooking, nobody could stay in front of him. Vintage UTEP magic.", "The assist numbers climb when he's locked in. Old-school floor general takes over."],
    underperform: ["The shot selection gets questionable when he's forcing it. Hero ball without the heroics.", "Turnovers pile up when the crossover becomes predictable. Even ankle-breakers have limits."],
    onPace: ["Steady point guard play with the occasional ankle-breaking highlight. Pure Hardaway.", "The crossover still works, just not on every possession. Smart veteran picking his spots."],
    turnovers: ["The crossover sometimes crosses himself up. High-risk, high-reward ball-handling."],
    defensive: ["Quick hands, quicker feet. The steal numbers reflected his gambling instincts."],
    bigGame: ["45 points against Washington in '97. The UTEP Two-Step in its purest form.", "16 assists against Detroit that same season. When the crossover opens everything up."],
    quietGame: ["Even legends have off nights. The crossover doesn't work on everyone, every time."],
    famousGameHint: ["That eight-steal game against Atlanta in December '97. Hardaway as pickpocket.", "When you drop 45 and dish 16 in the same month, people remember the season."],
    controversy: ["The homophobic comments in 2013 that required multiple apologies. Words that aged terribly.", "Always maintained he was misunderstood, not malicious. The damage was already done.", "The apology tour felt genuine, but some bridges don't get rebuilt easily."],
    formerTeam: ["Golden State games were emotional. Run TMC breakup still stung Miami fans."],
    rivalry: ["The Warriors rivalry carried over to Miami. Different uniform, same competitive fire."],
    milestones: ["Five All-Star selections and a Hall of Fame career built on one perfect crossover."],
    streakLines: ["When the crossover is working, defenses start backing up before he even moves.", "Cold streaks mean forcing the hero shots. The crossover can't solve everything."],
    salaryNarrative: ["At $40, you're paying for the crossover and the clutch gene. Both still work.", "Star money for a player whose best move is still unguardable thirty years later."],
    teamContext: ["Miami needed a floor general for their playoff push. Hardaway delivered veteran leadership."],
    draftAndPath: ["Golden State's lottery pick who became the engine of Run TMC. Worth every ping-pong ball."],
    opponentFlavor: { GSW: "Run TMC reunion games hit different. The chemistry never fully left.", LAL: "Magic's replacement who never quite replaced Magic. Different eras, same expectations.", CHI: "Jordan's Bulls were the wall Run TMC couldn't climb. So close, so far.", NYK: "Riley's old team getting schooled by his new point guard. Poetic justice.", SAS: "Tim vs Tim. Duncan usually won the battle, Hardaway won the highlight reel." },
    signatureGames: [
      { date: "1997-03-07", opponent: "WAS", fp: 69.9, line: "45p/7r/7a/4s in 51 minutes" },
      { date: "1997-12-20", opponent: "ATL", fp: 71.7, line: "18p/6r/13a/8s in 37 minutes" },
      { date: "1997-03-04", opponent: "DET", fp: 56.8, line: "28p/4r/16a/1s in 45 minutes" },
    ],
    teamEras: {
      MIA: {
        framing: ["The veteran years. Riley's point guard during Miami's first real playoff push.", "Post-injury Hardaway was still crafty. The crossover worked, just at half-speed."],
        bigGameVariant: "That 45-point vintage performance that reminded everyone the crossover still worked.",
        quietGameVariant: "Even at 35, some nights the old legs couldn't keep up with the young mind.",
      },
    },
  },

// Manu Ginobili — basePlayerId 1938 — teams: SAS
  ginobili_1938: {
    basePlayerId: "1938",
    nicknames: ["Manu", "The Blade", "El Contusion"],
    knownFor: "The left-handed magician who turned chaos into championships and eurostepping into art.",
    salaryTier: "value",
    tier1: ["Four rings as the sixth man. The Euro-step pioneer who made fundamentally sound look flashy.", "2008 Olympics gold with Argentina. Beat Team USA when that meant something."],
    tier2: ["The 2004 playoff run where he announced himself to America. Clutch gene imported from Buenos Aires.", "Never started more than 74 games in a season. The ultimate team-first superstar."],
    tier3: ["That bat-slapping incident became a meme before memes existed. Pure Manu randomness."],
    overperform: ["When Manu gets hot, physics takes a night off. Euro-steps through triple coverage somehow work.", "The playoff switch flips and suddenly Argentina Manu shows up. Different level entirely."],
    underperform: ["The gambling instincts backfire when shots aren't falling. Risky passes become turnovers.", "Father Time catches up to the reckless drives. The body couldn't cash every check."],
    onPace: ["Classic Manu efficiency. Seven assists, three steals, and basketball that makes you smile.", "The controlled chaos that made San Antonio appointment television for fifteen years."],
    turnovers: ["The price of creativity. When you see passes others don't, sometimes they don't exist."],
    defensive: ["Those quick hands turned steals into fast breaks. The gambling paid off more than it didn't."],
    bigGame: ["46 points against LeBron's Cavs in 2008. Peak Manu destroying peak LeBron was appointment TV.", "48 points against Phoenix in '05. The Spurs' secret weapon wasn't secret anymore."],
    quietGame: ["Even magicians have off nights. The Euro-step sometimes steps into traffic."],
    famousGameHint: ["That 46-point masterclass against Cleveland when LeBron was still figuring out finals.", "Four blocks against Toronto in '09. When Manu decided to play defense like offense."],
    controversy: ["The flopping reputation that followed him around. Europeans taught the NBA new physics.", "Critics called it simulation; fans called it craftsmanship. Art is subjective.", "Never apologized for drawing fouls creatively. The whistle was just another teammate."],
    formerTeam: [],
    rivalry: ["Lakers playoff battles defined careers. Manu's clutch gene versus Kobe's assassin mode."],
    milestones: ["Four championships and Olympic gold. The international resume that opened NBA doors."],
    streakLines: ["Hot Manu meant defenders checking over their shoulders. The Euro-step became unstoppable.", "Cold stretches brought out the gambler. Sometimes the risk didn't match the reward."],
    salaryNarrative: ["At $22, you're getting championship DNA and Euro-step mastery. Both age well.", "Value pick who delivered star production. The definition of exceeding expectations."],
    teamContext: ["Pop's perfect sixth man for two decades. The system and the player were made for each other."],
    draftAndPath: ["Second-round pick who became first-ballot Hall of Famer. Argentina's gift to basketball."],
    opponentFlavor: { LAL: "Kobe respected the competitive fire. Two perfectionists from different continents.", MIA: "The Heat couldn't solve the Euro-step. Riley's defense had no manual for this.", PHX: "Those playoff battles were basketball artistry. Manu vs Nash was point guard poetry.", GSW: "The Warriors learned pace and space from watching Manu operate in half-court sets.", OKC: "Young Durant got schooled by old Manu. Lesson in playoff basketball IQ." },
    signatureGames: [
      { date: "2008-02-13", opponent: "CLE", fp: 75, line: "46p/5r/8a/3s in 41 minutes" },
      { date: "2005-01-21", opponent: "PHX", fp: 63, line: "48p/5r/6a/1s in 44 minutes" },
      { date: "2008-02-11", opponent: "TOR", fp: 65, line: "34p/15r/6a/2s in 39 minutes" },
    ],
    teamEras: {
      SAS: {
        framing: ["The complete Spurs experience. Four rings, countless memories, one Euro-step.", "Pop's secret weapon became the league's worst-kept secret. Manu Magic was appointment TV."],
        bigGameVariant: "That 46-point eruption against LeBron when playoff Manu showed why he was different.",
        quietGameVariant: "Even legends rest. The minutes restriction kept the magic fresh for May.",
      },
    },
  },

