/**
 * playerCulture.ts — Basketball player culture database.
 * Keyed by normalized last name (lowercase).
 * Used by the commentary system for personalized, opinionated post-reveal copy.
 */

export interface PlayerCulture {
  nicknames: string[];
  knownFor: string;
  salaryTier: "max" | "star" | "role" | "value" | "flier";
  tier1: string[];
  tier2: string[];
  tier3: string[];
  overperform: string[];
  underperform: string[];
  onPace: string[];
  turnovers: string[];
  defensive: string[];
  bigGame: string[];
  quietGame: string[];
  controversy: string[];
  famousGameHint: string[];
  opponentFlavor?: Record<string, string>;
}

export const PLAYER_CULTURE: Record<string, PlayerCulture> = {
  harden: {
    nicknames: ["The Beard", "13", "Harden"],
    knownFor: "The most creative scorer of his generation, with an equally creative relationship with fourth quarters",
    salaryTier: "max",
    tier1: ["The step-back is basically its own landmark.", "The Beard has been getting buckets since before the beard was the thing."],
    tier2: ["Regular season Harden and playoff Harden are two different conversations.", "The step-back got officially ruled a non-travel. Still feels illegal."],
    tier3: ["The Houston era stats are all-time. The Conference Finals exits are also all-time.", "He demanded a trade from three different franchises. The buckets followed him to all of them."],
    overperform: ["Regular season Harden showed up. Nobody's stopping that.", "The Beard in rhythm is genuinely unfair. Tonight was proof.", "When Harden's cooking, the defense just picks a lane to die in."],
    underperform: ["Playoff mode in a regular season game. It happens.", "The Beard went quiet. The FP felt it.", "Some nights the step-back doesn't step forward."],
    onPace: ["The Beard delivered exactly what the salary promised. Clockwork.", "Harden at his average is still dangerous. The FP knows it."],
    turnovers: ["The Beard giveth. The Beard taketh away.", "Harden with turnovers — write it down, it was in the contract.", "Six giveaways. The reputation earns a nod on this one."],
    defensive: [],
    bigGame: ["That stat line has a story. Tap in and check what happened.", "The Beard dropped a game worth looking up. Seriously, check it.", "Numbers like that belong in a highlight reel. The box score tells the rest."],
    quietGame: ["The Beard went quiet. Some nights the step-back stays in the holster.", "Harden below his line means the defense found something. Temporarily."],
    controversy: ["Regular season Harden is a top-5 player. The rest is a longer conversation.", "Nobody creates their own shot like The Beard. Postseason scheduling may vary.", "The demand-a-trade era ended with a ring chase. The buckets never stopped."],
    famousGameHint: ["That game is worth a look. The Beard has some all-timers in the archive.", "Check that box score. Some of his games live rent-free in basketball memory.", "Tap the stats. This one might ring a bell."],
    opponentFlavor: { OKC: "Harden in OKC. Full circle energy.", HOU: "Back in Houston. The crowd probably had feelings.", PHI: "Former team game. The motivation was either there or it wasn't.", BKN: "Another former home. Harden has had a few." },
  },
  james: {
    nicknames: ["King James", "LBJ", "The Chosen One", "LeBron", "The King"],
    knownFor: "The most complete player in NBA history, who also has the most complete opinion of himself",
    salaryTier: "max",
    tier1: ["Twenty-plus years. Still doing this.", "The rings don't argue back."],
    tier2: ["The Decision was messy. The trophies were not.", "Called himself The Chosen One in a Sports Illustrated cover at 17. Then won four chips. The hubris was earned."],
    tier3: ["He passed Kareem on the all-time scoring list. Did it in LA, in front of his son. Knew the camera was ready.", "The G.O.A.T. conversation — he started it and then made everyone defend the other side. Bold strategy."],
    overperform: ["The King decided tonight was his. It was.", "LeBron above his line at year 21. The statute of limitations on this man has not arrived.", "When The Chosen One chooses to go off, the lineup just rides."],
    underperform: ["Even the King has nights off. Rare, but documented.", "LeBron had a human evening. It will not become a pattern.", "Quiet night for The King. He's probably fine about it."],
    onPace: ["LeBron at his floor is still the ceiling for most.", "The Chosen One delivered exactly what was chosen. Reliable.", "As cool as the other side of the pillow. Right on his line."],
    turnovers: ["The King with giveaways — aggressive game, the turnovers came with the tempo.", "LeBron turnovers mean he was trying to make plays. The FP disagreed with a few."],
    defensive: ["The King was locked in defensively tonight. Two-way mode activated."],
    bigGame: ["LeBron has games in the archive that belong in a museum. Check if this is one.", "That stat line might ring a bell. The King has some legendary nights in there.", "Worth a tap. LeBron's catalog has some all-timers."],
    quietGame: ["Even the King has off nights. The FP was honest about it.", "LeBron quiet is still 18 and 7 for most players. Tonight it wasn't enough."],
    controversy: ["The G.O.A.T. debate — he entered it voluntarily and then went and won four rings. Complicated.", "Two Cleveland exits. Two returns in different forms. The city has feelings. The trophies don't.", "The Decision press conference was a moment. History decided the rest."],
    famousGameHint: ["LeBron has games in the archive that belong in a museum. Check if this is one.", "That stat line might ring a bell. The King has some legendary nights in there.", "Worth a tap. LeBron's catalog has some all-timers."],
    opponentFlavor: { CLE: "Back in Cleveland. This one always has a temperature.", MIA: "South Beach chapter. The Heat years were something.", GSW: "Warriors Finals matchups made careers and ended debates.", SAS: "LeBron vs Spurs Finals. A few different decades, a few different results." },
  },
  antetokounmpo: {
    nicknames: ["Greek Freak", "Giannis"],
    knownFor: "Came from Lagos via Athens with nothing, became a two-time MVP and a champion, and runs at the basket like it owes him money",
    salaryTier: "max",
    tier1: ["The Greek Freak is exactly what it says on the box.", "From selling things on the streets of Athens to MVP. One of the real ones."],
    tier2: ["He can't shoot from deep and it doesn't matter. Which is insane.", "The Bucks built a championship around a player who can barely hit a midrange. And it worked."],
    tier3: ["Drafted 15th overall. The Milwaukee front office has been dining on that decision ever since.", "He got his passport the same year he got drafted. The whole story is unreal."],
    overperform: ["The Greek Freak happened. What exactly were you going to do about it.", "When the Greek Freak decides to take over, there is no punctuation for the other team.", "Giannis in full flight is a different sport from what everyone else is playing."],
    underperform: ["Even Giannis had a night where not everything showed up.", "The Greek Freak had a mortal evening. It will not become a trend.", "Giannis was quiet. By his standards. Which is still alarming by anyone else's."],
    onPace: ["The Freak at his average is still a problem. The FP confirmed it.", "Giannis delivering his line means the defense had a very long night."],
    turnovers: ["The Freak and turnovers — when he's going downhill you can't always stop the locomotive or the ball.", "Giannis with giveaways means he was aggressive. The math sometimes disagrees."],
    defensive: ["Not in his house tonight. The Greek Freak was everywhere defensively.", "When Giannis decides to lock down, it's almost unfair to the whole concept of offense."],
    bigGame: ["Giannis has some monster games in the archive. Check if this is one.", "Numbers like that come with a story. Tap and see what happened.", "The Greek Freak going off tends to be memorable. Box score's right there."],
    quietGame: ["The Greek Freak had a quiet chapter tonight.", "Giannis below his line is rare. The defense earned something tonight."],
    controversy: ["The free throw percentage discourse has been running for six years. The rings ended it.", "Can't shoot threes and won a chip anyway. Advanced metrics had to recalibrate.", "Back-to-back MVP. Then a Finals win. The 'when will he perform in the clutch' crowd got quiet."],
    famousGameHint: ["Giannis has some all-time performances in there. Check if this is one.", "The Greek Freak going off tends to be documented. Tap the stats.", "That performance from The Freak deserves a look. Box score's right there."],
  },
  westbrook: {
    nicknames: ["Brodie", "Russ", "Westbrook", "Mr. Triple-Double"],
    knownFor: "The most electric athlete in the league for a decade, who also had the most turbulent statistical relationship with wins",
    salaryTier: "star",
    tier1: ["Brodie plays every possession like his shoes are on fire.", "Nobody in the league has ever run faster to score 18 and lose by 20."],
    tier2: ["The triple-double record exists because of him. Whether it should is the debate.", "Westbrook's advanced stats have their own support group."],
    tier3: ["Oscar Robertson's triple-double record stood for 55 years. Russ broke it and then kept going. The historians are split.", "The MVP year in OKC was legitimately one of the great individual seasons ever. The efficiency crowd was not in attendance for the celebration."],
    overperform: ["Brodie went off and the FP followed. The volume was never the problem.", "When Westbrook gets it going, the stat sheet gets very busy very fast.", "Russ at full speed is still something. The numbers agree tonight."],
    underperform: ["Westbrook with a quiet game is almost conceptually difficult to process.", "Brodie had an off night. The assist numbers were not helped by this.", "Some games the engine fires on fewer cylinders. Tonight was that."],
    onPace: ["Brodie at his line means high volume, high energy, enough to make it work.", "Westbrook delivered the expected output. The chaos was included at no extra charge."],
    turnovers: ["Westbrook with turnovers — guaranteed feature, not a bug.", "Brodie being aggressive and careless simultaneously is the oldest story in basketball.", "The giveaways came with the territory. They always have."],
    defensive: ["Russ got his hands on some things defensively. The effort was never the question."],
    bigGame: ["Westbrook has some all-time games in there. Triple-double machines leave a trail.", "That stat line is worth checking. Russ has some nights that deserve documentation.", "Tap and see. Brodie's best games are genuinely something."],
    quietGame: ["Brodie quiet. The triple-double streak paused. The league exhaled briefly.", "Westbrook below his line is a curiosity. The effort was still visible."],
    controversy: ["Westbrook with turnovers — guaranteed feature, not a bug.", "The triple-double chase changed how he played. Whether that was good is still being argued.", "Shot 42% from the field for a decade and was also the most exciting player to watch. Statistics are complicated."],
    famousGameHint: ["Westbrook's catalog has some all-time numbers. Tap and see if this is one.", "Brodie has some historic stat lines in there. Worth checking.", "That Westbrook game is worth a look. The triple-double archive is extensive."],
    opponentFlavor: { OKC: "Westbrook vs OKC. The reunion games always have a chapter.", GSW: "Russ vs Golden State. The history runs deep and painful." },
  },
  durant: {
    nicknames: ["KD", "The Slim Reaper", "Durant", "Durantula"],
    knownFor: "The most unguardable scorer the game has ever seen, who chose the easiest path to rings and has not fully forgiven himself for noticing",
    salaryTier: "max",
    tier1: ["KD at seven feet who moves like a guard. The game hasn't figured it out yet.", "The Slim Reaper. The name is accurate."],
    tier2: ["Went to the Warriors as the best player on a 73-win team. The championships were real. The conversation never settled.", "The burner account situation happened. He replied to fans from a fake account. It's documented."],
    tier3: ["His first Finals MVP was with Golden State. His second was with Brooklyn, where he dragged them there almost single-handedly. The range of outcomes is staggering.", "Drafted second overall behind Greg Oden. The comparison was made once and then quietly retired."],
    overperform: ["When Durant is locked in, it is not fair. It never has been.", "The Slim Reaper decided tonight belonged to him. Nothing to be done.", "KD cooking is a masterclass. The FP just watched and took notes."],
    underperform: ["KD had a quiet one. The Slim Reaper was momentarily mortal.", "Durant below his line is still a real number. Just not the number.", "Even the Slim Reaper clocks out occasionally."],
    onPace: ["KD at his average is still a nightmare for the defense.", "The Slim Reaper delivered what the salary promised. Efficient and inevitable."],
    turnovers: ["KD with giveaways — aggressive, not careless. Usually. Tonight it cost.", "Durant turnovers are rare enough that they warrant acknowledgment."],
    defensive: ["The Slim Reaper was active on both ends tonight. The blocks are part of the package."],
    bigGame: ["The Slim Reaper has some all-time offensive performances in the archive. This might be one.", "KD going off tends to produce the kind of game people remember. Tap to check.", "Durant's big nights are documented. Worth a look."],
    quietGame: ["KD had a quiet night. The Slim Reaper rested the scythe.", "Durant below his line is worth noting. It doesn't happen often."],
    controversy: ["The Warriors move was the most debated decision in modern NBA history. The rings happened. The discourse didn't stop.", "He's never quite made peace with wanting the easy path. The production doesn't need to.", "Burner account era. Replied to NBA fans from a fake account. Acknowledged it. Moved on. The internet did not."],
    famousGameHint: ["KD has some all-time scoring performances in the archive. This might be one.", "The Slim Reaper's biggest games are worth knowing. Tap and check.", "Durant going off produces the kind of game people remember. Look it up."],
  },
  curry: {
    nicknames: ["Chef Curry", "Steph", "Curry", "Splash"],
    knownFor: "Permanently changed where the NBA thinks shooting ranges from, using ankles as his primary defensive weapon",
    salaryTier: "max",
    tier1: ["Chef Curry broke basketball's relationship with the half-court line.", "The shooting range that everyone laughed at and then copied."],
    tier2: ["Two unanimous MVP seasons. That's a very short list.", "Davidson College. Underprepared for the NBA. Reclassified the whole position."],
    tier3: ["The 2015-16 Warriors went 73-9 and he won the individual MVP unanimously. He was still the best player on a 73-win team.", "His handles took longer to respect than his shot. The crossover was always there."],
    overperform: ["Chef Curry had the stove on high tonight. The FP got cooked.", "When Steph gets hot it's not basketball anymore, it's performance art.", "Splash. The range that broke basketball is still unrepaired."],
    underperform: ["Curry had a cold night. The shot didn't fall. The FP noticed.", "Even Chef Curry has an off night in the kitchen. The menu suffered."],
    onPace: ["Steph on autopilot is still a problem for the other team.", "Chef Curry delivered the expected order. Exactly right."],
    turnovers: ["Chef Curry with turnovers — rare, felt, and worth noting."],
    defensive: ["Steph was active defensively tonight. The ankles were deployed."],
    bigGame: ["Curry's biggest games changed the sport. Check if this is one of them.", "Steph has performances in the catalog that belong in a different conversation. Tap and see.", "That stat line might be a famous one. Chef Curry has a few worth knowing."],
    quietGame: ["Chef Curry had a cold kitchen tonight. The shots didn't convert.", "Steph below his line is rare. The defense deserves credit."],
    controversy: [],
    famousGameHint: ["Curry's biggest games changed how the sport thinks. Check if this is one.", "Steph has some all-time performances in there. Tap and see.", "Chef Curry's best nights are worth knowing. Box score's right there."],
    opponentFlavor: { GSW: "Playing against his own franchise. The history is in the building." },
  },
  jokic: {
    nicknames: ["The Joker", "Nikola", "Jokić"],
    knownFor: "The most improbable MVP in NBA history — a slow, round Serbian center who is somehow the best player on Earth",
    salaryTier: "max",
    tier1: ["The Joker. Plays like he has all the time in the world and somehow he does.", "Three MVPs and a championship. The slow-footed center the league didn't see coming."],
    tier2: ["Drafted 41st overall. The Nuggets had no idea. Nobody did.", "He moves at half the speed of everyone else and still gets there first. It's philosophically disturbing."],
    tier3: ["The draft pick used on him was compensation in a trade. It became the best center in basketball.", "He has a horse racing stable back home in Serbia. His brother texts him race results during games. He's said so."],
    overperform: ["The Joker dealt a masterclass tonight. The best passing big man alive reminded everyone.", "When Jokić decides to take over, the stat sheet just becomes his. Tonight was his.", "Nikola in rhythm is a different sport from everyone else's sport."],
    underperform: ["The Joker had a quiet deal tonight. The hand was modest.", "Jokić below his line is a curiosity. The efficiency was still there, just less of it."],
    onPace: ["The Joker delivered. Efficient, quiet, decisive. The FP showed up.", "Jokić at his average is still the most interesting player on the floor."],
    turnovers: ["Jokić turnovers mean he was making the ambitious pass. The idea was correct. The execution varied."],
    defensive: [],
    bigGame: ["The Joker has some historically weird and excellent games on record. This might be one.", "Jokić's all-time performances are worth documenting. Check the box score.", "Nikola going off looks unlike anything else in the league. Tap and see what happened."],
    quietGame: ["The Joker played a quiet hand tonight. No dramatic dealing.", "Jokić was measured. Which means the defense got something right, briefly."],
    controversy: [],
    famousGameHint: ["The Joker's all-time performances are worth documenting. Check the box score.", "Jokić has some historically unusual and excellent games in there. Tap and see.", "Nikola going off tends to be memorable. Worth a look."],
  },
  doncic: {
    nicknames: ["Luka", "Dončić", "Luka Magic"],
    knownFor: "The 19-year-old who looked 40 and played like it — already generating the kind of numbers that make historians nervous",
    salaryTier: "max",
    tier1: ["Luka was doing this in Spain at 16. The NBA was not his first rodeo.", "The Kid from Ljubljana who made Dallas forget they traded him once."],
    tier2: ["The Mavs picked up his rights from Atlanta in a draft night trade. Atlanta got Trae Young and a pick. The discourse is alive.", "He flops. He complains. He also drops 35 and a Triple-Double. The package comes together."],
    tier3: ["Real Madrid winner at 18. Then the NBA. The resume started before most players had a college visit.", "The step-back three is his signature. He learned it in Europe. The whole league is still learning the counter."],
    overperform: ["Luka Magic was in the building tonight. The FP felt it.", "The Kid went off. Some things are just not age-appropriate to be this good.", "When Dončić decides the game is his, it becomes his. Tonight was the example."],
    underperform: ["Luka had a quiet one. The flopping wasn't enough to supplement the production tonight.", "The Kid took a night off. He's allowed one per season."],
    onPace: ["Luka at his line means a complete game was played. The proof is in the FP.", "Dončić delivered what the salary asked for. Routine excellence."],
    turnovers: ["Luka with turnovers — usually because he tried something ambitious. The vision was there.", "Dončić giveaways mean he was cooking and over-seasoned a little."],
    bigGame: ["Dončić has already put up some historical performances and he's still young. Check if this is one.", "Luka Magic has a few all-timers in the archive. Tap and see.", "Numbers like that from someone that age are worth documenting. The box score's there."],
    quietGame: ["Luka Magic had an off night. The rabbit stayed in the hat.", "Dončić below his line means the defense did something right. Write it down."],
    controversy: ["The flopping reputation follows him. The production made it irrelevant.", "The Atlanta trade — both sides think they won. Only one is correct, and the answer keeps changing."],
    famousGameHint: ["Dončić has already put up some historical performances. Check if this is one.", "Luka Magic has a few all-timers in the archive. Tap and see.", "Numbers like that from someone that young are worth documenting. Box score's there."],
    opponentFlavor: { ATL: "Against Atlanta. The other side of a draft day trade they're both trying to win.", GSW: "Luka vs the dynasty remnants. Always has a temperature." },
  },
  leonard: {
    nicknames: ["The Klaw", "Kawhi", "Board Man"],
    knownFor: "The most enigmatic superstar in NBA history — plays forty minutes, says ten words, wins a championship, disappears",
    salaryTier: "max",
    tier1: ["The Klaw. The hands. The shot. The silence.", "Board Man Gets Paid. And then gets load managed."],
    tier2: ["Won a title in San Antonio, won a title in Toronto, then signed with the team in his city and played 38 games.", "The laugh. If you know, you know. If you don't, look it up immediately."],
    tier3: ["The Shot against Philadelphia — Game 7, four bounces, in. The Raptors won the title the year after.", "Described himself as a 'fun guy.' The delivery was the whole joke."],
    overperform: ["The Klaw was available tonight and delivered. Health and production — the rarest Kawhi combo.", "When Leonard is on and locked in, he's the most complete two-way player alive.", "The Claw was out tonight. The grip did not let go."],
    underperform: ["Kawhi was quiet. Load management for the FP column.", "The Klaw had a passive evening. The board man took the night off."],
    onPace: ["Kawhi at his line means he was engaged. The FP confirmed.", "The Klaw delivered. Quiet, efficient, inevitable."],
    turnovers: ["Kawhi with turnovers — even the Klaw slips occasionally."],
    defensive: ["The Klaw was locked in defensively. This is his native language.", "Kawhi in defensive mode is the standard by which everyone else gets measured."],
    bigGame: ["Kawhi's healthy big games are special enough to check. Tap the stats.", "The Klaw in full flight is worth documenting. Box score's right there.", "A big Kawhi performance is worth verifying. He makes them count."],
    quietGame: ["The Klaw had a quiet evening. Load management implied.", "Kawhi below his line — the availability was there, the production was managed."],
    controversy: ["Load management as a lifestyle. The rings don't argue with the results.", "Left San Antonio quietly. Left Toronto immediately. Stayed in LA and played in spurts. The production was always there when available.", "The fun guy thing. He said it. He meant it. The gap between the words and the delivery is the whole personality."],
    famousGameHint: ["Kawhi's healthy big games are worth documenting. Tap and check.", "The Klaw has some iconic performances in there — the bounce, the silence, the result. Go look.", "A big Kawhi performance is worth checking. His catalog has weight."],
  },
  butler: {
    nicknames: ["Jimmy Buckets", "Jimmy", "Butler"],
    knownFor: "The anti-star star — demands trades, shows up to practice and embarrasses the starters, wins big when eliminated, somehow keeps getting max contracts",
    salaryTier: "star",
    tier1: ["Jimmy Buckets. The nickname is a description, not a compliment.", "The guy who demanded off teams that couldn't handle him and then immediately made the Finals."],
    tier2: ["Practiced with the Timberwolves third string and outscored the starters. Then asked for a trade. The power move of the decade.", "Made the Finals with the Heat as a five-seed. In the bubble. Without a real roster. They lost in six and he was the story."],
    tier3: ["Undrafted college career, picked 30th overall, forced his way into stardom by being undeniable.", "The coffee business is real. He charges $20 a cup at the hotel lobby during All-Star Weekend. It sells out."],
    overperform: ["Jimmy Buckets showed up and the buckets followed. It was in the name.", "Butler in full mode is one of the most unavoidable players in basketball.", "When Jimmy decides to take over, the stops don't come."],
    underperform: ["Jimmy Buckets had a quiet one. The bucket was on backorder.", "Butler went quiet. The FP felt the absence."],
    bigGame: ["Jimmy's best games tend to happen when it matters. Check if this was one of those.", "Butler going off has a flavor to it. Tap the stats and see what the game looked like.", "Jimmy Buckets' best nights are worth the look."],
    quietGame: [
      "Jimmy Buckets took the night off. The bucket was on backorder.",
      "Butler quiet is almost a contradiction. Tonight it was real.",
    ],
    onPace: [
      "Jimmy Buckets at his average means he squeezed the game until it gave him what he needed.",
      "Butler on his line is controlled aggression. The FP was earned, not given.",
    ],
    turnovers: [
      "Jimmy with giveaways — he was attacking. The turnovers are the cost of doing business.",
      "Butler turnovers mean he was in create mode. The math didn't always agree.",
    ],
    defensive: [],
    controversy: ["The practice facility incident is documented and worth knowing about.", "He demanded off three teams. All three teams eventually agreed he was right to leave."],
    famousGameHint: ["Jimmy Buckets' best games tend to come when the stakes are high. Check if this was one.", "Butler going off has a specific energy. Tap the stats.", "Jimmy's best nights are worth the look. Box score's right there."],
  },
  lillard: {
    nicknames: ["Dame", "Dame Time", "Lillard", "Dame D.O.L.L.A."],
    knownFor: "The most loyal star in NBA history until he wasn't, with a buzzer-beater addiction and a rap career that's earnest enough to respect",
    salaryTier: "star",
    tier1: ["Dame Time. The phrase exists because he kept making it true.", "Loyalest player in the league for twelve years, then asked out. Portland still hasn't fully processed it."],
    tier2: ["The series-winner against Oklahoma City — from the logo — was so deep that the defender's career got an asterisk.", "Weber State. Nobody recruited him seriously. He's been settling scores ever since."],
    tier3: ["Rapped at the ESPYs once. The lyrics were better than the delivery. The effort was genuine.", "Portland drafted him knowing he might never have a real supporting cast. He stayed anyway. For longer than most would."],
    overperform: ["Dame Time activated. The FP showed up to the moment.", "When Lillard gets going from distance, the defense can only watch and think about life choices.", "Dame at his peak is one of the most uncontainable forces in basketball. Tonight was a reminder."],
    underperform: ["Dame Time was delayed tonight. The clock ran out on the production.", "Lillard below his line means the defense found a way. Temporarily."],
    bigGame: ["Dame Time has some legendary performances in the archive. Buzzer-beaters, series-winners. Check if this is one.", "Lillard's biggest games have specific addresses. Tap and see if this has one.", "Dame's best games are worth knowing. The box score's right there."],
    quietGame: [
      "Dame Time was on pause tonight. The clock ran out on the production.",
      "Lillard went quiet. The defense found a wrinkle. It won't last.",
    ],
    onPace: [
      "Dame delivered. The consistency from Weber State to here has never wavered.",
      "Lillard at his line means he found his spots and put them away. Reliable.",
    ],
    turnovers: [
      "Dame with turnovers — he was pushing pace. The giveaways came with the aggression.",
      "Lillard turnovers usually mean he was trying to make something happen. Tonight it didn't.",
    ],
    defensive: [],
    controversy: ["The Portland exit — twelve years and then a trade request. Both sides have a story.", "Dame D.O.L.L.A. as a rap name. He committed to it fully. The commitment is respectable."],
    opponentFlavor: { OKC: "Against OKC. The logo three that ended a series lives in this building." },
    famousGameHint: ["Dame Time has some legendary games in the archive. Tap and see if this is one.", "Lillard's biggest performances have specific addresses. Go find this one.", "Dame's best nights are worth documenting. Box score's right there."],
  },
  george: {
    nicknames: ["PG13", "Playoff P", "PG", "George"],
    knownFor: "One of the five best players alive with a nickname that his detractors gave him and he adopted anyway",
    salaryTier: "star",
    tier1: ["PG13. The rating applies in both directions depending on the series.", "Playoff P — the nickname came from somewhere. You know where."],
    tier2: ["He leaned into Playoff P. Made it his own. Then went and had playoff runs that complicated the narrative.", "The injury in Team USA practice was one of the worst any basketball fan has watched. He came all the way back."],
    tier3: ["The OKC era with Westbrook was genuinely intriguing and never fully delivered. The 'what if' is real.", "LA Clippers era had a Bubble collapse that became the defining moment. The follow-up chapters rewrote it partially."],
    overperform: ["PG13 showed up and the rating was favorable tonight.", "Paul George in full flight is one of the cleanest two-way games in basketball.", "Playoff P arrived for a regular season game. The irony was delicious."],
    underperform: ["Playoff P energy in a game that needed PG13. The FP gap is self-explanatory.", "George went quiet. The Playoff P council is in session."],
    bigGame: [
      "Paul George has some big games in the archive. Check if this is one of them.",
      "PG going off tends to come with a story. Tap the stats.",
    ],
    quietGame: [
      "Playoff P energy on a night where PG13 was needed. The FP gap is real.",
      "George went quiet. The two-way engine ran on one side tonight.",
    ],
    onPace: [
      "PG13 delivered what the salary asked for. Clean game, right numbers.",
      "Paul George at his average is a complete two-way performance. The FP confirmed it.",
    ],
    turnovers: [
      "George with turnovers — he was making plays, not all of them landed.",
      "PG13 giveaways usually come when he's being aggressive. Tonight the defense won a few.",
    ],
    defensive: [],
    controversy: ["He adopted the Playoff P nickname. That's either the most confident or most reckless decision in sports branding.", "The Clippers bubble collapse is documented. The rehabilitation arc is also documented. Both are real."],
    famousGameHint: ["PG13 has some high-level performances in there. Tap and check.", "George's best games are cleaner than the nickname suggests. Box score's right there."],
  },
  derozan: {
    nicknames: ["DeRozan", "DeMar", "The Mid-Range Assassin"],
    knownFor: "The last true believer in the mid-range jumper, at a time when the league declared it extinct and he decided to make it personal",
    salaryTier: "star",
    tier1: ["DeRozan plays iso mid-range in an era of corner threes and he wins. Contrarianism as a lifestyle.", "The mid-range is not dead. DeMar has the numbers to prove it and the stubbornness to keep proving it."],
    tier2: ["The Toronto trade for Kawhi — he found out on the news. Not from the organization.", "The mental health conversation in 2018 — he opened up publicly about depression before athletes did that. It mattered."],
    tier3: [],
    overperform: ["The Mid-Range Assassin struck. The outdated shot with the timeless results.", "DeRozan doing DeRozan things and the FP agreeing. The mid-range is not a museum piece.", "DeMar found his spots tonight and put them away. Methodical and effective."],
    underperform: ["The mid-range was there. The rest of the game didn't cooperate tonight.", "DeRozan had a quiet one. The mid-range stayed in the holster."],
    bigGame: [],
    quietGame: [
      "The mid-range stayed in the holster tonight. The defense took something away.",
      "DeRozan quiet is unusual. The isolation spots weren't there.",
    ],
    onPace: [
      "DeRozan at his line means the mid-range was open and he took it. Clockwork.",
      "DeMar delivered. The outdated shot with the timeless results.",
    ],
    turnovers: [
      "DeRozan with turnovers — rare enough to notice, not rare enough to ignore.",
      "DeMar giveaways mean someone got in his spots. He won't forget.",
    ],
    defensive: [],
    controversy: [],
    famousGameHint: ["DeMar has put up some quietly excellent games in there. Worth a look.", "DeRozan's best nights are underrated historically. Tap and check."],
  },
};
