/**
 * teamFlavor.ts — Team culture database for basketball commentary.
 * Keyed by 3-letter team code (uppercase).
 */

export const TEAM_FLAVOR: Record<string, { identity: string; hype: string; cold: string; humor: string }> = {
  SAS: { identity: "San Antonio — the franchise that turned fundamentals into a dynasty", hype: "Spurs basketball did what Spurs basketball does.", cold: "Even a good game in San Antonio felt organized and efficient.", humor: "What a terribbble basketball game. Maybe too many churros tonight." },
  MIA: { identity: "Miami — the culture, the heat, the late nights, and the conference finals", hype: "Miami culture showed up. The city runs different.", cold: "South Beach had nothing to celebrate tonight.", humor: "The Heat culture would like a word about this performance." },
  BOS: { identity: "Boston — banners, history, and an opinion about every player who passes through", hype: "The Garden was the right place to get right.", cold: "Boston crowds are unforgiving. Tonight gave them material.", humor: "The Celtic faithful are composing the takes as we speak." },
  GSW: { identity: "Golden State — the dynasty that changed the game and is still around to remind you", hype: "Chase Center energy is contagious. The FP caught it.", cold: "Warriors defense is still legitimately problematic for everyone.", humor: "Dubs fans had feelings tonight. They always do." },
  LAL: { identity: "Los Angeles — Showtime, Kobe, LeBron, and sixteen banners that never let you forget", hype: "The lights were bright in LA and the lineup matched them.", cold: "The lights were bright in LA and the performance did not match.", humor: "Lakers Twitter is already processing this." },
  CHI: { identity: "Chicago — the ghost of 72-10 haunts every conversation about that franchise", hype: "The United Center got what it came for.", cold: "Chicago winters and cold performances. The tradition continues.", humor: "The Jordan comparisons are already being made. They are not flattering." },
  NYK: { identity: "New York — the Garden, the most famous arena in basketball, still waiting for the next banner", hype: "Madison Square Garden energy is different. Always has been.", cold: "MSG deserved more than this tonight.", humor: "The Garden crowd let them know. Diplomatically? No." },
  PHI: { identity: "Philadelphia — Trust The Process became Trust The Results, then became Trust The Health Update", hype: "Philly showed up and so did the lineup. Good night.", cold: "Philadelphia crowds don't hide their feelings. Neither did the FP.", humor: "The Sixers fan experience: stunning highs, documented lows, occasional health updates." },
  HOU: { identity: "Houston — Moreyball's birthplace, now rebuilding with maximum optimism", hype: "Houston is building something real. The FP was part of it tonight.", cold: "Toyota Center had a long evening.", humor: "The analytics department is already computing the efficiency rating on this." },
  DEN: { identity: "Denver — altitude, ball movement, and the most unlikely MVP trajectory in the league", hype: "Ball Arena, mile high, and the FP followed.", cold: "Even the altitude couldn't help the numbers tonight.", humor: "Denver fans bring their own oxygen. The performance needed some tonight." },
  MIL: { identity: "Milwaukee — built on drafting a Greek teenager and making him the best player alive", hype: "The Fiserv Forum got what it came for.", cold: "Wisconsin had a cold evening. Weather appropriate.", humor: "Bucks fans are passionate and specific. Tonight gave them specifics." },
  POR: { identity: "Portland — one of the most loyal fan bases watching one of the most unpredictable rebuilds", hype: "The Rose Garden faithful got their money's worth.", cold: "Moda Center was quiet. The FP explains why.", humor: "Portland will still sell out tomorrow. That's just who they are." },
  OKC: { identity: "Oklahoma City — where stars develop, then leave, then get mentioned forever", hype: "OKC's young core is a problem. The building noticed.", cold: "Quiet night in OKC. Both teams were quiet.", humor: "The Thunder arena energy is loud regardless. The scoreboard was the problem." },
  MIN: { identity: "Minnesota — perpetually almost, finally actually, with a cast that justifies watching", hype: "Target Center has something to cheer about now.", cold: "Minnesota sports and heartbreak — the relationship continues.", humor: "Timberwolves fans have been patient. The patience is noted." },
  CLE: { identity: "Cleveland — one of the great comeback stories in sports, authored by the player who left and came back", hype: "The Cavaliers faithful remembered why they showed up.", cold: "Cleveland deserved a better night than this.", humor: "The Cavs and drama have a long documented relationship." },
  ATL: { identity: "Atlanta — Trae Young's playground, and the other side of a draft trade that has never stopped being discussed", hype: "State Farm Arena got loud. The FP warranted it.", cold: "Atlanta had a quiet evening. The Hawks were cooperative.", humor: "The Trae Young era has made Atlanta basketball very loud and very complicated." },
  DAL: { identity: "Dallas — Dirk's house, now Luka's house, with a championship between them worth mentioning", hype: "American Airlines Center got its money's worth tonight.", cold: "Dallas had a long night. The Mavs contributed.", humor: "The Luka era has made Dallas very dramatic. Tonight was evidence." },
  BKN: { identity: "Brooklyn — the franchise that bet big, got burned, and is still figuring out what comes next", hype: "Barclays Center finally had a reason to be loud tonight.", cold: "Brooklyn basketball remains complicated. The evidence keeps arriving.", humor: "Nets fans have developed the calluses of a people who expect nothing and still get less." },
  BRK: { identity: "Brooklyn — the franchise that bet big, got burned, and is still figuring out what comes next", hype: "Barclays Center finally had a reason to be loud tonight.", cold: "Brooklyn basketball remains complicated. The evidence keeps arriving.", humor: "Nets fans have developed the calluses of a people who expect nothing and still get less." },
  CHA: { identity: "Charlotte — LaMelo's show and Michael Jordan's team, a combination that has produced exactly one playoff appearance since 2016", hype: "Spectrum Center had a good night. They don't get many — they'll take this.", cold: "Charlotte stayed Charlotte. Quiet arena, quiet stat lines.", humor: "The Hornets continue to exist, which is itself a form of accomplishment." },
  DET: { identity: "Detroit — Bad Boys banners and a long rebuild that refuses to cooperate", hype: "Little Caesars Arena got a win it can hold onto. That matters.", cold: "Detroit remembers Bad Boys basketball. Tonight was not that.", humor: "The Pistons are building toward something. Nobody is sure what yet." },
  IND: { identity: "Indiana — small market, big runs, the basketball state with something to prove", hype: "Gainbridge Fieldhouse was electric. Pacers basketball when it hums is something to see.", cold: "Indiana plays hard and fast. Tonight the 'fast' did not help.", humor: "Pacers fans know their basketball. That is both a gift and a curse." },
  LAC: { identity: "LA's other team — playoff heartbreak, injury reports, and the long shadow of the other building", hype: "Intuit Dome can be loud when there is a reason. Tonight qualified.", cold: "Clippers basketball had a long night. The injury report probably grew.", humor: "The Clippers curse is patient. It will wait as long as it takes." },
  MEM: { identity: "Memphis — grit-and-grind pride, Ja Morant chaos, and an identity you can see from space", hype: "FedExForum got loud. Memphis basketball at its most Memphis.", cold: "Grit and grind couldn't save this one. The box score is blunt.", humor: "The Grizzlies always play hard. Sometimes that is not enough, and that is also fine." },
  NOP: { identity: "New Orleans — Zion's health report and Brandon Ingram's quiet brilliance, balanced against decades of waiting", hype: "Smoothie King Center had a reason to show up tonight. Finally.", cold: "The Pelicans had a long evening. The injury report is already drafting.", humor: "Zion's availability and the team's success follow each other closely. Correlation, causation, either works." },
  ORL: { identity: "Orlando — the young core, the wingspan, the long climb back to relevance", hype: "Kia Center caught fire. The Magic's window is opening.", cold: "Orlando had a quiet night. Rebuilds have those.", humor: "The Magic's identity is 'our bench is seven feet tall on average.' Tonight they needed more than that." },
  PHX: { identity: "Phoenix — a superteam on paper, in practice, and in every flaming take", hype: "Footprint Center caught the vibe. Suns fans needed this.", cold: "Suns basketball had a long night. The group chat is ablaze.", humor: "The Big Three experiment continues. The results remain fluid." },
  SAC: { identity: "Sacramento — Light The Beam, Fox and Sabonis, a franchise that waited 16 years and now refuses to sit down", hype: "Golden 1 Center is beaming. Kings fans earned this one.", cold: "Sacramento had a quiet night. Not every hand lights the beam.", humor: "Kings fans are the most patient people in basketball. They have had to be." },
  TOR: { identity: "Toronto — one banner, international appeal, and a franchise that never stopped competing quietly", hype: "Scotiabank Arena got loud. Toronto doesn't forget how to show up.", cold: "The Raptors had a long night. Canada noticed.", humor: "The Toronto media is already writing eight different versions of this game." },
  UTA: { identity: "Utah — Stockton and Malone, Donovan Mitchell memories, Rudy Gobert ghosts, and a rebuild that still has altitude", hype: "Delta Center got loud. Utah basketball when it's right is a specific feeling.", cold: "Salt Lake stayed quiet. The Jazz had a long evening.", humor: "The Jazz rebuild is measured, patient, and extremely Utah." },
  WAS: { identity: "Washington — John Wall memories, a long rebuild, and the eternal search for the next franchise cornerstone", hype: "Capital One Arena got a win to remember. DC basketball needed this.", cold: "The Wizards had a long night. The rebuild continues.", humor: "Wizards fans have seen everything except a real run. They are still waiting patiently." },
};
