/**
 * teamFlavor.ts — Team culture database for basketball commentary.
 * Keyed by 3-letter team code (uppercase).
 */

export const TEAM_FLAVOR: Record<string, { identity: string; hype: string; cold: string; humor: string }> = {
  SAS: { identity: "San Antonio — the franchise that turned fundamentals into a dynasty", hype: "Spurs basketball did what Spurs basketball does.", cold: "Even a good game in San Antonio felt organized and efficient.", humor: "What a terribbble basketball game. Maybe too many churros tonight." },
  MIA: { identity: "Miami — the culture, the heat, the late nights, and the conference finals", hype: "Miami culture showed up. The city runs different.", cold: "South Beach had nothing to celebrate tonight.", humor: "The Heat culture would like a word about this performance." },
  BOS: { identity: "Boston — banners, history, and an opinion about every player who passes through", hype: "The Garden was the right place to get right.", cold: "Boston crowds are unforgiving. Tonight gave them material.", humor: "The Celtic faithful are composing the takes as we speak." },
  GSW: { identity: "Golden State — the dynasty that changed the game and is still around to remind you", hype: "Chase Center energy is contagious. The FP caught it.", cold: "Warriors defense is still legitimately problematic for everyone.", humor: "Dubs fans had feelings tonight. They always do." },
  LAL: { identity: "Los Angeles — Showtime, Kobe, LeBron, and sixteen banners that never let you forget", hype: "The lights were bright in LA and the lineup matched them.", cold: "The lights were bright in LA and the performance did not match.", humor: "Lakers Twitter is already processing this." },
  CHI: { identity: "Chicago — the ghost of 72-10 haunts every conversation about that franchise", hype: "The United Center got what it came for.", cold: "Chicago winters and cold performances. The tradition continues.", humor: "The Jordan comparisons are already being made. They are not flattering." },
  NYK: { identity: "New York — the Garden, the most famous arena in basketball, still waiting for the next banner", hype: "Madison Square Garden energy is different. Always has been.", cold: "MSG deserved more than this tonight.", humor: "The Garden crowd let them know. Diplomatically? No." },
  PHI: { identity: "Philadelphia — Trust The Process became Trust The Results, then became Trust The Health Update", hype: "Philly showed up and so did the lineup. Good night.", cold: "Philadelphia crowds don't hide their feelings. Neither did the FP.", humor: "The Sixers fan experience: stunning highs, documented lows, occasional health updates." },
  HOU: { identity: "Houston — Moreyball's birthplace, now rebuilding with maximum optimism", hype: "Houston is building something real. The FP was part of it tonight.", cold: "Toyota Center had a long evening.", humor: "The analytics department is already computing the efficiency rating on this." },
  DEN: { identity: "Denver — altitude, ball movement, and the most unlikely MVP trajectory in the league", hype: "Ball Arena, mile high, and the FP followed.", cold: "Even the altitude couldn't help the numbers tonight.", humor: "Denver fans bring their own oxygen. The performance needed some tonight." },
  MIL: { identity: "Milwaukee — built on drafting a Greek teenager and making him the best player alive", hype: "The Fiserv Forum got what it came for.", cold: "Wisconsin had a cold evening. Weather appropriate.", humor: "Bucks fans are passionate and specific. Tonight gave them specifics." },
  POR: { identity: "Portland — one of the most loyal fan bases watching one of the most unpredictable rebuilds", hype: "The Rose Garden faithful got their money's worth.", cold: "Moda Center was quiet. The FP explains why.", humor: "Portland will still sell out tomorrow. That's just who they are." },
  OKC: { identity: "Oklahoma City — where stars develop, then leave, then get mentioned forever", hype: "OKC's young core is a problem. The building noticed.", cold: "Quiet night in OKC. Both teams were quiet.", humor: "The Thunder arena energy is loud regardless. The scoreboard was the problem." },
  MIN: { identity: "Minnesota — perpetually almost, finally actually, with a cast that justifies watching", hype: "Target Center has something to cheer about now.", cold: "Minnesota sports and heartbreak — the relationship continues.", humor: "Timberwolves fans have been patient. The patience is noted." },
  CLE: { identity: "Cleveland — one of the great comeback stories in sports, authored by the player who left and came back", hype: "The Cavaliers faithful remembered why they showed up.", cold: "Cleveland deserved a better night than this.", humor: "The Cavs and drama have a long documented relationship." },
  ATL: { identity: "Atlanta — Trae Young's playground, and the other side of a draft trade that has never stopped being discussed", hype: "State Farm Arena got loud. The FP warranted it.", cold: "Atlanta had a quiet evening. The Hawks were cooperative.", humor: "The Trae Young era has made Atlanta basketball very loud and very complicated." },
  DAL: { identity: "Dallas — Dirk's house, now Luka's house, with a championship between them worth mentioning", hype: "American Airlines Center got its money's worth tonight.", cold: "Dallas had a long night. The Mavs contributed.", humor: "The Luka era has made Dallas very dramatic. Tonight was evidence." },
};
