  // Orbelín Pineda — Mexico MID $60 ORANGE — avgFP 48.3
  pineda: {
    nicknames: ["Orbe", "Orbelín"],
    knownFor: "Mexico's tireless midfield engine — the small man who runs the whole middle of the pitch.",
    salaryTier: "star",
    tier1: ["When Pineda is on, El Tri's tempo is on.", "The little guy in the middle who refuses to be outworked.", "Mexico's metronome — he sets the pace and the rest of the team finds it."],
    tier2: ["Came up through Querétaro and broke through with Chivas in the Liga MX title era.", "Took the leap to Europe via AEK Athens and Celta Vigo — earned every minute of his international shirt.", "The kind of midfielder who doesn't show up on highlight reels but shows up on tape."],
    tier3: ["Listed at 5'7\" — plays bigger than that in every duel.", "Wore the captain's armband for Chivas in his early twenties."],
    overperform: ["When Pineda decides to drive a match, the match drives where he wants.", "El Tri's whole engine is humming — and the spark plug is Orbelín.", "This is the version Tata kept calling up for a reason."],
    underperform: ["Even tireless legs eventually run out of road.", "Marked out of the game tonight — Mexico's midfield went silent with him.", "Pressed off the ball; the rhythm never quite arrived."],
    onPace: ["Standard Orbe shift — 90 minutes, three tackles, two key passes, no headlines.", "Did the running everyone else didn't want to do.", "The midfield grease — keeps the whole machine moving."],
    loosePlay: ["Tried to slip a pass through traffic and lost it cheaply.", "Yellow card for a tactical foul — the price of being everywhere.", "Heavy touch under pressure — even the workhorses misfire."],
    defensive: ["Tackles like he weighs twenty pounds more than he does.", "Reads the second ball before it bounces.", "The pressing trigger for everyone in front of him."],
    bigGame: ["PINEDA IS EVERYWHERE. Mexico's midfield belongs to him tonight.", "This is the box-to-box outlier game Mexicans dream about.", "Hudson would call him a buzzsaw — and tonight that buzz is deafening."],
    quietGame: ["Quiet shift — the legs went, and Mexico's tempo went with them.", "Subbed at 65 — the sprint count had reached its ceiling.", "Did the unseen work; the box scores won't reflect it."],
    controversy: ["Mexico's Tata Martino era was rough — Pineda was the player Tata kept defending publicly while the press wanted heads.", "Liga MX departure was bittersweet — Chivas fans wanted him to stay forever."],
    famousGameHint: ["Look up his Gold Cup performances — he's been Mexico's best midfielder in CONCACAF tournaments more than once.", "His Olympic bronze medal run in Tokyo 2020 — engine of a deep run."],
    opponentFlavor: {
      ARG: "Drew the unenviable assignment of trying to mark Messi in the group stage — held his own for 70 minutes.",
      POL: "Group-stage 0-0 grind — Mexico's midfield bossed it with him at the heart.",
      KSA: "Final group-stage match — Mexico won but went home on goal difference; he ran himself into the ground.",
    },
    formerTeam: ["Querétaro academy product.", "Chivas captain in his early twenties.", "AEK Athens and Celta Vigo brought him to Europe."],
    rivalry: ["Mexico-USA is in his bones — every CONCACAF qualifier mattered.", "Mexico-Argentina at the World Cup never gets old."],
    teamContext: ["When Tata Martino had Pineda fit, Mexico had a midfield. When he didn't, Mexico didn't.", "Played alongside Herrera and Guardado — the elder statesmen running point with him in the engine room."],
    salaryNarrative: ["At $60 ORANGE he's the surprise top of the value board — avgFP 48 says the algorithm noticed.", "ORANGE because the engine room rarely gets celebrated, but the numbers don't lie.", "Mexico's most paid-off midfielder for the price."],
  },

  // Salman Al-Faraj — Saudi Arabia MID $59 ORANGE — avgFP 42.8
  faraj: {
    nicknames: ["Salman", "Captain Salman"],
    knownFor: "Saudi Arabia's captain and Al-Hilal legend — the man with the armband against Argentina.",
    salaryTier: "star",
    tier1: ["The captain who walked his country into a moment they'll never forget.", "Saudi Arabia's midfield identity — he is the team's heartbeat.", "When you've worn the armband for a decade, the team plays your tempo."],
    tier2: ["Al-Hilal academy graduate — captained the club to AFC Champions Leagues.", "Over 70 caps for Saudi Arabia — quiet career, loud captaincy.", "The face of Saudi football's pre-Ronaldo era."],
    tier3: ["His Al-Hilal trophy cabinet stretches a wall — multiple league titles, multiple continental crowns.", "Has been rebuilding his game around an aging body for the last three seasons."],
    overperform: ["When Salman is conducting, the Saudi midfield finds notes nobody knew were on the page.", "The captain raised the floor of his entire team tonight.", "This is what Al-Hilal fans have watched for a decade."],
    underperform: ["Even the captain has nights when the legs say no.", "The age caught up to him in a way it hadn't yet — happens to everyone.", "Quiet game; the armband couldn't drag the body."],
    onPace: ["Standard captain shift — composed in possession, smart in pressing, organized everyone in front of him.", "Did the work expected of him; nothing flashy, nothing missing.", "Al-Hilal's tempo, Saudi Arabia's tempo, his tempo."],
    loosePlay: ["Passing game went off — the radar wobbled.", "Yellow card for the kind of tactical foul captains take.", "Caught in possession in his own third — rare lapse."],
    defensive: ["Reads the game two passes ahead.", "Positional discipline — never out of shape.", "Wins the second ball through positioning, not athleticism."],
    bigGame: ["SALMAN. The captain has decided the moment is his.", "This is the kind of performance you wear an armband for.", "Saudi Arabia's leader, in full song."],
    quietGame: ["Subbed early — the body had given what it could.", "Marked closely; the captain became a passenger.", "Tactical sub at 60 — saving him for the next match."],
    controversy: ["Hosted the controversial 2034 World Cup bid era's first big tournament — that's a different kind of pressure.", "Captained through coaching changes — every Saudi cycle since 2014."],
    famousGameHint: ["The 2-1 win over Argentina in the group stage — he was the man holding the shape that miracle ran on."],
    opponentFlavor: {
      ARG: "The Argentina upset — Saudi Arabia's biggest World Cup result, and he wore the armband.",
      POL: "Group-stage 0-2 loss — couldn't replicate the Argentina shape against a different problem.",
      MEX: "Final group game — Saudi Arabia went down with the captain trying to drag them through.",
    },
    formerTeam: ["Al-Hilal one-club man — the most decorated Saudi player of his generation.", "AFC Champions League winner multiple times."],
    teamContext: ["Saudi Arabia's tactical core revolved around him in midfield.", "Hervé Renard's pressing scheme depended on his positional reading."],
    milestones: ["AFC Champions League winner.", "Multi-time Saudi Pro League champion.", "Captain of the team that beat Argentina at a World Cup."],
    salaryNarrative: ["At $59 ORANGE he's the surprise pick — Saudi Arabia's avgFP 42 reflects volume of action, not just stardom.", "Cap-eater for a non-European team is rare — this is the exception."],
  },

  // Wataru Endo — Japan MID $56 ORANGE — avgFP 41.1
  endo: {
    nicknames: ["Endo", "The Samurai"],
    knownFor: "Japan's defensive midfield anchor — the destroyer who became Liverpool's surprise transfer.",
    salaryTier: "star",
    tier1: ["The midfielder who never stops — and rarely loses a duel.", "Japan's tactical foundation; everything Moriyasu builds starts with him.", "The kind of defensive midfielder every coach wants and few teams have."],
    tier2: ["Came through Shonan Bellmare and Urawa Reds in J-League before Belgium opened the European door.", "Stuttgart captain — the rare Asian player to wear the armband at a Bundesliga club.", "Liverpool came calling at 30 — late breakthrough, fully earned."],
    tier3: ["Captained Japan through their golden generation — Mitoma, Kubo, Kamada all build off his platform.", "Speaks German, Japanese, and enough English to lead Liverpool's press triggers."],
    overperform: ["When Endo decides he owns the middle of the park, he owns the middle of the park.", "Japan's tempo, his tempo — and tonight the tempo bent everyone backward.", "The destroyer became the conductor — that's a vintage Endo night."],
    underperform: ["Even the samurai has nights when the sword stays sheathed.", "Outrun by a younger leg — happens at 30.", "Marked out by a clever opposite number — credit them, but Endo will be back."],
    onPace: ["Standard Endo — three tackles, two interceptions, 90 minutes of shape.", "Did the unglamorous work; Japan's midfield held because of it.", "The captain's quiet shift."],
    loosePlay: ["Yellow card for the kind of cynical foul captains have to take.", "Heavy touch under pressure — rare from him.", "Pass intercepted; immediately won the ball back."],
    defensive: ["Tackles like the manual.", "Positional reading is what got him to Liverpool — and tonight it was on display.", "Won the ball five yards from his own box and started the counter."],
    bigGame: ["ENDO! Japan's anchor, the captain at his peak.", "This is the performance that earned him a Premier League move.", "The samurai's blade is sharp tonight."],
    quietGame: ["Quiet shift — Japan's whole midfield went with him.", "Subbed at 75 — saving the legs for the next round.", "Marked, doubled, contained — the opposition planned for him and executed."],
    controversy: ["Liverpool transfer surprised many — pundits underestimated him for years.", "Japan's J-League pay structure kept him domestic longer than his talent demanded."],
    famousGameHint: ["Look up Japan's group-stage win over Germany in 2022 — Endo was the foundation that upset held on.", "The Spain group-stage upset — same script, same anchor."],
    opponentFlavor: {
      GER: "Group-stage upset of Germany — Endo's tackles broke the German build-up four times in 90 minutes.",
      ESP: "Beat Spain to top the group — Endo's pressing triggered Mitoma's match-winning moment.",
      CRO: "Round-of-16 — lost on penalties to Modrić's Croatia, but Endo matched the maestro for 120 minutes.",
      CRC: "Group-stage loss to Costa Rica — Japan's only blip, and his anchor wasn't enough that night.",
    },
    formerTeam: ["Shonan Bellmare academy.", "Urawa Reds — J-League title winner.", "Sint-Truiden in Belgium for the European leap.", "Stuttgart captain — Bundesliga mainstay.", "Liverpool from 2023 — the Premier League breakthrough at 30."],
    teamContext: ["Japan's whole tactical identity in 2022 was Endo holding while the wingers ran.", "Moriyasu's pressing scheme used Endo as the trigger and the safety net."],
    milestones: ["Japan's captain at the 2022 World Cup.", "Stuttgart captain in the Bundesliga.", "Liverpool transfer at 30 — late-career validation."],
    salaryNarrative: ["At $56 ORANGE he's the value pick on Japan's roster — avgFP 41 reflects 90-minute volume.", "The destroyer cap is rare; this one earns it."],
  },

  // Yussuf Poulsen — Denmark MID $54 ORANGE — avgFP 39.0
  poulsen: {
    nicknames: ["Yussuf", "Poulsen"],
    knownFor: "Denmark's RB Leipzig forward — the lanky runner who's been the team's outlet for a decade.",
    salaryTier: "star",
    tier1: ["The kind of forward who runs all night and finds the goal in the 88th minute.", "Denmark's outlet — when the ball goes long, it goes to Yussuf.", "RB Leipzig built a Bundesliga identity around runners like him."],
    tier2: ["Came through Lyngby in Denmark before RB Leipzig signed him at 19 — grew with the club.", "One of Leipzig's longest-serving players — saw the rise from 2. Bundesliga to Champions League nights.", "Denmark's quiet workhorse — the kind of player every successful team needs but few highlight reels celebrate."],
    tier3: ["Tanzanian father, Danish mother — represented Denmark from youth level all the way through.", "Listed at 6'4\" — the kind of frame that gives center-backs nightmares in the air."],
    overperform: ["When Yussuf finds his stride, the long balls keep finding him.", "Denmark's outlet is in full song tonight.", "This is the version Hjulmand keeps starting for a reason."],
    underperform: ["Quiet game — the long ball didn't stick the way it usually does.", "Marked by a defender who matched his physicality — credit them.", "Couldn't find the channel; the runs didn't pay off."],
    onPace: ["Standard Yussuf — 90 minutes of running, one chance, one assist or close.", "Did the work; Denmark's shape held because of it.", "Long balls found him; he held them up; the team breathed."],
    loosePlay: ["Heavy touch — the kind that comes with running at full speed.", "Caught offside on a run he'd gambled on.", "Yellow card for a tactical foul on a turnover."],
    defensive: ["Tracks back when asked — the kind of forward who pressed before pressing was cool.", "Won an aerial duel that started a counter.", "Pressed the centre-back into a panicked clearance."],
    bigGame: ["POULSEN! The lanky frame, the late finish, the Danish roar.", "This is the kind of game that gets you a Bundesliga renewal.", "The outlet became the finisher tonight."],
    quietGame: ["Subbed at 70 — Hjulmand looking for fresh legs.", "Marked out of the channel; couldn't find the run.", "Quiet game; the headlines went to the wingers."],
    controversy: ["Denmark's 2022 World Cup was a disaster — Yussuf wasn't the cause but he wasn't the cure either.", "Leipzig's ownership controversy in Germany never quite stopped following him."],
    famousGameHint: ["His Euro 2020 performances when Eriksen collapsed — Denmark's emotional run had him at the heart of it.", "Look up his Russia 2018 goal against Peru — set up the Denmark group-stage advance."],
    opponentFlavor: {
      TUN: "Group-stage 0-0 — Denmark's frustrating opener; Yussuf couldn't crack the Tunisian back line.",
      FRA: "Group-stage loss — Mbappé's brace overshadowed Denmark's effort, Yussuf included.",
      AUS: "Group-stage loss — Denmark went out, and his channel never opened.",
    },
    formerTeam: ["Lyngby in Denmark — youth product.", "RB Leipzig from 2013 — saw the entire rise of the club.", "Long-serving Bundesliga forward."],
    teamContext: ["Denmark's tactical setup in 2022 was 'long balls to Poulsen' — when it didn't work, neither did the team.", "Hjulmand kept faith with him through bad patches because the running matters."],
    salaryNarrative: ["At $54 ORANGE he's a volume pick — avgFP 39 from 90-minute shifts.", "Cheap because Denmark went home early; productive because his minutes count."],
  },

  // Hakim Ziyech — Morocco MID $52 ORANGE — avgFP 38.1
  ziyech: {
    nicknames: ["The Wizard", "Hakim"],
    knownFor: "Morocco's left-footed magician — the wand that helped power Africa's first World Cup semifinal.",
    salaryTier: "star",
    tier1: ["When Ziyech's left foot is loaded, the goal is already half-scored.", "Morocco's creative engine — every dangerous moment in 2022 ran through him.", "The wand from Dronten — Dutch academy, Moroccan heart."],
    tier2: ["Born in the Netherlands, chose Morocco — and was vindicated by a semifinal run.", "Ajax to Chelsea for £33m — a Champions League winner with the Blues in 2021.", "Fell out with Walid Regragui's predecessor; was reinstated and helped make history."],
    tier3: ["His left foot has been compared to Robben's and Quaresma's in the same breath.", "The 'Hakim Ziyech retirement' saga from Morocco's national team in 2021 was one of the messier federation stories of the cycle."],
    overperform: ["When Ziyech is feeling it, every set piece is dangerous, every cross is a chance.", "The wizard has decided this is his match — the wand is glowing.", "Morocco's whole tournament tilted on nights like this."],
    underperform: ["Even the wand has nights when the spell doesn't land.", "Marked tightly; the left foot couldn't find space.", "Frustrated tonight — the kind of game that ends with him on a yellow card."],
    onPace: ["Standard Ziyech — three set pieces, two key passes, one shot from distance that nearly went in.", "Did the work; the chances were there, just not converted.", "Morocco's creativity ran through him as expected."],
    loosePlay: ["Yellow card for dissent — happens when the touch is off.", "Tried a cross-field switch that went straight out.", "Caught dribbling into trouble — rare for him."],
    defensive: ["Tracks back more than people give him credit for.", "Pressed the full-back into a giveaway.", "Won a tackle in midfield — Regragui's pressing scheme demanded it."],
    bigGame: ["ZIYECH! THE WAND IS DRAWN. Morocco's magician is in full song.", "This is the kind of left-footed performance that wins continents over.", "Hudson would call this 'magisterial' — and tonight it is."],
    quietGame: ["Quiet game — the marker stayed close all 90 minutes.", "Subbed at 75; the legs had given what they could.", "Couldn't find the angle; Morocco's creativity went through other channels."],
    controversy: ["Retired from international duty in 2021 after a fall-out with the federation — was coaxed back by Regragui in 2022.", "Chelsea move never quite worked out — the move that should have made him a global superstar didn't.", "Galatasaray in 2023 was a soft landing after years of frustration."],
    famousGameHint: ["His Spain shootout assist — the cross that started everything for Morocco's quarterfinal run.", "Look up his Belgium goal in the group stage — a free kick that announced Morocco was for real.", "His Portugal performance in the quarterfinal — Morocco made history and his left foot was central to it."],
    opponentFlavor: {
      BEL: "Group-stage free kick goal — announced Morocco was here to compete.",
      ESP: "Round-of-16 shootout — his cross created the move, Bono saved the rest.",
      POR: "Quarterfinal — Africa's first semifinalist, and Ziyech's wand was central to the build-up.",
      FRA: "Semifinal exit — held to a quiet game by France's tactical setup.",
      CRO: "Group-stage 0-0 — frustrating opener but Morocco didn't lose.",
    },
    formerTeam: ["Heerenveen youth — Dutch development.", "Twente — Eredivisie breakthrough.", "Ajax — the years that made him.", "Chelsea — Champions League winner, never quite settled.", "Galatasaray — soft landing in Turkey."],
    teamContext: ["Morocco's 2022 was Bono behind, Saïss in front, Ziyech ahead — the spine of a semifinalist.", "Regragui's tactical pivot to bring him back into the squad was the move that changed Moroccan football."],
    milestones: ["Champions League winner with Chelsea (2021).", "Africa Cup of Nations runner-up.", "First African nation to reach a World Cup semifinal — and he was central to it."],
    salaryNarrative: ["At $52 ORANGE he's a creative outlier pick — set-piece volume keeps his floor stable.", "The wand cap — when it works, it works for Morocco."],
  },

  // Joshua Kimmich — Germany MID $51 PURPLE — avgFP 36.9
  kimmich: {
    nicknames: ["Jo", "Kimmich"],
    knownFor: "Bayern Munich's midfield general — Germany's most complete two-way player.",
    salaryTier: "star",
    tier1: ["The closest thing Germany has to a Pirlo — except he tackles, too.", "Bayern Munich's tactical core — Flick, Nagelsmann, Tuchel all built around him.", "The footballer's footballer — every coach in Europe has him on their dream-XI list."],
    tier2: ["RB Leipzig to Bayern at 21 — Pep Guardiola signed him personally.", "Played right-back, central midfield, and even centre-back across his Bayern career — wherever the team needed.", "The face of post-Lahm Bayern Munich — captain in waiting since 2018."],
    tier3: ["Was vocal about COVID vaccination during the pandemic — created controversy in Germany.", "Listed at 5'9\" but plays bigger than every defensive midfielder in the Bundesliga."],
    overperform: ["When Kimmich is conducting, Germany's whole tempo bends to him.", "Eight Bundesliga titles say something about how often this version shows up.", "The complete midfielder in full song."],
    underperform: ["Even Kimmich has nights when the radar is off.", "Germany's whole midfield wobbled with him.", "Pressed off the ball; the rhythm never landed."],
    onPace: ["Standard Kimmich — 60 touches, 90% pass accuracy, three tackles, one set-piece chance.", "Did the work expected; Germany's shape held because of it.", "The metronome ran true."],
    loosePlay: ["Yellow card for tactical foul — the captain's tax.", "Caught in possession trying to play through a press — rare.", "Heavy touch under pressure; recovery tackle followed immediately."],
    defensive: ["Tackles like a defender, reads like a midfielder.", "His positional discipline is what makes Bayern Bayern.", "Won the ball five times tonight — the kind of shift that gets you Ballon d'Or votes."],
    bigGame: ["KIMMICH! Germany's general, the metronome at full song.", "This is the performance that wins Bundesliga titles.", "Drury would call this 'magisterial' and he'd be right."],
    quietGame: ["Quiet game — Germany went home early; the metronome ran into too many problems.", "Subbed at 80 — saving him for the next round that never came.", "Marked closely; couldn't find his usual rhythm."],
    controversy: ["The COVID vaccination saga in 2021-22 was front-page news in Germany — the federation publicly distanced itself from his stance.", "Germany's 2022 group-stage exit had him as one of the leadership voices that took heat.", "Leadership style has been called 'intense' — even Bayern teammates have noted it."],
    famousGameHint: ["Germany's group-stage 1-2 loss to Japan in 2022 — Kimmich was the captain trying to stem a disaster.", "Look up his goal against Brazil in the 7-1 — he was 21 years old and unfazed."],
    opponentFlavor: {
      JPN: "The Japan group-stage upset — Kimmich was the leader watching it unfold.",
      ESP: "Group-stage draw with Spain — Kimmich vs Rodri was the midfield matchup of the round.",
      CRC: "Final group game — Germany won but went home on goal difference. Kimmich's tournament ended in tears.",
    },
    formerTeam: ["VfB Stuttgart youth.", "RB Leipzig — Bundesliga breakthrough.", "Bayern Munich from 2015 — the franchise."],
    teamContext: ["Germany's 2022 tactical core — Flick built the midfield around him and Goretzka.", "Bayern Munich captain in waiting since 2018."],
    milestones: ["Eight Bundesliga titles with Bayern.", "Champions League winner (2020).", "Germany's most-capped active midfielder."],
    salaryNarrative: ["At $51 PURPLE he's the most reliable midfielder card on the German roster — avgFP 37 reflects 90-minute volume.", "PURPLE because Germany underperformed; in any other tournament he's ORANGE."],
  },

  // Ali Abdi — Tunisia DEF $53 ORANGE — avgFP 36.2
  abdi: {
    nicknames: ["Ali"],
    knownFor: "Tunisia's left-back — the dependable defender who quietly anchored the 2022 group stage upset.",
    salaryTier: "star",
    tier1: ["The kind of left-back every coach wishes they had in the squad.", "Tunisia's quiet warrior — does the work nobody else wants to.", "The defender who turned a Caen left-back slot into a World Cup starting role."],
    tier2: ["Came up through Tunisian club football before Caen in France gave him his European platform.", "Made his Tunisia debut later than most — proved that the slow path still gets you to a World Cup.", "Part of Tunisia's defensive group that drew Denmark and beat France in the group stage."],
    tier3: ["Plays his club football in Ligue 2 — the World Cup was a bigger stage than his weekly grind.", "Listed at 5'10\" — built like a modern wing-back, not an old-fashioned full-back."],
    overperform: ["When Abdi locks down his side, the wing belongs to Tunisia.", "Held up Mbappé for 70 minutes — that's a story to tell.", "Tunisia's left flank was a fortress with him in it."],
    underperform: ["Even the dependable defenders have nights when the marker beats them.", "Caught out of position once or twice — the kind of error that haunts a tournament.", "Frustrated tonight — and Tunisia paid for it."],
    onPace: ["Standard shift — 90 minutes of disciplined defending.", "Did the work; nobody got past him cheaply.", "Tunisia's left flank held because of him."],
    loosePlay: ["Yellow card for a late tackle.", "Caught flat-footed by a quick winger — rare for him.", "Pass from the back went straight out of play."],
    defensive: ["Tackles cleanly — old-school defending.", "Won every aerial duel his side asked of him.", "Read the cross before it left the boot."],
    bigGame: ["ABDI! Tunisia's wall on the left, holding firm against France.", "This is the kind of defender performance that gets you a Ligue 1 move.", "Africa's defense, in full song."],
    quietGame: ["Quiet shift — defenders' best games are often the ones nobody notices.", "Subbed late; tactical change.", "Tunisia's flank held; he was the reason."],
    controversy: ["Tunisia's federation cycle was rough in 2022 — coaching changes between qualifying and the tournament.", "Ligue 2 wages versus World Cup minutes — an interesting career snapshot."],
    famousGameHint: ["The 1-0 win over France in the group stage — Tunisia's biggest result, and Abdi was on the back four.", "Look up the Denmark draw — Tunisia's defensive shape held a Euro semifinalist scoreless."],
    opponentFlavor: {
      DEN: "Group-stage 0-0 — Tunisia held Denmark scoreless and Abdi was central to it.",
      AUS: "Group-stage 0-1 loss — the only blip in Tunisia's defensive run.",
      FRA: "1-0 over France in the dead rubber — went home with a win to remember.",
    },
    formerTeam: ["Caen in Ligue 2 — long-serving European chapter.", "Tunisian Pro League formative years."],
    teamContext: ["Tunisia's 2022 was a defensive identity — Abdi was one of the four reasons it worked.", "Jalel Kadri's tactical setup needed disciplined full-backs and got them."],
    salaryNarrative: ["At $53 ORANGE he's a defender outlier — avgFP 36 reflects clean sheets and tackle volume.", "ORANGE because Tunisia overperformed defensively — the algorithm noticed."],
  },

  // Alphonso Davies — Canada MID $49 PURPLE — avgFP 35.9
  davies: {
    nicknames: ["Phonzy", "The Roadrunner", "Phonzie"],
    knownFor: "Canada's flying full-back — born in a refugee camp, now Bayern Munich's left-back.",
    salaryTier: "star",
    tier1: ["The fastest left-back in world football — and there's a real argument for it.", "Canada's first true global star — the kid who took the maple leaf to a World Cup.", "When Davies hits the afterburners, the touchline becomes a runway."],
    tier2: ["Born in a Ghanaian refugee camp to Liberian parents fleeing civil war.", "Edmonton, Alberta to Vancouver Whitecaps to Bayern Munich — the most extraordinary career path in MLS history.", "Champions League winner at 19 — the youngest North American to lift the trophy."],
    tier3: ["His parents arrived in Canada when he was five; he chose to represent the country that took them in.", "Bayern Munich paid Vancouver $22m for him — at the time the largest MLS transfer fee ever."],
    overperform: ["When Davies decides to go, the touchline belongs to him.", "The Roadrunner is in full flight tonight.", "This is the version Bayern signed — and Canada's most dangerous player."],
    underperform: ["Even the rocket has nights when the legs don't fire.", "Caught defensively — the price of his attacking ambition.", "Frustrated; his runs didn't pay off and his side conceded down his channel."],
    onPace: ["Standard Phonzy — three sprints into the final third, two crosses, 90 minutes of width.", "Did the work; Canada's left flank ran because of him.", "Bayern's defensive numbers, Canada's attacking output — the duality."],
    loosePlay: ["Caught out of position — happens when you're 80 yards up the pitch.", "Heavy first touch — even rockets misfire.", "Yellow card for a tactical foul recovering."],
    defensive: ["Tackles when he's there; sometimes he isn't.", "His recovery pace makes up for positional gambles.", "Pressed the centre-back into a panicked clearance."],
    bigGame: ["DAVIES! Canada's hero, Bayern's rocket, the Roadrunner in full flight.", "This is the kind of full-back performance you watch on YouTube ten years later.", "Hudson would call him 'a ghost in the machine' — and tonight the machine is running."],
    quietGame: ["Quiet shift — Canada's tournament didn't go as hoped.", "Subbed at 70 — tactical shift.", "Marked tightly by a clever winger — credit them, but Davies will be back."],
    controversy: ["Took the captaincy young — some media questioned the timing.", "The Canadian federation's pay dispute around the World Cup created drama Davies handled diplomatically.", "Bayern contract negotiations have been a Bundesliga storyline for years."],
    famousGameHint: ["Canada's 2-1 loss to Belgium — Davies missed a penalty in his country's first World Cup match in 36 years.", "His Champions League final goal-line clearance for Bayern in 2020 — a 19-year-old won a continental trophy."],
    opponentFlavor: {
      BEL: "Group-stage opener — missed the penalty that would have given Canada a 1-0 lead in their first World Cup match in 36 years.",
      CRO: "Scored Canada's first-ever World Cup goal — a moment in his country's footballing history.",
      MAR: "Group-stage exit — Canada went home winless.",
    },
    formerTeam: ["Vancouver Whitecaps — MLS academy product.", "Bayern Munich from 2019 — Champions League winner at 19."],
    teamContext: ["Canada's 2022 attack ran through his left flank — when he didn't fire, the team didn't.", "John Herdman's tactical setup put him in the most attacking left-back role in CONCACAF."],
    milestones: ["Champions League winner (2020).", "Canada's first World Cup goalscorer in 36 years.", "First North American to win the Bundesliga's best young player award."],
    rivalry: ["Canada-USA at the international level — every CONCACAF qualifier mattered.", "Bayern-Dortmund — Davies has been on the right side of every Klassiker for years."],
    salaryNarrative: ["At $49 PURPLE he's the upside pick on the Canada roster — avgFP 36 reflects volume and chance creation.", "PURPLE because Canada went home early; in a longer tournament he's ORANGE."],
  },

  // Christian Eriksen — Denmark MID $49 PURPLE — avgFP 35.5
  eriksen: {
    nicknames: ["Eriksen", "Christian"],
    knownFor: "The Danish maestro who came back from cardiac arrest and made it to a World Cup.",
    salaryTier: "star",
    tier1: ["The midfielder who was clinically dead for minutes and came back to play in a World Cup.", "Denmark's playmaker — the kind of left foot every team wants.", "If you want to teach a kid how to whip a free kick, show them Eriksen tape."],
    tier2: ["Ajax academy graduate — Eredivisie at 16, Tottenham at 21, Inter at 28.", "Collapsed on the pitch at Euro 2020 — cardiac arrest, defibrillator, tears around the world.", "Came back via Brentford in the Premier League and signed for Manchester United at 30."],
    tier3: ["Has an ICD (implantable cardioverter-defibrillator) — and still plays at the highest level.", "His Brentford comeback in 2022 was one of the most emotional storylines in Premier League history."],
    overperform: ["When Eriksen's free-kick foot is loaded, the goal is already half-scored.", "Denmark's tempo lives in his left boot.", "This is the version that took Tottenham to a Champions League final."],
    underperform: ["Even Eriksen has nights when the legs don't quite hold up.", "Marked tightly; the creativity went elsewhere.", "Frustrated; the chances came and went."],
    onPace: ["Standard Christian — three set pieces, two key passes, one shot from distance.", "Did the work; Denmark's creativity ran through him.", "The metronome ran true."],
    loosePlay: ["Heavy touch under pressure — happens when the press triggers right.", "Yellow card for dissent — tactical frustration.", "Free-kick went over the bar by a foot."],
    defensive: ["Not his strength — but he tracks back when asked.", "Pressed the centre-back; not always successfully.", "Won a tackle in midfield — Hjulmand's setup demanded it."],
    bigGame: ["ERIKSEN! Denmark's maestro, in full song.", "This is the version that taught Tottenham how to attack.", "The free kick is loaded — and the keeper is praying."],
    quietGame: ["Quiet game — Denmark's tournament went badly, and Eriksen wasn't enough.", "Subbed at 75 — managing his minutes after the cardiac event.", "Marked closely; the creativity didn't land."],
    controversy: ["Inter Milan released him in 2021 because Italian rules forbid players with ICDs — a contract terminated by medical regulation.", "The Premier League's medical clearance for him was a nuanced legal-medical conversation.", "Manchester United fans had mixed feelings about his signing — some saw it as charity, others as a coup."],
    famousGameHint: ["Look up his Euro 2020 collapse — and his Euro 2024 return — they bookend a comeback story.", "His Tottenham Champions League run in 2019 — semifinal, final, the lot.", "His Brentford comeback debut — there wasn't a dry eye in the stadium."],
    opponentFlavor: {
      TUN: "Group-stage 0-0 — Denmark frustrated, Eriksen could not unlock the Tunisian defense.",
      FRA: "Group-stage loss — Mbappé brace overshadowed Denmark, including Eriksen.",
      AUS: "Group-stage loss — Denmark went home, and his tournament ended quietly.",
    },
    formerTeam: ["Ajax academy from 16.", "Tottenham from 2013 — eight years.", "Inter Milan — released after cardiac event.", "Brentford — emotional comeback.", "Manchester United from 2022."],
    teamContext: ["Denmark's whole tactical setup in 2022 was Eriksen creating, Poulsen running, the rest covering.", "Hjulmand's pressing scheme depended on Eriksen connecting midfield to forwards."],
    milestones: ["Euro 2020 cardiac arrest survivor — a footballing miracle.", "Premier League Player of the Month at Brentford.", "Over 130 caps for Denmark."],
    salaryNarrative: ["At $49 PURPLE he's the comeback story pick — avgFP 36 reflects volume not goals.", "PURPLE because Denmark underperformed; in any other tournament he's ORANGE."],
  },

  // Fabinho — Brazil MID $48 PURPLE — avgFP 34.5
  tavares: {
    nicknames: ["Fabinho", "Fabi"],
    knownFor: "Liverpool's defensive midfielder — Brazil's lighthouse in front of the back four.",
    salaryTier: "star",
    tier1: ["The defensive midfielder Klopp built Liverpool around for half a decade.", "Brazil's defensive shield — when Fabinho's right, the whole team is right.", "The kind of holding midfielder every successful team owes a championship to."],
    tier2: ["Came through Fluminense and Real Madrid Castilla before Monaco gave him his big break.", "Liverpool signed him in 2018 — won the Premier League, Champions League, and FA Cup with the Reds.", "Saudi Pro League move in 2023 was a surprise — but the cheque was extraordinary."],
    tier3: ["Originally a right-back at Monaco — Klopp converted him into a defensive midfielder and the rest is history.", "His 2018-19 Champions League run was one of the great defensive midfield performances of the decade."],
    overperform: ["When Fabinho is in form, Brazil's defensive shape is impenetrable.", "The lighthouse is on — and the whole midfield navigates by him.", "This is the version Liverpool fans miss every week."],
    underperform: ["Even Fabinho has nights when the legs aren't there.", "Marked out of the game — credit the opposite number.", "Pressed off the ball; rare from him."],
    onPace: ["Standard Fabinho — three tackles, two interceptions, 90 minutes of shape.", "Did the work; Brazil's midfield held because of it.", "The metronome ran true."],
    loosePlay: ["Yellow card for a tactical foul — the defensive midfielder's tax.", "Caught in possession — happens once a tournament.", "Heavy touch under pressure; recovery tackle followed."],
    defensive: ["Tackles like the manual.", "Reads the second ball before it lands.", "Won the ball five yards from his own box and started the counter."],
    bigGame: ["FABINHO! Brazil's anchor, holding the whole shape together.", "This is the kind of defensive midfield performance that wins championships.", "The lighthouse is shining."],
    quietGame: ["Quiet shift — Brazil's tournament ended in heartbreak; Fabinho's role wasn't enough.", "Subbed at 80; tactical change.", "Marked closely; couldn't impose his usual shape."],
    controversy: ["Saudi Pro League move in 2023 raised eyebrows — Liverpool fans saw it as betrayal, family saw it as a payday.", "Liverpool form dipped in 2022-23 — pundits debated whether he'd lost a step."],
    famousGameHint: ["His 2018-19 Champions League final performance — Tottenham couldn't get past him.", "Look up Brazil's quarterfinal against Croatia in 2022 — Fabinho was on the back foot for 90 minutes."],
    opponentFlavor: {
      SUI: "Group-stage 1-0 — Fabinho organized the midfield through a tight match.",
      CMR: "Group-stage loss — Brazil rotated, the shape wobbled, and Fabinho watched from the bench.",
      KOR: "Round-of-16 — Brazil won 4-1 and Fabinho controlled the tempo.",
      CRO: "Quarterfinal exit on penalties — the heartbreak that ended Brazil's tournament.",
    },
    formerTeam: ["Fluminense youth.", "Real Madrid Castilla — formative European years.", "Monaco — breakthrough.", "Liverpool from 2018 — championships.", "Al-Ittihad in Saudi Arabia from 2023."],
    teamContext: ["Brazil's tactical setup needed a defensive shield in front of the back four — Fabinho was the answer for years.", "Tite's 2022 squad had Casemiro starting; Fabinho was the deputy who came on when shape was needed."],
    milestones: ["Champions League winner (2019).", "Premier League winner (2020).", "FA Cup winner (2022)."],
    salaryNarrative: ["At $48 PURPLE he's a defensive midfielder card — avgFP 35 reflects 90-minute volume not goals.", "PURPLE because the holding midfielder rarely cracks the top of the avgFP rankings."],
  },

  // Ivan Perišić — Croatia DEF $48 PURPLE — avgFP 32.9
  perišić: {
    nicknames: ["Perica", "Perišić"],
    knownFor: "Croatia's left-sided weapon — the wing-back who keeps showing up at the biggest moments.",
    salaryTier: "star",
    tier1: ["When Perišić is in the box, the cross is going to find him.", "Croatia's left-sided weapon — wing-back, winger, finisher, all in one body.", "The kind of player Inter, Bayern, and Tottenham all wanted for a reason."],
    tier2: ["Came up through Hajduk Split and Sochaux before Borussia Dortmund and Wolfsburg made him a Bundesliga regular.", "Inter Milan from 2015 — won the Serie A title in 2021.", "Tottenham at 33 because Conte trusted him; Hajduk Split at 35 to come full circle."],
    tier3: ["Scored in the 2018 World Cup final against France — one of two Croatian goalscorers in that match.", "Listed at 6'2\" — the kind of frame that gives him aerial dominance most wingers don't have."],
    overperform: ["When Perišić finds the box, he finds the goal.", "Croatia's left flank is on fire — and the cross is coming.", "This is the version that scored a World Cup final goal."],
    underperform: ["Even Perišić has nights when the marker stays close.", "Frustrated tonight; the runs didn't pay off.", "Couldn't find the channel; Croatia's left flank went quiet."],
    onPace: ["Standard Perica — 90 minutes of width, two crosses, one chance taken cleanly.", "Did the work; Croatia's tempo ran through him.", "The reliable left-flank threat."],
    loosePlay: ["Heavy touch — the kind that comes with running at full speed.", "Caught offside on a run he'd gambled on.", "Yellow card for a late tackle."],
    defensive: ["Tracks back like the wing-back he became at Inter.", "Won an aerial duel that started a counter.", "Tackles cleanly — old-school work-rate."],
    bigGame: ["PERIŠIĆ! Croatia's left-sided rocket — and the goal is coming.", "This is the kind of game that gets you a Champions League final.", "Wing-back at his peak."],
    quietGame: ["Quiet shift — Croatia ran out of road eventually.", "Subbed at 80; legs given everything.", "Marked closely; the cross didn't land."],
    controversy: ["Tottenham move at 33 was questioned — pundits underestimated him as usual.", "Inter Milan exit was ugly — a contract dispute that left a sour taste."],
    famousGameHint: ["The 2018 World Cup final — Perišić scored Croatia's equalizer against France.", "Look up his Japan equalizer in 2022 — the goal that sent the match to penalties."],
    opponentFlavor: {
      JPN: "Round-of-16 equalizer that sent the match to penalties — Croatia won the shootout.",
      BRA: "Quarterfinal upset — Croatia knocked Brazil out and Perišić was central to the late equalizer build-up.",
      ARG: "Semifinal exit — Croatia couldn't crack Argentina.",
      MAR: "Third-place playoff loss — final World Cup match for the golden generation.",
      CAN: "Group-stage 4-1 win — Croatia's biggest scoreline.",
      BEL: "Group-stage 0-0 draw — Perišić bossed the left flank.",
    },
    formerTeam: ["Hajduk Split youth — coming home in 2024.", "Sochaux in France.", "Dortmund and Wolfsburg in the Bundesliga.", "Inter Milan from 2015 — Serie A winner.", "Tottenham from 2022."],
    teamContext: ["Croatia's left flank in 2022 was Perišić attacking, Sosa defending, Modrić feeding both.", "Dalić's tactical setup put him in the most attacking wing-back role in the squad."],
    milestones: ["2018 World Cup final goalscorer.", "Serie A winner with Inter (2021).", "Three World Cup tournaments."],
    rivalry: ["Croatia-Serbia is the deepest rivalry in his region.", "Inter-Juventus — Perišić has been on the right side of multiple Derby d'Italia."],
    salaryNarrative: ["At $48 PURPLE he's the underrated wing-back card — avgFP 33 reflects volume and chance creation.", "PURPLE because wing-backs rarely top the avgFP charts; the goals make the cap worth it."],
  },

  // Ibrahima Konaté — France DEF $46 PURPLE — avgFP 31.0
  konaté: {
    nicknames: ["Ibou", "Konaté"],
    knownFor: "Liverpool's centre-back — France's defensive answer alongside Varane and Upamecano.",
    salaryTier: "star",
    tier1: ["The centre-back built like a heavyweight boxer who reads the game like a chess master.", "Liverpool's defensive backbone — Klopp signed him to be Van Dijk's partner.", "France's depth at centre-back is so deep, Konaté is the third option — and he'd start for any other team."],
    tier2: ["Sochaux academy graduate — Ligue 2 to RB Leipzig in two years.", "Liverpool from 2021 — Klopp paid £36m for him at 22.", "Made his France debut in 2022 — late international breakthrough, fully earned."],
    tier3: ["Listed at 6'4\" — towers over most strikers in the air.", "His older brother is a basketball player — athletic genes run in the family."],
    overperform: ["When Konaté locks down the back, the box belongs to France.", "Held a striker scoreless for 90 minutes — that's a centre-back's masterclass.", "This is the version Klopp signed for £36m."],
    underperform: ["Even Konaté has nights when the marker beats him.", "Caught flat-footed by a quick striker — rare for him.", "Frustrated tonight — and the box paid for it."],
    onPace: ["Standard Ibou — two tackles, three clearances, 90 minutes of dominant aerial work.", "Did the work; France's back four held because of it.", "The wall."],
    loosePlay: ["Yellow card for a tactical foul — the centre-back's tax.", "Caught playing out from the back — heavy touch under pressure.", "Lost his man on a corner; recovery tackle followed."],
    defensive: ["Wins every aerial duel.", "Tackles cleanly — old-school defending with modern athleticism.", "Read the cross before it left the boot."],
    bigGame: ["KONATÉ! France's wall, Liverpool's heavyweight, the box is closed.", "This is the kind of centre-back performance that wins World Cup finals.", "The third-choice centre-back is a starter on any other team."],
    quietGame: ["Quiet shift — defenders' best games are often the ones nobody notices.", "Subbed at 80; tactical change.", "France's back held; he was part of the reason."],
    controversy: ["Liverpool injury history has been a Premier League storyline — but he's healthy when he's healthy.", "France's centre-back depth means he rotates — never quite the undisputed starter."],
    famousGameHint: ["The 2022 World Cup final — Konaté started in defense as France lost on penalties.", "Look up his Liverpool Champions League run in 2022 — semifinal performance against Villarreal."],
    opponentFlavor: {
      ARG: "World Cup final — started in central defense, conceded three goals across regulation and extra time, lost on penalties.",
      MAR: "Semifinal — France held Morocco's attack scoreless across most of the 90.",
      ENG: "Quarterfinal — France beat England, Konaté in the heart of the defense.",
      POL: "Round-of-16 — France advanced 3-1, Konaté solid throughout.",
      DEN: "Group-stage win — France controlled the back four.",
      AUS: "Group-stage 4-1 — France's emphatic opener.",
      TUN: "Group-stage 0-1 loss — the dead-rubber blip.",
    },
    formerTeam: ["Sochaux youth — Ligue 2 development.", "RB Leipzig from 2017 — Bundesliga breakthrough.", "Liverpool from 2021 — Premier League mainstay."],
    teamContext: ["France's 2022 squad had Varane and Upamecano as the first-choice centre-back pairing — Konaté was the depth that became a starter.", "Deschamps' tactical setup demanded centre-backs who could play out from the back; Konaté delivered."],
    milestones: ["World Cup final starter (2022).", "Premier League and Champions League experience with Liverpool.", "France international from 2022."],
    salaryNarrative: ["At $46 PURPLE he's a centre-back card — avgFP 31 reflects clean sheets and tackle volume.", "PURPLE because centre-backs rarely top the avgFP rankings; the floor is the value."],
  },

  // Gabriel Martinelli — Brazil FWD $54 ORANGE — avgFP 30.4
  martinelli: {
    nicknames: ["Gabi", "Martinelli"],
    knownFor: "Arsenal's flying winger — Brazil's left-sided weapon and the steal of the transfer window.",
    salaryTier: "star",
    tier1: ["The kind of winger that makes a left-back rethink their career.", "Arsenal's £6m signing that became a £100m talent.", "Brazil's future in attack — the runs, the finishes, the relentless energy."],
    tier2: ["Came up through Ituano in São Paulo — Arsenal signed him at 18 for £6m, the bargain of the decade.", "Made his Brazil debut at 21 — late international breakthrough by Brazilian standards.", "The kind of left winger that makes Arsenal title-contenders."],
    tier3: ["Italian-Brazilian heritage — could have played for Italy at youth level but chose Brazil.", "His Premier League goal celebration with Saka was a meme for half of 2022."],
    overperform: ["When Martinelli is on, the left flank is a runway.", "The Arsenal version showed up — and Brazil reaped the benefits.", "This is the kind of game that gets you a Ballon d'Or vote."],
    underperform: ["Even Martinelli has nights when the marker stays close.", "Frustrated tonight — the runs didn't pay off.", "Couldn't find the channel; Brazil's left went quiet."],
    onPace: ["Standard Gabi — three sprints, two crosses, 90 minutes of width.", "Did the work; Brazil's left flank ran because of it.", "The reliable winger shift."],
    loosePlay: ["Heavy touch under pressure — happens when you're running at full speed.", "Caught offside on a run he'd gambled on.", "Yellow card for a tactical foul."],
    defensive: ["Tracks back like an Arteta-disciplined winger.", "Pressed the centre-back into a panicked clearance.", "Won a tackle in his own third — Premier League work-rate."],
    bigGame: ["MARTINELLI! The flying Brazilian, Arsenal's rocket, the left flank is on fire.", "This is the version that drove Arsenal's 2022-23 title charge.", "Hudson would call him 'a bullet, a bullet, a bullet.'"],
    quietGame: ["Quiet shift — Brazil's tournament ended in heartbreak; Martinelli wasn't enough.", "Subbed at 70 — Tite making tactical changes.", "Marked closely; couldn't find his rhythm."],
    controversy: ["The £6m bargain transfer continues to embarrass every club that scouted Brazil and missed him.", "Brazilian press wanted more from him at the World Cup — fair criticism by Brazil's standards."],
    famousGameHint: ["His Arsenal 2022-23 Premier League season — title charge that fell at the last hurdle.", "Look up his Brazil debut goal — exactly the kind of finish you sign him for."],
    opponentFlavor: {
      SUI: "Group-stage 1-0 — Martinelli came on as a sub and changed the game.",
      KOR: "Round-of-16 4-1 — Martinelli involved in the rout.",
      CRO: "Quarterfinal exit on penalties — the heartbreak that ended Brazil's tournament.",
      SRB: "Group-stage 2-0 — Martinelli's tournament debut.",
      CMR: "Group-stage loss — Brazil rotated, Martinelli started, the team lost.",
    },
    formerTeam: ["Ituano in São Paulo state — formative years.", "Arsenal from 2019 — Premier League mainstay."],
    teamContext: ["Brazil's 2022 squad had Vinícius and Raphinha as first-choice wingers — Martinelli was the depth that became a starter.", "Tite's tactical setup put him on the left when Vinícius was struggling."],
    milestones: ["Arsenal Player of the Season nominations multiple times.", "Premier League goal-scorer at 18.", "Brazil international from 2022."],
    salaryNarrative: ["At $54 ORANGE he's a winger card — avgFP 30 reflects volume and chance creation.", "ORANGE because the upside is high — and Arsenal-form Martinelli is one of the best in the world."],
  },

  // Hassan Al-Tambakti — Saudi Arabia DEF $44 PURPLE — avgFP 30.1
  "al-tambakti": {
    nicknames: ["Tambakti", "Hassan"],
    knownFor: "Saudi Arabia's young centre-back — the Al-Shabab defender who held against Argentina.",
    salaryTier: "role",
    tier1: ["The kind of young centre-back who announces himself on the biggest stage.", "Saudi Arabia's defensive future — at 23, he was holding against Messi.", "When Tambakti's right, the back four sings."],
    tier2: ["Came up through Al-Shabab in Saudi Arabia — Pro League formative years.", "Broke into the Saudi national team in 2021 — fast tracked through World Cup qualifying.", "The kind of defender every club in the Gulf wants but Al-Shabab has held onto."],
    tier3: ["Listed at 6'1\" — built for modern centre-back demands.", "His Argentina performance in the 2-1 upset was the highlight of his international career so far."],
    overperform: ["When Tambakti locks down the box, the goal is closed.", "Held Messi scoreless for 50 minutes — that's a story to tell.", "Saudi Arabia's defensive future, in full song."],
    underperform: ["Even young centre-backs have nights when the marker beats them.", "Caught flat-footed — the price of inexperience.", "Frustrated tonight; the box paid for it."],
    onPace: ["Standard Hassan — two tackles, three clearances, 90 minutes of work.", "Did the work expected; Saudi Arabia's back four held because of it.", "The reliable shift."],
    loosePlay: ["Yellow card for a tactical foul — happens when you're young.", "Caught playing out from the back — heavy touch.", "Lost his man on a corner; recovery tackle followed."],
    defensive: ["Tackles cleanly.", "Wins aerial duels above his height.", "Read the cross before it left the boot."],
    bigGame: ["TAMBAKTI! Saudi Arabia's wall, Argentina's nightmare, the box is closed.", "This is the kind of centre-back performance that earns a European transfer.", "The young defender, in full song."],
    quietGame: ["Quiet shift — Saudi Arabia's tournament went home early.", "Subbed at 80; tactical change.", "Marked closely; couldn't impose himself."],
    controversy: ["Saudi Arabia's coaching cycle has been unstable — Tambakti has played for multiple managers in a short time.", "Al-Shabab versus Al-Hilal/Al-Nassr transfer drama is a domestic storyline."],
    famousGameHint: ["The 2-1 win over Argentina in the group stage — Saudi Arabia's biggest World Cup result, and Tambakti was central to the back four."],
    opponentFlavor: {
      ARG: "The Argentina upset — Saudi Arabia's biggest World Cup result, Tambakti held the back four together for 50 minutes.",
      POL: "Group-stage 0-2 loss — Tambakti's back four couldn't stop Lewandowski.",
      MEX: "Final group game — Saudi Arabia went home, and the defense conceded twice.",
    },
    formerTeam: ["Al-Shabab in Saudi Arabia — Pro League mainstay."],
    teamContext: ["Saudi Arabia's 2022 squad needed a young centre-back to play alongside the elder statesmen — Tambakti delivered.", "Hervé Renard's tactical setup demanded centre-backs who could press; Tambakti could."],
    salaryNarrative: ["At $44 PURPLE he's a flier pick — avgFP 30 from limited Saudi Arabia minutes is solid value.", "PURPLE because the upside is real if Saudi Arabia advances; the floor is decent."],
  },

  // Heung-Min Son — South Korea FWD $51 PURPLE — avgFP 28.7
  son: {
    nicknames: ["Sonny", "Son"],
    knownFor: "South Korea's captain and Tottenham's golden boy — Asia's greatest modern footballer.",
    salaryTier: "star",
    tier1: ["The most decorated Asian footballer in history — and at 30, still climbing.", "Tottenham's golden boy, Korea's captain, Asia's torchbearer.", "If Son has the ball at his feet 25 yards out, the keeper is already moving."],
    tier2: ["Came up through Hamburg's youth system after his father moved the family to Germany.", "Bayer Leverkusen and then Tottenham at 23 — the move that made him a global star.", "Premier League Golden Boot in 2021-22 — first Asian player ever to win it."],
    tier3: ["Played the 2022 World Cup with a protective face mask after a fractured eye socket weeks before the tournament.", "His father runs a famous football academy in Korea — he's been talked about as a coach in waiting since his teens."],
    overperform: ["When Son's left foot is loaded, the goal is already half-scored.", "Korea's captain has decided this match is his.", "The version Tottenham fans worship — and Korea reaps the benefit."],
    underperform: ["Even Sonny has nights when the marker stays close.", "Frustrated tonight; the runs didn't pay off.", "The eye socket fracture clearly didn't help — playing in a mask isn't easy."],
    onPace: ["Standard Sonny — three shots, two near-misses, 90 minutes of pressing.", "Did the work; Korea's attack ran through him.", "The captain's reliable shift."],
    loosePlay: ["Heavy touch under pressure — rare from him.", "Caught offside on a run he'd gambled on.", "Yellow card for dissent — frustration from the captain."],
    defensive: ["Tracks back like a Tottenham-disciplined winger.", "Pressed the centre-back into a hurried clearance.", "Won a tackle in his own third — Premier League work-rate."],
    bigGame: ["SON! Korea's captain, Asia's pride, the goal is coming.", "This is the version that won the Premier League Golden Boot.", "Hudson would call him 'magisterial' — and tonight he is."],
    quietGame: ["Quiet game — the eye-socket mask makes everything harder.", "Subbed at 75; the captain had given everything.", "Marked tightly; Korea's attack went elsewhere."],
    controversy: ["Played the 2022 World Cup in a protective face mask — a story that captured global attention.", "Korea's military service requirement — Son was exempted via the 2018 Asian Games gold medal.", "Tottenham's chronic underachievement in his prime years has been a Premier League storyline."],
    famousGameHint: ["South Korea's 2-1 win over Portugal in the group stage — Son's late assist sent Korea through.", "Look up his Premier League Golden Boot 2021-22 — 23 goals tied with Salah.", "The 2018 Asian Games — Son won military exemption via gold medal."],
    opponentFlavor: {
      POR: "The 2-1 group-stage win that sent Korea through — Son's stoppage-time assist won the match.",
      URU: "Group-stage 0-0 — frustrating opener for the captain.",
      GHA: "Group-stage 2-3 loss — Son scored but it wasn't enough.",
      BRA: "Round-of-16 4-1 thrashing — Korea outclassed and Son couldn't change it.",
    },
    formerTeam: ["Hamburg youth — Bundesliga formative years.", "Bayer Leverkusen from 2013.", "Tottenham from 2015 — Premier League mainstay."],
    teamContext: ["South Korea's 2022 squad was built around Son — when he played, Korea attacked.", "Paulo Bento's tactical setup gave him the freedom to roam, and he delivered against Portugal."],
    milestones: ["Premier League Golden Boot (2021-22) — first Asian winner.", "Korea's captain.", "Champions League final 2019 with Tottenham."],
    rivalry: ["Korea-Japan is the deepest rivalry in Asian football.", "Son-Kane was the most prolific Premier League partnership of the 2010s."],
    salaryNarrative: ["At $51 PURPLE he's the captain pick — avgFP 29 reflects the eye-socket fracture and Korean tournament length.", "PURPLE because Korea went home in the round of 16; in any other tournament he's ORANGE."],
  },

  // Edouard Mendy — Senegal GK $48 PURPLE — avgFP 28.0
  mendy: {
    nicknames: ["Eddy", "Mendy"],
    knownFor: "Chelsea's Champions League-winning keeper — Senegal's wall in the post-Bono era.",
    salaryTier: "star",
    tier1: ["The keeper who went from unemployed to Champions League winner in three years.", "Senegal's wall — Africa Cup of Nations winner and World Cup starter.", "Chelsea's £22m signing that delivered a Champions League trophy in his first season."],
    tier2: ["Was unemployed at 23 — couldn't get a club, almost gave up the sport.", "Reims and Rennes in Ligue 1 — slow burn breakthrough.", "Chelsea from 2020 — Champions League winner in his first season."],
    tier3: ["Born in France to Senegalese parents — chose Senegal at the international level.", "Won the 2022 Africa Cup of Nations with Senegal — the country's first AFCON title."],
    overperform: ["When Mendy is hot, the goal disappears.", "Senegal's wall — and tonight it's standing tall.", "This is the version that won Chelsea a Champions League."],
    underperform: ["Even Mendy has nights when the ball finds the corner.", "Conceded twice — the kind of game every keeper has occasionally.", "The defense had a rough one, and so did he."],
    onPace: ["Standard Mendy — three saves, calm distribution, 90 minutes of composure.", "Did the work; Senegal's back four held because of it.", "The reliable keeper shift."],
    loosePlay: ["Caught off his line — even the cool ones get the angle wrong.", "Punched when he should have caught.", "A long ball that didn't quite go where he intended."],
    defensive: ["Commands his box.", "Two-handed catch in traffic.", "Read the cross and snuffed it before the striker could meet it."],
    bigGame: ["MENDY! Senegal's wall, the goal is closed.", "This is the kind of keeper performance that wins continents over.", "The Champions League winner, in full song."],
    quietGame: ["Quiet day — the back four did their job.", "Two saves and a clean sheet — low-event but high-value.", "Comfortable. Composed. Asked little, delivered everything."],
    controversy: ["Chelsea's keeper rotation in 2022-23 was a Premier League storyline — Mendy lost his starting spot to Kepa.", "Al-Ahli move in 2023 raised eyebrows but the cheque was extraordinary."],
    famousGameHint: ["His Chelsea Champions League final 2021 — clean sheet against Manchester City.", "Look up Senegal's Africa Cup of Nations win in 2022 — Mendy's saves carried the team."],
    opponentFlavor: {
      NED: "Group-stage 0-2 loss — Mendy's defense couldn't stop the Dutch.",
      QAT: "Group-stage 3-1 win — Mendy's clean sheet performance.",
      ECU: "Group-stage 2-1 win — Mendy's late saves sealed the result.",
      ENG: "Round-of-16 0-3 loss — England outclassed Senegal.",
    },
    formerTeam: ["Reims and Rennes in Ligue 1 — slow burn breakthrough.", "Chelsea from 2020 — Champions League winner.", "Al-Ahli in Saudi Arabia from 2023."],
    teamContext: ["Senegal's 2022 squad missed Sadio Mané through injury — Mendy was the leadership voice in his absence.", "Aliou Cissé's tactical setup demanded a keeper who could play out from the back; Mendy delivered."],
    milestones: ["Champions League winner (2021).", "Africa Cup of Nations winner (2022).", "FIFA Best Goalkeeper (2021)."],
    salaryNarrative: ["At $48 PURPLE he's the keeper card — avgFP 28 reflects clean sheets when Senegal had them.", "PURPLE because Senegal went home in the round of 16; in a longer run he's ORANGE."],
  },

  // Aleksandar Mitrović — Serbia FWD $47 PURPLE — avgFP 26.2
  mitrović: {
    nicknames: ["Mitro", "Mitrović"],
    knownFor: "Serbia's all-time top scorer — Fulham's Premier League hero and Saudi Pro League's biggest signing.",
    salaryTier: "star",
    tier1: ["The kind of striker who scores in every league he plays in.", "Serbia's all-time top scorer — and at 28, still the focal point.", "Fulham's hero, Saudi Arabia's payday, Serbia's number 9."],
    tier2: ["Came up through Partizan Belgrade — Serbian Pro League formative years.", "Anderlecht and Newcastle in his early career — Premier League breakthrough at Fulham.", "Al-Hilal in Saudi Arabia from 2023 — the cheque that made headlines."],
    tier3: ["Won the EFL Championship Golden Boot in 2021-22 with 43 goals — record-breaking season.", "Listed at 6'2\" — built like a target man, plays like a complete striker."],
    overperform: ["When Mitrović is in form, the goal is going to come.", "Serbia's number 9, in full song.", "This is the version that scored 43 Championship goals in a season."],
    underperform: ["Even Mitro has nights when the marker stays close.", "Frustrated tonight; the chances came and went.", "Couldn't find his shot; Serbia paid for it."],
    onPace: ["Standard Mitro — three shots, one chance taken cleanly.", "Did the work; Serbia's attack ran through him.", "The reliable striker shift."],
    loosePlay: ["Yellow card for a late tackle — happens when you press hard.", "Heavy touch under pressure.", "Tried a flick that was a flick too far."],
    defensive: ["Tracks back when asked — the kind of striker who pressed before pressing was cool.", "Won an aerial duel that started a counter.", "Pressed the keeper into a hurried clearance."],
    bigGame: ["MITROVIĆ! Serbia's number 9, the goal is here.", "This is the kind of striker performance that earns a Saudi Pro League payday.", "The target man, in full song."],
    quietGame: ["Quiet game — Serbia's tournament didn't go as hoped.", "Subbed at 75; tactical change.", "Marked closely; the goal didn't come."],
    controversy: ["Saudi Pro League move in 2023 was a Premier League storyline — Fulham fans saw it as betrayal.", "On-pitch temperament has been a Premier League discussion point — multiple bookings, pushed a referee in 2023."],
    famousGameHint: ["His 2021-22 Championship season at Fulham — 43 goals, league record.", "Look up Serbia's group-stage 3-3 draw with Cameroon — Mitrović was central to the chaos."],
    opponentFlavor: {
      BRA: "Group-stage 0-2 loss — Serbia's opener, Mitrović couldn't crack the Brazilian defense.",
      CMR: "Group-stage 3-3 — Mitrović scored in the chaos.",
      SUI: "Group-stage 2-3 loss — Serbia went home, Mitrović scored but it wasn't enough.",
    },
    formerTeam: ["Partizan Belgrade youth.", "Anderlecht — Belgian breakthrough.", "Newcastle — Premier League formative years.", "Fulham from 2018 — promoted multiple times.", "Al-Hilal from 2023 — Saudi Pro League."],
    teamContext: ["Serbia's 2022 squad was built around him — when he scored, Serbia had a chance.", "Stojković's tactical setup demanded a target man; Mitrović was the answer."],
    milestones: ["Serbia's all-time top scorer.", "EFL Championship Golden Boot (2021-22) with 43 goals.", "Three-time Championship promotion winner with Fulham."],
    rivalry: ["Serbia-Croatia is the deepest rivalry in his region.", "Serbia-Albania has always been politically charged."],
    salaryNarrative: ["At $47 PURPLE he's the striker card — avgFP 26 reflects Serbia's group-stage exit.", "PURPLE because Serbia went home early; in a longer run he's ORANGE."],
  },

  // Keylor Navas — Costa Rica GK $40 PURPLE — avgFP 23.0
  navas: {
    nicknames: ["Keylor", "Navas"],
    knownFor: "Costa Rica's legendary keeper — Real Madrid's three-time Champions League winner.",
    salaryTier: "star",
    tier1: ["The keeper who won three straight Champions Leagues — and a fourth at PSG.", "Costa Rica's national hero — a small country's biggest footballer.", "If you watch one keeper to understand goalkeeping, watch Navas in 2014."],
    tier2: ["Came up through Saprissa in Costa Rica — Liga FPD formative years.", "Levante and Real Madrid in La Liga — the move that made him.", "PSG from 2019 — kept Donnarumma on the bench at times."],
    tier3: ["His 2014 World Cup performance vs Greece carried Costa Rica to the quarterfinals on penalties.", "Listed at 6'1\" — not the tallest keeper but the most decorated of his Costa Rican generation."],
    overperform: ["When Navas is hot, the goal disappears.", "Costa Rica's wall — and tonight it's standing tall.", "This is the version that won three Champions Leagues."],
    underperform: ["Even Keylor has nights when the ball finds the corner.", "Conceded multiple — the kind of game every keeper has at 36.", "The defense had a rough one, and so did he."],
    onPace: ["Standard Keylor — three saves, calm distribution, 90 minutes of composure.", "Did the work; Costa Rica's back four held because of it.", "The reliable keeper shift."],
    loosePlay: ["Caught off his line — even the cool ones get the angle wrong.", "Punched when he should have caught.", "A long ball that didn't quite go where he intended."],
    defensive: ["Commands his box.", "Two-handed catch in traffic.", "Read the cross and snuffed it before the striker could meet it."],
    bigGame: ["NAVAS! Costa Rica's hero, the goal is closed.", "This is the kind of keeper performance that wins Champions Leagues.", "Three trophies, three different defenders, one keeper. Tonight, vintage."],
    quietGame: ["Quiet day — the back four did their job.", "Two saves and a clean sheet — low-event but high-value.", "Comfortable. Composed. Asked little, delivered everything."],
    controversy: ["PSG's keeper rotation with Donnarumma in 2021-22 was a Ligue 1 storyline — Navas was the elder statesman pushed aside.", "Real Madrid's decision to sign Courtois and push him out was a divisive moment in the Madrid dressing room."],
    famousGameHint: ["The 2014 World Cup — Costa Rica's quarterfinal run, Navas saved the penalty against Greece.", "Look up his Real Madrid Champions League final performances — three winners' medals back to back.", "The 2022 group-stage 1-0 win over Japan — Navas was the keeper who held it."],
    opponentFlavor: {
      ESP: "Group-stage 0-7 loss — Spain ran riot, Navas couldn't have done much.",
      JPN: "Group-stage 1-0 win — Navas held it down, Costa Rica's only result.",
      GER: "Group-stage 2-4 loss — Costa Rica went home, but Navas still made saves.",
    },
    formerTeam: ["Saprissa in Costa Rica — formative years.", "Levante in La Liga — breakthrough.", "Real Madrid — three Champions Leagues.", "PSG from 2019."],
    teamContext: ["Costa Rica's 2022 squad was built around him — the spine of the team for a decade-plus.", "Suárez's tactical setup put him in the most important position; Navas delivered against Japan."],
    milestones: ["Three-time Champions League winner with Real Madrid.", "Costa Rica's most-capped keeper.", "2014 World Cup quarterfinalist."],
    salaryNarrative: ["At $40 PURPLE he's the elder statesman keeper — avgFP 23 reflects Costa Rica's group-stage exit.", "PURPLE because his floor is high but Costa Rica's results capped his ceiling."],
  },

