#!/usr/bin/env bash
# Generates docs/football-review-code-dump.md by concatenating the key football
# source files inline so ChatGPT can review without cloning the repo.
#
# Usage (from repo root):
#   bash docs/football-review-dump.sh
#
# Output: docs/football-review-code-dump.md

set -euo pipefail

OUT="docs/football-review-code-dump.md"

# File list with descriptions (description|path)
FILES=(
  "Sport config (tier ladder, FP weights per position, badges, economy)|football/src/adapters/footballConfig.ts"
  "Game adapter (within-position salary normalization — the parity foundation; lines 109-111 are the key comment)|football/src/adapters/gameAdapter.ts"
  "Sport adapter (extends shared base; small file)|football/src/adapters/SportAdapter.ts"
  "FTUE config + roster stubs|football/src/adapters/ftueRoster.ts"
  "GameView shim (158 lines, wraps shared GameView)|football/src/views/GameView.tsx"
  "App shell (auth + query params + sticky skip-landing)|football/src/App.tsx"
  "SoccerCard (FootballHero = flag + initials, BackStats with FP attribution)|football/src/components/SoccerCard.tsx"
  "Landing page shim (5 demo cards: Messi, Mbappé, Vinícius Jr., Bellingham, Saka)|football/src/components/LandingPage.tsx"
  "Edge-case unit tests (10 cases, all passing)|shared/__tests__/footballEdgeCases.test.ts"
  "Per-competition bonus pool API|api/bonus-pool.ts"
  "Shared GameAdapter contract (basketball/baseball/football all populate this)|shared/views/GameAdapter.ts"
  "Shared bonus pool store (now competition-aware)|shared/utils/bonusPoolStore.ts"
  "Shared RosterGrid (now renders optional slotLabels for FLEX-style rules)|shared/components/RosterGrid.tsx"
)

{
  printf '# Football SPA — code dump for review\n\n'
  printf 'Companion to `docs/football-review-brief.md`. Contains the actual source for the key football files inline so ChatGPT can review without needing to clone the repo. Read the brief first for context.\n\n'
  printf 'Generated by `docs/football-review-dump.sh` on %s.\n\n' "$(date -u +%Y-%m-%dT%H:%MZ)"
  printf 'Files are ordered roughly: config → adapters → views → components → tests → API → shared infrastructure changes.\n'

  for entry in "${FILES[@]}"; do
    desc="${entry%%|*}"
    path="${entry##*|}"
    if [[ ! -f "$path" ]]; then
      printf '\n---\n\n## `%s`\n\n*(File not found — skipped)*\n' "$path"
      continue
    fi
    case "$path" in
      *.ts|*.tsx) lang=typescript ;;
      *.js)       lang=javascript ;;
      *.html)     lang=html ;;
      *)          lang= ;;
    esac
    printf '\n---\n\n## `%s`\n\n*%s*\n\n' "$path" "$desc"
    printf '```%s\n' "$lang"
    cat "$path"
    printf '```\n'
  done
} > "$OUT"

LINES=$(wc -l < "$OUT")
printf 'Wrote %s (%s lines)\n' "$OUT" "$LINES"
