  // Gonçalo Ramos — Portugal FWD $60 ORANGE — avgFP 50.2
  ramos: {
    nicknames: ["Gonçalo", "GR9"],
    knownFor: "The Benfica striker who replaced Cristiano Ronaldo and scored a World Cup hat-trick.",
    salaryTier: "max",
    tier1: ["When the manager benched Cristiano, this is the kid who repaid him.", "A hat-trick in his first World Cup start. Read that sentence again.", "Portugal's number 9 future arrived on a Tuesday in December."],
    tier2: ["Came through Benfica's academy — the same factory line that produced João Félix and Bernardo Silva.", "Was an unknown to most of the world the morning of the Switzerland round-of-16.", "Walked off that night with a match ball and a country reorganized around him."],
    tier3: ["Born in Olhão on the Algarve coast — a long way from Lisbon's lights.", "Scored his first Benfica goal off the bench in his debut season."],
    overperform: ["When Ramos finishes like this, you forget who he replaced.", "Three goals on debut at a World Cup — the kind of fairy-tale that doesn't happen.", "The kid is announcing himself, and the whole world is listening."],
    underperform: ["The hat-trick night was the high; tonight was the reminder he's still 21.", "Marked tightly — the chances didn't come and he didn't force them.", "Quiet shift — the spotlight that came with the Switzerland game has weight."],
    onPace: ["Standard centre-forward shift — held the ball up, spun the channel, made the runs.", "Got his half-chance, didn't bury it, kept the line stretched.", "Did the hard work for the wider players to find the goal."],
    loosePlay: ["Heavy first touch under pressure — the moment that was supposed to be the chance.", "Flicked it into a defender's path — youth showing.", "Caught offside chasing a ball that wasn't on."],
    defensive: ["Pressed the centerbacks like a Benfica winger — that's the modern 9.", "Tracked the deep midfielder when the trigger came.", "Won a free kick by holding off two defenders in the corner."],
    bigGame: ["GONÇALO RAMOS! GONÇALO RAMOS! He doesn't replace Cristiano — he answers him.", "A HAT-TRICK. ON DEBUT. AT A WORLD CUP. The script writes itself.", "This is what happens when a kid stops waiting for permission."],
    quietGame: ["Followed up the Switzerland hat-trick with a more measured night — that's normal.", "Subbed at 70' — the manager protecting the asset.", "Quiet 90 — the goal will come. It always does for him now."],
    controversy: ["The Cristiano benching that gave him the start was the story of the tournament for Portugal.", "Some Portuguese media still wanted Cristiano back in the XI even after the hat-trick — football fandom never settles."],
    famousGameHint: ["Look up Portugal vs Switzerland in the 2022 round of 16 — three goals, one assist, a star born.", "His Benfica goals in the 2022/23 Champions League run hinted at what was coming.", "The Morocco quarterfinal — couldn't crack Bono, but the threat shaped the game."],
    opponentFlavor: {
      SUI: "The hat-trick — three goals, one assist, the entire Cristiano-replacement debate settled in 90 minutes.",
      MAR: "Quarterfinal exit — couldn't beat Bono, but the future of Portugal's attack was on the pitch.",
      KOR: "Group-stage cameo — the audition before the headline.",
    },
    formerTeam: ["Benfica academy product — the Lisbon factory line.", "PSG bought him in 2023 to be Mbappé's strike partner."],
    rivalry: ["Spain-Portugal is in his blood — every Iberian striker grows up dreaming of that fixture."],
    milestones: ["Hat-trick in his first World Cup start — youngest Portuguese player to do it.", "First Portuguese hat-trick at a World Cup since Eusébio in 1966."],
    streakLines: ["The Switzerland night was the spike — but his Benfica form predicted it.", "Goals come in flurries for him — three in a night, then quiet for two."],
    salaryNarrative: ["At $60 ORANGE he's priced for the Switzerland version — the hat-trick's the ceiling, the bench was the floor.", "ORANGE because the explosion is real — but the floor is wobblier than Mbappé's."],
    teamContext: ["The succession plan — Portugal's centre-forward future, with Cristiano transitioning out.", "Slotted into a front three with Bruno Fernandes and Bernardo Silva creating around him."],
    draftAndPath: ["Joined Benfica's youth setup at 11 — climbed every age group.", "First-team debut at 19 in the Primeira Liga.", "PSG paid €65m+ in 2023 to make him the next Ligue 1 9."],
    signatureGames: [
      { date: "2022-12-06", opponent: "SUI", fp: 110, line: "The hat-trick that replaced Cristiano — three goals, one assist, a star born in 90 minutes." },
      { date: "2022-12-10", opponent: "MAR", fp: 35, line: "Quarterfinal exit — Bono won the matchup, but the future of Portugal's attack played that night." },
    ],
  },

  // Thilo Kehrer — Germany DEF $60 ORANGE — avgFP 43.4
  kehrer: {
    nicknames: ["Thilo", "TK15"],
    knownFor: "Germany's versatile defender — fullback, centerback, whatever the manager needs.",
    salaryTier: "star",
    tier1: ["The kind of defender every manager wants — no headlines, no errors, just shifts.", "Plays three positions to a Bundesliga standard — versatility is its own talent.", "If you watch Kehrer for 90 minutes, you'll forget he's there. That's the point."],
    tier2: ["Schalke academy product — the same pipeline that produced Mesut Özil and Manuel Neuer.", "PSG bought him at 21 because his ceiling looked higher than his floor — both proved true.", "West Ham gave him Premier League minutes and a reset after Paris."],
    tier3: ["Born in Tübingen — a university town, not a football town.", "Spent four years at PSG without ever quite locking down a starting spot."],
    overperform: ["When Kehrer is on, Germany's right side disappears as a problem.", "Made three tackles, completed every pass, didn't look hurried — that's a 90 you sign up for.", "The full back you didn't notice, which means he was excellent."],
    underperform: ["A wobble at the back — credit the attacker, but Kehrer will rewatch the tape.", "Caught out of position once — the one-second lapse that becomes the highlight.", "Marked man got past him for the chance — the only blemish on a clean shift."],
    onPace: ["Standard Kehrer night — quiet, steady, position-correct.", "Did the boring things excellently and the hard things adequately.", "Reliable. Composed. The bedrock kind of fullback."],
    loosePlay: ["A rare giveaway in his own third — nervous moment, recovered.", "Booked for a tactical foul — the kind a smart defender takes.", "Underhit a clearance — the kind of detail that bothers him postgame."],
    defensive: ["Three tackles, two interceptions, a clean sheet — boxes ticked.", "Read the cross before it was hit — that's the experience.", "Tracked the runner all the way to the byline — discipline."],
    bigGame: ["THILO KEHRER, THE QUIET GERMAN — and tonight, the loud one.", "A goal from a fullback in a World Cup — ride that wave.", "He is everywhere. He is everything. He is the back four made flesh."],
    quietGame: ["Marked off the touchline — Germany's fullback was the safe option.", "Subbed at 75' — kept the legs for the next round.", "Quiet 90 — exactly what Germany asked of him."],
    controversy: ["Hansi Flick's rotation policy never quite settled on him as a starter — frustration showed in pressers.", "PSG fans never warmed to him; West Ham fans did, eventually."],
    famousGameHint: ["Look up Germany vs Costa Rica in 2022 — Kehrer scored, Germany won 4-2, and they still went home.", "His Bundesliga form at Schalke earned him the PSG move at 21.", "The Spain group-stage draw — Germany's defensive shape held up against the eventual finalist."],
    opponentFlavor: {
      JPN: "Group-stage opener — Germany lost 2-1, the back line was breached, the tournament wobbled from minute 75.",
      ESP: "1-1 draw against the eventual finalist — defensive shape held up, his shift was professional.",
      CRC: "Goal-scorer in a 4-2 win that wasn't enough — Germany went home on goal difference.",
    },
    formerTeam: ["Schalke academy → PSG (€37m, 2018) → West Ham (€12m, 2022) — the journeyman elite path.", "Monaco loan in 2024 — chasing minutes."],
    rivalry: ["Germany-Netherlands is the rivalry — every German defender grows up watching it on tape."],
    milestones: ["German international with 30+ caps.", "Bundesliga and Ligue 1 silverware at club level."],
    streakLines: ["Kehrer's good runs come in chunks — six clean shifts then one wobble.", "Versatile enough to start on either flank or in the middle — a streak by selection."],
    salaryNarrative: ["At $60 ORANGE he's priced as Germany's premium back — high floor, modest ceiling.", "ORANGE because Germany's defensive output is the reason — clean sheets carry his card."],
    teamContext: ["Hansi Flick's defensive Swiss army knife — could play wherever the gaps appeared.", "Germany's back line in 2022 was Rüdiger and Süle plus whoever Flick trusted at fullback. Kehrer made the cut."],
    draftAndPath: ["Schalke academy from age 9 — climbed through every youth team.", "PSG paid €37m for him at 21 — a vote of confidence that didn't fully cash in.", "West Ham gave him a Premier League platform; Monaco gave him minutes."],
  },

  // Juan Pablo Vargas — Costa Rica MID $57 ORANGE — avgFP 41.8
  vargas: {
    nicknames: ["Juan Pablo", "JPV"],
    knownFor: "Costa Rica's centre-back-turned-midfielder anchor — Millonarios' Colombian-league export.",
    salaryTier: "star",
    tier1: ["Costa Rica's defensive backbone — when he plays, the back line breathes.", "The kind of player every CONCACAF side needs — calm, positionally sharp, two-footed.", "If you watch Costa Rica's shape, watch Vargas. He's the reason it holds."],
    tier2: ["Made his name at Millonarios in Colombia's top flight — earned his international call-up the long way.", "Costa Rica's 2022 squad was built on veterans plus him — the bridge generation.", "Scored against Japan in the group stage — a centre-back goal at a World Cup is its own milestone."],
    tier3: ["Born in San José — Costa Rica's capital and football heartland.", "Spent his peak years in Colombia rather than chasing Europe — the road less travelled."],
    overperform: ["When Vargas is sharp, Costa Rica look like a tournament team.", "Two tackles, a goal, a clean sheet — that's a centre-back's perfect night.", "Tournament hero hands — punched above his weight all match."],
    underperform: ["Beaten by the through ball — even the calm ones get caught once.", "Costa Rica's whole back line had a rough one and Vargas couldn't paper over it.", "The defender was second to the cross — the goal came from his side."],
    onPace: ["Standard Vargas — heads everything, blocks the rest, distributes the ball cleanly.", "Quiet defensive shift — the kind that wins the pre-game scouting prep.", "Got his clearances, his interceptions, his positional discipline — full shift."],
    loosePlay: ["Caught in possession on the build-up — the rare loose touch.", "A clearance that found the opposition striker — the bad bounce.", "Booked for a desperate tackle — the kind of foul a tired defender takes."],
    defensive: ["Wins headers, tracks runners, organizes the line — the complete CB shift.", "Reads the diagonal ball before it's struck — experience showing.", "Made the tackle that saved a goal — back-line MOTM material."],
    bigGame: ["JUAN PABLO VARGAS! A goal from the centre-back — Costa Rica are in this one!", "He is the wall and the architect — Costa Rica are organized around him.", "This is what tournament veterans do — show up when the moment finds them."],
    quietGame: ["Quiet defensive 90 — exactly what you'd want.", "Costa Rica conceded; he wasn't the cause but he was on the pitch.", "Marked his man, lost his man, watched the goal go in — happens."],
    controversy: ["Played his peak years in Colombia rather than chasing Europe — some Costa Rican media wanted more ambition.", "Federation pay disputes have shadowed Costa Rica's program for years — every senior player has weighed in."],
    famousGameHint: ["Look up Costa Rica vs Japan in 2022 — Vargas scored, Costa Rica upset Japan 1-0.", "The Spain 7-0 humiliation in the group stage opener — every Costa Rican defender remembers that day.", "His Millonarios cup runs in Colombia's Liga BetPlay."],
    opponentFlavor: {
      ESP: "The 7-0 opener — every Costa Rican defender remembers that day. Vargas included.",
      JPN: "The goal — Costa Rica beat Japan 1-0 and Vargas wrote his name in CONCACAF history.",
      GER: "4-2 loss but not without dignity — the back line scrapped against a Bundesliga front line.",
    },
    formerTeam: ["Millonarios (Colombia) made him — Liga BetPlay's defensive standout.", "Brief Mexican-league stints. Stayed mostly in CONCACAF/CONMEBOL."],
    rivalry: ["Costa Rica-Mexico is CONCACAF's classic — every Tico defender lives for that fixture."],
    milestones: ["Costa Rica's senior team regular through the 2022 cycle.", "Colombian league silverware with Millonarios."],
    streakLines: ["Costa Rica's back-line stability when Vargas plays — direct correlation.", "Goals from a centre-back come in flurries — set-piece runs."],
    salaryNarrative: ["At $57 ORANGE he's priced for the goal upside — the Japan night spikes the average.", "Centre-back card with attacking value — that's why he sits in ORANGE."],
    teamContext: ["The defensive anchor of Luis Fernando Suárez's 2022 Costa Rica.", "Played alongside Francisco Calvo and behind Bryan Ruiz's veteran spine."],
    draftAndPath: ["Costa Rican youth football → Millonarios in Colombia → senior international.", "Skipped the European route most CONCACAF prospects chase — built his career in South America instead."],
  },

  // Enner Valencia — Ecuador FWD $60 ORANGE — avgFP 39.5
  valencia: {
    nicknames: ["Enner", "EV13"],
    knownFor: "Ecuador's all-time top scorer — every World Cup goal La Tri have scored, he's been involved in.",
    salaryTier: "max",
    tier1: ["Every Ecuador World Cup goal since 2014 has Enner Valencia's fingerprints on it.", "When La Tri need a goal, they look at one man. They've always looked at one man.", "Ecuador's all-time top scorer — and the gap to second place is enormous."],
    tier2: ["Came through El Nacional in Quito — Ecuador's traditional military-club factory.", "West Ham, Everton, Tigres — a journeyman path with a tournament heart.", "Has now scored in three different World Cups — that's a club only the immortals join."],
    tier3: ["Born in Esmeraldas on the Pacific coast — Afro-Ecuadorian football's heartland.", "Plays for Internacional in Brazil at club level — earning his keep in Brasileirão."],
    overperform: ["When Enner is hot, Ecuador are dangerous to anyone.", "A brace and a knee injury and he kept playing — that's the captain's badge.", "This is the version that scared Qatar in the opener and Senegal in the group decider."],
    underperform: ["The knee injury from the opener kept following him — the legs weren't fully there.", "Marked tightly by a Premier League back line — credit them.", "Quiet shift — Ecuador's chances dried up around him."],
    onPace: ["Standard Enner — held up the ball, won fouls, made the runs nobody else made.", "Got his half-chance, hit the target, kept La Tri ticking.", "The captain shift — vocal, organized, productive enough."],
    loosePlay: ["Heavy first touch in the box — the chance that became a corner.", "Tried a flick that was a flick too many.", "Booked for dissent — frustration with the ref boiling over."],
    defensive: ["Tracked back to defend corners — the captain's lead.", "Pressed the centerbacks when the trigger came.", "Won the long ball under pressure — old-fashioned 9 work."],
    bigGame: ["ENNER VALENCIA! ENNER VALENCIA! Ecuador's heartbeat strikes again!", "He has scored in every World Cup he's played in. That is not a coincidence.", "The captain. The icon. La Tri's all-time everything."],
    quietGame: ["Quiet 90 — the Premier League back line did its homework.", "Subbed at 75' — the knee, the legs, the long tournament.", "Couldn't find the chance — happens, even to him."],
    controversy: ["Skipped a child-support court date in Mexico years back — Mexican media never let it go.", "FIFA's age-fudging investigation around Ecuador's 2022 squad shadowed the whole tournament — Valencia wasn't named but the cloud hung over Quito."],
    famousGameHint: ["Look up Ecuador vs Qatar in the 2022 opener — Valencia scored both goals in a 2-0 win.", "His 2014 World Cup brace against Honduras — same player, same fingerprint, eight years apart.", "The Senegal group decider — Valencia equalized, Ecuador needed one more, didn't get it."],
    opponentFlavor: {
      QAT: "The 2-0 opener — Valencia scored both, including a header that won't be forgotten in Quito.",
      NED: "1-1 draw — Valencia's equalizer kept Ecuador alive in the group.",
      SEN: "1-2 loss in the decider — Valencia equalized but Ecuador couldn't find a second.",
    },
    formerTeam: ["El Nacional → Pachuca → West Ham → Everton → Tigres → Fenerbahçe → Internacional. The journeyman star path.", "Tigres made him a Liga MX legend; Fenerbahçe gave him a Turkish chapter."],
    rivalry: ["Ecuador-Colombia is CONMEBOL's underrated rivalry — every La Tri striker lives for that fixture."],
    milestones: ["Ecuador's all-time top scorer.", "Goals in three different World Cups — 2014, 2022, joining a select club.", "Liga MX silverware with Tigres."],
    streakLines: ["Tournament Valencia is different — opener, group decider, knockout if it gets there.", "Goals come in pairs at World Cups — Honduras 2014, Qatar 2022, both braces."],
    salaryNarrative: ["At $60 ORANGE he's the Ecuador card — La Tri's whole offense flows through him.", "ORANGE because the tournament floor is real — three World Cups of evidence."],
    teamContext: ["The captain, the focal point, the only proven international goalscorer in the squad.", "Gustavo Alfaro built the 2022 team to feed him — the strategy worked twice."],
    draftAndPath: ["El Nacional in Quito gave him his break.", "Pachuca took him to Mexico; West Ham took him to England.", "Settled into a journeyman's prime across Mexico, Turkey, and Brazil."],
    signatureGames: [
      { date: "2022-11-20", opponent: "QAT", fp: 75, line: "The opener — both goals in a 2-0 win that started the tournament with a statement." },
      { date: "2022-11-29", opponent: "SEN", fp: 50, line: "The equalizer that wasn't enough — Ecuador went out, but Valencia did his job." },
    ],
  },

  // David Raum — Germany DEF $56 ORANGE — avgFP 38.2
  raum: {
    nicknames: ["David", "DR15"],
    knownFor: "Germany's modern marauding left back — Hoffenheim's gift to the national team.",
    salaryTier: "star",
    tier1: ["The kind of fullback who turns into a winger when Germany have the ball.", "Crosses like a winger, defends like a fullback, runs all day.", "Hansi Flick's blueprint left back — overlap, recover, repeat."],
    tier2: ["Came through Greuther Fürth — second-division beginnings.", "Hoffenheim made him a Bundesliga starter; RB Leipzig bought him for the elite tier.", "Cracked the German national team late — the modern fullback who arrived just in time."],
    tier3: ["Born in Nuremberg — Bayern country, but not a Bayern player.", "Has the kind of crossing accuracy that earns assist totals other fullbacks don't see."],
    overperform: ["When Raum overlaps, Germany have a winger and a fullback in one body.", "Three crosses, an assist, a clean sheet — fullback dream sheet.", "He's playing the position the way the modern game wants it played."],
    underperform: ["Caught upfield when the counter came — the modern fullback's tax.", "His marker beat him to the byline — credit the winger.", "Quiet attacking shift — the cross didn't connect."],
    onPace: ["Standard Raum — overlapped, recovered, distributed.", "Made his runs, stayed disciplined enough, did the dual job.", "The fullback shift you'd want every match — present at both ends."],
    loosePlay: ["Tried a cross that didn't beat the first man — the small detail.", "Booked for a recovery foul — the price of overlapping.", "Caught out of position once — the moment that becomes the highlight."],
    defensive: ["Tracked back the full sprint — that's what the position demands now.", "Won his tackle in his own third — completing the dual role.", "Cleared the cross at the back post — discipline showing."],
    bigGame: ["DAVID RAUM, OVERLAPPING, OVERLAPPING — and the cross is buried!", "An assist from a fullback at a World Cup — modern football in one image.", "The kind of shift that gets you a Bayern Munich phone call."],
    quietGame: ["Quiet 90 from a fullback is usually a clean sheet — and tonight it was.", "Marked off the overlap by the opposition winger — credit them.", "Subbed at 80' — the legs of an overlapping fullback feel 90 minutes."],
    controversy: ["Some German fans wanted Robin Gosens or Jonas Hofmann ahead of him — the rotation debate hung over Flick."],
    famousGameHint: ["Look up Germany vs Spain in the 2022 group stage — Raum's cross created the chances that kept Germany alive.", "His Bundesliga assist tallies at Hoffenheim and Leipzig — fullbacks don't usually rack those up.", "The Costa Rica game — Germany won 4-2, Raum was at the heart of the build-up."],
    opponentFlavor: {
      JPN: "Group-stage opener — Germany lost, the overlap couldn't save the back line.",
      ESP: "The 1-1 draw — Raum's crossing was Germany's main attacking outlet.",
      CRC: "4-2 win — the overlap gave Germany their attacking shape.",
    },
    formerTeam: ["Greuther Fürth → Hoffenheim → RB Leipzig — the German football ladder.", "RB Leipzig paid €26m for him in 2022 — he had earned every cent at Hoffenheim."],
    rivalry: ["Bayern Munich — every RB Leipzig player carries that fixture in their head."],
    milestones: ["Bundesliga assist leader for fullbacks in his Hoffenheim days.", "DFB-Pokal silverware with RB Leipzig."],
    streakLines: ["Assist runs come from his crossing — when the wingers move, his numbers move.", "Fitness is his thing — full-throttle for 90, every match."],
    salaryNarrative: ["At $56 ORANGE he's priced for the cross-output — fullback assist value.", "ORANGE because the upside is real — multiple-assist nights live in his locker."],
    teamContext: ["Germany's left flank in 2022 — overlapping fullback, inverted winger, the modern shape.", "Hansi Flick trusted him early; the trust didn't waver."],
    draftAndPath: ["Greuther Fürth's academy — second-division roots.", "Hoffenheim gave him Bundesliga minutes at 22.", "RB Leipzig's €26m fee in 2022 made him an elite fullback by price tag."],
  },

  // Mohammed Kudus — Ghana FWD $60 ORANGE — avgFP 37.3
  kudus: {
    nicknames: ["Kudus", "MK20"],
    knownFor: "Ghana's young attacking midfielder — Ajax's most exciting export of the 2022 cycle.",
    salaryTier: "max",
    tier1: ["When Kudus runs at a defender, the defender's options shrink to bad and worse.", "Ajax's number 20 with Premier League destiny written all over him.", "Africa's most complete attacking midfielder under 25."],
    tier2: ["Came through Right to Dream Academy in Ghana — the same pipeline that produced Mohammed Salisu.", "Ajax bought him at 19 — the Eredivisie's rite of passage for African talent.", "West Ham paid £38m for him in 2023 — the move that should have happened earlier."],
    tier3: ["Born in Accra — Ghanaian football's capital.", "Plays multiple positions — false nine, attacking midfielder, winger — equally well in all three."],
    overperform: ["When Kudus decides to take over a match, he takes over a match.", "Two goals against Korea — the announcement to the planet.", "He moves with the kind of menace that bends defensive shapes."],
    underperform: ["Marked tightly — credit the back line.", "Frustrated by a deep block — even the great ones need space.", "Quiet shift by his standards. His standards are very high."],
    onPace: ["Standard Kudus — one moment of magic, two near-misses, three defensive recoveries.", "The complete attacking midfielder shift.", "Got his goal threat, made his decisions, looked the part."],
    loosePlay: ["Tried to dribble through three — the youth showing.", "Caught in possession — the small detail.", "A flick that didn't come off — the price of being adventurous."],
    defensive: ["Tracks back like a midfielder when he wants to.", "Won a tackle in midfield — that's a complete number 10.", "Pressed the centerback into a panic clearance."],
    bigGame: ["KUDUS! KUDUS! Ghana's young magician strikes!", "MAGISTERIAL. The kid from Accra has arrived.", "This is the player West Ham eventually paid £38m to watch."],
    quietGame: ["Marked into the ground — the doubles team did its job.", "Subbed at 70' — Ghana saving him for the next round.", "Couldn't find his rhythm — even Kudus has those nights."],
    controversy: ["Ghana's 2022 squad chemistry was reportedly fraught — multiple senior leaks suggested camp tension.", "His agent's negotiations during the West Ham move dragged the saga across the entire summer of 2023."],
    famousGameHint: ["Look up Ghana vs South Korea in 2022 — Kudus scored twice and announced himself.", "His Ajax Champions League goals — particularly against Liverpool — predicted everything.", "The Uruguay grudge match — Ghana lost, the 2010 ghosts won, Kudus did his job."],
    opponentFlavor: {
      KOR: "Two goals — the brace that announced Africa's next great attacker.",
      POR: "Group-stage loss — Cristiano scored, Kudus didn't, Ghana fell.",
      URU: "The grudge match — 2010 ghosts haunted Ghana again, Kudus couldn't lift them.",
    },
    formerTeam: ["Right to Dream Academy → FC Nordsjælland → Ajax → West Ham. The modern African star path.", "Ajax built around him for two seasons before West Ham came calling."],
    rivalry: ["Ghana-Uruguay — the 2010 quarterfinal still scars every Black Star fan."],
    milestones: ["Ghana's 2022 World Cup top scorer.", "Eredivisie title with Ajax.", "Premier League goal-scorer with West Ham."],
    streakLines: ["Brace nights are part of his pattern — he's a flurry scorer.", "When Kudus is hot, Ghana are dangerous to anyone."],
    salaryNarrative: ["At $60 ORANGE he's priced for the brace upside — Korea is the ceiling.", "ORANGE because the explosion is real and the ceiling justifies the cap hit."],
    teamContext: ["Ghana's attacking lynchpin in 2022 — the team flowed through him and Jordan Ayew.", "Otto Addo's tactical pivot was 'put Kudus in the 10 and let him cook.'"],
    draftAndPath: ["Right to Dream Academy — the Ghana-to-Europe pipeline.", "FC Nordsjælland in Denmark gave him his pro debut at 18.", "Ajax bought him at 19; West Ham paid £38m for him at 23."],
    signatureGames: [
      { date: "2022-12-02", opponent: "KOR", fp: 75, line: "The brace — two goals in a 3-2 win that announced Africa's next great attacker." },
      { date: "2022-12-02", opponent: "URU", fp: 30, line: "The 2010 grudge match — Ghana lost, the ghosts won, Kudus couldn't crack it." },
    ],
  },

  // Cody Gakpo — Netherlands MID $51 PURPLE — avgFP 36.7
  gakpo: {
    nicknames: ["Cody", "CG11"],
    knownFor: "PSV's homegrown attacker who scored in three straight World Cup games and earned Liverpool's call.",
    salaryTier: "star",
    tier1: ["Three goals in three games at his first World Cup — that's a tournament announcement.", "Cuts inside from the left, finds the corner, repeats. The modern Dutch winger.", "When Gakpo strikes from outside the box, you reorganize your defense."],
    tier2: ["PSV academy product — Eindhoven's pride.", "Arsenal, Manchester United, and Liverpool all chased him. Liverpool got him.", "Walked into Anfield in January 2023 with a World Cup CV that fit the badge."],
    tier3: ["Born in Eindhoven — PSV country from day one.", "His father is Togolese; he chose the Netherlands at the youth level."],
    overperform: ["When Gakpo's striking foot is dialed in, the corner is unguardable.", "Three goals in three games — that's a Mbappé-tier tournament rhythm.", "The player Klopp called 'a complete forward' arrived at the World Cup."],
    underperform: ["Marked off the left flank — credit the fullback.", "Couldn't find the cutback shape — even the great ones have those nights.", "Quiet shift — the goal didn't come, the team didn't need it."],
    onPace: ["Standard Gakpo — cuts inside, threatens the corner, makes the runs.", "Got his shot, missed, got it again, scored. That's his rhythm.", "Looked like a Liverpool player a few weeks before he was a Liverpool player."],
    loosePlay: ["Tried a flick that was a flick too far.", "Heavy first touch in the box — the chance that became a corner.", "Caught dribbling into trouble — youth showing."],
    defensive: ["Tracks back when the trigger comes — Klopp would later make this his identity.", "Pressed the centerback into a panic clearance.", "Won his tackle wide — the dual-job winger."],
    bigGame: ["GAKPO! GAKPO! THE THIRD IN THREE GAMES — the Eindhoven boy is on fire!", "Liverpool are watching this — and they are reaching for the cheque book.", "This is what a tournament breakout looks like."],
    quietGame: ["Marked tightly — sometimes the doubles team works.", "Subbed at 70' — saving him for the next round.", "Quiet 90 — the goal will come. It always does."],
    controversy: ["The transfer saga in January 2023 was Premier League back-page material for two weeks straight.", "PSV fans took the move hard — but Liverpool was always the right destination."],
    famousGameHint: ["Look up Netherlands vs Senegal in 2022 — Gakpo scored the opener.", "His Ecuador goal — the curling effort from outside the box, vintage Gakpo.", "The Qatar group-stage closer — three games, three goals."],
    opponentFlavor: {
      SEN: "Group-stage opener — Gakpo scored the goal that started the Dutch tournament.",
      ECU: "1-1 draw — Gakpo's strike kept Netherlands rolling.",
      QAT: "Group-stage closer — third goal in three games, a tournament-defining streak.",
      ARG: "Quarterfinal exit — Argentina won on penalties, Gakpo was Netherlands' threat all night.",
    },
    formerTeam: ["PSV academy → PSV first team → Liverpool (£37m, Jan 2023).", "Eindhoven made him a star; Anfield made him a champion."],
    rivalry: ["Netherlands-Belgium is the Low Countries derby — every Dutch attacker grows up dreaming of that fixture."],
    milestones: ["Goals in three straight World Cup group games.", "Liverpool signing in January 2023 — the marquee winter window move.", "PSV silverware before age 23."],
    streakLines: ["Three goals in three group games — World Cup hot streak.", "His PSV form bled directly into the Netherlands' tournament rhythm."],
    salaryNarrative: ["At $51 PURPLE he's the value Dutch attacker — produced ORANGE-tier output.", "PURPLE on the card, ORANGE on the pitch when the streak runs."],
    teamContext: ["Louis van Gaal's left-side attacker in 2022 — the system fit him perfectly.", "Played wide left in a 3-4-3 that asked him to cut inside and finish."],
    draftAndPath: ["PSV academy from age 7 — Eindhoven boy through and through.", "First-team debut at 19 in the Eredivisie.", "Liverpool's £37m fee in January 2023 reflected the World Cup form."],
    signatureGames: [
      { date: "2022-11-21", opponent: "SEN", fp: 60, line: "The opener — Gakpo's goal started the Netherlands' tournament with momentum." },
      { date: "2022-11-25", opponent: "ECU", fp: 50, line: "Strike two of three — the streak begins to look real." },
      { date: "2022-11-29", opponent: "QAT", fp: 55, line: "Three goals in three games — the breakout becomes the headline." },
    ],
  },

  // Luuk de Jong — Netherlands DEF $53 ORANGE — avgFP 36.1 (note: actually a striker)
  jong: {
    nicknames: ["Luuk", "LdJ"],
    knownFor: "Netherlands' veteran target man — Sevilla's Europa League winner, PSV's old reliable.",
    salaryTier: "star",
    tier1: ["The kind of striker every team needs in the 88th minute when the chips are down.", "Plays the old-fashioned 9 — heads everything, holds up the ball, finishes the cutback.", "Sevilla's Europa League hero in 2020 — the kind of moment that lasts."],
    tier2: ["Came through De Graafschap — provincial Dutch football's heartland.", "PSV made him a Dutch league legend; Sevilla turned him into a European one.", "Came on for Barcelona once and looked the part — the ultimate journeyman flex."],
    tier3: ["Born in Aigle, Switzerland — to a Dutch father and a Swiss mother.", "His brother Siem also plays international football — family business."],
    overperform: ["When de Jong gets a header in the box, the whole tournament leans toward him.", "Late-game substitute, late-game goal — vintage script.", "The veteran's value showed up exactly when Netherlands needed it."],
    underperform: ["Couldn't get on the end of the cutback — the touch wasn't there.", "Marked tightly by a quick centre-back — credit the matchup.", "Quiet sub cameo — happens to every veteran 9."],
    onPace: ["Standard de Jong — held up the ball, won the headers, brought others into play.", "Got his half-chance, didn't bury it, kept the pressure on.", "The veteran shift — vocal, organized, present."],
    loosePlay: ["Heavy touch under pressure — the small detail.", "Off-side flag against him — chased the line a half-second too early.", "Booked for a frustration foul — happens late in tournaments."],
    defensive: ["Defends corners like a centre-back — that's the modern target man.", "Won his header in his own box — the dual-job 9.", "Pressed the keeper into a hurried clearance."],
    bigGame: ["LUUK DE JONG! THE VETERAN STRIKES! Netherlands' old reliable!", "He doesn't score every match — but when he does, it changes the match.", "The veteran's gift — the moment that decides the game."],
    quietGame: ["Quiet sub cameo — 20 minutes, no goal, but the pressure was felt.", "Subbed on too late to change the script.", "The header didn't come his way tonight."],
    controversy: ["Barcelona signed him on a panic loan in 2021 — most fans groaned, the goals justified it briefly.", "Some Dutch media wanted the younger generation ahead of him — the rotation debate."],
    famousGameHint: ["Look up Sevilla vs Inter Milan in the 2020 Europa League final — de Jong scored both goals.", "His PSV Eredivisie title runs — the bedrock of his career.", "The Argentina quarterfinal — came on as a sub, didn't crack the back line."],
    opponentFlavor: {
      ARG: "Quarterfinal sub — couldn't crack the Argentine back line, Netherlands went out on penalties.",
      USA: "Round-of-16 — sub cameo, the win was sealed before he had time to score.",
      QAT: "Group-stage closer — sub appearance, secured the route.",
    },
    formerTeam: ["De Graafschap → Twente → Borussia Mönchengladbach → Newcastle (loan) → PSV → Sevilla → Barcelona (loan) → PSV again.", "The journeyman star path — every chapter has silverware."],
    rivalry: ["Ajax-PSV is the Dutch Klassieker — every Eindhoven striker plays both sides of it."],
    milestones: ["Europa League winner with Sevilla (2020) — both goals in the final.", "Multiple Eredivisie titles with PSV.", "Netherlands international across two World Cup cycles."],
    streakLines: ["Late-game goals are his signature — substitute appearances become decisive.", "Netherlands' 'break-glass' striker — used when the system needs a target."],
    salaryNarrative: ["At $53 ORANGE he's priced for the late-game spike — the sub cameo with a goal.", "ORANGE because the upside is real — Sevilla's Europa League final proves it."],
    teamContext: ["Louis van Gaal's veteran option off the bench in 2022.", "When the system needed a target, de Jong got the call. When it didn't, he watched."],
    draftAndPath: ["De Graafschap's youth setup — provincial Dutch football.", "Twente made him a Dutch league regular; PSV made him a Dutch league legend.", "Sevilla's Europa League win in 2020 was the European apex."],
  },

  // Jamal Musiala — Germany FWD $60 ORANGE — avgFP 35.7
  musiala: {
    nicknames: ["Bambi", "JM10", "The Wizard"],
    knownFor: "Germany's English-raised wonderkid — Bayern's number 10 of the future, ankle-breaker in chief.",
    salaryTier: "max",
    tier1: ["When Musiala glides past three defenders, you hear a stadium gasp.", "He plays the game like the ball is a marble and the pitch is glass.", "Germany's most exciting attacking talent since Mesut Özil — and arguably more direct."],
    tier2: ["Born in Stuttgart, raised in England, Chelsea youth, Bayern signing — the cross-cultural prodigy story.", "Chose Germany over England at 17 — England fans still wince about that one.", "Bayern's number 10 by 19, Bundesliga golden boy by 21."],
    tier3: ["Called 'Bambi' by Bayern teammates because of his low center of gravity and quick feet.", "Speaks fluent English and German — bilingual interviews are his thing."],
    overperform: ["When Musiala glides, the defense is just scenery.", "He doesn't beat defenders — he removes them from the screen.", "This is the Germany-Bayern axis the country has waited a decade for."],
    underperform: ["Marked into the ground — credit the back line.", "Even Bambi has nights when the dribble doesn't quite come off.", "Frustrated by a deep block — the chances dried up around him."],
    onPace: ["Standard Musiala — a piece of magic, a near-miss, a defender mentally retired.", "Did the things you'd expect. Including the things only he does.", "Looked like a Bayern player at the World Cup. Imagine that."],
    loosePlay: ["Tried to glide through four — even Bambi has limits.", "Caught dribbling into trouble — youth showing.", "Heavy first touch in the box — the chance that became a corner."],
    defensive: ["Tracks back when he wants to — which is more often now.", "Won a tackle in midfield — that's a complete attacking midfielder.", "Pressed the centerback into a hurried clearance."],
    bigGame: ["MUSIALA! BAMBI! Germany have a star and the star is glowing!", "MAGISTERIAL. The kid's left foot is enchanted.", "This is the Germany the Bundesliga has watched all season."],
    quietGame: ["Marked into the ground — sometimes the doubles team works.", "Subbed at 75' — Germany saving him for the next round that didn't come.", "Quiet 90 by his standards. His standards are stratospheric."],
    controversy: ["Choosing Germany over England at 17 still rankles English youth-football fans.", "Some German media questioned Hansi Flick for not building the team around him sooner."],
    famousGameHint: ["Look up Germany vs Spain in the 2022 group stage — Musiala's dribbles bent the back line repeatedly.", "His Bayern Champions League runs — particularly the 2022/23 cycle.", "The Costa Rica game — Germany won 4-2, Musiala was at the heart of it."],
    opponentFlavor: {
      JPN: "Group-stage opener — Germany lost, the kid still glided.",
      ESP: "1-1 draw — Musiala's dribbles were Germany's brightest moments.",
      CRC: "4-2 win — multiple chances, multiple dribbles, the future on display.",
    },
    formerTeam: ["Chelsea youth → Bayern Munich academy → Bayern first team. The cross-channel prodigy path.", "Bayern signed him at 17 from Chelsea — cost almost nothing, return is everything."],
    rivalry: ["Bayern-Dortmund is the Klassiker — every Bayern player carries that.", "Germany-England is the international wrinkle — and he chose Germany."],
    milestones: ["Bundesliga title with Bayern (multiple).", "Germany international from age 18.", "Bundesliga Player of the Month — multiple times by 21."],
    streakLines: ["Goal-and-assist runs are his signature — when Bambi is hot, Bayern are unstoppable.", "Bundesliga form rolls into international form — same player, same level."],
    salaryNarrative: ["At $60 ORANGE he's priced for the ceiling — the Bayern version is the ceiling.", "ORANGE because the floor is high and the ceiling is generational."],
    teamContext: ["Germany's number 10 of the future — and increasingly the present.", "Hansi Flick's tactical pivot in 2022 was 'put Musiala in space and let him be Musiala.'"],
    draftAndPath: ["Chelsea youth from age 7 — England's loss became Germany's gain.", "Bayern signed him at 17 — almost free in modern transfer terms.", "First-team Bundesliga debut at 17, never looked back."],
  },

  // Ricardo Horta — Portugal DEF $52 ORANGE — avgFP 35.2 (note: actually a forward)
  horta: {
    nicknames: ["Ricardo", "RH21"],
    knownFor: "Portugal's Braga winger — the late-call-up who quietly delivered.",
    salaryTier: "star",
    tier1: ["The kind of player every Portuguese squad needs — versatile, technical, unselfish.", "SC Braga's longest-serving forward — Primeira Liga consistency in human form.", "When Portugal needed a fresh-legs option in 2022, he was the call."],
    tier2: ["Came through Vitória de Setúbal — Primeira Liga's grassroots route.", "Málaga loan in La Liga, then home to Braga where he became a club legend.", "Earned his Portugal call-up the long way — at 28, with a tournament cap to show for it."],
    tier3: ["His brother André also plays for Portugal — family business.", "Holds Braga's all-time goals record by margin."],
    overperform: ["When Horta is sharp, Portugal's bench has another problem-solver.", "The substitute who came on, did his job, and changed the match's shape.", "Tournament veteran in his first tournament — that's how you know the work was done."],
    underperform: ["Sub cameo that didn't yield — 20 minutes is short.", "Marked tightly — credit the back line.", "Quiet 90 — the goal didn't come, the team didn't need it from him."],
    onPace: ["Standard Horta — pressed, ran, held up the ball when needed.", "The veteran's shift — vocal, organized, present.", "Did the unglamorous things excellently."],
    loosePlay: ["Heavy first touch — the chance that became a corner.", "Tried a cross that didn't beat the first man.", "Booked for a tactical foul late."],
    defensive: ["Tracks back like a Braga winger — the dual-job mentality.", "Pressed the fullback into a panic clearance.", "Won the deep ball under pressure."],
    bigGame: ["HORTA! THE BRAGA VETERAN STRIKES — Portugal smile!", "He's never been a household name, but tonight Lisbon knows it.", "This is what depth looks like at a World Cup."],
    quietGame: ["Sub cameo — short minutes, modest output.", "Quiet shift in a brief appearance.", "The fresh legs were used; the chance didn't come."],
    controversy: ["Some Portuguese media questioned Fernando Santos' selection — Horta over more glamorous names.", "Braga's whole 'forever player' identity around him — fans wanted him to leave for a bigger move that never came."],
    famousGameHint: ["Look up his Primeira Liga assist tallies at Braga — five-plus seasons of double-digit goal involvements.", "His Portugal call-up came late — earned by Braga consistency, not by transfer rumor.", "The Switzerland round-of-16 — Portugal won 6-1, he played a role."],
    opponentFlavor: {
      SUI: "Round-of-16 6-1 — Portugal cruised, Horta got minutes off the bench.",
      KOR: "Group-stage 2-1 loss — Portugal had qualified, rotated, lost.",
      MAR: "Quarterfinal exit — Bono shut Portugal down, Horta couldn't crack it.",
    },
    formerTeam: ["Vitória de Setúbal → Málaga → SC Braga (the forever home).", "Braga's all-time goalscorer at the club level."],
    rivalry: ["Braga vs Porto/Benfica — every Braga player lives in that shadow."],
    milestones: ["SC Braga's all-time top scorer.", "Portugal international across multiple cycles."],
    streakLines: ["Braga form is his form — Primeira Liga goals come in regular intervals.", "Portugal cameos are short but pressing-sharp."],
    salaryNarrative: ["At $52 ORANGE he's overpriced if he doesn't start — the squad-rotation tax.", "Card depends on Santos' rotation — value pick if he gets minutes, fade if he doesn't."],
    teamContext: ["Portugal's depth piece in 2022 — used in rotation games to manage the senior players.", "Fernando Santos trusted him because Braga's Primeira Liga consistency demanded the call."],
    draftAndPath: ["Vitória de Setúbal academy — Primeira Liga's bedrock.", "Málaga loan to La Liga — the mid-career detour.", "SC Braga from 2016 onward — became the forever player."],
  },

  // Serge Gnabry — Germany FWD $59 ORANGE — avgFP 33.3
  gnabry: {
    nicknames: ["Serge", "SG10", "GnabRY"],
    knownFor: "Bayern's English-trained winger — Arsenal reject, German champion, Champions League hero.",
    salaryTier: "max",
    tier1: ["When Gnabry cuts in from the right, the back post is in danger.", "Four goals against Tottenham in a single Champions League night — that's a calling card.", "Bayern's first-choice right winger for half a decade — that's not a coincidence."],
    tier2: ["Arsenal academy product — released after a West Brom loan flopped at 21.", "Werder Bremen rebuilt him; Hoffenheim refined him; Bayern made him a champion.", "Five Bundesliga titles and a Champions League — the redemption arc complete."],
    tier3: ["Born in Stuttgart to an Ivorian father — could have chosen Côte d'Ivoire, picked Germany.", "His four-goal Champions League night against Tottenham still appears in highlight packages."],
    overperform: ["When Gnabry's shooting from outside the box, the corner is unguardable.", "He scored four against Spurs in a Champions League knockout. Read that again.", "Bayern's right wing in human form."],
    underperform: ["Marked off the touchline — credit the fullback.", "Couldn't find his shot — even the great ones have those nights.", "Frustrated by a deep block — the chances dried up."],
    onPace: ["Standard Gnabry — cuts inside, threatens the corner, makes the runs.", "Got his shot, made his decisions, did the dual job.", "The Bayern winger shift — present at both ends."],
    loosePlay: ["Tried a cross that didn't beat the first man — the small detail.", "Caught dribbling into trouble — youth showing decade-late.", "Heavy first touch — the chance that became a corner."],
    defensive: ["Tracks back like a complete winger — Bayern's pressing system demands it.", "Pressed the fullback into a panic clearance.", "Won his tackle wide — the dual-job winger."],
    bigGame: ["GNABRY! GNABRY! Bayern's right wing strikes!", "MAGISTERIAL. He has been here before — Champions League and country.", "The four-goal Wembley night made him a household name. Tonight builds on it."],
    quietGame: ["Marked off the touchline — the doubles team did its job.", "Subbed at 75' — Hansi Flick managing minutes.", "Quiet 90 — the goal will come."],
    controversy: ["Posted a Paris Fashion Week trip during a Bayern injury layoff in 2023 — Bayern fans were not amused.", "The Arsenal release at 21 still gets brought up by English media."],
    famousGameHint: ["Look up Tottenham vs Bayern Munich, Champions League group stage 2019 — Gnabry scored four.", "His Germany goals across the 2018 cycle — the first-team breakthrough.", "The Costa Rica game — Germany won 4-2, Gnabry contributed."],
    opponentFlavor: {
      JPN: "Group-stage opener — Germany lost, the right wing wasn't enough.",
      ESP: "1-1 draw — held by Spain's left side.",
      CRC: "4-2 win — got involved in the build-up.",
    },
    formerTeam: ["Arsenal academy → West Brom (loan flop) → Werder Bremen → Hoffenheim → Bayern Munich.", "The redemption arc — released by Arsenal at 21, lifting Champions League trophies at 25."],
    rivalry: ["Bayern-Dortmund — every Bayern player carries that.", "Germany-England never settled."],
    milestones: ["Five Bundesliga titles with Bayern.", "Champions League winner (2020).", "Germany international from age 21."],
    streakLines: ["Goal-glut nights are his signature — four in a Champions League game lives in the legend.", "Bundesliga goals come in flurries — three across two weeks, then quiet for two."],
    salaryNarrative: ["At $59 ORANGE he's priced for the Bayern ceiling — the four-goal Tottenham night is the ceiling.", "ORANGE because the upside is real — multiple-goal games live in his locker."],
    teamContext: ["Germany's right winger of choice across 2018 and 2022 cycles.", "Hansi Flick trusted him because Bayern's tactical system was the German national team's tactical system."],
    draftAndPath: ["Stuttgart academy → Arsenal academy at 16 — early apex.", "West Brom loan flopped; Werder Bremen rebuilt; Hoffenheim refined.", "Bayern Munich made him a champion — five Bundesligas and a Champions League."],
  },

  // Thomas Meunier — Belgium DEF $47 PURPLE — avgFP 32.1
  meunier: {
    nicknames: ["Thomas", "TM15"],
    knownFor: "Belgium's veteran right back — PSG's old reliable, Dortmund's modern overlap.",
    salaryTier: "star",
    tier1: ["The kind of fullback every elite team needs — overlap, deliver, recover.", "Belgium's right side has been Meunier's right side for the entire Golden Generation era.", "PSG and Dortmund both built around his right-flank cross."],
    tier2: ["Came through Club Brugge — Belgian football's bedrock.", "PSG bought him at 25; Dortmund got him at 28; the Bundesliga gave him a second wind.", "Belgium's most-capped right back across the 2014-2022 cycles."],
    tier3: ["Born in Sainte-Ode — a Walloon village far from any major city.", "Played as a striker as a teenager before Brugge converted him to fullback."],
    overperform: ["When Meunier is overlapping, Belgium's right flank is a Premier League product.", "Two crosses, an assist, a clean sheet — fullback dream sheet.", "The veteran's quality showed up exactly when needed."],
    underperform: ["Caught upfield when the counter came — the modern fullback's tax.", "His marker beat him to the byline — credit the winger.", "Quiet attacking shift — the cross didn't connect."],
    onPace: ["Standard Meunier — overlapped, recovered, distributed.", "Made his runs, stayed disciplined, did the dual job.", "The veteran shift — every detail in the right place."],
    loosePlay: ["Tried a cross that didn't beat the first man — the small detail.", "Booked for a recovery foul — the price of overlapping.", "Caught out of position once — the moment that becomes the highlight."],
    defensive: ["Tracked back the full sprint — that's what the position demands.", "Won his tackle in his own third — completing the dual role.", "Cleared the cross at the back post — discipline showing."],
    bigGame: ["MEUNIER! THE VETERAN OVERLAPS — and Belgium have a goal!", "An assist from a fullback at his third World Cup — class never expires.", "This is what the Golden Generation looks like at age 31."],
    quietGame: ["Quiet 90 from a fullback is usually a clean sheet — and tonight it was.", "Marked off the overlap by the opposition winger — credit them.", "Subbed at 80' — the legs of an overlapping fullback feel 90 minutes."],
    controversy: ["The Dortmund move in 2020 came with PSG-fan grumbling — Meunier had to pick sides publicly.", "Belgium's 2022 squad chemistry was reportedly fraught — multiple senior leaks suggested camp tension."],
    famousGameHint: ["Look up Belgium vs Brazil in the 2018 World Cup quarterfinal — Meunier scored.", "His PSG Champions League runs — particularly 2019/20 to the final.", "The 2022 group stage — Belgium wobbled and Meunier was on the right side of every wobble."],
    opponentFlavor: {
      MAR: "Group-stage 2-0 loss — Belgium's defense was breached, Meunier was on the right side.",
      CAN: "1-0 win — disciplined defensive shift on the right.",
      CRO: "0-0 group-stage closer — Belgium went home, Meunier's tournament ended quietly.",
    },
    formerTeam: ["Club Brugge → PSG (€7m, 2016) → Dortmund (free, 2020) → Trabzonspor.", "PSG's Champions League nights, Dortmund's Bundesliga nights — both got the veteran's best."],
    rivalry: ["Belgium-Netherlands is the Low Countries derby — every Belgian fullback grows up dreaming of that fixture."],
    milestones: ["Belgium international with 60+ caps.", "Bundesliga titles with Dortmund (cup level).", "World Cup bronze with Belgium (2018) — the Golden Generation peak."],
    streakLines: ["Meunier's good runs come in chunks — six clean shifts then one wobble.", "Goals from a right back come from set pieces — diagonal balls find his head."],
    salaryNarrative: ["At $47 PURPLE he's the value Belgian back — produces ORANGE-tier output when overlapping.", "PURPLE because Belgium's defensive output is the reason — clean sheets carry his card."],
    teamContext: ["Belgium's right back of choice across three World Cups — 2014, 2018, 2022.", "Roberto Martínez's tactical anchor on the right — overlap with Hazard, recover with Vertonghen."],
    draftAndPath: ["Club Brugge youth at 18 — late bloomer for a Belgian.", "PSG paid €7m for him at 25 — bargain in retrospect.", "Dortmund's free transfer in 2020 was the veteran's reward."],
  },

  // Theo Hernández — France DEF $45 PURPLE — avgFP 30.6
  hernández: {
    nicknames: ["Theo", "TH22"],
    knownFor: "France's marauding left back — AC Milan's overlapping engine, the rocket on the left flank.",
    salaryTier: "star",
    tier1: ["When Theo overlaps, France have two wingers and one fullback.", "The fastest fullback in world football — and the crossing to match.", "Milan's left wing in human form — modern football's blueprint left back."],
    tier2: ["Came through Atlético Madrid's youth — La Liga roots.", "Real Madrid loaned him out, sold him cheap; Milan turned him into one of Europe's top fullbacks.", "His brother Lucas plays for France too — left-side family business."],
    tier3: ["Brother of Lucas Hernández — left back / centre-back family combo.", "Was at Atlético, then Real, then Milan — the unusual Iberian-to-Serie A path."],
    overperform: ["When Theo overlaps, the back post is in danger.", "Three crosses, an assist, a clean sheet — the modern fullback dream.", "He's playing the position the way the entire game wants it played."],
    underperform: ["Caught upfield when the counter came — the modern fullback's tax.", "His marker beat him to the byline — credit the winger.", "Quiet attacking shift — the cross didn't connect."],
    onPace: ["Standard Theo — overlapped, recovered, distributed.", "Made his runs, stayed disciplined enough, did the dual job.", "The fullback shift you'd want every match — present at both ends."],
    loosePlay: ["Tried a cross that didn't beat the first man — the small detail.", "Booked for a recovery foul — the price of overlapping.", "Caught out of position once — the moment that becomes the highlight."],
    defensive: ["Tracked back the full sprint — that's what the position demands.", "Won his tackle in his own third — completing the dual role.", "Cleared the cross at the back post — discipline showing."],
    bigGame: ["THEO HERNANDEZ! FRANCE'S ROCKET ON THE LEFT — and the cross is converted!", "An overlapping run from his own half — that's a Milan move on a World Cup pitch.", "MAGISTERIAL. The left flank is a runway and Theo is the jet."],
    quietGame: ["Quiet 90 from a fullback is usually a clean sheet — and tonight it was.", "Marked off the overlap by the opposition winger — credit them.", "Subbed at 80' — the legs of an overlapping fullback feel 90 minutes."],
    controversy: ["The Real Madrid sale at 21 was a bargain Madrid still regrets — Milan fans loved every minute.", "Brother Lucas had the ACL injury that opened up his starting spot in 2022 — family circumstance, professional opportunity."],
    famousGameHint: ["Look up France vs Argentina in the 2022 final — Theo's overlapping runs were France's main attacking outlet.", "His Milan Scudetto run in 2021/22 — the title that put him in the elite tier.", "The Morocco semifinal — held the left flank in the most-watched African game ever."],
    opponentFlavor: {
      ARG: "The 2022 final — overlapping runs were France's main creative outlet, the loss was the team's, not his.",
      MAR: "Semifinal — held the left flank in Africa's biggest game ever.",
      ENG: "Quarterfinal — defended Saka well enough, France advanced.",
      POL: "Round-of-16 — overlap fueled Mbappé's brace.",
    },
    formerTeam: ["Atlético Madrid → Real Madrid → Real Sociedad (loan) → AC Milan.", "Milan paid €20m in 2019 — bargain compared to the player they got."],
    rivalry: ["France-Italy at international level — but Milan-Inter at club level is his daily life."],
    milestones: ["AC Milan Scudetto winner (2021/22).", "France international from age 23.", "World Cup runner-up (2022) — the final hat-trick was Mbappé's, the assists Theo's."],
    streakLines: ["Assist runs come from his crossing — when Mbappé moves, Theo's numbers move.", "Fitness is his thing — full-throttle for 90, every match."],
    salaryNarrative: ["At $45 PURPLE he's the value French back — produces ORANGE-tier crossing output.", "PURPLE because Mbappé eats France's budget; Theo benefits from being undervalued by association."],
    teamContext: ["France's left flank in 2022 — overlapping fullback, with Mbappé inverted.", "Didier Deschamps' tactical pivot was 'let Theo overlap and let Mbappé cut inside.' It worked all the way to the final."],
    draftAndPath: ["Atlético Madrid academy — La Liga roots.", "Real Madrid signed him at 19; loaned him to Sociedad at 20.", "AC Milan paid €20m in 2019 — best bargain in Serie A."],
    signatureGames: [
      { date: "2022-12-18", opponent: "ARG", fp: 50, line: "The final — France lost on penalties, but the overlapping runs fueled the comeback." },
      { date: "2022-12-14", opponent: "MAR", fp: 45, line: "Held the left flank in Africa's biggest game ever — France into the final." },
    ],
  },

  // Alex Sandro — Brazil DEF $44 PURPLE — avgFP 30.1
  // Keyed as `lobo` (2nd-to-last word of "Alex Sandro Lobo Silva"): the
  // lookup tries last/2nd-to-last/first word; `sandro` is the 2nd word
  // and would never be tried.
  lobo: {
    nicknames: ["Alex", "AS6"],
    knownFor: "Brazil's veteran left back — Juventus' Serie A consistency, the Selecão's senior leader on the flank.",
    salaryTier: "star",
    tier1: ["The kind of fullback every Brazil squad needs — disciplined, two-footed, position-correct.", "Juventus' left back of choice for half a decade — that's not a coincidence.", "Brazil's defensive bedrock on the left flank across three World Cup cycles."],
    tier2: ["Came through Atlético Paranaense — Brazilian football's southern spine.", "Porto bought him as a 19-year-old; Juventus paid €26m for him at 24.", "Has now been a Brazil starter across 2014, 2018, and 2022 — that's longevity."],
    tier3: ["Born in Catanduva — small-town São Paulo state.", "Plays both fullback positions — left and right — at the club level."],
    overperform: ["When Sandro is on, Brazil's left flank disappears as a problem.", "Three tackles, two interceptions, a clean sheet — fullback dream sheet.", "The veteran's discipline showed up exactly when needed."],
    underperform: ["Caught upfield when the counter came — the modern fullback's tax.", "His marker beat him to the byline — credit the winger.", "Quiet attacking shift — Brazil's left was muted."],
    onPace: ["Standard Sandro — overlapped sparingly, recovered always, distributed cleanly.", "Did the boring things excellently and the hard things adequately.", "Reliable. Composed. The veteran kind of fullback."],
    loosePlay: ["A wobble at the back — credit the attacker, but Sandro will rewatch the tape.", "Caught out of position once — the moment that becomes the highlight.", "Marked man got past him for the chance — the only blemish on a clean shift."],
    defensive: ["Three tackles, two interceptions, a clean sheet — boxes ticked.", "Read the cross before it was hit — that's the experience.", "Tracked the runner all the way to the byline — discipline."],
    bigGame: ["ALEX SANDRO! THE VETERAN OVERLAPS — Brazil's left flank delivers!", "Class never expires — and tonight, Sandro showed the kids how it's done.", "The senior on the flank, the captain in spirit, the bedrock made flesh."],
    quietGame: ["Quiet 90 from a fullback is usually a clean sheet — and tonight it was.", "Marked off the overlap by the opposition winger — credit them.", "Subbed at 80' — Tite saving him for the next round."],
    controversy: ["Juventus' 2023 Serie A points deduction shadowed his whole season — fan loyalty tested.", "Brazil's 2022 squad chemistry was reportedly fraught — Neymar's injury timing affected everyone."],
    famousGameHint: ["Look up Brazil vs Croatia in the 2022 quarterfinal — Sandro played the full 120 + penalties.", "His Juventus Serie A title runs — multiple Scudetti.", "The 2018 World Cup quarterfinal against Belgium — Brazil out, Sandro on the pitch."],
    opponentFlavor: {
      CRO: "Quarterfinal exit — 120 minutes plus penalties, Brazil out, Sandro played every second.",
      KOR: "Round-of-16 4-1 win — Brazil's most polished tournament performance.",
      SUI: "Group-stage 1-0 win — disciplined defensive shift.",
      SRB: "Group-stage 2-0 win — Brazil opened with a statement.",
    },
    formerTeam: ["Atlético Paranaense → Porto → Juventus (€26m, 2015) → Al-Hilal (2024).", "Juventus' Serie A nights gave him a decade of elite-level experience."],
    rivalry: ["Brazil-Argentina is in his bones — every Selecão fullback lives for that fixture."],
    milestones: ["Multiple Serie A titles with Juventus.", "Brazil international across three World Cups.", "Coppa Italia silverware."],
    streakLines: ["Sandro's good runs come in chunks — half a season clean, then a wobble.", "Brazil's defensive shape stabilizes when he plays — direct correlation."],
    salaryNarrative: ["At $44 PURPLE he's the value Brazil back — Juventus consistency at a Selecão price.", "PURPLE because Brazil's attack eats the budget — Sandro is the cheap floor."],
    teamContext: ["Brazil's left flank in 2022 — disciplined fullback, with Vinícius cutting inside.", "Tite trusted him because Juventus' Serie A consistency was Brazil's defensive blueprint."],
    draftAndPath: ["Atlético Paranaense youth — Brazilian football's southern bedrock.", "Porto bought him at 19; Juventus paid €26m at 24.", "A decade at Juventus — Serie A's left back of choice."],
  },

  // Michy Batshuayi — Belgium FWD $53 ORANGE — avgFP 29.6
  batshuayi: {
    nicknames: ["Batsman", "MB23"],
    knownFor: "Belgium's super-sub striker — Chelsea title medal, Crystal Palace folk hero, France's nightmare.",
    salaryTier: "star",
    tier1: ["The kind of striker who scores when you bring him on — that's a rare gift.", "Belgium's emergency 9 across three World Cup cycles — and emergency 9 isn't a complaint.", "Premier League fans love him; Belgian fans need him."],
    tier2: ["Came through Standard Liège — Belgian football's traditional scoring factory.", "Marseille made him a Ligue 1 name; Chelsea paid £33m for him at 22.", "Crystal Palace loan turned him into a Premier League cult hero — the Selhurst Park goal celebrations are legend."],
    tier3: ["Born in Brussels to Congolese parents.", "Memorably hit the post against England in a friendly and celebrated like he'd scored — the moment is on YouTube forever."],
    overperform: ["When Batshuayi comes on, the back four take a deep breath.", "Late-game substitute, late-game goal — vintage script.", "The super-sub shows up — every tournament, every cycle."],
    underperform: ["Sub cameo that didn't yield — 20 minutes is short.", "Marked tightly by a quick centre-back — credit the matchup.", "The chance didn't come his way — happens."],
    onPace: ["Standard Batshuayi — held up the ball, made the runs, stayed dangerous.", "Got his half-chance, didn't bury it, kept the pressure on.", "The super-sub shift — vocal, energetic, present."],
    loosePlay: ["Heavy first touch under pressure — the small detail.", "Tried a flick that was a flick too far.", "Off-side flag against him — chased the line a half-second too early."],
    defensive: ["Pressed the centerbacks like a winger — that's the modern 9.", "Won the long ball under pressure.", "Tracked back to defend a corner — sub mentality."],
    bigGame: ["BATSHUAYI! THE SUPER-SUB STRIKES! Belgium have life!", "The bench produced the moment — that's what subs are for.", "Tonight, Marseille and Brussels and Selhurst Park all sing together."],
    quietGame: ["Sub cameo — short minutes, modest output.", "Quiet shift in a brief appearance.", "The fresh legs were used; the chance didn't come."],
    controversy: ["Self-deprecating tweets and Instagram moments made him a cult favorite — Belgian football's most likable star.", "Some Belgian media wanted Lukaku's understudy to be a more serious figure — Batshuayi was always the cheerful one."],
    famousGameHint: ["Look up Belgium vs Wales in Euro 2016 — Batshuayi scored the second goal in a 3-1 win.", "His Crystal Palace loan goals — folk hero status confirmed.", "The 2022 group stage — Belgium scored once in three games, and he scored it."],
    opponentFlavor: {
      CAN: "Group-stage opener — Batshuayi scored the only goal in a 1-0 win.",
      MAR: "Group-stage 2-0 loss — sub cameo, couldn't crack Bono.",
      CRO: "0-0 group-stage closer — Belgium went home, Batshuayi played sub minutes.",
    },
    formerTeam: ["Standard Liège → Marseille → Chelsea (£33m, 2016) → Borussia Dortmund (loan) → Valencia (loan) → Crystal Palace (loan, twice) → Beşiktaş → Galatasaray.", "Champions League winner with Chelsea — squad medal, but a medal."],
    rivalry: ["Belgium-Netherlands is the Low Countries derby."],
    milestones: ["Premier League title with Chelsea (squad).", "Belgium international with 50+ caps.", "Multiple Bundesliga and Ligue 1 silverware loans."],
    streakLines: ["Late-game goals are his signature — substitute appearances become decisive.", "The super-sub identity has been his career — and it works."],
    salaryNarrative: ["At $53 ORANGE he's priced for the spike — the Canada game's the floor, the brace's the ceiling.", "ORANGE because the super-sub gift is real — but the floor is rotation-dependent."],
    teamContext: ["Belgium's super-sub striker across three World Cup cycles.", "When Lukaku has been injured — like 2022 — Batshuayi has stepped up. When healthy, he's the bench impact."],
    draftAndPath: ["Standard Liège academy at 17.", "Marseille made him a Ligue 1 name.", "Chelsea paid £33m for him at 22 — the move that should have been bigger than it ended up being."],
    signatureGames: [
      { date: "2022-11-23", opponent: "CAN", fp: 60, line: "The opener — Batshuayi scored the only goal in a 1-0 win, Belgium's tournament started." },
    ],
  },

  // Randal Kolo Muani — France FWD $50 PURPLE — avgFP 28.4
  muani: {
    nicknames: ["RKM", "Randal"],
    knownFor: "France's late-call-up striker — Frankfurt's Bundesliga star, the chance-on-the-final hero who almost was.",
    salaryTier: "star",
    tier1: ["When Kolo Muani came on as a sub against Morocco, France's whole attack shifted up a gear.", "The kid who was at Nantes 18 months before the final — and almost won the final.", "Eintracht Frankfurt's gift to the French national team."],
    tier2: ["Came through Nantes — Ligue 1's youth-development bedrock.", "Frankfurt signed him in 2022; he scored 23 goals and won Bundesliga rookie of the year.", "PSG paid €90m for him after the World Cup — the post-tournament transfer that defined the cycle."],
    tier3: ["Born in Bondy — the same suburb as Mbappé.", "Two Bondy kids were on the World Cup final pitch in 2022 — Mbappé starting, Kolo Muani as the supersub."],
    overperform: ["When Kolo Muani's running in behind, the back line panics.", "Came on as a sub against Morocco — France's whole attack changed shape.", "The version of him that almost won the World Cup with one chance."],
    underperform: ["Sub cameo that didn't yield — the chance was there, the touch wasn't.", "Marked tightly — credit the matchup.", "The radar was off — happens to every striker."],
    onPace: ["Standard Kolo Muani — pace, presence, runs in behind.", "Got his half-chance, kept the pressure on, stretched the line.", "The young striker's shift — vocal, energetic, present."],
    loosePlay: ["Heavy first touch in the box — the chance that became a corner.", "Tried a flick that was a flick too many.", "Off-side flag against him — chased the line a half-second too early."],
    defensive: ["Pressed the centerbacks like a winger — that's the modern 9.", "Tracked back to defend a corner — sub mentality.", "Won the long ball under pressure."],
    bigGame: ["KOLO MUANI! THE BONDY KID — and France are level!", "MAGISTERIAL. The Bundesliga's best young striker is announcing himself.", "This is the Frankfurt version — the version Paris paid €90m for."],
    quietGame: ["Sub cameo — short minutes, modest output.", "Quiet shift in a brief appearance.", "The fresh legs were used; the chance didn't quite come."],
    controversy: ["The 2022 final chance — one-on-one with Martínez at the death — has haunted French football podcasts since.", "His PSG move in 2023 came with €90m attached — the price tag inflated expectations."],
    famousGameHint: ["Look up France vs Morocco in the 2022 semifinal — Kolo Muani scored as a sub.", "The 2022 final's 122nd minute — the one-on-one with Emi Martínez that defined the moment.", "His Bundesliga 2022/23 campaign at Frankfurt — 23 goals, rookie of the year."],
    opponentFlavor: {
      MAR: "Semifinal — sub appearance, scored the goal that sealed the win.",
      ARG: "The final's 122nd minute — one-on-one with Martínez, saved, France lost on penalties.",
      POL: "Round-of-16 — sub cameo as France comfortably advanced.",
    },
    formerTeam: ["Nantes → Eintracht Frankfurt (free, 2022) → PSG (€90m, 2023).", "The Bundesliga rookie-of-the-year run was the breakthrough."],
    rivalry: ["France-Argentina from 2022 will live in his head forever."],
    milestones: ["France international from age 22.", "Bundesliga rookie of the year (2022/23).", "World Cup runner-up (2022) — but the final 122nd-minute miss."],
    streakLines: ["Frankfurt-form Muani was different — 23 goals before age 24.", "Sub cameos at France produce moments — the goal vs Morocco proves it."],
    salaryNarrative: ["At $50 PURPLE he's the value French striker — Frankfurt form at a French price.", "PURPLE because Mbappé eats France's budget; Muani benefits from being undervalued."],
    teamContext: ["France's super-sub striker in 2022 — the impact piece off the bench.", "Didier Deschamps used him in the latter knockouts — semifinal hero, final near-hero."],
    draftAndPath: ["Bondy youth football — same suburb as Mbappé.", "Nantes academy at 16 — Ligue 1 development bedrock.", "Frankfurt's free transfer in 2022 was the year's best Bundesliga move."],
    signatureGames: [
      { date: "2022-12-14", opponent: "MAR", fp: 55, line: "Semifinal sub — scored the second goal that sent France to the final." },
      { date: "2022-12-18", opponent: "ARG", fp: 35, line: "The 122nd-minute miss — one-on-one with Martínez, saved, France lost on penalties." },
    ],
  },

  // Kevin De Bruyne — Belgium FWD $49 PURPLE — avgFP 27.6 (note: actually a midfielder)
  bruyne: {
    nicknames: ["KDB", "Kevin", "The Wizard"],
    knownFor: "Manchester City's playmaker — best midfielder of his generation, Belgium's heart.",
    salaryTier: "max",
    tier1: ["He plays passes other midfielders don't see, let alone attempt.", "Best playmaker of his generation — the City years are evidence on tape.", "If you watch one midfielder to understand the modern game, watch De Bruyne with the ball at his feet."],
    tier2: ["Came through Genk — Belgian football's bedrock.", "Chelsea sold him at 22 — one of the worst transfer decisions in Premier League history.", "Manchester City have built a Premier League dynasty around him."],
    tier3: ["Born in Drongen — small-town Flemish Belgium.", "His ginger hair and pale skin made him an easy target for Belgian media — until the assists started piling up."],
    overperform: ["When De Bruyne picks his head up, somebody is about to score.", "MAGISTERIAL. The cross-pitch ball is his signature — and tonight, it sang.", "Premier League MVP form on a World Cup pitch."],
    underperform: ["Frustrated tonight — the ball didn't move quickly enough around him.", "Belgium's 2022 squad chemistry was reportedly bad — and KDB's body language confirmed it.", "Quiet shift by his standards. His standards are stratospheric."],
    onPace: ["Standard De Bruyne — runs the midfield, picks the pass, threatens the goal.", "Did the things you'd expect. Including the things only he does.", "The maestro at his desk, conducting another piece."],
    loosePlay: ["Tried to thread a pass nobody else could see — and the receiver couldn't see it either.", "Booked for tactical frustration — Belgium's bad chemistry showed.", "Misplaced a long ball — the cardinal sin he commits maybe once a tournament."],
    defensive: ["Tracks back like a 30-year-old captain — the body language earned.", "Pressed the centerback into a panic clearance.", "Won a tackle in midfield — the dual-job number 8."],
    bigGame: ["DE BRUYNE! KDB! Belgium's wizard speaks!", "MAGISTERIAL. The wardrobe is open — and out comes another masterpiece.", "If he's MOTM, it's because he conducted, played 30 yards from goal, and made everyone else look better."],
    quietGame: ["Frustrated. Subbed. Walked off. Tomorrow's another day.", "Belgium's squad-chemistry issues bled into his form — the pundits all said it postgame.", "Marked into the ground — the doubles team did its job."],
    controversy: ["After the 0-0 with Croatia he publicly said the squad was 'too old' — the locker room never recovered.", "Chelsea's 2014 sale of him at 22 is a transfer-decision case study now — he was sold for £20m, City paid £55m a year later."],
    famousGameHint: ["Look up his Manchester City Premier League title runs — multiple, all decorated with his assists.", "His 2018 World Cup — Belgium's bronze, KDB at his international peak.", "The 2022 Croatia 0-0 — the postgame interviews were the headline, not the football."],
    opponentFlavor: {
      CAN: "Group-stage opener — Belgium won 1-0, KDB was fine but not magical.",
      MAR: "Group-stage 2-0 loss — Morocco's midfield smothered him.",
      CRO: "The 0-0 closer — and the postgame interview that defined the tournament.",
    },
    formerTeam: ["Genk → Chelsea (£7m, 2012) → Werder Bremen (loan) → Wolfsburg → Manchester City (£55m, 2015).", "The Chelsea sale at 22 is one of football's most-cited transfer mistakes."],
    rivalry: ["Manchester City-Liverpool was his daily life for half a decade.", "Belgium-Netherlands is in his bones."],
    milestones: ["Multiple Premier League titles with Manchester City.", "Champions League winner (2023).", "Bundesliga player of the year (2014/15)."],
    streakLines: ["Assist runs come in flurries — three across two weeks at City, then two quiet matches.", "His City form bleeds into Belgium's form — direct correlation."],
    salaryNarrative: ["At $49 PURPLE he's the value playmaker — Premier League MVP form at a Belgian price.", "PURPLE because Belgium's tournament struggled — his ceiling is higher than the card suggests."],
    teamContext: ["Belgium's playmaker across three World Cup cycles — 2014, 2018, 2022.", "Roberto Martínez built around him; the system worked until the 2022 squad imploded."],
    draftAndPath: ["Genk academy at 14 — Belgian football's traditional pipeline.", "Chelsea paid £7m for him at 21; sold him at 22; Manchester City paid £55m a year later.", "City have built a Premier League dynasty around him."],
  },

  // Wojciech Szczęsny — Poland GK $42 PURPLE — avgFP 24.5
  szczęsny: {
    nicknames: ["Wojciech", "WS1"],
    knownFor: "Poland's veteran keeper — Juventus' bedrock, Arsenal's prodigal son, the Messi-penalty saver.",
    salaryTier: "star",
    tier1: ["The kind of keeper who saves Lionel Messi penalties — and yes, that's a thing he did.", "Poland's number 1 across three World Cup cycles — that's consistency.", "Juventus' goalkeeper of choice for half a decade — the Allianz Arena trusted him."],
    tier2: ["Came through Legia Warsaw — Poland's traditional capital club.", "Arsenal signed him at 16; lost him at 25 in a public falling-out with Wenger.", "Roma made him a Serie A name; Juventus made him a champion."],
    tier3: ["Smoked a cigarette in the Arsenal showers after a 2-0 loss to Southampton — the moment that became a meme and ended his Arsenal career.", "His father Maciej was also a Poland goalkeeper — family business."],
    overperform: ["When Szczęsny is hot, the goal disappears.", "Saved two penalties from Messi at the World Cup — that's a Wikipedia entry.", "Tournament hero hands — punched above his weight all match."],
    underperform: ["Conceded a soft one — even Wojciech has those nights.", "Couldn't hold the cross — the small detail that became the goal.", "The defense had a rough one and so did he."],
    onPace: ["Standard Szczęsny — calm, positioned, hard to beat from anywhere.", "Made the saves he was supposed to and found the long pass when needed.", "Reliable. Composed. The Polish back line's safety blanket."],
    loosePlay: ["Punched when he should have caught — minor wobble.", "A long ball that didn't quite go where he intended.", "Caught off his line — even the cool ones get the angle wrong once."],
    defensive: ["Commands his box like a captain.", "Two-handed catch in traffic — exactly what you want from your keeper.", "Read the cross and snuffed it before the striker could meet it."],
    bigGame: ["SZCZĘSNY! HE SAVES MESSI! HE SAVES MESSI!", "Tournament keeper performance — pinned in highlight reels for a generation.", "Penalties saved, glory earned, history made."],
    quietGame: ["Quiet day — the back four did their job and Szczęsny did his job, which was supervision.", "Two saves and a clean sheet — a low-event but high-value night.", "Comfortable. Composed. Asked little, delivered everything."],
    controversy: ["The 2014 Arsenal 'shower cigarette' incident effectively ended his Arsenal career — and made him a meme.", "His public criticism of Polish football federation politics has earned him both admirers and detractors at home."],
    famousGameHint: ["Look up Poland vs Argentina in the 2022 group stage — Szczęsny saved a Messi penalty.", "The 2014 Arsenal cigarette incident — the cultural moment.", "His Juventus Serie A title runs — multiple Scudetti."],
    opponentFlavor: {
      ARG: "Saved a Messi penalty — and Argentina still won 2-0. Both stories happened.",
      MEX: "0-0 group-stage opener — Lewandowski missed a penalty, Szczęsny did his.",
      KSA: "Group-stage 2-0 win — clean sheet, professional shift.",
      FRA: "Round-of-16 — France won 3-1, Szczęsny couldn't stop the rocket.",
    },
    formerTeam: ["Legia Warsaw → Arsenal (2006-15) → Brentford (loan) → Roma (loan, then permanent) → Juventus (2017-).", "Arsenal's Polish keeper for a decade — until the cigarette."],
    rivalry: ["Poland-Russia at international level (when scheduled).", "Juventus-Inter and Juventus-Milan at club level."],
    milestones: ["Multiple Serie A titles with Juventus.", "Coppa Italia silverware.", "Poland's all-time appearance leader for goalkeepers."],
    streakLines: ["Penalty-save streak in 2022 — saved Messi, faced Lewandowski's training drills daily.", "His Juventus form bled into Poland's tournament rhythm."],
    salaryNarrative: ["At $42 PURPLE he's the value GK — Juventus consistency at a Polish price.", "PURPLE because Poland's defensive output is mid-tier; the saves spike the average."],
    teamContext: ["Poland's defensive identity in 2022 was built around him — Lewandowski up top, Szczęsny at the back.", "Czesław Michniewicz's tactical setup needed a keeper who could play one-touch under pressure — Szczęsny delivered."],
    draftAndPath: ["Legia Warsaw youth — Polish football's traditional capital.", "Arsenal signed him at 16 — early apex.", "Juventus made him a Serie A champion at 27."],
    signatureGames: [
      { date: "2022-11-30", opponent: "ARG", fp: 40, line: "Saved a Messi penalty — and Argentina still won. The save will outlast the result." },
      { date: "2022-12-04", opponent: "FRA", fp: 20, line: "Round-of-16 — France won 3-1, Szczęsny couldn't stop the Mbappé rocket." },
    ],
  },

  // Lawrence Ati-Zigi — Ghana GK $37 BLUE — avgFP 21
  "ati-zigi": {
    nicknames: ["Lawrence", "LAZ"],
    knownFor: "Ghana's number 1 keeper — St. Gallen's Swiss-league bedrock, Black Stars' defensive last line.",
    salaryTier: "role",
    tier1: ["Ghana's number 1 across the 2022 cycle — that's a senior international.", "St. Gallen's Swiss Super League regular — the Eastern European pipeline made flesh.", "When Ghana need a save, they look at one man."],
    tier2: ["Came through African football's youth scouting networks — Liberty Professionals in Accra to Sochaux in France.", "St. Gallen made him a Swiss Super League starter — five-plus seasons of top-flight minutes.", "Ghana's 2022 World Cup keeper — the Otto Addo era's defensive last line."],
    tier3: ["Born in Accra — Ghanaian football's capital.", "Has a French passport from his Sochaux youth days — but Ghana was always the choice."],
    overperform: ["When Ati-Zigi is hot, Ghana's back line breathes.", "Five saves and a clean sheet — keeper hero hands.", "The kind of night that gets you a phone call from a bigger club."],
    underperform: ["Conceded the soft one — the small detail that becomes the goal.", "Couldn't hold the cross — credit the attacker, but tape will be reviewed.", "The defense had a rough one and so did he."],
    onPace: ["Standard Ati-Zigi — calm, positioned, hard to beat from anywhere.", "Made the saves he was supposed to and found the long pass when needed.", "Reliable. Composed. Ghana's safety blanket."],
    loosePlay: ["Punched when he should have caught — minor wobble.", "A long ball that didn't quite go where he intended.", "Caught off his line — the angle was wrong."],
    defensive: ["Commands his box — that's the senior international.", "Two-handed catch in traffic — exactly what you want.", "Read the cross and snuffed it before the striker could meet it."],
    bigGame: ["ATI-ZIGI! GHANA'S WALL! Africa's bedrock!", "Tournament keeper performance — saves, organization, command.", "When Ghana need it, he provides it."],
    quietGame: ["Quiet day — the back four did their job and Ati-Zigi did his job, which was supervision.", "Two saves and a clean sheet — a low-event but high-value night.", "Comfortable. Composed. Asked little, delivered everything."],
    controversy: ["Ghana's 2022 squad chemistry was reportedly fraught — multiple senior leaks suggested camp tension.", "Some Ghanaian fans wanted Richard Ofori as number 1 — the rotation debate hung over Otto Addo."],
    famousGameHint: ["Look up Ghana vs South Korea in 2022 — Ati-Zigi conceded three but Ghana won 3-2.", "His Swiss Super League performances at St. Gallen — five-plus seasons of top-flight minutes.", "The Uruguay grudge match — Ghana lost, the 2010 ghosts won."],
    opponentFlavor: {
      KOR: "3-2 win — Ghana's most polished tournament performance, Ati-Zigi did his part.",
      POR: "Group-stage loss — Cristiano scored, Ati-Zigi couldn't stop everything.",
      URU: "The grudge match — Ghana lost, the 2010 ghosts haunted again.",
    },
    formerTeam: ["Liberty Professionals (Accra) → Sochaux (France youth) → Sochaux first team → St. Gallen (Switzerland).", "St. Gallen made him a Swiss Super League regular for half a decade."],
    rivalry: ["Ghana-Uruguay — the 2010 quarterfinal still scars every Black Star fan."],
    milestones: ["Ghana's 2022 World Cup number 1.", "Swiss Super League regular for half a decade.", "African Cup of Nations participation."],
    streakLines: ["Ati-Zigi's good runs come in chunks — three clean sheets, then a wobble.", "St. Gallen form is his form — Swiss league consistency."],
    salaryNarrative: ["At $37 BLUE he's the value GK — Swiss-league consistency at a Ghana price.", "BLUE because the WC keeper market is cheap. Productive when Ghana defend well."],
    teamContext: ["Ghana's defensive identity in 2022 was built on him plus the Salisu-Amartey centreback pairing.", "Otto Addo's tactical setup needed a keeper who could play under African-football pressure."],
    draftAndPath: ["Liberty Professionals in Accra — Ghana's youth pipeline.", "Sochaux took him to France's lower divisions at 19.", "St. Gallen in Switzerland gave him top-flight minutes — and he never let go."],
  },
