  // Jean-Charles Castelletto — Cameroon DEF $60 ORANGE — avgFP 50
  castelletto: {
    nicknames: ["JCC", "Charles"],
    knownFor: "Cameroon's centre-back anchor — French-born, Indomitable Lion by choice.",
    salaryTier: "star",
    tier1: ["When Cameroon's back four is calm, it's because Castelletto is calm.", "The kind of centre-back who turns chaos into a clean-up job.", "Old-school stopper with modern legs."],
    tier2: ["Born in Paris, came up through Saint-Étienne's youth ranks before declaring for Cameroon.", "Settled into Nantes as a Ligue 1 regular — the springboard to international football.", "The Indomitable Lions back line was rebuilt around him in the run-up to Qatar."],
    tier3: ["Cameroon's federation has a complicated relationship with French-born players — Castelletto's commitment was never in doubt.", "Played alongside Onana in the dressing room and against Onana on the pitch in the same tournament — only at this World Cup."],
    overperform: ["Cleared his lines, scored a goal, owned the back third — that's a centre-back's dream shift.", "When Castelletto leads, the back line follows.", "The kind of game that turns scouts' heads in January."],
    underperform: ["Caught flat-footed on a runner — every defender has one of those.", "The marker got behind him once, and the goal came from it.", "Off the pace tonight — Cameroon's back line missed the anchor."],
    onPace: ["Standard Castelletto shift — headers won, lines held, no fuss.", "Read the cross, won the duel, cleared the danger. Boring is a defender's compliment.", "Did his job. The way you want a centre-back to do his job."],
    loosePlay: ["A heavy clearance straight to the opposition midfielder — they all happen.", "Booked for a late tackle — frustration creeping in.", "Played a pass into traffic — a rare lapse from a calm head."],
    defensive: ["Wins the aerial, holds the line, organizes the four — the complete centre-back shift.", "Slide tackle in the box — emergency defending done right.", "Pressed the striker into a hurried touch and won the second ball."],
    bigGame: ["Headed home the goal that beat Brazil — Cameroon's improbable group-stage win.", "He scored against Brazil. He scored AGAINST BRAZIL. Read that again.", "The defender's goal that wrote a chapter in Cameroon's World Cup history."],
    quietGame: ["Untested for long stretches — Cameroon's midfield kept the ball away from him.", "Subbed late with the result safe.", "A quiet 90 — exactly what a centre-back wants."],
    controversy: ["Cameroon's federation drama in 2022 nearly derailed the squad — he stayed above it.", "The Onana fallout cast a shadow over the team; Castelletto kept his head down."],
    famousGameHint: ["Look up Cameroon's win over Brazil — Castelletto's header changed the narrative of a tournament.", "His Switzerland matchup in the group stage was a centre-back masterclass on the losing side."],
    opponentFlavor: {
      BRA: "Headed home the winner against Brazil — Cameroon's most famous group-stage result of the tournament.",
      SUI: "Group-stage opener — Cameroon lost 1-0 but his defending kept it that close.",
      SRB: "The 3-3 thriller — defended through chaos, held the line when it mattered.",
    },
    formerTeam: ["Saint-Étienne youth, then Nantes via Brest — a French Ligue 1 lifer.", "The Nantes back line was built around him for years before the World Cup."],
    teamContext: ["Cameroon's defensive identity in 2022 ran through him and Castelletto in front of Onana — until Onana left the squad.", "The Indomitable Lions' shape was four-at-the-back with him as the right-side organizer."],
    salaryNarrative: ["At $60 ORANGE he's the priciest defender on the board — the goal against Brazil paid the salary in one game.", "ORANGE because of the bigGame ceiling, not the floor — defenders don't usually price like this."],
    draftAndPath: ["Saint-Étienne academy, loaned and traded across France's lower divisions before settling at Nantes.", "Declared for Cameroon at 23 after years of dual eligibility chatter."],
  },

  // Dušan Tadić — Serbia MID $59 ORANGE — avgFP 42.9
  tadić: {
    nicknames: ["Duško", "The Captain"],
    knownFor: "Serbia's captain and creative engine — Ajax legend who set Eredivisie records.",
    salaryTier: "star",
    tier1: ["The captain's armband fits him like a tailored suit.", "When Tadić has space, the whole midfield bends to his vision.", "Serbia's metronome — the rhythm starts and ends with him."],
    tier2: ["From Vojvodina to Groningen to Twente to Southampton — and finally to Ajax, where he became a legend.", "Lifted the Eredivisie, scored in a Champions League semifinal, and captained Serbia to a World Cup.", "Ajax's player of the year three times — that doesn't happen by accident."],
    tier3: ["Famously turned around for the Tottenham Champions League semifinal goal in 2019 — the chip past Lloris.", "His left foot has been Serbia's primary creative outlet for over a decade."],
    overperform: ["When Tadić runs the midfield, Serbia look like a top-eight team.", "Set-piece deliveries that look like they're on a string — that's tonight's vintage.", "The captain stamped his authority on this game from minute one."],
    underperform: ["Even captains have nights where the legs say no.", "Marked tightly — and when Tadić can't find space, Serbia's attack stalls.", "Frustrated tonight — the body language said everything."],
    onPace: ["Standard Tadić shift — a creator's pass, a set piece delivered, the captain's tempo.", "Conducted the midfield. Did the unglamorous work. Earned his keep.", "The maestro at his desk — Serbia's tempo, Tadić's metronome."],
    loosePlay: ["Tried a flick under pressure that didn't come off.", "Booked for a tactical foul — a captain's necessary sin.", "Lost the ball in midfield — and the press punished it."],
    defensive: ["Tracked back when needed — captain's responsibility.", "Pressed the centre-back into a hurried clearance.", "Won a tackle in his own half — not flashy, but useful."],
    bigGame: ["TADIĆ. The captain conducting his orchestra.", "This is the Ajax-form Tadić showing up for his country.", "Set-piece magic, creative passes, leadership — the complete captain's shift."],
    quietGame: ["Marked, doubled, denied space — Serbia's plan B isn't always there.", "Subbed at 75 — the captain saving energy.", "Quiet 90 — sometimes the maestro just doesn't get the ball."],
    controversy: ["Serbia's flag-and-banner political incidents have been a federation headache for years — he's stayed above the fray.", "The Kosovo political flag in the dressing room in 2022 created an international incident he didn't address publicly."],
    famousGameHint: ["Look up his Ajax run to the 2019 Champions League semifinal — the Tottenham game made him a global name.", "Serbia's 3-3 with Cameroon — Tadić's set pieces were the only reason Serbia got close to a result."],
    opponentFlavor: {
      BRA: "Group-stage 2-0 loss to Brazil — Tadić rarely got the ball in dangerous areas.",
      CMR: "The 3-3 thriller — captain's set-piece deliveries kept Serbia in the game.",
      SUI: "Eliminated by Switzerland — Serbia's exit was orchestrated through Tadić, just not the result he wanted.",
    },
    formerTeam: ["Vojvodina → Groningen → Twente → Southampton → Ajax — the slow climb to the top of European football.", "Ajax made him their captain and their player of the year three times.", "Fenerbahçe in his thirties — the elder-statesman move."],
    rivalry: ["Serbia-Croatia is the deepest derby in his region — politically and footballingly fraught."],
    milestones: ["Three-time Ajax Player of the Year.", "Eredivisie title and Cup with Ajax.", "Serbia's all-time top assist provider."],
    salaryNarrative: ["At $59 ORANGE he's pricier than his floor would suggest — but his ceiling on a good day justifies it.", "ORANGE because of the captain's tax — Serbia's whole offense flows through him."],
    teamContext: ["Captained Serbia through the 2022 cycle — the squad's organizational center.", "Stojković's tactical setup needed a deep-lying creator — Tadić was the obvious answer."],
  },

  // Eden Hazard — Belgium MID $57 ORANGE — avgFP 41.4
  hazard: {
    nicknames: ["Eden", "The Magician"],
    knownFor: "Belgium's golden generation captain — once the best dribbler in Europe.",
    salaryTier: "star",
    tier1: ["When Hazard is on it, defenders just get out of the way.", "The Belgian magician — at his peak, only Messi danced like him.", "Captain of the most-talented Belgium squad of all time."],
    tier2: ["Lille to Chelsea was the Premier League's smoothest transition — two title-winning seasons.", "The €100m Real Madrid move that never quite worked — injuries, fitness, and timing all conspired.", "Belgium's golden generation captain through three tournaments — 2014, 2018, 2022."],
    tier3: ["Famously said he'd rather have a burger than do extra fitness work — the running joke of his Madrid tenure.", "His brother Thorgan was also at the Qatar World Cup — Belgium's footballing family."],
    overperform: ["When the magic returns, the whole stadium feels it.", "This is the Chelsea-form Hazard that broke Premier League defenses for years.", "Vintage Eden — a stepover, a body feint, a goal the keeper can't even see."],
    underperform: ["Even the magician has nights where the wand doesn't work.", "The legs aren't what they were — the Madrid years took something he hasn't gotten back.", "Subbed at 60' — frustrated, slow, mortal."],
    onPace: ["Standard Hazard shift — a flash of class, a creator's pass, a glimpse of the old days.", "The Belgium captain went through the motions efficiently.", "Did his job — even if the highlight reel was shorter than it used to be."],
    loosePlay: ["Heavy first touch — even the great ones lose it under tight marking.", "Tried a stepover that the defender read like a book.", "Lost in possession — a rarity at his peak, more common now."],
    defensive: ["Tracks back when he wants to — which, at this stage of his career, isn't always.", "Pressed the centre-back into a panicked clearance.", "Defensive contribution wasn't the headline — Hazard's never been that player."],
    bigGame: ["EDEN. EDEN HAZARD. The magician's wardrobe is open.", "This is the player Real Madrid paid €100m for — the rare night it shows up.", "Belgium's captain at his most magnetic."],
    quietGame: ["Marked out — Belgium's plan A stalled.", "Frustrated, subbed, watched the rest from the bench.", "The body wasn't there tonight — and at 31, that's the new normal."],
    controversy: ["The 'I prefer burgers to gym' quote followed him through his Madrid years.", "Belgium's golden generation never quite gelled — and he wore the captain's responsibility for it.", "Reportedly clashed with Roberto Martínez over fitness in the lead-up to Qatar."],
    famousGameHint: ["Look up his Chelsea years — 2014/15 PFA Player of the Year run was as good as Premier League wing play gets.", "Belgium's 2018 World Cup semifinal — Hazard was world-class through that tournament."],
    opponentFlavor: {
      CAN: "Group-stage opener — Belgium scraped a 1-0 win and Hazard didn't look right.",
      MAR: "The 2-0 loss to Morocco — captain's worst night of the tournament.",
      CRO: "Group-stage exit — Hazard subbed off, Belgium eliminated, the golden generation done."
    },
    formerTeam: ["Lille raised him — Ligue 1's best teenager for two seasons running.", "Chelsea bought him in 2012 — seven years, two Premier League titles, two Europa Leagues.", "Real Madrid paid €100m in 2019 — the move never delivered."],
    rivalry: ["Belgium-Netherlands is the Low Countries derby — fierce on both sides.", "Belgium's golden generation vs. France's golden generation defined late-2010s European football."],
    milestones: ["Two Premier League titles with Chelsea.", "PFA Player of the Year 2014/15.", "Belgium's all-time top assist provider."],
    salaryNarrative: ["At $57 ORANGE he's the captain's-ego price — pays for the name, not the 2022 form.", "Better days were $80; 2022 form is closer to $40 — the gap is the salary risk."],
    teamContext: ["Belgium's golden-generation captain — the responsibility weighed.", "Roberto Martínez's tactical setup hinged on him; in 2022, the system creaked."],
    draftAndPath: ["Belgian regional youth ranks; Lille at 16; Chelsea at 21; Real Madrid at 28.", "Retired from international football after Belgium's 2022 group-stage exit."],
  },

  // Carlos Henrique Casemiro — Brazil MID $54 ORANGE — avgFP 39.3
  casimiro: {
    nicknames: ["Casemiro", "Carlos Henrique", "The Tank"],
    knownFor: "Brazil's defensive midfield anchor — five Champions Leagues with Real Madrid.",
    salaryTier: "star",
    tier1: ["The midfielder every other midfielder wants behind them.", "Casemiro doesn't tackle — he detonates.", "If you build a midfield from scratch, you start with him."],
    tier2: ["Started at São Paulo, signed by Real Madrid at 21, lifted five Champions Leagues with Modrić and Kroos.", "United paid €70m in 2022 to fix their midfield — and for one season, he did exactly that.", "Brazil's anchor through three World Cups — 2014, 2018, 2022."],
    tier3: ["The Modrić-Kroos-Casemiro triangle is one of the most-decorated midfield trios in football history.", "Famously stoic — the on-pitch persona that earned him 'The Tank' across Brazilian media."],
    overperform: ["When Casemiro decides nobody passes through midfield, nobody passes through midfield.", "Scored AND tackled AND organized — the holding-mid hat trick.", "The kind of complete shift that wins Champions Leagues."],
    underperform: ["Even The Tank has nights where the legs are heavier than the body.", "Caught upfield on a counter — every defensive mid does it once a tournament.", "Yellow card in the first 20 — he played the rest of the game on a tightrope."],
    onPace: ["Standard Casemiro shift — three tackles, two interceptions, the pivot does the unglamorous work.", "Brazil's midfield ran because he ran the midfield.", "Did the work that doesn't make the highlights — and Brazil controlled the game because of it."],
    loosePlay: ["A heavy clearance into traffic — happens to every defensive mid once a match.", "Tactical foul, yellow card — the price of playing the position.", "Slipped at the wrong moment and the counter punished it."],
    defensive: ["Ball-winning at its purest — three tackles in the first 20 minutes set the tone.", "Reads the pass before it's played — that's positional intelligence.", "The reason Brazil's back four was rarely tested in 2022 — he ate the pressure first."],
    bigGame: ["CASEMIRO. The tank rolls.", "This is the kind of holding-mid performance that wins tournaments.", "Brazil's whole defensive shape ran through him tonight — and he ran it perfectly."],
    quietGame: ["Subdued — Brazil's midfield got bypassed and so did he.", "Off the pace tonight — and Brazil missed the anchor.", "Subbed at 75 with a yellow already in his pocket."],
    controversy: ["United's 2023/24 collapse with him in midfield raised questions about the Brazil legs.", "Saudi move in 2024 was the headline that ended his European chapter — he denied it was about money."],
    famousGameHint: ["Look up Real Madrid's 2014 Champions League run — Casemiro's emergence as a starter changed the team.", "Brazil's 2022 quarterfinal exit to Croatia — Casemiro's foul-and-yellow tightrope shaped the second half."],
    opponentFlavor: {
      SRB: "Group-stage opener — Brazil 2-0, Casemiro ate everything in midfield.",
      SUI: "His goal against Switzerland — long-range strike that won a tight group game.",
      KOR: "Round-of-16 dominance — Brazil 4-1, Casemiro coasted at 75% effort.",
      CRO: "Quarterfinal exit — Casemiro's tightrope game on a yellow card, eventually subbed.",
    },
    formerTeam: ["São Paulo academy, Real Madrid signed him in 2013 for €6m — the bargain of the decade.", "United paid €70m in 2022 — the move that fixed their midfield for one beautiful season.", "Saudi move in 2024 closed the European chapter."],
    rivalry: ["Brazil-Argentina is in his bones — the deepest South American derby."],
    milestones: ["Five Champions Leagues with Real Madrid (2014, 2016, 2017, 2018, 2022).", "Three La Liga titles.", "Copa América winner with Brazil in 2019."],
    streakLines: ["When Casemiro plays well, Brazil wins. The correlation is almost perfect.", "Five Champions League winning seasons — that's a streak nobody talks about because he made it look routine."],
    salaryNarrative: ["At $54 ORANGE he's the anchor-tax price — defensive mids don't price like this without a reason.", "ORANGE because his ceiling includes goals and assists, not just tackles."],
    teamContext: ["Brazil's midfield identity in 2022 was built around him — Paquetá and Fred ahead, Casemiro the foundation.", "Tite's tactical setup assumed Casemiro would eat the opposition's number 10. He usually did."],
    draftAndPath: ["São Paulo academy from 14, first-team debut at 18.", "Real Madrid bought him at 21 for €6m — became their starter by 2016.", "United paid €70m in 2022 — became their best midfielder overnight."],
    signatureGames: [
      { date: "2022-12-02", opponent: "SUI", fp: 60, line: "The long-range strike that won a tight Group G match — Casemiro the unlikely hero." },
    ],
  },

  // Luis Chávez — Mexico MID $53 ORANGE — avgFP 38.2
  chávez: {
    nicknames: ["Luis", "El Chavo"],
    knownFor: "Mexico's midfield engine — scorer of one of the great World Cup free kicks.",
    salaryTier: "star",
    tier1: ["When Chávez strikes a dead ball, you stop and watch.", "Mexico's midfield muscle — the kind of player Tata Martino built around.", "The free kick against Saudi Arabia is on every World Cup highlight reel."],
    tier2: ["Came through Pachuca's academy — one of Liga MX's most reliable production lines.", "Made his Mexico debut in 2021 and locked down a starting role within a year.", "The Qatar World Cup was his coming-out party on the global stage."],
    tier3: ["His free kick against Saudi Arabia in the group-stage finale was clocked at over 70 mph.", "Mexico's elimination on goal differential despite his goal made it the cruelest exit of the tournament."],
    overperform: ["When Chávez strikes from distance, the keeper just becomes a witness.", "Set-piece deliveries from range that keepers can only watch.", "This is the engine Mexico needed in midfield — finally producing on the biggest stage."],
    underperform: ["Box-to-box energy wasn't quite there tonight.", "Marked out of central areas — Mexico's midfield stalled with him.", "Off the pace — every midfielder has those nights."],
    onPace: ["Standard Chávez shift — covered ground, won duels, took his set pieces seriously.", "The midfield engine kept Mexico ticking over.", "Box-to-box discipline — exactly what the system needs."],
    loosePlay: ["Booked for a late challenge — the price of playing the engine role.", "Tried a long-range strike that ended up in the stands.", "Caught upfield on a counter — happens to every box-to-box mid."],
    defensive: ["Three tackles in midfield — Mexico's first line of defense.", "Tracked back to win a ball in his own third — engine-room shift.", "Pressed the opposition midfielder into a hurried clearance."],
    bigGame: ["CHÁVEZ. THE FREE KICK. INTO THE TOP CORNER.", "World Cup folklore right there — the strike that almost saved Mexico's tournament.", "This is what set-piece specialists dream of."],
    quietGame: ["Subdued — Mexico's midfield got bypassed.", "Quiet 90 — the system left him as the second option.", "Subbed at 70 — saving him for the next match."],
    controversy: ["Tata Martino's selection choices took criticism in Mexico — Chávez was rarely the target.", "Mexico's group-stage exit on goal differential was the country's most painful in decades — and he was the standout positive."],
    famousGameHint: ["Look up his free kick against Saudi Arabia — top corner from 35 yards out, one of the best dead balls of the tournament.", "His Argentina performance in the group stage — Mexico lost but Chávez was their best midfielder."],
    opponentFlavor: {
      POL: "Group-stage opener — 0-0, Chávez covered every blade of grass.",
      ARG: "Lost to Argentina 2-0 — Chávez was Mexico's best midfielder on a tough night.",
      KSA: "The free-kick goal that nearly saved Mexico's campaign — the kind of strike that lives forever.",
    },
    formerTeam: ["Pachuca academy graduate — Liga MX's most reliable producer.", "Joined Dynamo Houston in MLS in 2024 — the next chapter."],
    rivalry: ["Mexico-USA is one of football's fiercest border rivalries."],
    salaryNarrative: ["At $53 ORANGE he's priced for his ceiling, not his floor — the free-kick goal alone justified one game's salary.", "ORANGE because of the set-piece dimension — Mexico's primary dead-ball threat."],
    teamContext: ["Mexico's midfield engine in 2022 — paired with Edson Álvarez behind him.", "Tata Martino's system relied on him for box-to-box energy and set-piece delivery."],
    signatureGames: [
      { date: "2022-11-30", opponent: "KSA", fp: 65, line: "The free-kick top-corner thunderbolt — the goal Mexico will replay for a generation." },
    ],
  },

  // Axel Disasi — France DEF $54 ORANGE — avgFP 37.2
  disasi: {
    nicknames: ["Axel"],
    knownFor: "France's quietly reliable centre-back — Monaco's defensive anchor in 2022.",
    salaryTier: "star",
    tier1: ["The kind of centre-back who shows up, plays the position, and goes home.", "France's defensive depth was elite — Disasi was a reason why.", "Solid is a compliment for a centre-back, and he's nothing but solid."],
    tier2: ["Came through Paris FC and Reims before Monaco bought him — the French Ligue 1 development pipeline.", "Made his France debut at 24 — late by golden-generation standards but earned every cap.", "Chelsea paid £38m for him in 2023 — the Premier League finally noticed."],
    tier3: ["Born in Gonesse, the same suburb that produced a long line of French Ligue 1 centre-backs.", "Famously calm in possession — the kind of CB who can play out from the back without panic."],
    overperform: ["Headers won, lines held, lines moved — the complete shift.", "When Disasi is on it, France's back four looks unbreakable.", "Cleared two off the line — the unsung centre-back's afternoon."],
    underperform: ["A rare lapse — the marker got behind him and the goal came from it.", "Caught flat-footed on a runner — happens once a tournament.", "Off the pace — and France's back line missed the anchor."],
    onPace: ["Standard Disasi shift — quiet, organized, no fuss.", "Read the cross, won the duel, moved on.", "Did his job — exactly what France needed from the third centre-back."],
    loosePlay: ["A heavy clearance into traffic — minor wobble.", "Tactical foul, yellow card — the price of position.", "Misjudged the bounce — every defender does it once."],
    defensive: ["Three headers won, two clearances, no fuss.", "Slide tackle in the box — emergency defending done right.", "Pressed the striker into a hurried first touch."],
    bigGame: ["Disasi against Argentina in the final — held his own against Messi for 90 minutes plus extra time.", "France's defensive resilience in 2022 had Disasi at the center of it.", "Big-stage debut, big-stage performance — that's the player."],
    quietGame: ["Untested for long stretches — France's midfield kept the ball away.", "Quiet 90 — exactly what a centre-back wants.", "Cruise control — France's back four did its job in the easier games."],
    controversy: ["Limited public profile — Disasi keeps his head down.", "France's federation has had drama elsewhere; he's stayed clear of it."],
    famousGameHint: ["Look up his France 2022 World Cup final appearance — held his own against Messi and Argentina.", "His Monaco performances in 2022/23 caught Chelsea's eye — £38m followed."],
    opponentFlavor: {
      ARG: "The 2022 final — Disasi played 90+ minutes against Messi and didn't break.",
      MAR: "Semifinal clean sheet against Morocco — France's defensive shape held.",
      ENG: "Quarterfinal — France defended deep and held on, Disasi part of the wall.",
      POL: "Round-of-16 — France 3-1, Disasi cleared everything in the first half.",
      DEN: "Group-stage 2-1 win — Disasi solid through the second half.",
      AUS: "Group-stage opener — France 4-1 in a comfortable shift.",
      TUN: "The 1-0 loss — France rotated heavily, Disasi was a victim of system experimentation."
    },
    formerTeam: ["Paris FC academy, Reims, Monaco — the slow climb through Ligue 1.", "Chelsea bought him in 2023 for £38m — the Premier League finally noticed."],
    salaryNarrative: ["At $54 ORANGE he's priced for France's defensive role — third CB pricing.", "ORANGE because France always reaches the latter stages — defensive points accumulate."],
    teamContext: ["France's defensive depth in 2022 — Konaté, Varane, Disasi rotated through the centre-back pairing.", "Deschamps' tactical setup needed CBs who could play out from the back — Disasi was a fit."],
    draftAndPath: ["Paris FC youth, Reims signed him at 19, Monaco at 22.", "Chelsea bought him at 25 — £38m in 2023."],
  },

  // Mathías Olivera — Uruguay DEF $54 ORANGE — avgFP 36.7
  olivera: {
    nicknames: ["Mathías"],
    knownFor: "Uruguay's left-back — Napoli's Scudetto-winning fullback.",
    salaryTier: "star",
    tier1: ["When Olivera bombs forward, the whole left flank moves with him.", "Uruguay's modern fullback — the kind of athlete the position demands now.", "Napoli paid for the full package — defending and attacking, both ends of the pitch."],
    tier2: ["Came up through Nacional in Montevideo before Getafe took him to La Liga.", "Napoli signed him in 2022 — and he won a Scudetto in his first season.", "Locked down the Uruguay left-back spot at 24 — the reward for years of consistency."],
    tier3: ["Part of the Napoli squad that won their first league title since Maradona — historic season.", "His ball-carrying from deep is one of Uruguay's primary attacking outlets."],
    overperform: ["When Olivera's running the touchline, the wide channel becomes Uruguay's possession.", "Three tackles, an assist, two key passes — the modern fullback's full shift.", "This is the Napoli-Scudetto form bleeding into international football."],
    underperform: ["Caught upfield on a counter — every attacking fullback's risk.", "Beaten on the byline once — and the cross became a goal.", "Off the pace — and Uruguay's left flank looked exposed."],
    onPace: ["Standard Olivera shift — covered the touchline both ways.", "Bombed forward when the moment was right, defended when it wasn't.", "Two-way fullback discipline — exactly the modern model."],
    loosePlay: ["A loose pass under pressure — the press found him caught upfield.", "Booked for a tactical foul on the counter.", "Heavy first touch in a dangerous area — minor wobble."],
    defensive: ["Wins the 1v1 down the touchline.", "Tracks the runner all the way back — fullback's responsibility.", "Slide tackle on the byline to deny the cross."],
    bigGame: ["Olivera's Napoli-Scudetto form in a Uruguay shirt — the full package.", "Bombed up and down the touchline like a man possessed.", "The kind of complete fullback shift that wins matches."],
    quietGame: ["Quiet 90 — Uruguay's midfield kept the ball away from his flank.", "Untested defensively — the back four did their job.", "Subbed at 75 — saving him for the next round."],
    controversy: ["The Uruguay-Ghana group-stage incident in Qatar — Olivera was on the field for the chaos at full-time.", "Uruguay's federation drama in 2022 was a backdrop he stayed clear of."],
    famousGameHint: ["Look up his Napoli 2022/23 season — the Scudetto-winning campaign.", "His Uruguay group-stage games in Qatar — the left flank was his territory."],
    opponentFlavor: {
      KOR: "Group-stage 0-0 — Olivera contained the right wing all night.",
      POR: "Lost to Portugal 2-0 — Olivera tested by Bernardo Silva.",
      GHA: "The 2-0 win that wasn't enough — Uruguay went out on goal difference, the post-match scenes were ugly.",
    },
    formerTeam: ["Nacional Montevideo academy, Getafe in La Liga, Napoli for the Scudetto.", "Napoli's first league title since Maradona was the medal of his life."],
    rivalry: ["Uruguay-Argentina is South America's deepest rivalry — Olivera's grown up watching it.", "Uruguay-Ghana has bad blood from 2010 and 2022 — the Suárez incident still echoes."],
    salaryNarrative: ["At $54 ORANGE he's the modern-fullback price — assists and clean sheets both possible.", "ORANGE because Uruguay's defensive ceiling assumes him at his Napoli-form best."],
    teamContext: ["Uruguay's left-back nailed down — the position had been a revolving door before him.", "Diego Alonso's tactical setup wanted bombing-forward fullbacks; Olivera delivered."],
    draftAndPath: ["Nacional Montevideo academy graduate, Getafe at 22, Napoli at 24.", "Won a Scudetto in his first Napoli season — the dream debut campaign."],
  },

  // Youssef Msakni — Tunisia MID $50 PURPLE — avgFP 36.1
  msakni: {
    nicknames: ["Msakni", "The Captain"],
    knownFor: "Tunisia's captain and creative talisman — the country's biggest football star of the era.",
    salaryTier: "star",
    tier1: ["Tunisia's captain — the man the country watches when the camera cuts away.", "When Msakni's on the ball, every Tunisian fan stops what they're doing.", "The technical heart of a generation of Carthage Eagles."],
    tier2: ["Esperance de Tunis raised him; Lekhwiya in Qatar paid him; the Gulf circuit defined his club career.", "Captained Tunisia at three Africa Cup of Nations and the 2022 World Cup.", "Tunisia's most recognizable footballer of the 2010s and 2020s."],
    tier3: ["His goal against France in Qatar was disallowed by VAR for offside — the most painful what-if of the tournament.", "Plays in the Qatari Stars League at the height of his career — money and family stability over Europe."],
    overperform: ["When Msakni shines, Tunisia shines.", "The captain's assist threaded the defense — vintage creative work.", "This is the version Tunisia has been waiting for — the Africa Cup form on a global stage."],
    underperform: ["Marked tightly — Tunisia's plan A often runs out when Msakni's contained.", "Frustrated tonight — the legs and the time both running short.", "Captain's worst night — the body language said everything."],
    onPace: ["Standard Msakni shift — a creator's pass, set pieces taken seriously, captain's tempo.", "Conducted the midfield. Did the unglamorous work.", "The maestro at his desk — Tunisia's tempo, Msakni's metronome."],
    loosePlay: ["Tried a flick under pressure that didn't come off.", "Lost the ball in midfield — the press punished it.", "A tactical foul — the captain's necessary sin."],
    defensive: ["Tracks back when needed — captain's responsibility.", "Pressed the centre-back into a panicked clearance.", "Won a tackle in his own half — useful, unflashy."],
    bigGame: ["MSAKNI. THE CAPTAIN. Tunisia's beating heart.", "His goal against France that VAR took away — the cruellest cut of the tournament.", "Africa Cup-form Msakni on a World Cup stage."],
    quietGame: ["Marked, doubled, denied space — Tunisia's plan B isn't always there.", "Subbed at 75 — captain saving energy.", "Quiet 90 — sometimes the maestro just doesn't get the ball."],
    controversy: ["Tunisia's federation politics have been complicated — Msakni stayed above them.", "His Qatari club career drew criticism in Europe — he's never apologized for it."],
    famousGameHint: ["Look up Tunisia's group-stage game against France — Msakni's disallowed goal is the moment to find.", "His Africa Cup of Nations runs across the 2010s — the captain at his peak."],
    opponentFlavor: {
      DEN: "Group-stage 0-0 draw — Tunisia's dogged defending had Msakni at the heart of it.",
      AUS: "Lost to Australia — Tunisia's most disappointing 90 of the tournament.",
      FRA: "The 1-0 win that wasn't enough — Msakni's disallowed goal was the moment.",
    },
    formerTeam: ["Esperance de Tunis raised him, Lekhwiya/Al-Duhail in Qatar paid him for most of his career.", "Brief Eupen stint in Belgium was the closest he came to a European top league."],
    rivalry: ["Tunisia-Algeria is North Africa's deepest derby."],
    milestones: ["Tunisia's all-time top scorer.", "Three Africa Cup of Nations appearances as captain.", "Most-capped Tunisian footballer of his generation."],
    salaryNarrative: ["At $50 PURPLE he's the captain's tax for a tier-2 nation — Tunisia's whole offense flows through him.", "PURPLE because Tunisia's ceiling is limited; ORANGE on individual nights."],
    teamContext: ["Tunisia's captain and offensive identity through three tournament cycles.", "Kadri Jalel's tactical setup needed a deep-lying creator — Msakni was always the answer."],
  },

  // Mehdi Taremi — Iran FWD $49 PURPLE — avgFP 35.6
  taremi: {
    nicknames: ["Mehdi"],
    knownFor: "Iran's number 9 — the Porto striker who thrived in the Champions League.",
    salaryTier: "star",
    tier1: ["When Taremi gets a half-yard, the half-yard is enough.", "Iran's most complete striker — the kind of number 9 that Champions League nights are written about.", "If you've watched Porto in Europe, you've watched Taremi play big."],
    tier2: ["Came up through Iran's domestic leagues — Persepolis was the springboard to Europe.", "Rio Ave loan in Portugal was the breakthrough — Porto bought him in 2020.", "Inter Milan signed him on a free in 2024 — the final stop before international football's twilight."],
    tier3: ["Famously prolific in the Champions League — goals against Chelsea, Atlético, and others.", "Iran's 2022 World Cup squad rallied around him as the senior creative force in attack."],
    overperform: ["When Taremi finishes, the keeper just becomes a witness.", "Brace and an assist — the complete striker's shift.", "This is the Porto-Champions League form on the World Cup stage."],
    underperform: ["Marked tightly — Iran's plan A stalled.", "Couldn't find his shot — even the great strikers have those nights.", "Frustrated, subbed, tomorrow's another match."],
    onPace: ["Standard Taremi shift — a goal threat every time the ball came in.", "Held the ball up, brought the midfield in — the centre-forward's necessary work.", "Did his job — got his goal, hit the post once."],
    loosePlay: ["Heavy first touch in the box — happens to every striker.", "Offside three times — the runner's price.", "Lost the ball under pressure — minor lapse."],
    defensive: ["Pressed the keeper into a hurried clearance.", "Tracked back to win a ball in his own half — captain-class effort.", "Won the header in his own box — defending corners is part of the job."],
    bigGame: ["TAREMI. THE STRIKE. Iran's beating heart.", "His goals against Wales were the moment Iran believed.", "Champions League-form Taremi on the World Cup stage."],
    quietGame: ["Marked out — Iran's attack stalled.", "Subbed at 75 — frustrated, slow.", "Quiet 90 — and Iran's chances dried up with him."],
    controversy: ["The Iranian players' decision not to sing the anthem in 2022 was a federation-level issue — Taremi was part of the squad's silent stand.", "Iran's federation has been difficult — Taremi stayed publicly neutral."],
    famousGameHint: ["Look up his goals against Wales in the 2022 group stage — the 90+ minute drama that lifted a nation briefly.", "His Champions League goals for Porto across 2020-23 — the striker's actual peak."],
    opponentFlavor: {
      ENG: "The 6-2 group-stage opener — Taremi's brace from a losing position.",
      WAL: "The 2-0 stoppage-time win — Iran's most joyful World Cup moment.",
      USA: "The 1-0 loss that ended Iran's tournament — Taremi quiet on a tight night.",
    },
    formerTeam: ["Persepolis academy, Rio Ave loan, Porto's franchise striker for four seasons.", "Inter Milan in 2024 — the elder-statesman Italian move."],
    milestones: ["Porto's leading European goalscorer in the Taremi era.", "Iran's primary international striker for the 2022 cycle."],
    salaryNarrative: ["At $49 PURPLE he's the value-for-money pick at striker — Champions League form on a tier-2 national team budget.", "PURPLE because Iran's ceiling is limited; the goals come anyway."],
    teamContext: ["Iran's number 9 and creative anchor — the team played to him.", "Carlos Queiroz's tactical setup ran through Taremi as the deep-lying-and-finishing fulcrum."],
    signatureGames: [
      { date: "2022-11-21", opponent: "ENG", fp: 55, line: "Brace against England in the 6-2 opener — Iran lost, but Taremi's stock rose." },
    ],
  },

  // Ellyes Skhiri — Tunisia MID $48 PURPLE — avgFP 34.8
  skhiri: {
    nicknames: ["Ellyes"],
    knownFor: "Tunisia's midfield engine — Bundesliga's quietly elite ball-winner.",
    salaryTier: "role",
    tier1: ["The midfielder you only notice when he's not there.", "Tunisia's midfield runs through him — the engine room incarnate.", "Bundesliga-quality ball-winning in a Carthage Eagles shirt."],
    tier2: ["Born in Lunel, France; chose Tunisia at the youth level after Köln gave him his Bundesliga debut.", "Köln's player of the year in 2022/23 — Frankfurt paid for him on a free in 2023.", "Locked down Tunisia's holding-mid spot through the Qatar cycle."],
    tier3: ["Famously calm in possession — the kind of mid who can play under pressure without panic.", "Bundesliga's underrated ball-winner of the early 2020s — Frankfurt got the bargain of the year."],
    overperform: ["When Skhiri runs the engine room, Tunisia's midfield ticks over.", "Three tackles, two interceptions, an assist — the complete shift.", "The Köln-form Skhiri showing up for Tunisia."],
    underperform: ["Even engines run hot — and tonight the legs were heavier.", "Caught upfield on a counter — once a tournament for every B2B mid.", "Yellow card in the first 20 — played the rest on a tightrope."],
    onPace: ["Standard Skhiri shift — covered the ground, won the duels, played the simple pass.", "Tunisia's midfield kept ticking because he kept ticking.", "The unglamorous engine room — exactly what the system needs."],
    loosePlay: ["A heavy clearance into traffic — minor lapse.", "Tactical foul, yellow card — the price of position.", "Slipped at the wrong moment — the counter punished it."],
    defensive: ["Three tackles, two interceptions — pure ball-winning shift.", "Reads the pass before it's played — that's positional intelligence.", "Pressed the centre-back into a panicked clearance."],
    bigGame: ["SKHIRI. The engine room is on fire.", "Tunisia's midfield ran through him tonight — and he ran it perfectly.", "The kind of complete-midfielder shift that doesn't make highlights but wins matches."],
    quietGame: ["Subdued — Tunisia's midfield got bypassed.", "Off the pace tonight — and Tunisia missed the engine.", "Subbed at 75 with a yellow already in the pocket."],
    controversy: ["His decision to play for Tunisia over France raised eyebrows — vindicated by his role at the World Cup.", "Köln's relegation in 2023 was a backdrop he handled professionally."],
    famousGameHint: ["Look up Tunisia's 1-0 win over France in the 2022 group stage — Skhiri's engine-room shift was the foundation.", "His Köln 2022/23 season — Bundesliga player-of-the-year level work."],
    opponentFlavor: {
      DEN: "Group-stage 0-0 — Skhiri's defensive shift was the foundation.",
      AUS: "Lost to Australia — Tunisia's midfield stalled and so did he.",
      FRA: "The 1-0 win that wasn't enough — Skhiri's defensive work locked it down.",
    },
    formerTeam: ["Montpellier youth, Köln from 2019, Frankfurt from 2023 on a free.", "Bundesliga's underrated ball-winner of his era."],
    salaryNarrative: ["At $48 PURPLE he's the engine-room price — defensive mid value pick.", "PURPLE because Tunisia's ceiling is limited; the work shows up regardless."],
    teamContext: ["Tunisia's midfield base in 2022 — Skhiri behind, Msakni ahead.", "Kadri Jalel's tactical setup needed a holding-mid who could play out — Skhiri delivered."],
    draftAndPath: ["Montpellier academy, Köln debut at 24, Frankfurt at 28.", "France-born; chose Tunisia at the youth level."],
  },

  // Silvan Widmer — Switzerland DEF $49 PURPLE — avgFP 33.1
  widmer: {
    nicknames: ["Silvan"],
    knownFor: "Switzerland's right-back — Mainz's Bundesliga regular and Swiss steady hand.",
    salaryTier: "role",
    tier1: ["Switzerland's right-back nailed down — quiet, reliable, two-way.", "When Widmer bombs forward, the right flank moves with him.", "The kind of fullback every coach wants — does the job, takes no headlines."],
    tier2: ["Came up through Aarau in Switzerland; FC Aarau to Udinese to Basel to Mainz — the slow climb.", "Mainz's right-back since 2021 — Bundesliga regular at the senior level.", "Switzerland's right-back through the 2022 cycle — locked it down at 29."],
    tier3: ["Famously consistent — the kind of player whose Bundesliga rating barely moves match-to-match.", "Switzerland's tactical setup at Qatar relied on him to balance the right flank both ways."],
    overperform: ["When Widmer runs the touchline, the right flank becomes Switzerland's possession.", "An assist, two tackles, a clean sheet — the complete fullback shift.", "Mainz-form Widmer in a Switzerland shirt."],
    underperform: ["Caught upfield on a counter — the attacking fullback's risk.", "Beaten on the byline once — and the cross became a goal.", "Off the pace — Switzerland's right flank looked exposed."],
    onPace: ["Standard Widmer shift — covered the touchline both ways.", "Bombed forward when the moment was right, defended when it wasn't.", "Two-way fullback discipline."],
    loosePlay: ["A loose pass under pressure — minor wobble.", "Booked for a tactical foul on the counter.", "Heavy first touch — every fullback has them."],
    defensive: ["Wins the 1v1 down the touchline.", "Tracks the runner all the way back — fullback's responsibility.", "Slide tackle on the byline to deny the cross."],
    bigGame: ["Widmer's full shift against Brazil — the right flank held against Vinícius and Raphinha.", "The kind of complete fullback performance that wins games.", "Two-way work on a tournament stage."],
    quietGame: ["Quiet 90 — Switzerland's midfield kept the ball away from his flank.", "Untested defensively — the back four did their job.", "Cruise control — comfortable shift."],
    controversy: ["Limited public profile — Widmer keeps his head down.", "Switzerland's federation has been steady; no drama on his side."],
    famousGameHint: ["Look up Switzerland's 1-0 win over Serbia at Qatar — Widmer's full shift secured the spot in the round of 16.", "His Mainz Bundesliga consistency — the player-rating chart is a flat line."],
    opponentFlavor: {
      CMR: "Group-stage 1-0 win — Widmer locked down the right.",
      BRA: "Lost to Brazil 1-0 — Widmer tested by Vinícius all night.",
      SRB: "The 3-2 win that sent Switzerland through — Widmer's full shift on both ends.",
      POR: "Round-of-16 6-1 loss — Widmer overrun by Portugal's wave.",
    },
    formerTeam: ["FC Aarau, Udinese, Basel, Mainz — the slow Bundesliga climb.", "Mainz's right-back since 2021 — Bundesliga regular."],
    salaryNarrative: ["At $49 PURPLE he's the value-for-money fullback pick.", "PURPLE because Switzerland's ceiling is limited; the work shows up regardless."],
    teamContext: ["Switzerland's right-back through the 2022 cycle.", "Murat Yakin's tactical setup wanted a two-way fullback — Widmer was the obvious answer."],
  },

  // Joško Gvardiol — Croatia DEF $47 PURPLE — avgFP 31.9
  gvardiol: {
    nicknames: ["Joško", "The Tank", "Gvardiol"],
    knownFor: "Croatia's young centre-back — €90m to Manchester City after Qatar.",
    salaryTier: "star",
    tier1: ["The 20-year-old centre-back who looked like a 30-year-old at the World Cup.", "Croatia's defensive future arrived early — Gvardiol owns the back four now.", "If you draft a centre-back to build a team around for a decade, you draft Joško."],
    tier2: ["Dinamo Zagreb academy, Leipzig at 19, Manchester City at 21 for £77m.", "Played in Qatar with a face mask after a broken nose in November — the iconic look of his tournament.", "City paid £77m in 2023 — the most expensive defender in football history at the time."],
    tier3: ["Born in 2002 — younger than some senior internationals' kids.", "Plays both centre-back and left-back at elite level — the modern, two-footed defender."],
    overperform: ["When Gvardiol leads the back four at 20, the rest of the league takes notice.", "Tackles, headers, a goal up at the other end — the complete centre-back shift.", "This is the form that justified the £77m fee."],
    underperform: ["A rare lapse — the marker got behind him and the goal came from it.", "Off the pace — and Croatia's back line missed the anchor.", "Even Gvardiol has nights at 20 where the legs say no."],
    onPace: ["Standard Gvardiol shift — quiet, organized, no fuss.", "Read the cross, won the duel, moved on.", "Did his job — exactly what Croatia needed from the youngest CB on the pitch."],
    loosePlay: ["A heavy clearance into traffic — minor wobble.", "Tactical foul, yellow card — the price of position.", "Misjudged the bounce — every defender does it once."],
    defensive: ["Three headers won, two clearances, no fuss.", "Slide tackle in the box — emergency defending done right.", "Pressed the striker into a hurried first touch."],
    bigGame: ["GVARDIOL. The 20-year-old captain in waiting.", "His Argentina semifinal — went one-on-one with Messi and held his own as much as anyone could.", "The kind of CB performance that gets pinned in highlight reels for a generation."],
    quietGame: ["Untested for long stretches — Croatia's midfield kept the ball away.", "Quiet 90 — exactly what a centre-back wants.", "Cruise control — comfortable shift."],
    controversy: ["The face mask in Qatar made him an instant icon — broken-nose comeback story.", "City's £77m valuation drew criticism — the early Premier League returns justified it."],
    famousGameHint: ["Look up his Argentina semifinal in 2022 — went one-on-one with Messi as a 20-year-old, held his own.", "His Croatia 2022 World Cup — face mask, third place, future locked in."],
    opponentFlavor: {
      ARG: "The semifinal — went one-on-one with Messi and didn't break.",
      BRA: "Quarterfinal upset — Croatia eliminated Brazil; Gvardiol's defensive shift was central.",
      JPN: "Round-of-16 — Croatia were second-best for 90 and Gvardiol kept the score level.",
      MAR: "Third-place playoff — Croatia 2-1 win, Gvardiol leading the back line.",
      BEL: "Group-stage 0-0 — both midfields cancelled out, Gvardiol untested.",
      CAN: "Group-stage 4-1 — comfortable shift.",
    },
    formerTeam: ["Dinamo Zagreb academy, Leipzig at 19, Manchester City at 21.", "City's £77m fee in 2023 broke the world record for a defender."],
    rivalry: ["Croatia-Serbia is the deepest derby in his region."],
    milestones: ["Most expensive defender in football history at the time of his City move.", "Croatia's third-place finish at 2022 World Cup — Gvardiol the youngest starting CB at the tournament."],
    salaryNarrative: ["At $47 PURPLE he's the future-star pick — produces ORANGE-tier ceilings as a centre-back.", "PURPLE on the card; ORANGE on his ceiling — the value pick of the defensive board."],
    teamContext: ["Croatia's defensive identity in 2022 was Gvardiol and the veterans organized around him.", "Dalić's tactical setup leaned on Gvardiol for two-way ability — defensive and ball-carrying."],
    draftAndPath: ["Dinamo Zagreb academy from 13, first-team debut at 18.", "Leipzig at 19, Manchester City at 21 for £77m."],
  },

  // Achraf Hakimi — Morocco DEF $45 PURPLE — avgFP 30.4
  hakimi: {
    nicknames: ["Achraf", "Hakimi"],
    knownFor: "Morocco's right-back — PSG's marquee fullback and Africa's modern face.",
    salaryTier: "star",
    tier1: ["When Hakimi runs, the touchline becomes a runway.", "Morocco's right-back is one of the best in the world — full stop.", "The kind of fullback that makes the position look like a luxury."],
    tier2: ["Real Madrid academy graduate, loaned to Dortmund, sold to Inter, signed by PSG for €60m.", "Captained Morocco's run to the 2022 World Cup semifinals — Africa's first.", "Born in Madrid; chose Morocco at youth level — his identity, his choice."],
    tier3: ["Scored the winning penalty in the round-of-16 shootout against Spain — against the country he was born in.", "His mother is famously involved in his life — the most-loved family figure of the tournament."],
    overperform: ["When Hakimi bombs the right flank, the whole pitch tilts.", "Goal, assist, three tackles, two clearances — the complete modern fullback shift.", "This is PSG-form Hakimi on a World Cup stage."],
    underperform: ["Caught upfield on a counter — the attacking fullback's risk.", "Beaten on the byline once — and the cross became a goal.", "Off the pace — Morocco's right flank looked exposed."],
    onPace: ["Standard Hakimi shift — covered the touchline both ways.", "Bombed forward when the moment was right, defended when it wasn't.", "The complete two-way fullback — pace plus discipline."],
    loosePlay: ["A loose pass under pressure — rare from him.", "Booked for a tactical foul — happens to every fullback.", "Heavy first touch under the press — minor wobble."],
    defensive: ["Wins the 1v1 down the touchline.", "Tracks the runner all the way back — and burns past him on the return.", "Slide tackle on the byline to deny the cross."],
    bigGame: ["HAKIMI. THE PANENKA. Morocco are through.", "His chipped penalty against Spain in the shootout — the cheekiest pen of the tournament.", "Africa's biggest moment had Hakimi at the center of it."],
    quietGame: ["Quiet 90 — Morocco's midfield kept the ball.", "Untested defensively — the back four did their job.", "Subbed at 75 — saving him for the next round."],
    controversy: ["Sexual assault allegations in 2023 led to a French criminal investigation — ongoing throughout his career since.", "The Spain game in Qatar carried the personal-rivalry subtext — born in Madrid, scored against Spain."],
    famousGameHint: ["Look up his Panenka penalty against Spain in the 2022 round-of-16 shootout — sent Morocco to the quarters.", "His Inter Serie A run in 2020/21 — fullback of the season."],
    opponentFlavor: {
      ESP: "Panenka penalty in the shootout — Morocco through, Spain home, Hakimi's mother in tears in the camera.",
      POR: "Quarterfinal — locked down Cristiano's right flank, Morocco won 1-0.",
      FRA: "Semifinal — Hakimi against Mbappé was the marquee fullback matchup of the tournament.",
      CRO: "Group-stage 0-0 — Hakimi tested but solid.",
      BEL: "Group-stage 2-0 win — Hakimi's right flank dominated.",
      CAN: "Group-stage 2-1 — comfortable shift.",
    },
    formerTeam: ["Real Madrid academy, Dortmund loan, Inter for €40m, PSG for €60m.", "PSG's marquee right-back since 2021."],
    rivalry: ["Morocco-Algeria is the deepest North African derby.", "His Spain matchup carries the born-in-Madrid subtext."],
    milestones: ["Africa's first World Cup semifinal — Morocco 2022, Hakimi captain.", "PSG's marquee fullback signing.", "Africa Cup of Nations runner-up multiple times."],
    salaryNarrative: ["At $45 PURPLE he's the value-for-money modern fullback pick.", "PURPLE because Morocco's ceiling has limits; the work and goals come anyway.", "Most paid-off PURPLE defender on the board."],
    teamContext: ["Morocco's marquee player and right-flank engine through the 2022 run.", "Walid Regragui's tactical setup needed Hakimi bombing forward; he delivered every match."],
    draftAndPath: ["Madrid-born to Moroccan parents.", "Real Madrid academy from 8, Dortmund loan at 19, Inter at 21, PSG at 22."],
    signatureGames: [
      { date: "2022-12-06", opponent: "ESP", fp: 55, line: "The Panenka penalty in the shootout — Morocco to the quarters, Hakimi an icon." },
    ],
  },

  // Francisco Calvo — Costa Rica DEF $44 PURPLE — avgFP 30.1
  calvo: {
    nicknames: ["Francisco"],
    knownFor: "Costa Rica's veteran centre-back — Saprissa academy product, MLS regular.",
    salaryTier: "role",
    tier1: ["Costa Rica's defensive backbone — the kind of centre-back every CONCACAF team wants.", "When Calvo organizes the back four, Costa Rica's ceiling rises.", "Veteran's presence in a young Tica defense."],
    tier2: ["Saprissa academy graduate — Costa Rica's most reliable producer.", "MLS journey from Minnesota to Chicago — the league's preferred Costa Rican centre-back.", "Captained Costa Rica through the 2022 cycle."],
    tier3: ["Famously vocal on the pitch — the organizer of the back line.", "Costa Rica's golden generation around Keylor Navas was built around defenders like Calvo."],
    overperform: ["When Calvo leads the back four, Costa Rica's ceiling lifts.", "Headers won, lines held, no goals conceded — the centre-back's dream shift.", "Veteran composure when the pressure was at its worst."],
    underperform: ["A rare lapse — the marker got behind him and the goal came from it.", "Off the pace — Costa Rica's back line creaked.", "Caught flat-footed on a runner — every CB's bad night."],
    onPace: ["Standard Calvo shift — quiet, organized, no fuss.", "Read the cross, won the duel, moved on.", "Veteran centre-back doing veteran centre-back things."],
    loosePlay: ["A heavy clearance into traffic — minor wobble.", "Tactical foul, yellow card — the price of position.", "Lost the runner once — the goal came from it."],
    defensive: ["Three headers won, two clearances, no fuss.", "Slide tackle in the box — emergency defending done right.", "Organized the line — captain's responsibility."],
    bigGame: ["Calvo's Japan group-stage win — the back four held against the favorites.", "Veteran's masterclass on a World Cup stage.", "The kind of CB shift that wins matches Costa Rica wasn't supposed to win."],
    quietGame: ["Quiet 90 — Costa Rica's midfield kept the ball away.", "Untested defensively — the back four did their job.", "Comfortable shift."],
    controversy: ["MLS journeyman — none of his transfers have been controversial.", "Costa Rica's federation has had drama; Calvo stayed clear."],
    famousGameHint: ["Look up Costa Rica's 1-0 win over Japan at the 2022 World Cup — Calvo's defensive shift was the foundation.", "His Saprissa years — Costa Rica's youth pipeline at its best."],
    opponentFlavor: {
      ESP: "The 7-0 group-stage opener loss — Costa Rica's worst World Cup result, the back four overrun.",
      JPN: "The 1-0 win — Calvo's centre-back shift was the foundation.",
      GER: "Lost to Germany 4-2 — Calvo's tournament ended on the wrong end of a high-scoring loss.",
    },
    formerTeam: ["Saprissa academy, Minnesota United, Chicago Fire — the MLS journey.", "Costa Rica's go-to centre-back through the 2022 cycle."],
    salaryNarrative: ["At $44 PURPLE he's a value-for-money defender pick.", "PURPLE because Costa Rica's defensive ceiling is limited; the work shows up regardless."],
    teamContext: ["Costa Rica's defensive identity through 2022 — Calvo organized in front of Keylor Navas.", "Luis Fernando Suárez's tactical setup needed a vocal CB; Calvo was the obvious answer."],
  },

  // Cho Gue-sung — South Korea FWD $52 ORANGE — avgFP 29.2
  cho: {
    nicknames: ["Gue-sung", "Cho"],
    knownFor: "South Korea's striker — the brace against Ghana made him a global meme overnight.",
    salaryTier: "star",
    tier1: ["When Cho gets a half-yard in the box, somebody's net is moving.", "South Korea's number 9 — the breakout star of the 2022 World Cup.", "If you weren't watching Korean football before Qatar, you were watching it after."],
    tier2: ["Came up through Korean university football — late bloomer by tournament-football standards.", "Jeonbuk Hyundai Motors made him a K League regular before he became Korea's striker.", "His brace against Ghana made him a global name in 90 seconds — and a global meme in 60."],
    tier3: ["The two headers against Ghana came inside three minutes — one of the strangest brace sequences of the tournament.", "Became internet-famous overnight — Korean fans called him the 'Beautiful Striker' from then on."],
    overperform: ["When Cho's headers find the corner, Korea has a striker.", "Brace inside three minutes — the wildest scoring sequence of the tournament.", "This is the version Korea has been waiting for."],
    underperform: ["Marked tightly — Korea's plan A stalled.", "Couldn't find his shot — even great strikers have those nights.", "Frustrated, subbed, tomorrow's another match."],
    onPace: ["Standard Cho shift — held the ball up, brought the midfield in.", "A goal threat in the box — even when the chances didn't quite come.", "Did the centre-forward's necessary work."],
    loosePlay: ["Heavy first touch — happens in the box.", "Offside three times — the runner's price.", "Lost the ball under pressure — minor lapse."],
    defensive: ["Pressed the keeper into a hurried clearance.", "Tracked back to win a header in his own box — defending corners is part of it.", "Won an aerial in his own half."],
    bigGame: ["CHO. CHO. THE BRACE AGAINST GHANA.", "Two headers in three minutes — the wildest striker sequence of the tournament.", "Korea's beautiful striker arrived in 90 seconds."],
    quietGame: ["Marked out — Korea's attack stalled.", "Subbed at 75 — quiet shift.", "Off the pace — and Korea's chances dried up with him."],
    controversy: ["His viral moment in 2022 led to internet thirst-trap memes that he handled with grace.", "Korean military service obligations have been a backdrop — the World Cup performance helped."],
    famousGameHint: ["Look up his brace against Ghana at the 2022 World Cup — two headers in three minutes, the breakout moment.", "His K League seasons with Jeonbuk Hyundai Motors — striker development at the elite Korean level."],
    opponentFlavor: {
      URU: "Group-stage 0-0 — Cho contained on a tight night.",
      GHA: "The brace — two headers in three minutes that nearly saved Korea's tournament.",
      POR: "The 2-1 stoppage-time win — Korea through to the round of 16, Cho the focal point.",
      BRA: "Round-of-16 4-1 loss — Korea's attack overrun.",
    },
    formerTeam: ["Jeonbuk Hyundai Motors — K League regular before the 2022 breakout.", "Mainz signed him in 2024 — the Bundesliga move that followed the World Cup."],
    rivalry: ["Korea-Japan is East Asia's deepest derby — Cho's grown up watching it."],
    salaryNarrative: ["At $52 ORANGE he's priced for the bigGame ceiling, not the floor.", "ORANGE because of the Ghana brace — the pricing assumes the high-ceiling games."],
    teamContext: ["South Korea's number 9 in 2022 — paired with Son Heung-min as the focal point.", "Paulo Bento's tactical setup needed a target striker; Cho fit the role."],
    signatureGames: [
      { date: "2022-11-28", opponent: "GHA", fp: 65, line: "The brace in three minutes — the breakout moment of the tournament." },
    ],
  },

  // Hirving Lozano — Mexico FWD $50 PURPLE — avgFP 28.3
  lozano: {
    nicknames: ["Chucky", "Hirving"],
    knownFor: "Mexico's left-winger — Napoli regular, the man who scored the goal vs. Germany in 2018.",
    salaryTier: "star",
    tier1: ["When Chucky's running at you, you're already losing.", "Mexico's left flank — the kind of pace that bends defensive shapes.", "The 2018 goal against Germany lives in Mexican football history forever."],
    tier2: ["Pachuca raised him; PSV took him to Europe; Napoli paid for him at 24.", "His goal against Germany in the 2018 World Cup opener was Mexico's most-celebrated moment in 30 years.", "Locked down Mexico's left-wing spot through three World Cup cycles."],
    tier3: ["The 'Chucky' nickname comes from a teammate's joke about his hair as a teenager — it stuck.", "Napoli's Scudetto-winning squad in 2022/23 — Lozano part of the title-winning rotation."],
    overperform: ["When Chucky cuts inside, the whole defense reorganizes.", "A goal, an assist, two key passes — the complete winger's shift.", "This is the Napoli-form Lozano on a World Cup stage."],
    underperform: ["Marked tightly — Mexico's plan A stalled.", "Couldn't find space — even the great wingers have those nights.", "Frustrated, subbed, tomorrow's another match."],
    onPace: ["Standard Chucky shift — drove down the left, cut inside, made the defense move.", "Got his half-chance, hit the post once.", "Did his job — pace and threat for 90 minutes."],
    loosePlay: ["Heavy first touch — even great wingers have them.", "Tried a stepover that the defender read.", "Caught dribbling into trouble — minor lapse."],
    defensive: ["Tracks back when needed — winger's responsibility.", "Pressed the centre-back into a panicked clearance.", "Won a tackle in his own half — useful, unflashy."],
    bigGame: ["LOZANO. THE GOAL AGAINST GERMANY. Mexico's eternal moment.", "Chucky's pace tore Germany apart in 2018 — the world found out who he was.", "This is the version Mexico keeps showing up for at every World Cup."],
    quietGame: ["Marked out — Mexico's attack stalled.", "Subbed at 75 — frustrated, slow.", "Quiet 90 — and Mexico's chances dried up."],
    controversy: ["A career-threatening head injury in 2021 against Honduras — recovered fully.", "Mexico's federation drama in 2022 was a backdrop he stayed clear of."],
    famousGameHint: ["Look up his goal against Germany in the 2018 World Cup opener — Mexico's biggest moment of the modern era.", "His Napoli 2022/23 Scudetto-winning season — title-winning rotation."],
    opponentFlavor: {
      POL: "Group-stage 0-0 — Lozano marked tightly.",
      ARG: "Lost to Argentina 2-0 — Lozano was Mexico's most threatening attacker.",
      KSA: "The 2-1 win that wasn't enough — Lozano took the chances Mexico needed.",
    },
    formerTeam: ["Pachuca academy, PSV from 2017, Napoli from 2019, San Diego in MLS in 2024.", "Napoli's Scudetto-winning squad of 2022/23."],
    rivalry: ["Mexico-USA is one of football's fiercest border rivalries.", "Mexico-Argentina has decades of World Cup matchups."],
    milestones: ["The 2018 goal against Germany — Mexico's most-celebrated moment in 30 years.", "Napoli Scudetto winner 2022/23.", "Mexico's primary left-winger across three World Cups."],
    salaryNarrative: ["At $50 PURPLE he's the value-for-money winger pick.", "PURPLE because Mexico's ceiling is limited; the goals come anyway."],
    teamContext: ["Mexico's left-wing identity since 2018 — Tata Martino built around him.", "When Lozano plays well, Mexico's attack runs. When he doesn't, the team stalls."],
    draftAndPath: ["Pachuca academy from 11, first-team debut at 18.", "PSV at 22, Napoli at 24, San Diego at 28."],
  },

  // Vinícius Júnior — Brazil FWD $47 PURPLE — avgFP 26.4
  vinícius: {
    nicknames: ["Vini Jr.", "Vini"],
    knownFor: "Real Madrid's left-winger — the next great Brazilian, already a Champions League winner.",
    salaryTier: "star",
    tier1: ["When Vinícius runs, the whole left flank becomes a runway.", "Real Madrid's franchise winger — Brazil's golden boy in real time.", "The pace plus the technique — defenders just have to choose which way to lose."],
    tier2: ["Flamengo raised him; Real Madrid signed him at 18 for €45m.", "Won the Champions League at 21 with the winning goal in the final against Liverpool.", "Brazil's left-wing future — the heir apparent to Neymar's number 10 role."],
    tier3: ["Famously targeted by racist abuse in La Liga across 2022/23 — became the global face of football's anti-racism push.", "His 2022 World Cup was muted — but the post-tournament Real Madrid form was a different player."],
    overperform: ["When Vini's on it, the left flank is Brazil's possession.", "Goal, assist, three key passes — the complete winger's shift.", "Real Madrid-form Vinícius on the international stage."],
    underperform: ["Marked tightly — Brazil's plan A stalled.", "Couldn't find space — even the elite wingers have those nights.", "Frustrated, subbed, tomorrow's another match."],
    onPace: ["Standard Vini shift — drove down the left, cut inside, made the defense move.", "Got his half-chance, hit the post once.", "Pace and threat for 90 minutes."],
    loosePlay: ["Heavy first touch — happens to every winger.", "Tried a stepover that the defender read.", "Caught dribbling into trouble — minor lapse."],
    defensive: ["Tracks back when he wants to — and he wants to more often than the highlight reel suggests.", "Pressed the centre-back into a panicked clearance.", "Won a tackle in his own half."],
    bigGame: ["VINÍCIUS. The next Brazilian icon.", "His Champions League final goal at 21 was the calling card — the World Cup stage was the next step.", "This is what generational pace looks like."],
    quietGame: ["Marked out — Brazil's attack stalled with him.", "Subbed at 75 — frustrated, slow.", "Quiet 90 — sometimes the elite wingers just don't get the ball."],
    controversy: ["The racist abuse in La Liga across 2022/23 became the central story of his career — handled with dignity.", "His on-pitch celebrations and dance routines drew criticism from old-school media — Vini ignored it."],
    famousGameHint: ["Look up his Champions League final goal in 2022 against Liverpool — Real Madrid's title clincher.", "His Real Madrid 2022/23 season — Ballon d'Or-conversation form."],
    opponentFlavor: {
      SRB: "Group-stage 2-0 — Vinícius's first World Cup win.",
      SUI: "Group-stage 1-0 — quiet shift.",
      KOR: "Round-of-16 4-1 — Vinícius opened the scoring with a thunderbolt.",
      CRO: "Quarterfinal exit — Brazil eliminated, Vinícius's tournament over.",
    },
    formerTeam: ["Flamengo academy, Real Madrid from 2018 for €45m.", "Real Madrid's franchise winger since 2021/22."],
    rivalry: ["Brazil-Argentina is in his bones.", "His individual rivalry with the Spanish footballing establishment over racism became a tournament-level story."],
    milestones: ["Champions League winner 2022 — scored the winning goal in the final.", "Real Madrid's franchise winger.", "Brazil's left-wing heir apparent."],
    salaryNarrative: ["At $47 PURPLE he's the value-for-money pick at the elite winger tier.", "PURPLE because his 2022 form was muted; ORANGE on the Real Madrid form."],
    teamContext: ["Brazil's left-wing in 2022 — paired with Raphinha on the right and Neymar in the middle.", "Tite's tactical setup wanted Vini's pace stretching defenses; in 2022, the form didn't quite arrive."],
    draftAndPath: ["Flamengo academy from 8, first-team debut at 16.", "Real Madrid signed him at 18 for €45m — the rest is history."],
    signatureGames: [
      { date: "2022-12-05", opponent: "KOR", fp: 60, line: "The thunderbolt that opened a 4-1 round-of-16 win — Vinícius announced himself." },
    ],
  },

  // Guillermo Ochoa — Mexico GK $40 PURPLE — avgFP 23.3
  ochoa: {
    nicknames: ["Memo", "Paco", "Ochoa"],
    knownFor: "Mexico's iconic keeper — five World Cup appearances, the country's beating heart in goal.",
    salaryTier: "star",
    tier1: ["When Memo's between the sticks, Mexico believes.", "Five World Cups — that's not a career, that's a monument.", "Mexico's most-loved athlete of his generation, full stop."],
    tier2: ["Came up through América in Mexico City; played in France, Spain, and Italy across his career.", "His 2014 World Cup performance against Brazil made him a global name.", "Mexico's first-choice keeper across five World Cups — 2006, 2010, 2014, 2018, 2022."],
    tier3: ["The 2014 Brazil game in Fortaleza — Ochoa made saves that became internet folklore.", "Famously composed under pressure — saved penalties at three different World Cups."],
    overperform: ["When Memo's hot, the goal disappears.", "This is the form that got him five World Cups.", "Strikers checked their boots and the lighting — none of it explained him."],
    underperform: ["Even Memo has nights when the ball finds the corner.", "Conceded — but kept Mexico in it.", "Off the pace — the back line had a rough one too."],
    onPace: ["Standard Ochoa shift — calm, positioned, hard to beat.", "Made the saves he was supposed to make.", "Reliable. Composed. Mexico's safety blanket."],
    loosePlay: ["Punched when he should have caught — minor wobble.", "A long ball that didn't quite go where he wanted.", "Caught off his line — even the cool ones get the angle wrong."],
    defensive: ["Commands his box like a captain.", "Two-handed catch in traffic — exactly what you want.", "Read the cross and snuffed it before the striker could meet it."],
    bigGame: ["OCHOA. SAVED IT. Mexico's beating heart between the sticks.", "His penalty save at the 2022 World Cup — vintage Memo at 37.", "The kind of GK shift Mexico's been getting from him for 16 years."],
    quietGame: ["Quiet day — the back four did their job and Ochoa supervised.", "Two saves and a clean sheet — low-event, high-value.", "Comfortable. Composed."],
    controversy: ["Limited international club career — a topic of debate in Mexican media for years.", "Mexico's federation drama in 2022 was a backdrop; Memo stayed above it."],
    famousGameHint: ["Look up his 2014 Mexico vs. Brazil — the saves that made him an internet legend.", "His 2022 penalty save against Poland — Lewandowski denied, Ochoa at 37 still doing it."],
    opponentFlavor: {
      POL: "Saved Lewandowski's penalty — vintage Memo.",
      ARG: "Lost to Argentina 2-0 — Ochoa kept the score from being worse.",
      KSA: "The 2-1 win that wasn't enough — Memo's last World Cup goodbye.",
      BRA: "His career-defining 2014 game in Fortaleza — saves that became internet folklore.",
    },
    formerTeam: ["América Mexico City raised him; AC Ajaccio, Málaga, Granada, Standard Liège, América again, Salernitana — the long European journey.", "Mexico's all-time most-capped goalkeeper."],
    rivalry: ["Mexico-USA is football's fiercest border rivalry."],
    milestones: ["Five World Cup appearances — Mexican record.", "Penalty saves at three different World Cups.", "Mexico's most-capped goalkeeper of all time."],
    salaryNarrative: ["At $40 PURPLE he's the elder-statesman keeper — the brand pricing.", "PURPLE because the floor is steady; the bigGame ceiling is iconic."],
    teamContext: ["Mexico's first-choice keeper for two decades — three managers, five World Cups, one Memo.", "When Ochoa plays well, Mexico stays in games. When he doesn't, the dam breaks."],
    draftAndPath: ["América Mexico City academy from 10, first-team debut at 18.", "Played across France, Spain, Belgium, and Italy in his European chapter."],
    signatureGames: [
      { date: "2022-11-22", opponent: "POL", fp: 50, line: "Saved Lewandowski's penalty — vintage Memo at 37, the goodbye tour in full." },
    ],
  },
