  // Devis Epassy — Cameroon GK $60 ORANGE — avgFP 70
  epassy: {
    nicknames: ["Devis", "Epassy"],
    knownFor: "Cameroon's Qatar surprise — the keeper who came in cold and ended up beating Brazil.",
    salaryTier: "max",
    tier1: ["The shot-stopper who turned a tournament cameo into Cameroon's defining moment.", "When Onana left, Epassy stepped in and didn't blink.", "Africa's most underrated keeper of the 2022 cycle."],
    tier2: ["Was the third-choice keeper coming into Qatar — left it as Cameroon's hero.", "Plies his trade away from the European spotlight, which is why this run shocked everyone but him.", "The Indomitable Lions found their wall at the back when they needed it most."],
    tier3: ["Stepped into the starting role mid-tournament after the Onana coaching dispute.", "Has spent most of his career in lower-profile leagues — earning every call-up the hard way."],
    overperform: ["When Epassy is hot, the goal becomes a postage stamp.", "Saves you didn't think he had in him — but the tape says he always did.", "Cameroon's defense looked twice as organized with him calm in the back."],
    underperform: ["A keeper's bad night — sometimes the ball just keeps finding the corner.", "Conceded — but kept the score reachable, which is half the job.", "Distribution wobbled tonight; the back four had to bail him out."],
    onPace: ["Standard Epassy — calm, positioned, no theatrics.", "Made the saves he was supposed to make and held his shape.", "Reliable shift between the sticks."],
    loosePlay: ["Came off his line on a cross he shouldn't have.", "A rushed clearance — even calm keepers get fluttery.", "Punched when he had two hands free — minor wobble."],
    defensive: ["Commands his box with quiet authority.", "Read the cross before the striker even arrived.", "Two-handed catch in traffic — exactly the textbook."],
    bigGame: ["EPASSY. EPASSY. The lion roars from the back.", "This is the keeper performance that puts a country on the map.", "Cameroon's wall just held up against Brazil — let that sink in."],
    quietGame: ["Quiet day at the office — back four did the heavy lifting.", "A handful of saves, all of them routine. Job done.", "Asked little, delivered everything."],
    controversy: ["Caught up in the Onana mid-tournament fallout — but stayed out of the headlines himself.", "Cameroon's federation drama is its own genre — Epassy mostly avoided it."],
    famousGameHint: ["Look up Cameroon-Brazil in the 2022 group stage — the historic 1-0 he helped lock down.", "His Serbia performance — Cameroon came back from 3-1 down to draw 3-3."],
    opponentFlavor: {
      BRA: "The 1-0 Brazil shock — Cameroon's first ever win over the five-time champions, and Epassy's wall held.",
      SRB: "The 3-3 thriller — conceded three but kept Cameroon in it long enough to find an equalizer.",
      SUI: "Group-stage opener loss — beaten once, but not by much.",
    },
    teamContext: ["Stepped up when Cameroon needed a cool head between the sticks the most.", "Rigobert Song's selection vindicated when he took the gloves and didn't let go."],
    draftAndPath: ["Long road through African and second-tier European football to a World Cup starting role.", "Earned his minutes the hard way — every call-up is a story by itself."],
  },

  // Antoine Griezmann — France MID $60 ORANGE — avgFP 44.1
  griezmann: {
    nicknames: ["Grizou", "El Principito", "Griezmann"],
    knownFor: "France's selfless creator — the conductor who made Mbappé look even faster.",
    salaryTier: "max",
    tier1: ["The player every coach wants and every fan underrates.", "He plays the hardest position in football — the one that doesn't show up on stat sheets.", "If France's attack is a band, Griezmann's the bassist who holds the whole thing together."],
    tier2: ["Rejected by every French academy as a teenager — moved to Real Sociedad at 14.", "Won the World Cup in 2018 and ran the final hat-trick game in 2022 from a deeper role.", "The 2018 Ballon d'Or top-three finisher who never quite got the trophy."],
    tier3: ["Idolized David Beckham as a kid — even has a Beckham tribute haircut in his back catalogue.", "His sister survived the Bataclan attacks in 2015 — he dedicated his Euro 2016 run to her."],
    overperform: ["When Griezmann decides to play number 10, the whole French attack unlocks.", "Drops deep, finds the gap nobody saw, splits the press — vintage Grizou.", "Goal threat plus playmaker plus presser — all in 90 minutes."],
    underperform: ["Quiet game — even Grizou has nights when the connections don't click.", "Marked closely; the playmaker passes had nowhere to go.", "Frustrated but professional — he'll be back next match."],
    onPace: ["Standard Grizou shift — an assist, a press trigger, a couple of late runs into the box.", "The metronome hummed all night.", "Did the things that don't make highlights and won France the match anyway."],
    loosePlay: ["A heavy touch in midfield — rare for him.", "Tried to thread a pass nobody else could see — and the receiver couldn't either.", "Caught dribbling into traffic. Tomorrow's another day."],
    defensive: ["Tracks back like a defensive midfielder — that's why Deschamps trusts him.", "Pressed the centerback into a panicked clearance.", "Won the ball back high up the pitch — the unsung Grizou."],
    bigGame: ["GRIEZMANN. The Little Prince has the keys to the kingdom tonight.", "This is what a complete forward looks like — goal, assist, defensive shift, all of it.", "Vintage Grizou. The artist's signature on a French win."],
    quietGame: ["Drifted into the deeper role tonight — saving his runs for the next match.", "Subbed at 75 — Deschamps managing minutes carefully.", "Quiet by his standards is still 70 minutes of perfect shape."],
    controversy: ["Made a video with Dembélé in 2019 mocking Japanese hotel staff — apologized, but it followed him.", "Atletico-Barcelona transfer saga had two parts and both were awkward.", "His Spurs flirtation in 2017 ended with the famous Netflix-style 'La Decisión' documentary."],
    famousGameHint: ["Look up his 2018 World Cup Final goal — France beat Croatia and he scored from the spot.", "His Argentina semifinal in 2022 — quietly excellent in a deeper midfield role.", "Euro 2016 — six goals as France's tournament top scorer, runner-up to Portugal."],
    opponentFlavor: {
      AUS: "Group-stage opener — assist on Mbappé's goal, classic deep playmaker shift.",
      DEN: "Group-stage 2-1 win — quiet but vital in the build-up phase.",
      POL: "Round-of-16 — set up the second goal for Mbappé, then defended for 90.",
      ENG: "Quarterfinal — won his individual matchup with Bellingham in midfield.",
      MAR: "Semifinal — controlled the tempo against Morocco's pressing trap.",
      ARG: "The 2022 final — assists, runs, defensive shifts. France lost. He didn't lose his shift.",
    },
    formerTeam: ["Real Sociedad raised him; Atlético Madrid made him a star; Barcelona was a difficult chapter.", "Returned to Atlético after the Barcelona stint — back where he was loved."],
    rivalry: ["Atletico-Real and Atletico-Barcelona shaped his club career.", "France-Argentina is the modern World Cup rivalry now — and he's been at the heart of both finals."],
    milestones: ["2018 World Cup winner.", "Euro 2016 Golden Boot (six goals).", "Atlético Madrid all-time leading scorer."],
    streakLines: ["Six goals at Euro 2016 — a tournament-defining run.", "Two World Cup finals across 2018 and 2022 — that's a captain's CV.", "Goal contributions in nearly every France knockout match across two tournaments."],
    salaryNarrative: ["At $60 ORANGE he's the floor pick — guaranteed contributions every match.", "You don't pay for goals; you pay for the way he makes everyone around him better.", "Cap-eater because France's whole midfield runs through him."],
    teamContext: ["Deschamps' tactical anchor — drop-deep playmaker plus second striker.", "Carried France's creative load while Mbappé ran the channels.", "When Griezmann is on form, France are unbeatable. When he isn't, France are still good — that's the point."],
    draftAndPath: ["Rejected by every French academy — Saint-Étienne, Lyon, all of them said no.", "Real Sociedad spotted him at a tournament at 13 and took a chance.", "Atlético Madrid in 2014 — and the rest is history."],
    signatureGames: [
      { date: "2022-12-18", opponent: "ARG", fp: 50, line: "The final — assists, defensive shifts, 120 minutes of total football." },
      { date: "2022-12-10", opponent: "ENG", fp: 55, line: "Quarterfinal — won his midfield matchup with Bellingham." },
      { date: "2022-12-14", opponent: "MAR", fp: 48, line: "Semifinal control — broke Morocco's press with the deeper role." },
    ],
  },

  // Salem Al-Dawsari — Saudi Arabia MID $58 ORANGE — avgFP 42.6
  dawsari: {
    nicknames: ["Salem", "Al-Dawsari"],
    knownFor: "The Saudi winger whose curling left foot beat Argentina in the 2022 group stage.",
    salaryTier: "star",
    tier1: ["When Al-Dawsari takes the ball on the left, the whole match leans his way.", "Saudi Arabia's biggest moment in football history started at his left foot.", "The kind of player whose ceiling rises with the moment."],
    tier2: ["Spent his entire career at Al-Hilal — Riyadh's pride and the kingdom's franchise.", "Brief loan spell at Villarreal in 2018 to test the Spanish waters.", "Carried the green-and-white stripes through three World Cup cycles."],
    tier3: ["His curling left-foot strike against Argentina in 2022 won FIFA's Goal of the Tournament shortlist nods.", "Has been the face of Saudi football's domestic boom for nearly a decade."],
    overperform: ["When Al-Dawsari's left foot is speaking, defenders just listen.", "Two assists in the first half and a goal of the tournament — that's the ceiling.", "Saudi Arabia's whole creative load lifted on his shoulders, and he carried it."],
    underperform: ["Even Salem has nights when the wing closes down.", "Marked tightly — credit the right-back, but he'll be furious about it.", "The legs weren't there tonight — three games in nine days catches everyone."],
    onPace: ["Standard Al-Dawsari shift — a couple of crosses, a shot from range, the threat constant.", "Drove down the wing all match. Got fouled. Got back up. Did it again.", "Reliable creator — nothing flashy, just good football."],
    loosePlay: ["Caught dribbling into traffic on the wing.", "Heavy touch on the cross-field switch.", "A booking for tactical frustration — losing 2-0 will do that."],
    defensive: ["Tracks back when Saudi Arabia need it — which against tier-one opposition is always.", "Pressed the right-back into a hurried clearance.", "Won a tackle in his own third — the unglamorous winger work."],
    bigGame: ["AL-DAWSARI. Saudi Arabia's left foot just shook the world.", "This is the moment that becomes folklore — the goal kids in Riyadh will copy on every pitch for a decade.", "Out of the wardrobe of his mind, a finish for the ages."],
    quietGame: ["Marked out — sometimes the doubles team is just too much.", "Quiet by his standards. Subbed at 70.", "Frustrated, but the team needed his shape more than his runs."],
    controversy: ["Saudi Arabia's federation politics never quite reach him — he stays above it.", "The Al-Hilal-vs-everyone storyline in Saudi football puts him at the center occasionally."],
    famousGameHint: ["Look up Argentina-Saudi Arabia in 2022 — the curling left-foot winner that broke a tournament open.", "His Asian Cup performances over the years — the constant in a changing Saudi side."],
    opponentFlavor: {
      ARG: "The goal of the group stage — the curling left-foot strike that beat Argentina 2-1 in their opener.",
      POL: "Group-stage loss — quiet game, marked out by Lewandowski's defenders.",
      MEX: "Group-stage 2-1 loss — fought hard, came up short on the crowded scoreline.",
    },
    formerTeam: ["Al-Hilal raised him; Villarreal loan tested him; Al-Hilal kept him.", "The face of Saudi domestic football for over a decade."],
    milestones: ["Asian Champions League winner with Al-Hilal.", "Multiple Saudi Pro League titles.", "Saudi Arabia's most-capped attacker in the 2022 cycle."],
    teamContext: ["Saudi Arabia's tournament identity in 2022 was built around his left wing.", "Hervé Renard's tactical setup needed a creator who could carry the attack alone — Al-Dawsari delivered.", "When he's hot, Saudi Arabia have a ceiling. When he isn't, they don't."],
    salaryNarrative: ["At $58 ORANGE he's the surprise high-tier — Argentina shock or bust.", "Cap-eater because Saudi Arabia's whole attack runs through him.", "ORANGE for a reason — when he's hot, he carries the whole kingdom."],
    signatureGames: [
      { date: "2022-11-22", opponent: "ARG", fp: 70, line: "The curling left-foot winner — Saudi Arabia 2, Argentina 1, the world's biggest shock." },
    ],
  },

  // Eduardo Camavinga — France DEF $60 ORANGE — avgFP 40.9
  camavinga: {
    nicknames: ["Cama", "Eduardo"],
    knownFor: "France's box-to-box prodigy — Real Madrid's heir to the Casemiro role at 20.",
    salaryTier: "max",
    tier1: ["When Camavinga gets the ball, the whole midfield speeds up.", "He's twenty years old and already the best ball-progressing midfielder at Real Madrid.", "If you wanted to draw a modern midfielder, you'd draw Camavinga."],
    tier2: ["Born in a refugee camp in Angola, raised in Brittany, made in Madrid.", "Rennes gave him his Ligue 1 debut at 16; Real Madrid signed him at 18 for €31m.", "Was the youngest player at the 2022 World Cup squad — and Deschamps trusted him in the final."],
    tier3: ["His family lost everything in a house fire when he was 11; football was the way out.", "Plays with a fearlessness that other 20-year-olds spend a decade learning."],
    overperform: ["When Camavinga is on, France's midfield is a different machine.", "Drives forward like Pogba, defends like Kanté — the rare combination.", "The kid who looks 20 but plays 30."],
    underperform: ["Even Cama has nights where the legs are 20 and the brain hasn't caught up.", "Marked closely; the press was tight and the ball didn't quite move.", "A booking for an over-eager tackle — the lesson is being learned in public."],
    onPace: ["Standard Cama shift — three tackles, two ball-progressions, one through-ball.", "Did everything Deschamps asked, including the things he wasn't.", "Reliable midfield engine."],
    loosePlay: ["A heavy touch under the press — rare for him.", "Caught dribbling into a triangle of three defenders.", "Tried to thread a pass that wasn't there."],
    defensive: ["Tackles like a centerback in midfielder's clothes.", "Reads the press before it triggers.", "His positional discipline is criminally underrated for a 20-year-old."],
    bigGame: ["CAMAVINGA. The future of French midfield is the present.", "This is a generational performance from a generational midfielder.", "Real Madrid bought him for €31m and got change — that's what this looks like."],
    quietGame: ["Quiet game — he's 20 in a final, give him a moment.", "Subbed at 75 — Deschamps managing the youngest squad member.", "Marked out by experienced midfield — credit the opposition."],
    controversy: ["Caught speeding in Madrid in 2023 — a young man's mistake.", "His name being mispronounced is a recurring TV gag — even Spanish commentators get it wrong."],
    famousGameHint: ["Look up his France-Argentina 2022 final — slotted in at left-back at 20 years old, played 120 minutes.", "His debut for France at 17 — youngest French international in over a century."],
    opponentFlavor: {
      ARG: "The 2022 final — played 120 minutes plus penalties at left-back, age 20. Composure beyond his years.",
      ENG: "Quarterfinal — won his individual midfield battle with Bellingham despite being two years younger.",
      MAR: "Semifinal — broke Morocco's press repeatedly with progressive carries.",
      POL: "Round-of-16 — quiet but assured shift in front of the back four.",
      DEN: "Group-stage 2-1 win — six tackles, two interceptions, one assist.",
    },
    formerTeam: ["Rennes raised him from the academy.", "Real Madrid in 2021 for €31m — the bargain of the decade.", "Carlo Ancelotti's tactical pet project — left-back, midfield, anywhere needed."],
    rivalry: ["Camavinga-Bellingham is the modern Anglo-French midfield rivalry.", "His club tussles with Barcelona's midfielders are must-watch."],
    milestones: ["Youngest French international in over a century (debut at 17).", "Champions League winner with Real Madrid.", "World Cup finalist at 20."],
    streakLines: ["Hot run through France's knockout games — a different player every match.", "Real Madrid form bled directly into France's tournament.", "Three consecutive starts in the knockout stage at 20 years old — that's elite."],
    salaryNarrative: ["At $60 ORANGE he's the youngest cap-eater on the board.", "Defensive position, midfield production — the cap classification undersells the role.", "PURPLE in any other generation; ORANGE because Real Madrid pays him like a star."],
    teamContext: ["Deschamps' tactical wildcard — slotted at left-back in the final because the team needed him there.", "France's midfield future is built around him and Tchouaméni.", "When Cama plays, the midfield ages five years younger and ten years smarter."],
    draftAndPath: ["Born in an Angolan refugee camp; family moved to France when he was a baby.", "Rennes academy from 11; Ligue 1 debut at 16.", "Real Madrid in 2021 — the kind of move that defines a club's next decade."],
    signatureGames: [
      { date: "2022-12-18", opponent: "ARG", fp: 55, line: "The final — 120 minutes at left-back at 20 years old. Composure for the ages." },
      { date: "2022-12-10", opponent: "ENG", fp: 50, line: "Quarterfinal — won his midfield duel with Bellingham despite the age gap." },
    ],
  },

  // Vahid Amiri — Iran MID $53 ORANGE — avgFP 38.5
  amiri: {
    nicknames: ["Vahid", "Amiri"],
    knownFor: "Iran's box-to-box workhorse — Persepolis legend and Team Melli mainstay.",
    salaryTier: "star",
    tier1: ["The kind of midfielder every team needs but nobody puts on a poster.", "When Iran win, Amiri is usually somewhere in the middle of the move.", "Persian football's quiet engine."],
    tier2: ["Persepolis FC's longest-serving midfielder of his generation.", "Three World Cup cycles in the green-red-white kit — the constant in changing Iran sides.", "The Iranian Pro League's tactical center for nearly a decade."],
    tier3: ["Spent most of his career at Persepolis — Tehran's biggest club.", "Has been Iran's reliable starter through three different head coaches."],
    overperform: ["When Amiri's lungs are on, Iran's pressing trap clicks.", "Box-to-box for 90 — and the box at both ends benefits.", "The defensive shift plus the attacking burst — vintage Amiri."],
    underperform: ["Even the engine needs a service.", "Quiet game — credit the opposition's midfield.", "A booking for a frustrated tackle in the second half."],
    onPace: ["Standard Amiri shift — three tackles, two interceptions, a couple of progressive runs.", "Did the dirty work and made the smart pass.", "Reliable. Steady. Iranian football's metronome."],
    loosePlay: ["A heavy touch in midfield under the press.", "Tried to thread a pass that wasn't quite on.", "Caught dribbling into a crowd."],
    defensive: ["Tackles you didn't see and interceptions that turn into counters.", "His positional discipline anchors Iran's shape.", "The kind of defensive work that goes unnoticed until you watch the tape."],
    bigGame: ["AMIRI. Iran's engine room is humming.", "This is what a complete midfielder looks like — quiet, effective, everywhere.", "Vintage Vahid — the box-to-box shift Iran needs every match."],
    quietGame: ["Quiet shift — Iran played defensive and he played his role.", "Marked out by tier-one opposition — happens to every Iranian midfielder.", "Subbed at 75 — saving the legs for the next match."],
    controversy: ["Iran's Team Melli politics are their own genre — Amiri stays mostly out of it.", "Iranian Pro League refereeing controversies have caught him a few yellow cards he didn't deserve."],
    famousGameHint: ["Look up Iran-Wales 2022 — Iran won 2-0 in the dying minutes, and Amiri was at the heart of the late surge.", "His goal contributions across Iran's 2018 and 2022 World Cup campaigns."],
    opponentFlavor: {
      ENG: "Group-stage opener — beaten 6-2, but he ran 90 minutes anyway.",
      WAL: "The 2-0 win — late drama, and Amiri at the heart of the build-up.",
      USA: "Group-stage decider 1-0 loss — fought hard, came up short.",
    },
    formerTeam: ["Persepolis FC for nearly a decade — Tehran's biggest club.", "Earned every cap the hard way — through the Iranian domestic system."],
    milestones: ["Multiple Iranian Pro League titles with Persepolis.", "Three World Cup cycles for Team Melli.", "AFC Champions League final appearances with Persepolis."],
    teamContext: ["Iran's midfield engine — the shape of the team starts with his positioning.", "Carlos Queiroz and his successors all kept him in the team for a reason.", "Team Melli's longest-serving box-to-box of the modern era."],
    salaryNarrative: ["At $53 ORANGE he's the reliable Iranian floor — 38 FP every match.", "ORANGE because Iran's set-piece volume rewards box-to-box players.", "The midfielder you take when you want a guaranteed shift, not a ceiling."],
  },

  // Ghilane Chalali — Tunisia MID $52 ORANGE — avgFP 38
  chalali: {
    nicknames: ["Ghilane", "Chalali"],
    knownFor: "Tunisia's tireless midfield runner — Espérance's homegrown box-to-box.",
    salaryTier: "star",
    tier1: ["The midfielder Tunisia builds the press around.", "When Chalali runs, the whole shape moves with him.", "North African football's engine room in a single body."],
    tier2: ["Came through Espérance de Tunis — the most decorated club in African football.", "Multiple CAF Champions League runs with the Eagles of Carthage.", "Carried Tunisia's midfield through the 2022 cycle."],
    tier3: ["The Espérance youth pipeline has produced Tunisia's spine for two decades — Chalali is the latest.", "Plies his trade in the Tunisian league — a rare modern Africa starter who didn't move to Europe."],
    overperform: ["When Chalali's lungs are on, Tunisia look organized.", "Box-to-box shift with progressive carries that nobody saw coming.", "The unsung Tunisian engine showed up tonight."],
    underperform: ["Even Ghilane has nights when the legs run on empty.", "Marked closely by tier-one opposition — credit the press.", "Quiet game by his standards."],
    onPace: ["Standard Chalali shift — three tackles, two interceptions, the shape held all night.", "Did the dirty work nobody else wanted.", "Reliable midfield engine — exactly what Tunisia hired him for."],
    loosePlay: ["A heavy touch under press.", "Tried a switch of play that didn't quite carry.", "Caught dribbling into traffic."],
    defensive: ["Tackles you didn't see, interceptions that become counter-attacks.", "Disciplined positioning — never out of shape.", "The North African midfield archetype, executed."],
    bigGame: ["CHALALI. Tunisia's heart is beating loud.", "This is the Espérance pipeline at full output.", "The Eagles of Carthage have a midfielder, and tonight everyone watching saw why."],
    quietGame: ["Quiet shift — Tunisia were defensive and he played his role.", "Marked out by tier-one opposition.", "Subbed late — minutes managed."],
    controversy: ["Espérance vs Étoile du Sahel domestic rivalry has put him in a few flashpoint matches.", "Tunisian federation politics are their own thing — Chalali keeps his head down."],
    famousGameHint: ["Look up Tunisia-France 2022 — Tunisia won 1-0, and Chalali was in the engine room.", "His CAF Champions League finals with Espérance."],
    opponentFlavor: {
      FRA: "Tunisia's 1-0 win in the group stage — a stunning result, and Chalali was at the heart of the press.",
      AUS: "Group-stage 1-0 loss — fought all 90.",
      DEN: "Group-stage 0-0 draw — defensive shift, exactly what was needed.",
    },
    formerTeam: ["Espérance de Tunis — Africa's most decorated club, his entire senior career.", "Carthage's pride."],
    milestones: ["CAF Champions League winner with Espérance.", "Multiple Tunisian Ligue 1 titles.", "Eagles of Carthage starter through the 2022 World Cup."],
    teamContext: ["Tunisia's midfield identity is built around his work-rate.", "Jalel Kadri's tactical pressing trap depends on his positional discipline.", "When Chalali runs, the whole team runs."],
    salaryNarrative: ["At $52 ORANGE he's the volume midfielder — guaranteed minutes and shifts.", "ORANGE for a reason — Tunisia's set-piece volume is high.", "The kind of pick you take for the floor, not the ceiling."],
  },

  // Kieran Trippier — England MID $51 PURPLE — avgFP 36.9
  trippier: {
    nicknames: ["Tripps", "Bury Beckham"],
    knownFor: "England's right-back with the wickedest set-piece delivery in the squad.",
    salaryTier: "star",
    tier1: ["When Trippier whips one in from a dead ball, the whole box holds its breath.", "He plays right-back with the brain of a midfielder and the foot of a 10.", "England's set-piece secret weapon for two World Cups running."],
    tier2: ["Manchester City youth product who couldn't break through — left for Burnley, then made his name.", "Spent two years at Atlético Madrid winning La Liga before coming home to Newcastle.", "Free-kick goal in the 2018 World Cup semifinal — Trippier's signature moment."],
    tier3: ["His delivery is statistically among the most accurate in the Premier League era.", "Took a brief gambling-related ban from the FA in 2020 — handled it quietly and moved on."],
    overperform: ["When Tripps gets the ball wide, every set piece is a chance.", "Two assists from corners and a cross that nearly broke the net — the full Trippier shift.", "Right-back, right footed, right place every time."],
    underperform: ["Even the best deliverers have nights when the corners don't quite curl.", "Defensive errors creep in when the legs are tired — happens to every overlapping fullback.", "Quiet game — but the set pieces still threatened."],
    onPace: ["Standard Tripps — five crosses, two corners that nearly went in, no mistakes at the back.", "Defended his side, attacked his side, repeated for 90.", "The complete fullback shift."],
    loosePlay: ["Caught upfield on a counter — the overlapping fullback's eternal risk.", "Misplaced a long ball — rare for him.", "A booking for a tactical foul — sometimes needed."],
    defensive: ["Tackles cleanly, intercepts intelligently, marks tightly — a complete defensive performance.", "His positional discipline is why Southgate kept picking him.", "The unsexy fullback work — done to perfection."],
    bigGame: ["TRIPPIER. The whip from the wide right just curled into the top corner.", "This is what set-piece football looks like at the highest level.", "Bury Beckham, indeed."],
    quietGame: ["Quiet shift — defended his flank, didn't get forward as often.", "Subbed at 75 — saving him for the next round.", "Frustrated by the tight space, but the back four held."],
    controversy: ["The 2020 FA gambling ban — 10 weeks for sharing transfer info, fully served.", "Atletico-Newcastle transfer in 2022 raised eyebrows about player power."],
    famousGameHint: ["Look up his free-kick goal in the 2018 World Cup semifinal vs Croatia — opened the scoring at Wembley.", "His set-piece delivery numbers from the 2022 cycle — top three in the tournament.", "Won La Liga with Atlético Madrid in 2021 — the only Englishman in the squad."],
    opponentFlavor: {
      IRN: "Group-stage opener — assist from a corner, England won 6-2.",
      USA: "Group-stage 0-0 draw — quiet but solid defensive shift.",
      WAL: "Group-stage closer — set up the third goal from a delivery.",
      SEN: "Round-of-16 — defensive shift, no errors, England won 3-0.",
      FRA: "Quarterfinal — beaten in his individual matchup with Mbappé occasionally, but recovered.",
    },
    formerTeam: ["Manchester City academy → Burnley → Tottenham → Atlético Madrid → Newcastle.", "La Liga winner with Atlético Madrid in 2021 — a rare English title abroad."],
    rivalry: ["Spurs vs Atletico vs Newcastle — three clubs, three sets of fans, mutual respect everywhere."],
    milestones: ["La Liga title with Atlético Madrid (2021).", "Free-kick goal in the 2018 World Cup semifinal.", "Multiple England starts across two World Cups."],
    teamContext: ["Southgate's set-piece anchor — Trippier's delivery is a tactical weapon.", "Right-back of the Newcastle revolution under Eddie Howe.", "England's most reliable fullback of the 2022 cycle."],
    salaryNarrative: ["At $51 PURPLE he's the set-piece bonus pick.", "Defensive shift plus assist threat — the value combo at the price.", "PURPLE because the role is fullback; the production is winger-tier."],
  },

  // Jae-Sung Lee — South Korea MID $50 PURPLE — avgFP 36.1
  lee: {
    nicknames: ["Jae-Sung", "JSL"],
    knownFor: "South Korea's box-to-box engine — Mainz's Bundesliga regular and Son's midfield partner.",
    salaryTier: "star",
    tier1: ["When Lee Jae-Sung gets going, Korea's midfield runs on his lungs.", "The kind of midfielder who does five things every play and only one of them shows up on the stat sheet.", "Mainz fans will tell you — this is the most underrated Korean export of the modern era."],
    tier2: ["Came through Jeonbuk Hyundai's academy — Korea's domestic powerhouse.", "Holstein Kiel made him a Bundesliga 2 star; Mainz promoted him to the top flight.", "Three World Cup cycles for the Taeguk Warriors."],
    tier3: ["Plies his trade in the Bundesliga's middle tier — never a star, always a starter.", "Korean football's quiet engine for nearly a decade."],
    overperform: ["When Lee's lungs are on, Korea's pressing trap snaps into place.", "Box-to-box shift with the assist nobody saw coming.", "The unsung Korean midfielder showed up tonight."],
    underperform: ["Even Jae-Sung has nights when the press doesn't trigger.", "Marked closely; the engine ran on fumes.", "Quiet game by his standards."],
    onPace: ["Standard Lee shift — three tackles, two through-balls, every recovery completed.", "Did the dirty work and made the smart pass.", "Reliable. Disciplined. Korean football's metronome."],
    loosePlay: ["A heavy touch under press in midfield.", "Tried to thread a pass nobody else could see.", "Caught dribbling into a Bundesliga-style press trap."],
    defensive: ["Tackles like a Bundesliga 6, intercepts like a 10.", "Pressed the centerback into a panicked clearance.", "His ball-winning is the Korean defensive engine."],
    bigGame: ["LEE JAE-SUNG. Korea's heart is in midfield, and tonight it's pumping loud.", "This is the Mainz man at full Bundesliga output.", "The Taeguk Warriors' engine just took over."],
    quietGame: ["Quiet shift — Korea defensive, Lee played his role.", "Marked out by tier-one opposition.", "Subbed at 75 — saving him for the next match."],
    controversy: ["Korean federation politics never quite reach him — he stays above it.", "Bundesliga refereeing has caught him a few yellow cards he didn't deserve."],
    famousGameHint: ["Look up Korea-Portugal 2022 — Korea won 2-1 to advance, and Lee was in the engine room.", "His Bundesliga form for Mainz across the 2021/22 season — the launchpad to Qatar."],
    opponentFlavor: {
      URU: "Group-stage 0-0 draw — disciplined defensive shift.",
      GHA: "Group-stage 3-2 loss — battled, came up short.",
      POR: "The 2-1 win to advance — Lee at the heart of the late surge.",
      BRA: "Round-of-16 4-1 loss — outclassed but he ran 90 minutes anyway.",
    },
    formerTeam: ["Jeonbuk Hyundai academy → K League 1 → Holstein Kiel → Mainz.", "Bundesliga regular for Mainz since 2021."],
    milestones: ["Multiple K League 1 titles with Jeonbuk.", "Bundesliga regular at Mainz.", "Three World Cup cycles for South Korea."],
    teamContext: ["Korea's midfield identity is built around his work-rate.", "Paulo Bento's pressing system depends on his positional discipline.", "When Lee runs, Korea run."],
    salaryNarrative: ["At $50 PURPLE he's the volume midfielder pick.", "PURPLE because the production is reliable, not flashy.", "The kind of pick you take for the floor."],
  },

  // Wahbi Khazri — Tunisia MID $49 PURPLE — avgFP 35.8
  khazri: {
    nicknames: ["Wahbi", "Khazri"],
    knownFor: "Tunisia's set-piece dead-ball specialist and Saint-Étienne's longtime creator.",
    salaryTier: "star",
    tier1: ["When Khazri stands over a free kick, the whole box leans forward.", "Tunisia's most-capped attacker of the modern era.", "Ligue 1's underrated playmaker, North Africa's reliable star."],
    tier2: ["Born in Ajaccio, raised in Corsica, plays for Tunisia — a French-Tunisian dual story.", "Saint-Étienne for half a decade — the franchise creator.", "Captained the Eagles of Carthage through the 2022 cycle."],
    tier3: ["His left foot has been Tunisia's dead-ball weapon for nearly a decade.", "Brief Sunderland spell in 2016 — relegation year, but his free kicks were the brightest spot."],
    overperform: ["When Khazri's left foot is speaking, defenders just listen.", "An assist from a corner, a goal from a free kick — vintage Wahbi.", "The dead-ball master at full output."],
    underperform: ["Even Khazri has nights when the set pieces don't curl.", "Marked closely; the playmaker passes had nowhere to go.", "Quiet game by his standards."],
    onPace: ["Standard Khazri shift — three crosses, a free kick on target, the threat constant.", "Did the playmaker work and took the dead balls.", "Reliable creator from set pieces."],
    loosePlay: ["A heavy touch under press.", "Tried a flick that wasn't on.", "A booking for tactical frustration."],
    defensive: ["Tracks back when Tunisia need it.", "Pressed the centerback into a panicked clearance.", "Won a tackle in his own third — the unglamorous playmaker work."],
    bigGame: ["KHAZRI. The dead ball just curled past the wall.", "This is what set-piece football looks like at North African elite level.", "Tunisia's left foot just shook the pitch."],
    quietGame: ["Quiet shift — Tunisia defensive, Khazri played his role.", "Marked out by tier-one opposition.", "Subbed at 70 — saving the legs."],
    controversy: ["His French-Tunisian heritage occasionally causes friction in both fan bases.", "Saint-Étienne's relegation woes put a difficult end to his Ligue 1 stint."],
    famousGameHint: ["Look up Tunisia-France 2022 — Khazri scored the winner in a 1-0 shock.", "His set-piece numbers across Ligue 1 — top five for free-kick conversion in his peak years."],
    opponentFlavor: {
      FRA: "The 1-0 winner — Khazri scored the shocking goal that beat the eventual finalists.",
      AUS: "Group-stage 1-0 loss — fought, came up short.",
      DEN: "Group-stage 0-0 draw — set-piece threats but no breakthrough.",
    },
    formerTeam: ["Bastia raised him; Bordeaux gave him Ligue 1; Sunderland was a brief Premier League taste.", "Saint-Étienne for half a decade — the franchise creator.", "Montpellier in the latter years."],
    rivalry: ["Tunisia-Algeria is the African Clásico — Khazri's free kicks have been at the heart of it for years."],
    milestones: ["Multiple Tunisia top-scorer awards.", "Ligue 1 regular for over a decade.", "Eagles of Carthage captain at the 2022 World Cup."],
    teamContext: ["Tunisia's tournament identity in 2022 was built around his set-piece threat.", "Captain, creator, dead-ball specialist — all in one body.", "When Khazri's left foot is on, Tunisia have a chance."],
    salaryNarrative: ["At $49 PURPLE he's the dead-ball pick.", "PURPLE because the goals come in clusters around set pieces.", "The kind of pick you take when Tunisia have favorable refereeing."],
    signatureGames: [
      { date: "2022-11-30", opponent: "FRA", fp: 60, line: "The 1-0 winner — Tunisia shocked the eventual finalists, and Khazri scored." },
    ],
  },

  // Rodrigo Bentancur — Uruguay MID $49 PURPLE — avgFP 35.3
  bentancur: {
    nicknames: ["Bentancur", "Rodrigo"],
    knownFor: "Uruguay's deep-lying midfield engine — Spurs' South American conductor.",
    salaryTier: "star",
    tier1: ["When Bentancur receives the ball under press, time slows down.", "Uruguay's midfield is built around his composure.", "Spurs paid €25m for him and got every euro back in the first season."],
    tier2: ["Boca Juniors raised him; Juventus signed him at 19; Spurs poached him at 24.", "Three World Cup cycles for La Celeste — the constant in Uruguay's midfield.", "Italian-Uruguayan football pedigree — the family business is football."],
    tier3: ["His knee injury in 2023 cost him most of the Spurs season — but he came back strong.", "Has been Uruguay's defensive midfield anchor since the post-Diego Godín era began."],
    overperform: ["When Bentancur is on, Uruguay's midfield doesn't lose the ball.", "Three interceptions, two through-balls, the shape held all match.", "The South American 6 at full output."],
    underperform: ["Even Bentancur has nights when the press is too tight.", "Marked closely; the deep playmaker passes had nowhere to go.", "Quiet game by his standards."],
    onPace: ["Standard Bentancur shift — five tackles, four progressive passes, no mistakes.", "Did the dirty work and made the smart pass.", "Reliable. Composed. Uruguay's metronome."],
    loosePlay: ["A heavy touch under press — rare for him.", "Tried to thread a pass that wasn't quite on.", "A booking for tactical frustration."],
    defensive: ["Tackles cleanly, intercepts intelligently, holds shape — a complete defensive midfielder.", "His positional reading is why Spurs trust him.", "The unsexy 6 work — done to perfection."],
    bigGame: ["BENTANCUR. Uruguay's heart is in midfield, and tonight it's beating loud.", "This is what a South American 6 looks like at full Premier League level.", "La Celeste's engine just took over."],
    quietGame: ["Quiet shift — Uruguay defensive, Bentancur played his role.", "Marked out by tier-one opposition.", "Subbed at 75 — minutes managed."],
    controversy: ["Caught up in a six-game ban for an alleged racial slur in 2023 — apologized, served the ban, moved on.", "Italian-Uruguayan dual heritage occasionally causes selection debates."],
    famousGameHint: ["Look up Uruguay-Portugal 2022 — Uruguay lost 2-0 but Bentancur ran the midfield.", "His Spurs form across the 2022/23 season — Premier League's most underrated 6."],
    opponentFlavor: {
      KOR: "Group-stage 0-0 draw — disciplined defensive shift.",
      POR: "Group-stage 2-0 loss — outclassed but he ran 90.",
      GHA: "Group-stage 2-0 win — Uruguay went out on goal difference, but Bentancur was the engine.",
    },
    formerTeam: ["Boca Juniors raised him.", "Juventus 2017–2022 — won multiple Serie A titles.", "Tottenham 2022–present — Spurs' midfield anchor."],
    rivalry: ["Uruguay-Argentina-Brazil — the eternal South American triangle.", "His club tussles with Brazilian midfielders are must-watch."],
    milestones: ["Multiple Serie A titles with Juventus.", "Premier League regular at Spurs.", "Three World Cup cycles for Uruguay."],
    teamContext: ["Uruguay's midfield identity is built around his composure.", "The post-Godín era pivoted to his ball-progression.", "When Bentancur plays, Uruguay's shape holds."],
    salaryNarrative: ["At $49 PURPLE he's the floor pick.", "PURPLE because the production is reliable, not flashy.", "The kind of pick you take for the shape, not the goals."],
  },

  // Niclas Füllkrug — Germany FWD $59 ORANGE — avgFP 33.4
  füllkrug: {
    nicknames: ["Lücke", "Füllkrug", "The Werder Wall"],
    knownFor: "Germany's late-blooming target striker — Bremen folk hero, Qatar's surprise package.",
    salaryTier: "max",
    tier1: ["When Füllkrug arrives at the back post, the whole box pivots.", "He plays the number 9 like it's still 1995 — and it works.", "Germany's surprise tournament weapon at 29 years old."],
    tier2: ["Spent half a decade in Bundesliga 2 before breaking through at Werder Bremen at 28.", "Earned his first Germany cap at 29 and scored on debut.", "The classical centre-forward Germany had been missing for a decade."],
    tier3: ["Famous for the gap-toothed smile that gave him the nickname 'Lücke' (the gap).", "Werder Bremen fans treat him like a folk hero — the working-man's striker."],
    overperform: ["When Füllkrug arrives, the back post is his.", "Two goals from set pieces, an assist from a knockdown — vintage target-man shift.", "Germany's classical 9, fully on tonight."],
    underperform: ["Even Lücke has nights when the crosses don't find him.", "Marked closely by tier-one defenders — credit the centerback.", "Quiet game — Germany's wide play wasn't reaching him."],
    onPace: ["Standard Füllkrug shift — a goal from a knock-down, two headers, the post hit once.", "Held the ball up, brought others into play, finished one chance.", "Classical 9, classical shift."],
    loosePlay: ["A clumsy touch — the price of being a target striker.", "Caught offside three times — the price of always running the line.", "A booking for a frustrated foul on a centerback."],
    defensive: ["Defends corners like a centerback in striker's clothes.", "Won a header in his own box — the complete striker.", "Pressed the keeper into a hurried clearance."],
    bigGame: ["FÜLLKRUG. The Werder Wall just smashed it home.", "This is what a target striker looks like at full Bundesliga output.", "Germany found their classical 9 just in time."],
    quietGame: ["Quiet shift — Germany's wide play wasn't reaching him.", "Subbed at 75 — Flick managing the legs.", "Marked tightly by Costa Rica's centerbacks. Nothing came of it."],
    controversy: ["Hansi Flick's selection was questioned at the time — vindicated by Füllkrug's tournament.", "Bremen's relegation-promotion saga is its own genre — Füllkrug was the constant."],
    famousGameHint: ["Look up Germany-Spain 2022 — Füllkrug came off the bench and equalized in the 83rd minute.", "His Werder Bremen form across the 2022/23 Bundesliga season — top scorer in Germany."],
    opponentFlavor: {
      JPN: "Group-stage 2-1 loss — Germany's shock opening defeat. Füllkrug was on the bench.",
      ESP: "The 1-1 draw — Füllkrug came off the bench and scored the equalizer in the 83rd.",
      CRC: "Group-stage 4-2 win — Germany advanced on goal difference. Füllkrug scored.",
    },
    formerTeam: ["Werder Bremen — the folk hero years.", "Spent time at Hannover and Nürnberg in Bundesliga 2 before the Bremen breakthrough.", "Borussia Dortmund signed him in 2023."],
    rivalry: ["Germany-Italy, Germany-Netherlands, Germany-Spain — the eternal European triangle.", "Werder Bremen vs Hamburg has been at the heart of his Bundesliga career."],
    milestones: ["Bundesliga top scorer 2022/23.", "Germany debut goal at 29.", "World Cup goalscorer."],
    teamContext: ["Hansi Flick's late-tournament solution — the target striker Germany had been missing.", "Germany's wide play needed a target; Füllkrug was the answer.", "When the crosses come in, he's there. That's the role."],
    salaryNarrative: ["At $59 ORANGE he's the surprise high-tier — Spain equalizer or bust.", "Cap-eater because Germany's whole attack came through him.", "ORANGE for a reason — when he scores, he scores big."],
    signatureGames: [
      { date: "2022-11-27", opponent: "ESP", fp: 65, line: "Came off the bench, equalized in the 83rd, kept Germany alive." },
      { date: "2022-12-01", opponent: "CRC", fp: 50, line: "Scored in the 4-2 win — Germany went out on goal difference, but he didn't go quietly." },
    ],
  },

  // Mohamed Salisu — Ghana DEF $48 PURPLE — avgFP 32.3
  salisu: {
    nicknames: ["Salisu", "Mohamed"],
    knownFor: "Ghana's Premier League centerback — Southampton's rock, Black Stars' anchor.",
    salaryTier: "star",
    tier1: ["When Salisu steps in front of a striker, the striker reconsiders.", "Ghana's defensive identity in Qatar started with him.", "Southampton's most-coveted centerback before the Monaco move."],
    tier2: ["Came through Real Valladolid in Spain — La Liga's African pipeline at work.", "Southampton signed him in 2020 — the year Ghana finally had a Premier League rock again.", "Switched from Spain U20 to Ghana senior — vindicated by the 2022 World Cup call-up."],
    tier3: ["Born in Accra; moved to Spain at 18 to pursue football.", "His debut for Ghana came in 2022 — late call-up, instant starter."],
    overperform: ["When Salisu is on, the strikers vanish.", "Three clearances on the line, two interceptions in the channel — vintage Premier League centerback shift.", "Ghana's defensive backbone showed up tonight."],
    underperform: ["Even Salisu has nights when the line gets caught.", "A defensive error — happens to every centerback.", "Quiet game by his standards — but the back four still held."],
    onPace: ["Standard Salisu shift — five clearances, two interceptions, no mistakes.", "Won his aerial duels, cleared his line, played his shape.", "Reliable. Composed. Ghana's anchor."],
    loosePlay: ["A heavy touch under press — rare for him.", "Misplaced a long ball.", "A booking for a tactical foul."],
    defensive: ["Tackles cleanly, intercepts intelligently, marks tightly — a complete centerback performance.", "His positional reading is Premier League-grade.", "The kind of defending that wins Premier League seasons."],
    bigGame: ["SALISU. Ghana's wall just held against the wave.", "This is what a Premier League centerback looks like at full African output.", "The Black Stars have a rock at the back — and tonight everyone watching saw why."],
    quietGame: ["Quiet shift — Ghana's defensive structure held.", "Subbed at 75 — minutes managed.", "Frustrated by tier-one strikers, but the line held."],
    controversy: ["Switched from Spain U20 to Ghana senior — Spanish federation wasn't thrilled, but FIFA's rules permitted it.", "Southampton's relegation in 2023 was a difficult chapter — but he stayed loyal."],
    famousGameHint: ["Look up Ghana-South Korea 2022 — Ghana won 3-2, but Salisu's defensive shifts kept the score reachable.", "His Premier League form across the 2021/22 season — Southampton's MVP."],
    opponentFlavor: {
      POR: "Group-stage 3-2 loss — Ghana fought hard, lost by an inch.",
      KOR: "The 3-2 win — Ghana's only victory of the campaign.",
      URU: "Group-stage 2-0 loss — Ghana went out on goal difference. Bitter exit.",
    },
    formerTeam: ["Real Valladolid raised him in Spain.", "Southampton signed him in 2020 for €13m — the bargain of the year.", "Monaco bought him in 2023 — Ligue 1's African pipeline."],
    rivalry: ["Ghana-Uruguay has been a World Cup grudge match since 2010 — Suarez's handball haunts a generation.", "African Cup of Nations rivalries with Egypt, Morocco, Senegal."],
    milestones: ["Premier League regular at Southampton.", "Ghana senior debut and instant starter.", "Black Stars' 2022 World Cup centerback."],
    teamContext: ["Ghana's defensive identity in 2022 was built around him and Daniel Amartey.", "Otto Addo's tactical setup needed a Premier League centerback — Salisu delivered.", "When Salisu plays, the Black Stars have a chance."],
    salaryNarrative: ["At $48 PURPLE he's the defensive floor pick.", "PURPLE because the role is defensive; the production is captain-tier.", "The kind of pick you take for the shape, not the goals."],
  },

  // Jurriën Timber — Netherlands DEF $45 PURPLE — avgFP 30.6
  timber: {
    nicknames: ["Timber", "Jurriën"],
    knownFor: "Ajax's homegrown centerback — Arsenal's heir to William Saliba's partnership.",
    salaryTier: "star",
    tier1: ["When Timber steps out with the ball, you remember Ajax's pipeline still works.", "The Dutch centerback who plays like a midfielder and defends like a 30-year-old.", "Arsenal's £40m signing in 2023 — for a reason."],
    tier2: ["Came through Ajax's De Toekomst academy — the pipeline that produced De Ligt, Frenkie de Jong, and the rest.", "Ajax first-team debut at 19; centerback partner with Lisandro Martinez before both left.", "Twin brother Quinten plays for Utrecht — the Timber family is football."],
    tier3: ["Born in Utrecht; raised in the Ajax system from age 9.", "Has played centerback, right-back, and defensive midfield — Van Gaal's tactical Swiss army knife."],
    overperform: ["When Timber is on, Netherlands' defensive structure holds.", "Five clearances, two interceptions, three progressive passes from the back.", "The Ajax pipeline at full output."],
    underperform: ["Even Timber has nights when the press is too high and the line breaks.", "A defensive error — happens to every centerback.", "Quiet game by his standards — but the shape held."],
    onPace: ["Standard Timber shift — clean defensive performance, ball-progression from the back.", "Won his aerial duels, played his shape, started attacks.", "Modern Dutch centerback — exactly the role."],
    loosePlay: ["A heavy touch under press — rare for him.", "Misplaced a switch of play.", "A booking for tactical disruption."],
    defensive: ["Tackles cleanly, intercepts intelligently, plays the shape.", "His positional reading is Ajax-trained, Premier League-tested.", "The complete modern centerback."],
    bigGame: ["TIMBER. The Dutch wall just stood firm.", "This is what an Ajax centerback looks like at full international output.", "Netherlands have a defender — the future is now."],
    quietGame: ["Quiet shift — Dutch shape held.", "Subbed at 75 — Van Gaal managing minutes.", "Frustrated by quick attacks, but the line stayed disciplined."],
    controversy: ["Manchester United wanted him in 2022 — Ten Hag pushed for it; Timber chose to stay.", "Arsenal signed him in 2023 — and he tore his ACL on debut. Cruel timing."],
    famousGameHint: ["Look up Netherlands-Argentina 2022 quarterfinal — penalty shootout heartbreak after a 2-2 ninety.", "His Ajax form across the 2021/22 Eredivisie season — Champions League regular at 21."],
    opponentFlavor: {
      SEN: "Group-stage 2-0 win — Timber and Van Dijk locked Senegal out.",
      ECU: "Group-stage 1-1 draw — quiet defensive shift.",
      QAT: "Group-stage 2-0 win — comfortable.",
      USA: "Round-of-16 3-1 win — Timber's defensive shift was tournament-best.",
      ARG: "Quarterfinal — 2-2 after 120, Argentina won on penalties. Timber didn't lose his individual shift.",
    },
    formerTeam: ["Ajax academy → first team → Arsenal in 2023 for €40m.", "Should have been at Manchester United in 2022 — Ten Hag wanted him."],
    rivalry: ["Ajax vs Feyenoord — the eternal Dutch rivalry shaped him.", "Netherlands-Belgium is a quiet rivalry now, but his generation will revive it."],
    milestones: ["Eredivisie titles with Ajax.", "Champions League regular at 21.", "Arsenal signing in 2023 — the £40m heir."],
    teamContext: ["Van Gaal's tactical Swiss army knife — centerback, right-back, defensive midfield.", "Netherlands' defensive future built around him and Van Dijk.", "When Timber plays, the shape doesn't break."],
    salaryNarrative: ["At $45 PURPLE he's the modern defender pick.", "PURPLE because the production is steady, not flashy.", "The kind of pick you take for the cap room."],
    draftAndPath: ["De Toekomst academy from age 9.", "Ajax first-team debut at 19.", "Arsenal signing at 22 for €40m."],
  },

  // Richarlison — Brazil FWD $54 ORANGE — avgFP 30.2
  richarlison: {
    nicknames: ["Richarlison", "The Pigeon"],
    knownFor: "Brazil's pigeon-celebration striker — the bicycle kick goal of the tournament against Serbia.",
    salaryTier: "max",
    tier1: ["When Richarlison gets the ball in the box, defenders just hope it bounces somewhere else.", "Brazil's number 9 with the celebration that became a meme and a movement.", "The man who scored the goal of the 2022 World Cup."],
    tier2: ["Came through Brazilian football's lower divisions — América-MG, Fluminense, Watford.", "Everton signed him in 2018 — became a Premier League regular.", "Spurs paid €60m for him in 2022 — the year he scored the goal of the tournament."],
    tier3: ["His pigeon celebration started as a tribute to street kids in Brazil who feed pigeons.", "Mental health advocate — has spoken openly about depression and tournament pressure."],
    overperform: ["When Richarlison takes flight, defenders just watch the replay.", "A bicycle kick, a pigeon celebration, two goals — vintage Brazilian striker.", "Brazil's number 9 fully on tonight."],
    underperform: ["Even the Pigeon has nights when the crosses don't find him.", "Marked closely by tier-one defenders — credit the centerback.", "Quiet game — Brazil's wide play wasn't reaching him."],
    onPace: ["Standard Richarlison shift — a goal from a knock-down, two headers, one shot from range.", "Held the ball up, brought others into play, finished his chance.", "Brazilian 9, Brazilian shift."],
    loosePlay: ["A clumsy touch — the price of always running the line.", "Caught offside repeatedly — the price of always making the run.", "A booking for a frustrated foul on a centerback."],
    defensive: ["Defends corners like a centerback in striker's clothes.", "Won a header in his own box — the complete striker.", "Pressed the keeper into a hurried clearance."],
    bigGame: ["RICHARLISON. The bicycle kick of the tournament. THIS IS BRAZILIAN FOOTBALL.", "Out of the wardrobe of his mind — that's a finish nobody else thinks of.", "The Pigeon just flew."],
    quietGame: ["Quiet shift — Brazil's wide play wasn't reaching him.", "Subbed at 75 — Tite managing the legs.", "Marked tightly by tier-one centerbacks. Nothing came of it."],
    controversy: ["The pigeon celebration drew racism from some opposing fans — Brazil's federation called it out.", "Has been open about depression and tournament pressure — admirable in a sport that doesn't talk about it.", "Spurs form was inconsistent post-2022 — the World Cup high was hard to maintain."],
    famousGameHint: ["Look up Brazil-Serbia 2022 — Richarlison's bicycle kick was FIFA's Goal of the Tournament.", "His Everton hat-trick against Crystal Palace — the Premier League breakout.", "His 2018 World Cup appearance — quieter, but the pipeline was already showing."],
    opponentFlavor: {
      SRB: "The bicycle kick — FIFA's Goal of the Tournament. Brazil 2, Serbia 0.",
      SUI: "Group-stage 1-0 win — quiet shift, Casemiro scored.",
      CMR: "Group-stage 1-0 loss — Brazil rotated, Richarlison started anyway.",
      KOR: "Round-of-16 4-1 win — Richarlison scored in the dance party.",
      CRO: "Quarterfinal 1-1, lost on penalties — Richarlison frustrated by Croatian defenders.",
    },
    formerTeam: ["América-MG → Fluminense → Watford → Everton → Spurs.", "Everton's Premier League regular for three seasons.", "Spurs in 2022 for €60m."],
    rivalry: ["Brazil-Argentina runs through every Brazilian striker's career.", "Spurs vs Arsenal — the North London Derby has been his Premier League stage."],
    milestones: ["FIFA Goal of the Tournament 2022 (vs Serbia).", "Olympic gold with Brazil 2020 (Tokyo).", "Premier League regular for half a decade."],
    streakLines: ["Brazil's tournament hot run was Richarlison's hot run.", "The pigeon celebration came out three times in Qatar — that's a tournament streak.", "Goal contributions in every Brazilian win until the quarterfinal."],
    salaryNarrative: ["At $54 ORANGE he's Brazil's secondary striker pick after Neymar.", "Cap-eater because Brazil's whole attack came through him and Neymar.", "ORANGE for a reason — bicycle kicks count for big FP."],
    teamContext: ["Brazil's tactical 9 in 2022 — the target for crosses and the finisher of channels.", "Tite's selection vindicated by the bicycle kick.", "When Richarlison flies, Brazil have a striker."],
    draftAndPath: ["Lower-division Brazilian football — América-MG and Fluminense.", "Watford signed him in 2017; Everton in 2018; Spurs in 2022.", "The slow Premier League climb to a €60m valuation."],
    signatureGames: [
      { date: "2022-11-24", opponent: "SRB", fp: 75, line: "The bicycle kick — FIFA's Goal of the 2022 World Cup. Vintage Brazilian striker." },
      { date: "2022-12-05", opponent: "KOR", fp: 55, line: "Scored in the round-of-16 dance party — Brazil 4, Korea 1." },
    ],
  },

  // Kim Moon-Hwan — South Korea DEF $44 PURPLE — avgFP 29.9
  kim: {
    nicknames: ["Kim", "Moon-Hwan"],
    knownFor: "South Korea's right-back — Jeonbuk's overlapping fullback and Son's wide partner.",
    salaryTier: "star",
    tier1: ["When Kim Moon-Hwan overlaps, Korea's wide attack opens up.", "South Korea's right flank has been his for half a decade.", "Jeonbuk's right-back, Korea's reliable starter."],
    tier2: ["Came through the Jeonbuk Hyundai academy — Korea's domestic powerhouse.", "Multiple K League 1 titles with the franchise.", "Earned his Korea spot the hard way — through the domestic system."],
    tier3: ["Has been Korea's right-back through three different head coaches.", "Plies his trade in the K League — a rare modern Korean starter who didn't move to Europe."],
    overperform: ["When Kim's lungs are on, Korea's wide attack opens up.", "Three crosses, two recoveries, the right flank locked down.", "The complete fullback shift."],
    underperform: ["Even Kim has nights when the press catches him upfield.", "Marked closely by tier-one wingers — credit the opposition.", "Quiet game by his standards."],
    onPace: ["Standard Kim shift — defended his side, overlapped when needed, no mistakes.", "Did the dirty work and made the smart cross.", "Reliable Korean fullback — exactly the role."],
    loosePlay: ["A heavy touch on a switch of play.", "Caught upfield on a counter — the overlapping fullback's risk.", "A booking for a tactical foul."],
    defensive: ["Tackles cleanly, intercepts intelligently, marks tightly.", "His positional discipline anchors Korea's right flank.", "Disciplined fullback work — exactly the modern role."],
    bigGame: ["KIM. The Korean right flank just delivered.", "This is what a K League fullback looks like at full international output.", "The Taeguk Warriors have a defender — and tonight the world saw why."],
    quietGame: ["Quiet shift — Korea defensive, Kim played his role.", "Subbed at 75 — minutes managed.", "Frustrated by tier-one wingers, but the line held."],
    controversy: ["K League refereeing politics have caught him a few yellow cards.", "Jeonbuk's domestic dominance has put him at the heart of Korean football's biggest rivalries."],
    famousGameHint: ["Look up Korea-Portugal 2022 — Korea won 2-1 to advance, and Kim was at the heart of the right flank.", "His K League 1 form across the 2021 and 2022 seasons."],
    opponentFlavor: {
      URU: "Group-stage 0-0 draw — disciplined defensive shift on the right.",
      GHA: "Group-stage 3-2 loss — Ghana scored from his side once.",
      POR: "The 2-1 win — Kim's flank was the stable side.",
      BRA: "Round-of-16 4-1 loss — outclassed by Vinícius, but he ran 90.",
    },
    formerTeam: ["Jeonbuk Hyundai — multiple K League 1 titles.", "Tehran Tractor (Iran) brief loan."],
    milestones: ["Multiple K League 1 titles with Jeonbuk.", "AFC Champions League winner with Jeonbuk.", "Three World Cup cycles for South Korea."],
    teamContext: ["Korea's right-back identity has been his since 2018.", "Paulo Bento's pressing system depends on his positional discipline.", "When Kim plays, the right flank is steady."],
    salaryNarrative: ["At $44 PURPLE he's the volume fullback pick.", "PURPLE because the role is defensive; the production comes from set-piece volume.", "The kind of pick you take for the floor."],
  },

  // Christian Pulisic — United States FWD $51 PURPLE — avgFP 28.5
  pulisic: {
    nicknames: ["Captain America", "Pulisic", "CP10"],
    knownFor: "American football's biggest export — the Hershey kid who broke into Dortmund and Chelsea.",
    salaryTier: "star",
    tier1: ["When Pulisic gets the ball on the left, the whole American team leans forward.", "He's the most expensive American player in football history — for a reason.", "Captain America. The face of US Soccer for a decade."],
    tier2: ["Came through Borussia Dortmund's youth system — moved to Germany at 16.", "Chelsea signed him in 2019 for $73m — the most expensive American transfer ever.", "Won the Champions League with Chelsea in 2021 — first American to do so."],
    tier3: ["His grandfather is Croatian — he's eligible for Croatia but chose USA.", "Suffered a pelvic injury scoring against Iran in 2022 — the goal that sent USA to the round of 16."],
    overperform: ["When Captain America is on, the US attack runs through him.", "Two assists, a goal, the left flank his — vintage Pulisic shift.", "American football's ceiling on full display tonight."],
    underperform: ["Even Pulisic has nights when the shoulder injury or the ankle injury or the something-else injury catches up.", "Marked closely by tier-one defenders — credit the right-back.", "Quiet game — USA's wide play wasn't getting him the ball."],
    onPace: ["Standard Pulisic shift — a goal threat every time he gets the ball.", "Drove down the left, cut inside, made the defense move.", "Got his goal contribution and beat his man twice."],
    loosePlay: ["Caught dribbling into traffic on the wing.", "A heavy touch under press.", "Tried a flick that wasn't quite on."],
    defensive: ["Tracks back like a Premier League grown-up — not always, but more than you'd think.", "Pressed the centerback into a panicked clearance.", "The unsung Pulisic defensive work."],
    bigGame: ["PULISIC. CAPTAIN AMERICA. THE GOAL THAT SENT THE USA THROUGH.", "This is what American football's ceiling looks like.", "Hershey, Pennsylvania to a World Cup knockout round — that's the path."],
    quietGame: ["Marked out — sometimes the doubles team works.", "Subbed at 70 — recovering from the Iran injury.", "Quiet by his standards. Frustrated, but professional."],
    controversy: ["Chelsea form was inconsistent post-2021 — the loyalty/move debate ran for years.", "The Iran injury in 2022 was scary — he scored, then was carried off.", "AC Milan move in 2023 was needed — Chelsea wasn't working anymore."],
    famousGameHint: ["Look up USA-Iran 2022 — Pulisic's goal sent USA to the round of 16, but he had to be subbed off injured.", "His Champions League run with Chelsea in 2020/21 — the first American to lift the trophy.", "His Dortmund years from 2016-2019 — the breakthrough."],
    opponentFlavor: {
      WAL: "Group-stage 1-1 draw — Pulisic created the goal.",
      ENG: "Group-stage 0-0 draw — quiet shift, marked closely.",
      IRN: "The 1-0 win — Pulisic scored and was carried off injured. The goal that sent USA through.",
      NED: "Round-of-16 3-1 loss — the USA's tournament ended, but Pulisic ran 90.",
    },
    formerTeam: ["PA Classics youth → Dortmund academy → Dortmund first team.", "Chelsea 2019-2023 — the $73m American.", "AC Milan 2023 — the Italian chapter."],
    rivalry: ["USA-Mexico is the CONCACAF Clásico — Pulisic at the heart of it for a decade.", "USA-Canada has heated up since 2022 — generational rivalry brewing."],
    milestones: ["Champions League winner with Chelsea (2021).", "USA's all-time leading scorer.", "Most expensive American transfer ever ($73m)."],
    streakLines: ["Hot run through 2022 group stage — the Iran goal was the peak.", "Three knockout-round goals across his Chelsea Champions League run.", "American football's ceiling-raiser since 2017."],
    salaryNarrative: ["At $51 PURPLE he's the American star pick.", "PURPLE because the role is winger; the production is captain-tier when he's healthy.", "Cap-eater for a reason — the US attack runs through him."],
    teamContext: ["USA's tactical fulcrum — left winger plus 10 plus deep playmaker.", "Berhalter's tactical setup needed a creator who could carry the attack alone — Pulisic delivered.", "When Pulisic is healthy, USA have a chance. When he isn't, USA struggle."],
    draftAndPath: ["Hershey, Pennsylvania kid — not the typical American football pipeline.", "Dortmund academy at 16 — the first big American move at that age.", "Chelsea in 2019 for $73m — the most expensive American ever."],
    signatureGames: [
      { date: "2022-11-29", opponent: "IRN", fp: 50, line: "The goal that sent USA to the round of 16 — and the injury that nearly cost him the rest." },
      { date: "2022-12-03", opponent: "NED", fp: 35, line: "Round-of-16 exit — but he ran 90 minutes despite the pelvis." },
    ],
  },

  // Milan Borjan — Canada GK $48 PURPLE — avgFP 28
  borjan: {
    nicknames: ["Milan", "Borjan"],
    knownFor: "Canada's Serbian-born keeper — Red Star Belgrade legend, Maple Leaf wall.",
    salaryTier: "star",
    tier1: ["When Borjan commands his box, Canada's defensive identity holds.", "The keeper who took Red Star to a Champions League and Canada to a World Cup.", "Canadian football's most-experienced international goalkeeper."],
    tier2: ["Born in Croatia, fled to Serbia as a child during the Yugoslav wars, grew up in Canada.", "Made his name at Red Star Belgrade — multiple Serbian SuperLiga titles.", "Carried Canada's qualifying campaign for 2022 — first World Cup since 1986."],
    tier3: ["His refugee story is its own piece — Croatian-born, Serbian heritage, Canadian flag.", "Has been Canada's #1 keeper for over a decade — through generations of changing rosters."],
    overperform: ["When Borjan is hot, the goal disappears.", "Three saves from the angles, two penalty stops in the bag — vintage Red Star shift.", "Canada's wall held firm tonight."],
    underperform: ["Even Borjan has nights when the corner finds the corner.", "Conceded — but kept the score reachable.", "A keeper's bad night — sometimes the ball just won't stop."],
    onPace: ["Standard Borjan shift — calm, positioned, hard to beat from anywhere.", "Made the saves he was supposed to and found the long pass.", "Reliable Canadian wall."],
    loosePlay: ["Caught off his line on a cross.", "Punched when he should have caught.", "A long ball that didn't quite go where he intended."],
    defensive: ["Commands his box like a captain.", "Two-handed catch in traffic — exactly the textbook.", "Read the cross before the striker arrived."],
    bigGame: ["BORJAN. The Canadian wall just held.", "This is the keeper performance that puts a country on the map.", "Red Star to Doha — the journey vindicated."],
    quietGame: ["Quiet day — Canadian back four did the heavy lifting.", "A handful of saves, all of them routine.", "Asked little, delivered everything."],
    controversy: ["His Croatian-Serbian-Canadian heritage is its own story — handled with grace.", "Canada's 2022 federation labor dispute caught him in the headlines briefly."],
    famousGameHint: ["Look up Canada's 2022 World Cup qualifying campaign — first since 1986, and Borjan was the lock.", "His Champions League nights with Red Star Belgrade — multiple group-stage runs."],
    opponentFlavor: {
      BEL: "Group-stage 1-0 loss — Canada's first WC game since 1986. Borjan saved a penalty in the loss.",
      CRO: "Group-stage 4-1 loss — Croatia were too much, but Borjan ran 90.",
      MAR: "Group-stage 2-1 loss — Canada went out winless, but the experience was built.",
    },
    formerTeam: ["Red Star Belgrade — multiple Serbian SuperLiga titles.", "Brief stints at Korona Kielce (Poland) and Slovan Liberec (Czech).", "Slavia Prague briefly before Red Star."],
    rivalry: ["Red Star vs Partizan is the Eternal Derby — Borjan was at the heart of it for years.", "Canada-USA-Mexico is the CONCACAF triangle."],
    milestones: ["Multiple Serbian SuperLiga titles with Red Star.", "Champions League group-stage appearances with Red Star.", "Canada's first World Cup keeper since 1986."],
    teamContext: ["Canada's defensive identity in 2022 was built around him at the back.", "John Herdman's tactical setup needed a calm keeper — Borjan delivered.", "When Borjan plays, Canada have a chance."],
    salaryNarrative: ["At $48 PURPLE he's the experience pick.", "PURPLE because Canada conceded a lot — saves were available.", "The kind of keeper pick you take for save volume."],
    draftAndPath: ["Born in Croatia; refugee in Serbia; raised in Canada.", "Senior debut for Canada in 2008 — the long road to a World Cup.", "Red Star Belgrade made him a name in European football."],
  },

  // Dani Olmo — Spain FWD $46 PURPLE — avgFP 26.1
  olmo: {
    nicknames: ["Dani", "Olmo"],
    knownFor: "Spain's creative midfielder — La Masia kid, Leipzig's tactical fulcrum.",
    salaryTier: "star",
    tier1: ["When Olmo gets the ball between the lines, La Roja's attack unlocks.", "He's the modern Spanish 10 — Iniesta's heir in the chaos era.", "RB Leipzig's tactical fulcrum, Spain's reliable creator."],
    tier2: ["Came through La Masia — Barcelona's academy, the same one that produced Messi.", "Left for Dinamo Zagreb at 16 because Barcelona blocked his path.", "RB Leipzig signed him in 2020 — became their tactical fulcrum."],
    tier3: ["His older brother Carlos is also a footballer — La Masia produced both.", "Speaks Croatian fluently from his Dinamo Zagreb years."],
    overperform: ["When Olmo is between the lines, defenders can't decide who marks him.", "Two assists, a goal, the half-spaces fully exploited — vintage La Masia shift.", "Spain's modern 10 fully on tonight."],
    underperform: ["Even Olmo has nights when the press is too tight.", "Marked closely by tier-one midfielders — credit the opposition.", "Quiet game by his standards."],
    onPace: ["Standard Olmo shift — three through-balls, an assist, no mistakes.", "Did the playmaker work between the lines.", "Reliable Spanish creator."],
    loosePlay: ["A heavy touch under press.", "Tried to thread a pass nobody else could see.", "Caught dribbling into a triangle of three defenders."],
    defensive: ["Tracks back when Spain need it.", "Pressed the centerback into a panicked clearance.", "Won a tackle in his own third — the unsung 10 work."],
    bigGame: ["OLMO. La Roja's heart is between the lines, and tonight it's beating loud.", "This is what a La Masia 10 looks like at full Bundesliga output.", "Spain found their playmaker — the future is now."],
    quietGame: ["Quiet shift — Spain's possession was high but the half-spaces closed.", "Subbed at 75 — Luis Enrique managing minutes.", "Marked tightly by tier-one midfielders."],
    controversy: ["Left La Masia at 16 because Barcelona blocked his path — vindicated by his Spain career.", "Barcelona transfer rumors have followed him since 2022 — he says he wants to come home eventually."],
    famousGameHint: ["Look up Spain-Costa Rica 2022 — 7-0, and Olmo opened the scoring.", "His Euro 2020 goal contributions — Spain's semifinal run.", "RB Leipzig's tactical setup is built around him."],
    opponentFlavor: {
      CRC: "Group-stage 7-0 win — Olmo opened the scoring in a thrashing.",
      GER: "Group-stage 1-1 draw — quiet shift, Spain's high possession didn't translate.",
      JPN: "Group-stage 2-1 loss — Spain advanced on goal difference, but Olmo was substituted.",
      MAR: "Round-of-16 0-0, Spain lost on penalties — Morocco's Bono saved two.",
    },
    formerTeam: ["La Masia academy → Dinamo Zagreb at 16 → RB Leipzig at 22.", "Croatian league title with Dinamo Zagreb."],
    rivalry: ["Spain-Portugal — the Iberian Clásico has been his international stage.", "Bundesliga vs La Liga is a stylistic rivalry he embodies."],
    milestones: ["Croatian league title with Dinamo Zagreb.", "Champions League regular with RB Leipzig.", "Euro 2020 semifinalist with Spain."],
    teamContext: ["Spain's creative fulcrum in 2022 — the half-space player Luis Enrique built around.", "When Olmo plays well, Spain look unstoppable. When he doesn't, Spain look ordinary.", "La Roja's modern 10 — the Iniesta heir in the chaos era."],
    salaryNarrative: ["At $46 PURPLE he's the Spanish creator pick.", "PURPLE because Spain's possession is high but the goals can be scarce.", "The kind of pick you take for assist volume."],
    draftAndPath: ["La Masia academy — the same pipeline that produced Messi.", "Dinamo Zagreb at 16 because Barcelona blocked his first-team path.", "RB Leipzig in 2020 — the Bundesliga breakthrough."],
  },

  // Thibaut Courtois — Belgium GK $37 BLUE — avgFP 21.1
  courtois: {
    nicknames: ["Thibaut", "Courtois", "The Wall"],
    knownFor: "Real Madrid's Champions League final hero — the best goalkeeper in the world on his day.",
    salaryTier: "max",
    tier1: ["When Courtois is on, the goal becomes a postage stamp.", "The keeper who won the 2022 Champions League final basically by himself.", "On his day, the best goalkeeper on the planet — and his day comes often."],
    tier2: ["Came through Genk's academy in Belgium — Genk's pipeline at work.", "Atlético Madrid loan at 19 — La Liga winner before he turned 21.", "Chelsea 2014-2018, Real Madrid 2018-present — five seasons of Madrid magic."],
    tier3: ["Stands 6'7\" — one of the tallest goalkeepers in modern football.", "Won the Yashin Trophy in 2022 — the first keeper to win it as a Real Madrid player."],
    overperform: ["When Courtois is hot, strikers shrug and accept it.", "Eight saves, two penalty stops, the wall held all night.", "Real Madrid's Champions League hero at full international output."],
    underperform: ["Even Courtois has nights when the ball finds the corner.", "Conceded — but kept the score reachable.", "A keeper's bad night — sometimes the deflections all go the wrong way."],
    onPace: ["Standard Courtois — calm, positioned, hard to beat.", "Made the saves he was supposed to and found the long pass.", "Reliable Belgian wall."],
    loosePlay: ["Caught off his line on a cross — rare for him.", "Punched when he should have caught.", "A goal kick that didn't quite reach the target."],
    defensive: ["Commands his box like a 6'7\" captain.", "Two-handed catch in traffic — textbook.", "Read the cross before the striker arrived."],
    bigGame: ["COURTOIS. The Belgian wall just stood firm.", "This is what Yashin Trophy form looks like.", "Real Madrid's Champions League hero just owned 90 more minutes."],
    quietGame: ["Quiet day — Belgian back four did the heavy lifting.", "A handful of routine saves.", "Asked little, delivered everything."],
    controversy: ["Refused to take a Belgium press conference in 2022 about not getting a captain's role — front-page Belgian news.", "His Belgium career has been complicated by golden-generation politics.", "Withdrew from Belgium's 2024 cycle — handled professionally but it shaped the team."],
    famousGameHint: ["Look up Real Madrid vs Liverpool 2022 Champions League final — Courtois made nine saves and won the trophy almost single-handedly.", "His Belgium 2018 World Cup performances — the bronze-medal run.", "His Atlético Madrid title-winning loans 2011-2014."],
    opponentFlavor: {
      CAN: "Group-stage 1-0 win — Courtois saved a Davies penalty in a tight match.",
      MAR: "Group-stage 2-0 loss — the upset that started Morocco's run.",
      CRO: "Group-stage 0-0 draw — Belgium went out, Courtois was the bright spot.",
    },
    formerTeam: ["Genk academy → Atlético Madrid loans (2011-2014) → Chelsea (2014-2018) → Real Madrid (2018-present).", "Multiple Champions League titles with Real Madrid."],
    rivalry: ["Real Madrid vs Barcelona — El Clásico has been his stage for half a decade.", "Belgium's golden generation politics put him at the heart of every captaincy debate."],
    milestones: ["Champions League winner with Real Madrid (2022).", "Yashin Trophy 2022 — best goalkeeper in the world.", "Multiple La Liga titles."],
    streakLines: ["Real Madrid form bled directly into Belgium tournament play — when he's on, he's untouchable.", "Eight-saves-or-more performances are a Courtois streak across multiple seasons.", "The 2022 Champions League run was a one-man show."],
    salaryNarrative: ["At $37 BLUE he's the bargain keeper pick of the board — Yashin Trophy winner at value pricing.", "BLUE because Belgium underwhelmed in Qatar; the keeper market reflects it.", "The most paid-off BLUE keeper in the pool when he plays."],
    teamContext: ["Belgium's golden generation went out in the group stage — disappointing end to a cycle.", "Roberto Martinez's tactical setup needed Courtois to bail out the defense — sometimes he could, sometimes he couldn't.", "When Courtois plays the way he does for Real Madrid, Belgium have a chance."],
    draftAndPath: ["Genk academy from age 8.", "Atlético Madrid bought him at 19 and loaned him back — La Liga title at 21.", "Chelsea 2014; Real Madrid 2018 — the standard top-of-the-game keeper path."],
    signatureGames: [
      { date: "2022-11-23", opponent: "CAN", fp: 35, line: "Saved a penalty from Davies — Belgium won 1-0, and Courtois was the difference." },
    ],
  },

