/**
 * basketball/src/components/DailySeasonReelGate.tsx
 *
 * Wraps the game view with a once-per-UTC-day "season reel" reveal. On the
 * first game entry of the day, the reel animates and lands on the
 * predetermined season picked by `pickTodaysSeason`. On subsequent entries
 * within the same UTC day, the gate is transparent — children render
 * immediately.
 *
 * Season coupling: the daily season follows the daily BOSS. The gate pins the
 * active season to the boss's season (boss anchors the day; solo slate follows),
 * so the boss page and solo play always read ONE season. `pickTodaysSeason`
 * remains as the safe fallback when a boss season isn't in the solo manifest.
 * The picked season drives the data layer via setActiveSeason → ensureLoaded.
 */

import { useEffect, useRef, useState } from "react";
import {
  loadSeasonsManifest,
  manifestLabelsChronological,
  pickTodaysSeason,
  type SeasonsManifest,
  type SeasonManifestEntry,
} from "@shared/utils/seasonPicker";
import { getDailyBonusDateKey } from "@shared/utils/dailyBonus";
// Precomputed daily boss-season schedule. seasons[dayOffsetFromEpoch] = the
// boss's season_code for that day, generated by the SAME canonical resolver the
// boss writer uses (scripts/build-boss-schedule.mjs; drift + anti-fork guarded
// by api/__tests__/boss-schedule-artifact-drift.test.ts). Imported as pure JSON
// because the resolver itself (scheduleHeadline → node:crypto, plus node:fs in
// bossGenerator) cannot enter the SPA bundle.
import bossSchedule from "@shared/data/bossSchedule.generated.json";
import { SeasonReel } from "@shared/components/SeasonReel";
import { SeasonIntroOverlay } from "@shared/components/SeasonIntroOverlay";
// Side-effect import — basketball's wrapper calls configurePerSeason() so
// importing it here guarantees the engine is in per-season mode by the
// time we call setActiveSeason.
import "../engines/dataEngine";
import { setActiveSeason } from "@shared/engines/dataEngine";
import seasonIntros from "../data/seasonIntros.json";

const MANIFEST_URL = "/basketball/data/seasons/_manifest.json";
const TODAYS_PICK_KEY = "replaymod_todays_season_pick_basketball";
/** When the FTUE bypass is on, pin to the latest season — that's what the
 *  ceremony wall (real 2025-26 First-Team cards) + scripted hand expect.
 *  Any newer season key takes precedence if added in the future; this is
 *  the conservative default. */
const FTUE_SEASON_KEY = "2526";

type BossSchedule = { _meta: { epoch: string; horizonDays: number; bankVersion: string }; seasons: string[] };
const BOSS_SCHEDULE = bossSchedule as BossSchedule;
const BOSS_EPOCH_MS = Date.parse(BOSS_SCHEDULE._meta.epoch + "T00:00:00Z");
const DAY_MS = 86_400_000;

/**
 * Season coupling — resolve today's season FROM THE BOSS. Returns the manifest
 * entry for the boss's season on `today`, or null to fall back to the legacy
 * daily pick. Offset math matches resolveBossForDate exactly: UTC whole-day diff
 * from the epoch, clamped to >= 0 (dates before the epoch degrade to the epoch
 * day's boss). Returns null when the boss season isn't in the solo manifest so a
 * future un-manifested boss season degrades safely instead of failing to load.
 */
function pickBossSeason(today: Date, m: SeasonsManifest): SeasonManifestEntry | null {
  const seasons = BOSS_SCHEDULE.seasons;
  if (!seasons.length) return null;
  const todayKey = getDailyBonusDateKey(today); // UTC YYYY-MM-DD — same date basis as the writer
  const offset = Math.floor((Date.parse(todayKey + "T00:00:00Z") - BOSS_EPOCH_MS) / DAY_MS);
  const idx = Math.min(seasons.length - 1, Math.max(0, offset));
  const seasonKey = seasons[idx];
  return m.seasons.find(s => s.key === seasonKey) ?? null;
}

type Stored = { dateKey: string; seasonKey: string; seasonLabel: string };

function readStored(): Stored | null {
  try {
    const raw = localStorage.getItem(TODAYS_PICK_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    if (!parsed?.dateKey || !parsed?.seasonKey) return null;
    return parsed as Stored;
  } catch {
    return null;
  }
}

function writeStored(s: Stored): void {
  try { localStorage.setItem(TODAYS_PICK_KEY, JSON.stringify(s)); } catch { /* ignore */ }
}

type Props = {
  /** When true (e.g. FTUE active), the reel is bypassed entirely AND
   *  the active season is pinned to FTUE_SEASON_KEY — the hardcoded
   *  FTUE roster expects that data. Distinct from `skipReel`: bypass
   *  is the FTUE escape hatch; skipReel resolves today's season
   *  normally and only hides the animation. */
  bypass?: boolean;
  /** When true, resolve today's daily season normally (manifest +
   *  pickTodaysSeason + setActiveSeason) but never play the reel
   *  animation. Use this for routes that have their own era context
   *  (e.g. /basketball/challenge/:id, where the landing screen
   *  already shows the season-reel caption above the score). When
   *  bypass is also true, bypass wins (FTUE behavior dominates). */
  skipReel?: boolean;
  /** When `bypass` is true, override the season the data engine is
   *  pinned to. Without this, bypass mode hard-codes FTUE_SEASON_KEY —
   *  correct for FTUE (the hardcoded roster needs 2025-26 data) but
   *  WRONG for challenge replay (the recipient needs the CHALLENGE'S
   *  original season's logs so retired/historical players in the
   *  snapshot resolve correctly). Caller passes `challengeCtx?.season`
   *  here when in challenge mode. */
  bypassSeasonKey?: string | null;
  /** Glass-round-2: gate the reel decision on auth resolution. `skipReel` for
   *  the scripted FTUE is only trustworthy once auth has resolved (a signed-in
   *  user is transiently indistinguishable from a cold anon). While false, the
   *  gate holds in its loading state (children blocked) rather than risk showing
   *  the reel before the FTUE-vs-reel decision is settled. Defaults true so
   *  callers that don't pass it are never blocked. */
  authReady?: boolean;
  children: React.ReactNode;
};

export function DailySeasonReelGate({ bypass = false, skipReel = false, bypassSeasonKey = null, authReady = true, children }: Props) {
  const [manifest, setManifest] = useState<SeasonsManifest | null>(null);
  const [pick, setPick] = useState<SeasonManifestEntry | null>(null);
  // null = unresolved; true = show reel; false = skip reel
  const [shouldShowReel, setShouldShowReel] = useState<boolean | null>(null);
  // Independent gate for the season-intro overlay. Shown after the reel
  // completes OR (when reel is skipped because the user already saw it
  // earlier today) shown directly on the first game entry of the day.
  // Storage-keyed by date+seasonKey so it doesn't re-fire mid-day.
  const [showIntro, setShowIntro] = useState<boolean>(false);

  // FTUE-exit one-shot reel (feat/ftue-scripted-hand). When set, play the REAL
  // day-slate reel ONCE on FTUE completion, landing on this season, then reveal
  // the game (IDLE). Distinct from the daily gate: this path does NOT stamp the
  // daily day-key (writeStored), so the user's genuine entry-of-day reel later is
  // preserved. null = not playing.
  const [ftueExitReelPick, setFtueExitReelPick] = useState<SeasonManifestEntry | null>(null);

  // Track previous bypass value. When bypass transitions true → false
  // (user just finished the FTUE), we want the reel to take over IMMEDIATELY
  // without a frame of game-view rendering in between. Manifest pre-fetched
  // during the FTUE bypass branch so the reel can mount without a network gap.
  const prevBypassRef = useRef(bypass);

  // Resolve season pick + reel-or-not on mount. Two responsibilities:
  //   1. Pin the active season on dataEngine BEFORE children render so the
  //      slate selector loads the right season's data.
  //   2. Decide whether to show the visual reel (skipped during FTUE and
  //      after the user has already seen today's reveal).
  useEffect(() => {
    let cancelled = false;
    // Glass-round-2: hold the loading state (children blocked) until auth
    // resolves — the FTUE-vs-reel decision (skipReel) is only trustworthy on a
    // settled isAnonymous. Re-runs when authReady flips (dep below).
    if (!authReady) { setShouldShowReel(null); return; }
    // If we're transitioning out of FTUE (bypass true → false), reset the
    // gate to its loading state synchronously so children stop rendering
    // until the reel mounts. Without this, the GameView with the FTUE
    // anchor season (2025-26) flashes for ~1 frame before the reel covers.
    const justExitedFtue = prevBypassRef.current && !bypass;
    prevBypassRef.current = bypass;
    if (justExitedFtue) {
      setShouldShowReel(null);
    }
    (async () => {
      // QA / dev escape hatch — `?reel=force` always plays the reel,
      // even during FTUE. Checked first so the bypass path doesn't
      // short-circuit it.
      const forceReel = typeof window !== "undefined" &&
        new URLSearchParams(window.location.search).get("reel") === "force";

      // Bypass: skip the reel and pin the active season directly.
      //   - FTUE (no bypassSeasonKey): use FTUE_SEASON_KEY (2526). The
      //     hardcoded FTUE roster expects 2025-26 data.
      //   - Challenge replay (bypassSeasonKey set): use the challenge's
      //     original season. The recipient's snapshot has players from
      //     that era (e.g. 1617). Without this override, retired-by-now
      //     players (Aldridge, Whiteside, etc.) resolve to null logs
      //     and score 0 FP because logsByKey only has 2025-26 entries.
      // Pre-fetch the manifest in the background so the reel can fire
      // immediately when bypass ends (no second wait).
      if (bypass && !forceReel) {
        const pinKey = bypassSeasonKey ?? FTUE_SEASON_KEY;
        setActiveSeason(pinKey);
        // eslint-disable-next-line no-console
        console.info("[DailySeasonReelGate] bypass-mode season pin", {
          source: bypassSeasonKey ? "challenge_ctx" : "ftue_default",
          pin_key: pinKey,
        });
        setShouldShowReel(false);
        loadSeasonsManifest(MANIFEST_URL).catch(() => { /* ignore — caught in main path */ });
        return;
      }

      try {
        const m = await loadSeasonsManifest(MANIFEST_URL);
        if (cancelled) return;
        setManifest(m);

        const today = new Date();
        // QA / dev escape hatch — `?season=KEY` (e.g. `?season=9899`) pins
        // the active season to a specific manifest entry. Falls back to
        // the daily deterministic pick if the key isn't found.
        const seasonOverride = typeof window !== "undefined"
          ? new URLSearchParams(window.location.search).get("season")
          : null;
        const overridePick = seasonOverride
          ? m.seasons.find(s => s.key === seasonOverride) ?? null
          : null;
        // Season coupling: slate follows the boss. Precedence —
        //   1. ?season=KEY override (QA/dev) wins.
        //   2. today's boss season (the coupling).
        //   3. legacy daily pick (safe fallback if the boss season isn't in
        //      the solo manifest).
        const todaysPick = overridePick ?? pickBossSeason(today, m) ?? pickTodaysSeason("basketball", today, m);
        if (!todaysPick) {
          // Manifest empty — fall back to FTUE_SEASON_KEY so something loads.
          setActiveSeason(FTUE_SEASON_KEY);
          setShouldShowReel(false);
          return;
        }
        setPick(todaysPick);

        const dateKey = getDailyBonusDateKey(today);
        const stored = readStored();
        // Read BEFORE write so first-of-day shows the reel.
        const alreadySeenToday = stored?.dateKey === dateKey && stored?.seasonKey === todaysPick.key;

        // Pin the season on the dataEngine. Children (GameView) will call
        // ensureLoaded() and get this season's files. Synchronous — no
        // network — so it's set by the time we resolve shouldShowReel.
        setActiveSeason(todaysPick.key);

        // Don't mark today as seen when skipReel is on. The user is on a
        // route with its own era context (e.g. challenge landing) and
        // hasn't actually witnessed the reveal — leaving the marker
        // unwritten lets a later normal-play entry today still get the
        // daily reel.
        if (!skipReel) {
          writeStored({ dateKey, seasonKey: todaysPick.key, seasonLabel: todaysPick.label });
        }
        const willShow = forceReel || (!alreadySeenToday && !skipReel);
        console.info("[DailySeasonReelGate]", {
          forceReel,
          alreadySeenToday,
          willShowReel: willShow,
          pick: todaysPick.label,
          bypass,
          skipReel,
        });
        setShouldShowReel(willShow);
      } catch (e) {
        // Manifest unavailable — fail open. Pin to FTUE_SEASON_KEY so the
        // engine has something to load; skip the reveal.
        console.warn("[DailySeasonReelGate] manifest load failed; using fallback season:", e);
        if (!cancelled) {
          setActiveSeason(FTUE_SEASON_KEY);
          setShouldShowReel(false);
        }
      }
    })();
    return () => { cancelled = true; };
  }, [bypass, skipReel, bypassSeasonKey, authReady]);

  // FTUE-exit one-shot reel. GameView sets a durable flag (rm_ftue_exit_reel_pending)
  // + dispatches replaymod:ftue-exit-reel on the FTUE-completion REPLAY. We arm on
  // BOTH the event (same session — bypass doesn't flip mid-session and the main
  // effect above won't re-run) AND on mount (reload-durable). Re-resolves TODAY'S
  // REAL season (pickBossSeason → setActiveSeason) — this is what flips the lingering
  // 2526 FTUE pin over to the real daily slate, so the reel previews and the first
  // hand deals the real slate. Deliberately does NOT writeStored: the daily day-key
  // is left un-consumed so the genuine entry-of-day reel still fires independently.
  useEffect(() => {
    let cancelled = false;
    const arm = async () => {
      try { if (localStorage.getItem("rm_ftue_exit_reel_pending") !== "1") return; }
      catch { return; }
      // Fire-once: consume the durable flag AT ARM-TIME (read-and-remove), BEFORE the
      // async manifest load. Previously the flag was cleared only at onComplete, so any
      // re-mount before then (navigation OR the login re-render — glass hit both) re-read
      // a still-present "1" and re-fired the reel. Consuming here means a re-entry reads
      // an absent flag and bails. The reel still plays from in-memory ftueExitReelPick;
      // onComplete's removeItem below is now a redundant safety, kept idempotent.
      try { localStorage.removeItem("rm_ftue_exit_reel_pending"); } catch { /* noop */ }
      try {
        const m = await loadSeasonsManifest(MANIFEST_URL);
        if (cancelled) return;
        const today = new Date();
        const pick = pickBossSeason(today, m) ?? pickTodaysSeason("basketball", today, m);
        if (!pick) { try { localStorage.removeItem("rm_ftue_exit_reel_pending"); } catch { /* noop */ } return; }
        setManifest(m);
        setActiveSeason(pick.key); // flip the 2526 FTUE pin → today's real daily slate
        setFtueExitReelPick(pick);
      } catch {
        // Manifest unavailable — clear the flag so we don't wedge on the reel.
        try { localStorage.removeItem("rm_ftue_exit_reel_pending"); } catch { /* noop */ }
      }
    };
    void arm();
    const onExit = () => { void arm(); };
    if (typeof window !== "undefined") window.addEventListener("replaymod:ftue-exit-reel", onExit);
    return () => {
      cancelled = true;
      if (typeof window !== "undefined") window.removeEventListener("replaymod:ftue-exit-reel", onExit);
    };
  }, []);

  // FTUE-exit one-shot reel — TOP priority (overrides bypass / loading / normal).
  // Plays today's real day-slate reel once, then clears the durable flag and
  // reveals the game (IDLE) so the user taps DEAL for the first real hand. This
  // path NEVER calls writeStored → the daily day-key is left un-consumed.
  if (ftueExitReelPick && manifest) {
    const exitLabels = manifestLabelsChronological(manifest);
    return (
      <>
        {children}
        <SeasonReel
          labels={exitLabels}
          targetLabel={ftueExitReelPick.label}
          onComplete={() => {
            try { localStorage.removeItem("rm_ftue_exit_reel_pending"); } catch { /* noop */ }
            setFtueExitReelPick(null); // reveal children (IDLE) — user taps DEAL
          }}
        />
      </>
    );
  }

  // Block rendering until we know whether to show the reel — avoids the
  // child mounting briefly, then being covered, then becoming interactive.
  if (shouldShowReel === null) {
    // Loading manifest. Render nothing rather than flicker; if this hangs
    // we fail-open after fetch resolves.
    return null;
  }

  if (shouldShowReel && manifest && pick) {
    const labels = manifestLabelsChronological(manifest);
    return (
      <>
        {children}
        <SeasonReel
          labels={labels}
          targetLabel={pick.label}
          onComplete={() => {
            // Reel done → hand off to intro overlay before revealing
            // the game view. setShowIntro first so there's no frame in
            // between the reel and the intro.
            setShowIntro(true);
            setShouldShowReel(false);
          }}
        />
      </>
    );
  }

  // Season intro overlay — shows once after the reel lands.
  if (showIntro && pick) {
    const introText = (seasonIntros as Record<string, string>)[pick.key]
      ?? `Today we're going back to ${pick.label}. Good luck.`;
    return (
      <>
        {children}
        <SeasonIntroOverlay
          seasonLabel={pick.label}
          introText={introText}
          onDismiss={() => setShowIntro(false)}
        />
      </>
    );
  }

  return <>{children}</>;
}
