/**
 * baseball/src/adapters/gameAdapter.ts
 * Orchestration layer between GameView and the shared engines.
 * Forked from basketball — baseball uses P/BAT slots, different log filter.
 */

import { sportAdapter } from "./SportAdapter";
import { getPlayers, getLogsByKey } from "../engines/dataEngine";
import { generateRoster, redrawRoster as engineRedraw, mulberry32, randomSeed } from "../engines/rosterEngine";
import { resolveCards } from "../engines/resolveEngine";
import { DEFAULT_ECONOMY_CONFIG, tierFromSalary } from "../engines/economyEngine";
import { buildDailyBonusMap, getDailyBonusPlayers, type DailyBonusPlayer } from "@shared/utils/dailyBonus";
import { buildBonusPoolFromPlayers } from "@shared/utils/dailyBonusPool";
import { getDealPool } from "@shared/utils/dealGate";
import { SessionRepeatLimit, DEFAULT_REPEAT_LIMIT } from "@shared/utils/sessionRepeatLimit";
import { getCachedSlate } from "@shared/utils/slateSelector";
import { isSlateV2Enabled } from "@shared/featureFlags";
import { track } from "@shared/analytics/analytics";
import type { PlayerCard } from "./types";
import type { PlayerEval, GeneratedCard } from "../engines/rosterEngine";
import type { EconomyConfig } from "../engines/economyEngine";

/** Module-level session singleton — sliding window of recent draws. No-op when
 *  no records have been pushed; `record()` populates it after each deal.
 *  onRelaxed → fires the internal-only `repeat_limit_relaxed` event so we can
 *  see when the soft cap is being undermined by a too-small pool floor. */
const repeatLimit = new SessionRepeatLimit(() => {
  track("slate", "repeat_limit_relaxed", {}, "baseball");
});

function buildProjections(players: any[]): { projByBaseId: Map<string, number> } {
  const projByBaseId = new Map<string, number>();
  for (const p of players) {
    const bid = String(p.basePlayerId ?? p.id ?? "").trim();
    const proj = Number(p.avgFP ?? p.projectedFp ?? 0);
    if (bid) projByBaseId.set(bid, proj);
  }
  return { projByBaseId };
}

function getEconomyConfig(): EconomyConfig {
  return {
    ...DEFAULT_ECONOMY_CONFIG,
    capMax: sportAdapter.salaryCap,
  };
}

const VALID_TIERS = new Set(["RED", "ORANGE", "PURPLE", "BLUE", "GREEN", "WHITE"]);

function toPlayerEval(p: any, projByBaseId: Map<string, number>): PlayerEval {
  const baseId = String(p.basePlayerId ?? p.id ?? "");
  const proj = projByBaseId.get(baseId) ?? Number(p.avgFP ?? p.projectedFp ?? 0);
  const eco = getEconomyConfig();
  // Universal pattern: clamp only the LOWER bound. Top superstar salaries must
  // flow through unclamped so they're distinguishable — no caps, ever.
  const salary = Math.max(eco.salaryMin, Number(p.salary ?? 10));
  // Trust the per-pool tier from players.json (regenerated by
  // scripts/recalc-tiers.mjs). Cross-pool salary thresholds don't map
  // here — top BAT salary $56 is RED in its pool but PURPLE under the
  // shared salary thresholds. Fall back to salary lookup only if tier
  // is missing or invalid.
  const jsonTier = String(p.tier ?? "").toUpperCase();
  const tier = VALID_TIERS.has(jsonTier) ? jsonTier as any : tierFromSalary(salary, eco);
  return {
    id: String(p.id),
    basePlayerId: baseId,
    personKey: String(p.personKey ?? baseId),
    cardId: `${baseId}-${Math.random().toString(36).slice(2, 7)}`,
    name: String(p.name ?? ""),
    team: String(p.team ?? ""),
    season: String(p.season ?? ""),
    position: sportAdapter.normalizePosition(p.position),
    photoCode: p.photoCode ?? String(p.basePlayerId ?? p.id ?? ""),
    projectedFp: proj,
    salary,
    tier,
  };
}

/**
 * Baseball log validity check — thresholds match recalc-tiers.mjs EHLP filters.
 * Pitchers: ip >= 4 (qualifying start).
 * Hitters: pa >= 3 AND at least one counting event.
 */
function hasValidLogs(basePlayerId: string, position: string, logsByKey: Map<string, any[]>): boolean {
  const base = basePlayerId.trim();
  if (!base) return false;
  const candidates = logsByKey.get(`${base}|2425`) ?? logsByKey.get(base) ?? [];
  if (candidates.length === 0) return false;

  const isPitcher = sportAdapter.isPitcherPosition(position);

  return candidates.some((l: any) => {
    const s = l.stats ?? {};
    if (isPitcher) {
      const ip = Number(s.ip ?? 0);
      return ip >= 4;
    } else {
      const pa = Number(s.pa ?? 0);
      const events = Number(s.h ?? 0) + Number(s.hr ?? 0) + Number(s.r ?? 0) +
                     Number(s.rbi ?? 0) + Number(s.bb ?? 0) + Number(s.sb ?? 0) +
                     Number(s.doubles ?? 0) + Number(s.triples ?? 0);
      return pa >= 3 && events >= 1;
    }
  });
}

/** Build the bonus-eligible pool: players with valid logs, tier from salary. */
function buildBonusPool(): Array<{ basePlayerId: string; name: string; tier: string }> {
  const logs = getLogsByKey();
  const eco = getEconomyConfig();
  const allBonusEligible = buildBonusPoolFromPlayers(
    getPlayers(),
    (p: any) => hasValidLogs(
      String(p.basePlayerId ?? p.id ?? ""),
      String(p.position ?? ""),
      logs,
    ),
    (salary) => tierFromSalary(salary, eco),
    eco.salaryMin,
  );

  // When slate v2 is ON for baseball, restrict bonus picks to today's slate
  // so bonus players are guaranteed drawable.
  if (isSlateV2Enabled("baseball")) {
    const slateIds = new Set(getCachedSlate(sportAdapter as any, new Date()));
    return allBonusEligible.filter(p => slateIds.has(p.basePlayerId));
  }
  return allBonusEligible;
}

/** Today's 3 hot players with their bonus FP values — shown in Legend modal. */
export function getTodaysStars(): DailyBonusPlayer[] {
  return getDailyBonusPlayers(buildBonusPool());
}

/** Internal: today's bonus map (basePlayerId → bonus FP), used at resolve time. */
function getDailyBonusMapNow(): Map<string, number> {
  return buildDailyBonusMap(buildBonusPool());
}

export async function dealInitialRoster(): Promise<{ roster: PlayerCard[] }> {
  const allPlayers = getPlayers();
  const logs = getLogsByKey();

  // Slate v2 gate (no-op when feature flag is OFF — returns input unchanged).
  // Each player needs basePlayerId for the gate; cast is safe because RawPlayer
  // includes optional basePlayerId and we fall back to id when missing.
  const slatePool = getDealPool(
    sportAdapter as any,
    allPlayers.map((p: any) => ({ ...p, basePlayerId: String(p.basePlayerId ?? p.id ?? "").trim() })),
  );
  // Repeat limit — sliding window with pool-floor relaxation.
  // FLAG-GATED to preserve byte-equivalence when flag OFF.
  const players = isSlateV2Enabled("baseball")
    ? repeatLimit.filter(slatePool, DEFAULT_REPEAT_LIMIT)
    : slatePool;

  const { projByBaseId } = buildProjections(players);

  const evalPool = players
    .filter((p: any) => hasValidLogs(
      String(p.basePlayerId ?? p.id ?? ""),
      String(p.position ?? ""),
      logs
    ))
    .map(p => toPlayerEval(p, projByBaseId));

  if (evalPool.length === 0) {
    console.error('[gameAdapter] evalPool is empty — game-logs.json missing or all players filtered out');
  }

  const rnd = mulberry32(randomSeed());
  const rosterConfig = {
    rosterSize: sportAdapter.rosterSize,
    slotRequirements: sportAdapter.rosterSlots as string[],
    excludeFromFlex: [] as string[],
  };

  const cards = generateRoster(evalPool, rosterConfig, getEconomyConfig(), rnd);

  // Record drawn cards for the repeat-limit window — FLAG-GATED.
  if (isSlateV2Enabled("baseball")) {
    repeatLimit.record(
      cards.map((c: any) => String(c.basePlayerId ?? "")).filter(Boolean),
      DEFAULT_REPEAT_LIMIT,
    );
  }

  return { roster: cards as unknown as PlayerCard[] };
}

export async function redrawRoster({
  currentCards,
  lockedCardIds,
}: {
  currentCards: PlayerCard[];
  lockedCardIds: Set<string>;
}): Promise<{ roster: PlayerCard[] }> {
  const allPlayers = getPlayers();
  const logs = getLogsByKey();

  // Slate v2 gate + repeat-limit (no-op when feature flag is OFF).
  const slatePool = getDealPool(
    sportAdapter as any,
    allPlayers.map((p: any) => ({ ...p, basePlayerId: String(p.basePlayerId ?? p.id ?? "").trim() })),
  );
  const players = isSlateV2Enabled("baseball")
    ? repeatLimit.filter(slatePool, DEFAULT_REPEAT_LIMIT)
    : slatePool;

  const { projByBaseId } = buildProjections(players);

  const evalPool = players
    .filter((p: any) => hasValidLogs(
      String(p.basePlayerId ?? p.id ?? ""),
      String(p.position ?? ""),
      logs
    ))
    .map(p => toPlayerEval(p, projByBaseId));

  const heldSlots = new Set<number>();
  currentCards.forEach((c, i) => {
    const id = String((c as any).cardId ?? (c as any).basePlayerId ?? "");
    if (lockedCardIds.has(id)) heldSlots.add(i);
  });

  const rnd = mulberry32(randomSeed());
  const rosterConfig = {
    rosterSize: sportAdapter.rosterSize,
    slotRequirements: sportAdapter.rosterSlots as string[],
    excludeFromFlex: [] as string[],
  };

  const cards = engineRedraw(
    currentCards as unknown as GeneratedCard[],
    heldSlots,
    evalPool,
    rosterConfig,
    getEconomyConfig(),
    rnd,
  );

  // Record drawn cards for the repeat-limit window (held + redrawn cards) — FLAG-GATED.
  if (isSlateV2Enabled("baseball")) {
    repeatLimit.record(
      cards.map((c: any) => String(c.basePlayerId ?? "")).filter(Boolean),
      DEFAULT_REPEAT_LIMIT,
    );
  }

  return { roster: cards as unknown as PlayerCard[] };
}

export async function resolveRoster({
  finalCards,
}: {
  finalCards: PlayerCard[];
}): Promise<{ roster: PlayerCard[]; mvpCardId?: string }> {
  const logsByKey = getLogsByKey();
  const rnd = mulberry32(randomSeed());

  const { resolved, mvpCardId } = resolveCards(
    finalCards as unknown as GeneratedCard[],
    logsByKey,
    {
      fpScale: 1,
      minMinutes: 0, // baseball has no minutes filter
      dailyBonusMap: getDailyBonusMapNow(),
    },
    sportAdapter,
    rnd,
  );

  return { roster: resolved as unknown as PlayerCard[], mvpCardId };
}
